### ISSUE TITLE
How to deal with mutable attribute?

### ISSUE THREAD

**Issue by anhanh11001** [airbnb/epoxy#1000]
I'm having an icon that its visibility depends on the line number of a TextView `icon.isVisible = textView.lines > 5`. But in order for this to work, the model should have been built so that the line number of the textview can be counted. 

In other way, it means that I have to update model attribute after the model has been built. What should I do to make this work with Epoxy and is it something against Epoxy's architecture?

**Comment by elihart** [comment]
your model attributes should not include the number of lines, just the text as a string. after binding the text to the text view you can post a callback, or use a layout listener or predraw listener or other similar approach to get a callback once the textview has been laid out with the text. you can then check how many lines it is and then have it toggle the visibility of your icon.

so this logic would all be internal to your view/viewholder.

**Comment by anhanh11001** [comment]
Thank you, do you know when will Epoxy introduce supports for the new Android Paging library 3.0?
