### ISSUE TITLE
[Question] Firing off visibility events only when the RecyclerView is not scrolling?

### ISSUE THREAD

**Issue by josephwongcl** [airbnb/epoxy#1004]
(Apologies if this has been answered already, doing an issue search I was unable to come across any answers.)

At the moment, the visibility callbacks (`onVisibilityStateChanged/onVisibilityChanged`) are fired for each item as expected whenever a user flings the recycler view. However, I don't want to act on business impression logic if the user is flinging through items, I only want the events to fire if the RecyclerView isn't scrolling.

Is there a way to invoke a Model's `onVisibilityStateChanged` or `onVisibilityChanged` only if the recycler view is not scrolling? Has anyone else come across this requirement?

**Comment by eboudrant** [comment]
You can call `requestVisibilityCheck()` at anytime on the visibility tracker.

https://github.com/airbnb/epoxy/blob/bfa26078c7cb9584b29152134a26956c3f68f81a/epoxy-adapter/src/main/java/com/airbnb/epoxy/EpoxyVisibilityTracker.java#L185

**Comment by josephwongcl** [comment]
Thank you for the quick response, this was exactly the information I was looking for :) Closing the issue!
