### ISSUE TITLE
Swipe to delete: show delete button

### ISSUE THREAD

**Issue by AgneseBussone** [airbnb/epoxy#1011]
Hello!
I'd like to ask for some advice about setting up a swipe-to-delete feature on an epoxy RV.

**What I want to achieve**
An iOS like behaviour: swiping the row to the left, it shows a "Delete" button that can be hidden tapping or swiping the item back.

**What I tried**
I was able to achieve a good enough version in this way: the `ItemModel` (model for a single row) has a hidden `Delete` button. When the swipe ends, there is a callback that animates the layout showing the button. The `ItemModel` handles the click reversing the animation if necessary.
During the swipe, the `SwipeEpoxyCallback.onSwipeProgressChanged()` draws a red rectangle with a text to fake the button and triggers the callback on the item in the `clearView()` if necessary.

**What I'd like to change**
The main problem with the current solution is that before showing the real `delete` button, the animation bounce back to the original position. It's a weird effect, I'd like to stop the animation before the item reaches the right edge, so the delete button stays visible.
I'd also like to simplify the `ItemModel` layout removing the hidden delete button and using the one drawn by the `SwipeEpoxyCallback`. This will allow me to reuse this behaviour for other RVs without changing the layout of their rows.

I tried to override the `onChildDraw()` in the `SwipeEpoxyCallback` and I was able to keep the delete text visible, but I don't understand how to recognise the click on the delete area or on the item.

**Setup**
`SwipeEpoxyCallback` extends `EpoxyModelTouchCallback<ItemModel>`.

This is how I setup the swipe on the RV:
```            
ItemTouchHelper swipeHelper = new ItemTouchHelper(new SwipeEpoxyCallback(controller, ItemModel.class,
                    getString(R.string.delete),
                    getResources().getDimensionPixelSize(R.dimen.text_large),
                    this));
            swipeHelper.attachToRecyclerView(layoutBinding.epoxyRV);
```

The epoxy RV has a drag&drop handler too that crashes if a swiped item showing the delete text is clicked
```
EpoxyTouchHelper.initDragging(controller)
                    .withRecyclerView(layoutBinding.epoxyRV)
                    .forVerticalList()
                    .withTarget(ItemModel.class)
                    .andCallbacks(new EpoxyTouchHelper.DragCallbacks<ItemModel>() {......}
```

How can I improve this? Should I use different classes or different setups?

Thank you.

**Comment by AgneseBussone** [comment]
Not relevant anymore.
Decided to use [SwipeLayout](https://github.com/zerobranch/SwipeLayout) for each row without using ItemTouchHelper.

**Comment by 1240** [comment]
```
 EpoxyTouchHelper.initSwiping(binding.recyclerView)
            .left()
            .withTarget(ListItemBindingModel_::class.java)
            .andCallbacks(object : EpoxyTouchHelper.SwipeCallbacks<ListItemBindingModel_>() {

                val background = ColorDrawable(ContextCompat.getColor(requireContext(), R.color.red))
                val icon = requireNotNull(ContextCompat.getDrawable(requireContext(), R.drawable.ic_delete))

                override fun onSwipeCompleted(model: ListItemBindingModel_, itemView: View, position: Int, direction: Int) {
                    viewModel.onSwipeCompleted(model.id)
                }

                override fun onSwipeProgressChanged(model: ListItemBindingModel_, itemView: View, swipeProgress: Float, canvas: Canvas) {
                    super.onSwipeProgressChanged(model, itemView, swipeProgress, canvas)
                    val dx = (itemView.width * swipeProgress).roundToInt()
                    val iconMargin = (itemView.height - icon.intrinsicHeight) / 2
                    val iconTop = itemView.top + (itemView.height - icon.intrinsicHeight) / 2
                    val iconBottom = iconTop + icon.intrinsicHeight
                    when {
                        swipeProgress < 0 -> {
                            val iconLeft = itemView.right - iconMargin - icon.intrinsicWidth
                            val iconRight = itemView.right - iconMargin

                            background.setBounds(itemView.right + dx, itemView.top, itemView.right, itemView.bottom)
                            icon.setBounds(iconLeft, iconTop, iconRight, iconBottom)
                        }
                        else -> {
                            background.setBounds(0, 0, 0, 0)
                        }
                    }
                    background.draw(canvas)
                    icon.draw(canvas)
                }

            })
```
