### ISSUE TITLE
Potential memory leak in removed Adapter

### ISSUE THREAD

**Issue by ekimmel-ta** [airbnb/epoxy#1032]
Even though Epoxy has the functionality to unbind its adapter and clear out models, there seems to still be a memory leak coming from [ViewTypeManager.lastModelForViewTypeLookup](https://github.com/airbnb/epoxy/blob/2de36ba0fdb2223dcb51900efd41da952b5cd1cf/epoxy-adapter/src/main/java/com/airbnb/epoxy/ViewTypeManager.java#L14).

The EpoxyController/Adapter of a Carousel nested inside another EpoxyRecyclerView will hold on to this EpoxyModel between recycling uses.  If this EpoxyModel has a reference to a Fragment or ViewModel that has been destroyed, it will leak it.

**Comment by elihart** [comment]
Thanks for reporting this clearly, I have a fix for the next release.

It shouldn't be too bad of a leak, as it will be cleared the next time the adapter is used, or when the adapter is garbage collected, but good to fix none the less

**Comment by elihart** [comment]
Fixed in 4.0 https://github.com/airbnb/epoxy/pull/1046

**Comment by ekimmel-ta** [comment]
Thank you.  It wasn't a long-lived leak, but it was being caught by leak canary.
