### ISSUE TITLE
Published 4.0.0-beta6 out of sync with tagged release

### ISSUE THREAD

**Issue by ichrisanderson** [airbnb/epoxy#1042]
The published artifact for 4.0.0-beta6 appears to be out of sync with the 4.0.0-beta6 release branch. For example the published artifact doesn't contain `GroupModel`. The sha1 signature for 4.0.0-beta6 appears to be the same as 4.0.0-beta5.

https://repo1.maven.org/maven2/com/airbnb/android/epoxy/4.0.0-beta5/epoxy-4.0.0-beta5.aar.sha1
https://repo1.maven.org/maven2/com/airbnb/android/epoxy/4.0.0-beta6/epoxy-4.0.0-beta6.aar.sha1

**Comment by elihart** [comment]
Good catch, sorry about that, I must have made a mistake when publishing. I will be releasing a new version in the next few days with latest changes

**Comment by elihart** [comment]
4.0.0 release has just gone out
