### ISSUE TITLE
Errors occurring in package-info.java when using DataBinding annotations

### ISSUE THREAD

**Issue by Taresin** [airbnb/epoxy#1044]
When migrating to `4.0.0-beta5` or `4.0.0-beta6`, the annotations in my `package-info.java` file highlights the following issues:

`'@EpoxyDataBindingPattern' not applicable to package`
`'@EpoxyDataBindingLayouts' not applicable to package`

This does not happen with `4.0.0-beta4` and below.

Couldn't find any documentation on this on Google so thought I might ask if this was a breaking change that was introduced.

**Comment by harmittaa** [comment]
Check out the 4.0.0-beta5 notes:

https://github.com/airbnb/epoxy/releases/tag/4.0.0-beta5

> The annotation that support databinding, EpoxyDataBindingLayouts and EpoxyDataBindingPattern,
must now be placed on a class or interface instead of in a package-info.java file. The interface
or class must be in Java, Kotlin is not supported. This is necessary to support incremental processing.

**Comment by elihart** [comment]
@harmittaa is correct, thank you

**Comment by Taresin** [comment]
@harmittaa thanks for that.
Would it be possible to ask the for the databinding docs to be updated to reflect this change?
I'm still having trouble trying to implement it based off the changelog notes.

**Comment by harmittaa** [comment]
@Taresin 

I recommend cloning the repo and checking out the `kotlinsample` project. If that doesn't click, you can check out my small test project https://github.com/harmittaa/MovieBrowser (I wouldn't consider it any sort of reference for anything, but maybe it helps you).

I recommend creating a separate issue for the docs update.
