### ISSUE TITLE
Is there a plan to eventually have enableParallelEpoxyProcessing set to true by default? 

### ISSUE THREAD

**Issue by Minirogue** [airbnb/epoxy#1053]
Some libraries release optional build arguments with the plan to eventually have them active by default. I was wondering if this was the plan here so I can keep our build.gradle a little cleaner and wait until the feature has had a little more real-world testing.

**Comment by elihart** [comment]
I think it makes sense to default it to true eventually if there are no reported issues after a while. That said I have no timeline in mind - however we have been using it internally for our very large project for several months with no issues and I feel pretty confident about it working well for everyone

**Comment by Minirogue** [comment]
Thanks for the response. It seems like a great feature that I hope other annotation-based libraries pick up (if they're not already doing it). I'll probably keep it off in the short-term. Our project likely isn't big or Epoxy-heavy enough to see a noticeable improvement at this stage, so it's probably better for us to wait for a few more projects to be using it without issue first.
