### ISSUE TITLE
Why  buildWithModels sytanx different in v4.1.0 ?

### ISSUE THREAD

**Issue by RageshAntony** [airbnb/epoxy#1058]
I am learning Epoxy . I used epoxy in a project that used v3.4.2 . 

In that the buildWithModels looks like this

```
            epoxyRecyclerview.buildModelsWith {

                it.apply {
                    carousel {
                        id("catcarousal")
                        padding(Carousel.Padding.dp(0, 4, 0, 16, 8))
                        hasFixedSize(true)
                        models(models)
                    }
                }
            }
```

Now I created a new project with v4.1.0 , here I cant use above syntax since it's showing errors  .. I have to use like this 

```
            epoxyRecyclerview.buildModelsWith(object :
                EpoxyRecyclerView.ModelBuilderCallback {
                override fun buildModels(controller: EpoxyController) {
                    controller.apply {
                        carousel {
                            id("catcarousal")
                            padding(Carousel.Padding.dp(0, 4, 0, 6, 8))
                            hasFixedSize(true)
                            models(models)
                        }
                    }
                }

            })
```

Why this happening ? I liked the earlier type ? pls help me

**Comment by elihart** [comment]
Use `EpoxyController#withModels` to get a kotlin first lambda with receiver, which is better than `buildModelsWith` was originally. The change is because the class was converted to Kotlin.

I'd recommend taking some time to explore the class's API first

**Comment by RageshAntony** [comment]
@elihart  

Why this code throwing error :

```
                    bn.epoxy.withModels {
                        carousel {
                            id(1001)
                            it.forEach {

                                jobItem {
                                    id(it.id)
                                    job(it)
                                }
                            }
```

` java.lang.IllegalStateException: A value is required for setModels`

**Comment by realpranavp** [comment]
> @elihart
> 
> Why this code throwing error :
> 
> ```
>                     bn.epoxy.withModels {
>                         carousel {
>                             id(1001)
>                             it.forEach {
> 
>                                 jobItem {
>                                     id(it.id)
>                                     job(it)
>                                 }
>                             }
> ```
> 
> ` java.lang.IllegalStateException: A value is required for setModels`

Any update on this one? I am having similar issue with no more information. 
Error is: 

`java.lang.IllegalStateException: A value is required for buttonText at com.exampe.adapter.models.someViewModel_.addTo`
