### ISSUE TITLE
enableParallelEpoxyProcessing was not recognised by any processor

### ISSUE THREAD

**Issue by shah-nishant** [airbnb/epoxy#1077]
We recently upgraded to latest epoxy version 4.1.0 and to enable parallel processing we added following lines in our build.gradle file

```
project.android.buildTypes.all { type ->
    type.javaCompileOptions.annotationProcessorOptions.arguments = [
            logEpoxyTimings              : "true",
            enableParallelEpoxyProcessing: "true"
    ]
}
```

Our gradle files have these dependencies
```
implementation "com.airbnb.android:epoxy:4.1.0"
kapt "com.airbnb.android:epoxy-processor:4.1.0"
```

We are still getting following warning in console logs
```The following options were not recognized by any processor: '[enableParallelEpoxyProcessing, kapt.kotlin.generated, room.incremental, logEpoxyTimings]'[WARN] ```

We are using Android Gradle plugin 4.1.0 and gradle 6.5

**Comment by elihart** [comment]
What module are you seeing those in? I imagine you might be adding the annotation processor arguments to all modules, and the ones without epoxy give that warning.

**Comment by shah-nishant** [comment]
My bad. That was the case
