### ISSUE TITLE
[Question] Model ClickListener on EpoxyModelGroup

### ISSUE THREAD

**Issue by nomanr** [airbnb/epoxy#1082]
hi @elihart - I've been going through documentation and kotlin sample but couldn't find a way to add a `ModelClickListener` on. 

I am using epoxy with databinding. Is there a way to make click listener work with groups like it works with databinding? 

For the time being, as a workaround I added a ViewStub that matches width/height of the group and on that ViewStub I am adding a View that work as only a click listener. 

Thanks for your help!

**Comment by elihart** [comment]
The `ModelClickListener` only works on model classes that are generated. You can force a model to be generated by subclass the model group class and adding an epoxy annotation, or you can subclass the model group and add a function for `ModelClickListener` manually

**Comment by nomanr** [comment]
Noted, I'll try that. Thank you! 

Closing for now, will re-open if have any other question about it.
