### ISSUE TITLE
Add more then one type of epoxy model inside a single carousel

### ISSUE THREAD

**Issue by PrabakaranPerfUtil** [airbnb/epoxy#1104]
Hi, First Thanks for Epoxy ;) .

I'm trying to show horizontal scrolling carousel with paging. I have implemented the pagination part. I need to show a Loading progress bar while getting the next page data. 

So I need to add a loader model to the carousel. But carousel model only accepts one type of epoxy model list at a time. I'm already setting my Item model here.

How do I achieve this? Can anyone give me some pointers? Thanks

**Comment by varunlibra3** [comment]
@PrabakaranPerfUtil any luck on this? I am trying the same but couldn't find much help.

**Comment by elihart** [comment]
> carousel model only accepts one type of epoxy model list

This is not true, the carousel takes a generic list of models, so it can contain as many different types as you want. If your problem is that you are using the paging epoxy controller you can override its function to modify the models list after models are built to add a loader
