### ISSUE TITLE
Update value data class on Click event

### ISSUE THREAD

**Issue by choiruru** [airbnb/epoxy#1105]
![img_ask](https://user-images.githubusercontent.com/2399900/101160558-d3ea3000-3661-11eb-8025-c08f7562f1ed.png)
I have design like this, 
when I click plus/minus button, the counter will increase and decrease.
and the top is total from all counter will update automatically too
how to achive that..??

I tried to update data class value, and got error like this
<img width="1364" alt="Screenshot 2020-12-04 at 6 55 40 PM" src="https://user-images.githubusercontent.com/2399900/101160958-71456400-3662-11eb-91ae-db925d7e80fc.png">

**Comment by Juan755145** [comment]
you have to update the data class outside of your controller, then call requestModelBuild() to update your ui

**Comment by choiruru** [comment]
solved, 
need to add this in build.gradle
```
project.android.buildTypes.all { buildType ->
    buildType.javaCompileOptions.annotationProcessorOptions.arguments =
            [
                    validateEpoxyModelUsage     : "false",
            ]
}
```

**Comment by elihart** [comment]
That is not a solution, that is working around your bug, but the problem is still there. You should not be updating values of a class reference. Instead, use immutable data and/or copy your data instances when you need to make changes (like using `copy` in a kotlin data class)

Without doing it this proper way you may experience subtle bugs

**Comment by choiruru** [comment]
@elihart thank you for your response
for now, I change my code as your suggestion, and its working

```
val temp = listDatas[index] as MyDataModel
val newData = MyDataModel(temp.param1, temp.param2, temp.param3, param_that_I_want_to_update, temp.param4)
listDatas[index] = newData
```
