### ISSUE TITLE
Is there a way to get the previous model property value when building models in an EpoxyController?

### ISSUE THREAD

**Issue by blah1234** [airbnb/epoxy#1108]
I'm using a TypedEpoxyController to build my models.  For some models I would like to know what the previous value assigned to a model property was.  e.g.,

    override fun buildModels(photos: List<Photo>, loadingMore: Boolean) {
        header {
            id("header")
            title("My Photos")
            description("My album description!")
        }

        photos.forEach {
            photoView {
                id(it.id())
                url(it.url())
            }
        }

        if (loadingMore) loaderView { id("loader") }
    }

Is there a way to get what the previous values passed into "title" and "description" are?  Are there any listeners for this?

**Comment by elihart** [comment]
There is no built in way to do this in the controller. You could potentially get the copy of current models off of the controller adapter, but you would need to look up the corresponding model by id or position - it wouldn't be very efficient.

The most efficient way to do it would be to have any logic related to changes be in your model, and the bind callback of the model allows you to see the previous model that was bound so the two values can be compared.

**Comment by blah1234** [comment]
> The most efficient way to do it would be to have any logic related to changes be in your model, and the bind callback of the model allows you to see the previous model that was bound so the two values can be compared.

I'm kind of confused by the above statement.  I'm using epoxy models generated automatically from databindings, and I THINK what you're referring to is the OnModelBoundListener registered with the onBind() method for the generated Model?  But in my testing it seems like the model argument passed to the OnModelBoundListener will be the CURRENT model and not the PREVIOUS model.

**Comment by blah1234** [comment]
Nevemind. I see in DataBindingEpoxyModel

`public void bind(@NonNull DataBindingHolder holder, @NonNull EpoxyModel<?> previouslyBoundModel) {
    setDataBindingVariables(holder.dataBinding, previouslyBoundModel);
    holder.dataBinding.executePendingBindings();
  }`
