### ISSUE TITLE
How to update specific views dynamically?

### ISSUE THREAD

**Issue by luizfilho00** [airbnb/epoxy#1112]
I've a use case where i've a lot of static views that form like a list of views but has two views in the middle of that list that need to be updated with a request to my API, so i need a manner to update only that views without rebuild all the list, how can i do that? I've tried to get the list from adapter but it throws an error of immutability check.

Now, i solved this making the request before the call `epoxyRecyclerView.withModels { }` but it's not what i desired...

**Example:** 

I've not a list of itens, all the items are added using:
```
epoxyRecyclerView.withModels {
      modelA()
      modelB()
      modelC()
 }
 ```

So, how can i update my modelB after an async request?

**Comment by elihart** [comment]
> i need a manner to update only that views without rebuild all the list

This is not how Epoxy works. You are _supposed_ to always rebuild the list any time you want to make any changes. Please read the wiki and familiarize yourself with the sample.
