### ISSUE TITLE
Drag and drop for items inside an EpoxyModelGroup

### ISSUE THREAD

**Issue by ArthurCideron** [airbnb/epoxy#1116]
Isn't there a way to set an ItemTouchHelper on a recyclerview that applies to items _inside_ an epoxy model group?
So that we can have a list of drag-and-droppable items in a group within the bigger RecyclerView.

This might be similar to #534 

Additional context:
I have a layout that uses epoxy model groups to display a list within a bigger scrollable layout (an EpoxyRecyclerView).
I'm using a recycler view inside that model group so I can use an ItemTouchHelp for dragging and dropping item in that inner list.

The issue I'm facing is that when the inner list is longer than the screen, I can't drag and item out to scroll the whole parent view. Which makes sense since the ItemTouchHelper is attached to that inner recyclerview.
But if I attach the ItemTouchHelper to the outer recyclerView then, I can't drag the individual items inside the epoxy group.

**Comment by elihart** [comment]
This isn't currently supported. I suspect it might be possible but quite difficult to implement this as you want. You're welcome to put up a PR to add the functionality you want

**Comment by ArthurCideron** [comment]
"Quite difficult" is my impression of it, yes :D.
Well thanks for the answer, I'll see if I can get it working for a PR (low expectations on that one)

**Comment by milimetron** [comment]
Were you successful in finding a solution?
