### ISSUE TITLE
Compile time duplicate error due to Epoxy using kotlin-parcelize

### ISSUE THREAD

**Issue by sanogueralorenzo** [airbnb/epoxy#1118]
Hello everyone 👋 

From epoxy versions 4.2.0 and up I'm getting the following error. It is caused by the removal of kotlin-android-extensions plugin and the replacement with kotlin-parcelize

![image](https://user-images.githubusercontent.com/5630683/104092094-fafbd900-5281-11eb-97c1-05634689c38b.png)

Since it is a plugin that is causing a duplicate I'm not sure what is the approach to fix this compilation error.

Migrating away from kotlin-android-extensions is not feasible as a solution in the short term due to the amount of synthetics the project I'm working on has.
```
Duplicate class kotlinx.android.parcel.IgnoredOnParcel found in modules 
kotlin-android-extensions-runtime-1.4.20-RC (org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.20-RC)
and kotlin-parcelize-runtime-1.4.20-RC (org.jetbrains.kotlin:kotlin-parcelize-runtime:1.4.20-RC)
```

**Comment by andreii-sp** [comment]
@sanogueralorenzo bumped into the same issue. Found any solution?

**Comment by sanogueralorenzo** [comment]
@andreii-sp not yet, I tried a few things that didn't work so I just created this issue

**Comment by egor-egorov-xero** [comment]
Having the same issue.

**Comment by elihart** [comment]
Have you tried version 4.3.1?

**Comment by egor-egorov-xero** [comment]
@elihart yep, having the same issue

**Comment by sanogueralorenzo** [comment]
@elihart yes same here

any version above and including 4.2.0 has this issue

**Comment by van-dn** [comment]
having the same issue

**Comment by degea9** [comment]
It seems to be fixed on epoxy version 4.4.0. I have built successfully without the error with version 4.4.0.

**Comment by egor-egorov-xero** [comment]
Same for me, 4.4.0 has fixed the issue!

**Comment by sanogueralorenzo** [comment]
Can confirm, closing the issue! Thanks whoever fixed it 😄
