### ISSUE TITLE
Listen for scrolling 

### ISSUE THREAD

**Issue by sh3lan93** [airbnb/epoxy#1125]
when using `onVisibilityChanged` and `onVisibilityStateChanged` they are called only when calling `requestModelBuild` and I need to observe scrolling state when user scroll in the epoxy recycler view

I tried using the layout manager for doing this behaviour and when using `findFirstCompletelyVisibleItemPosition` it always returns 0  

is there any way for continuous observing scrolling state/position?

**Comment by NattyBadWolf** [comment]
Hi, how did you manage to observe scrolling?
