### ISSUE TITLE
Can't call notifyItemChanged(position) to trigger revert swipe for PageListEpoxyController.

### ISSUE THREAD

**Issue by Gelacio** [airbnb/epoxy#1128]
@elihart 
This is similar to https://github.com/airbnb/epoxy/issues/954.

 Calling notifyItemChanged(position) for PagedListEpoxyController to revert the swipe action is not working. Neither submitting a new page list with the swiped item changed in the data source.

Any workaround for this?

Thanks

**Comment by bloooi** [comment]
why are you closed? is there any solutions?
