### ISSUE TITLE
Support KSP

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#1129]
https://android-developers.googleblog.com/2021/02/announcing-kotlin-symbol-processing-ksp.html

This will be important for us to improve build speeds.

**Comment by ColtonIdle** [comment]
KSP 1.0

https://android-developers.googleblog.com/2021/09/accelerated-kotlin-build-times-with.html

**Comment by elihart** [comment]
We're working on it

**Comment by hm-tamim** [comment]
Any update?

**Comment by elihart** [comment]
KSP has been supported since version 5.0 beta (https://github.com/airbnb/epoxy/releases/tag/5.0.0beta02). It's working great for us at airbnb
