### ISSUE TITLE
Support Explicit API Mode for Kotlin

### ISSUE THREAD

**Issue by tinder-christopherperry** [airbnb/epoxy#1133]
Compiling with `strict` enabled causes a compile error. See: https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors

Example from Epoxy output on an example project:

```kotlin
inline fun ModelCollector.highlightCard(modelInitializer: HighlightCardModelBuilder.() -> Unit) {
  add(
  HighlightCardModel_().apply {
    modelInitializer()
  }
  )
}
```

This would have to have visibility modifiers explicitly stated in the declaration.

**Comment by elihart** [comment]
Thanks for reporting, should be an easy fix if anyone wants to put up a PR to add explicit modifiers for this file.
