### ISSUE TITLE
Monitoring when item is shown in EpoxyController

### ISSUE THREAD

**Issue by brunofamilynet** [airbnb/epoxy#1141]
I use the `EpoxyController` and `EpoxyRecyclerView` in a fragment where I display a lot of different model views. I would like to be able to monitor when a given view is shown to the user for tracking purposes. Is there any quick and easy was to do this in Epoxy? Is it possible to somehow check if a view is visible based on its id?

I guess one way of doing this would be to extend the model view and override the `bind()` functions and track that the view was shown to the user there, but this method appears to be a bit tedious for the simple purpose of checking where a view is visible or not. Is there a better way to go about achieving this?

Thanks in advance.

**Comment by elihart** [comment]
did you check the wiki? https://github.com/airbnb/epoxy/wiki/Visibility-Events

**Comment by brunofamilynet** [comment]
My mistake. I'd completely overlooked this section. Thanks.
