### ISSUE TITLE
ActivityRecyclerPool not sharing as intended when EpoxyRecyclerView used in fragment

### ISSUE THREAD

**Issue by wbonnefond** [airbnb/epoxy#1152]
When fragments host an `EpoxyRecyclerView`, the `ActivityRecyclerPool` is not properly sharing `PoolReference`'s between fragments. This is causing a cache miss and the internal `ActivityRecyclerPool.pools` list to grow continually.

The problem occurs in `EpoxyRecyclerView.initViewPool()`, the context passed to `getPool()` is a `FragmentContextWrapper` rather than an `Activity`, this wrapper is different for each fragment instance and even across recreation of fragments view's during navigation. This is causing a cache miss when checking `poolReference.context === context`. A simple solution would be to unwrap the context until we find the parent `Activity`.

If this sounds like a reasonable approach, I'd be happy to open a PR to fix it.

**Comment by elihart** [comment]
Is this a duplicate of https://github.com/airbnb/epoxy/issues/1025? 

I'm not sure if anything has changed on the Hilt side to better support this, but unwrapping the context may be a good approach (it's been a while since I looked at this)

**Comment by wbonnefond** [comment]
Yes, it appears to be the same issue, I didn't realize `FragmentContextWrapper` was coming from Hilt. I subclassed `EpoxyRecyclerView` and did the unwrapping step in our app without any issue (though I needed to copy `ActivityRecyclerPool` to get it working). I'll close this issue in favor of the other.
