### ISSUE TITLE
Is there any way I can trigger a model rebuild in `PagingDataEpoxyController`?

### ISSUE THREAD

**Issue by Gensoukyou1337** [airbnb/epoxy#1160]
As far as I've seen, `PagingDataEpoxyController` is great for displaying data from a `PagingData`.

However, I need to implement a single selection on it by using a Data Class as a State, and triggering a model rebuild whenever the state is changed by an onClick.

Right now, unless I missed something, I see no way to trigger said model rebuild in `PagingDataEpoxyController`. There's a function that does that in `PagedListEpoxyController` by clearing the `modelCache` and calling the `requestModelBuild()`, but I'm not sure about using it in `PagingDataEpoxyController`.

So yeah, how do I trigger the model rebuild in a `PagingDataEpoxyController`?

EDIT: My implementation is as follows:
```
class ExamplePagingAdapter : PagingDataEpoxyController<ExampleModel>() {
    
    companion object {
        val state = ExampleState()

        val selectionAndModelDiffCallback = object : DiffUtil.ItemCallback<ExampleModel>() {
            override fun areItemsTheSame(oldItem: ExampleModel, newItem: ExampleModel) = oldItem.id == newItem.id
            override fun areContentsTheSame(oldItem: ExampleModel, newItem: ExampleModel) = 
                oldItem == newItem && computeSelected(oldItem) == computeSelected(newItem)
        }

        fun computeSelected(item: ExampleModel) = item.id == state.selectedItem?.id ?: false
    }
    
    override fun buildItemModel(currentPosition: Int, item: ExampleModel?): EpoxyModel<*> {
        return ExampleViewModel_()
                    .id("example_item_${item!!.id}")
                    .model(item)
                    .spanSizeOverride { _, _, _ -> 1 }
                    .onItemClicked { 
                        state.selectedItem = it
                        requestModelBuild()
                    }
    }
}
```

This code does trigger the `OnModelBuildFinishedListener`, but not the model building itself. Is there something I missed in this code?

**Comment by rohithThammaiah** [comment]
@elihart Can an option to clear the `modelCache` be added in `PagingDataEpoxyController`? I think there was an option in `epoxy-paging2`.

**Comment by Gensoukyou1337** [comment]
> @elihart Can an option to clear the `modelCache` be added in `PagingDataEpoxyController`? I think there was an option in `epoxy-paging2`.

There is, but it's in the `PagedListEpoxyController`. I'm not sure whether, or how, it works with `PagingData`.

**Comment by rohithThammaiah** [comment]
I have created a PR(#1161) that contains this option in`PagingDataEpoxyController` just not sure whether to invalidate the whole `modelCache` or just a particular element in the `modelCache`

**Comment by Gensoukyou1337** [comment]
> I have created a PR(#1161) that contains this option in`PagingDataEpoxyController` just not sure whether to invalidate the whole `modelCache` or just a particular element in the `modelCache`

Thanks.

Correct me if I'm wrong, but from the examples I've seen, 'triggering a model rebuild' implies invalidating everything.

**Comment by Gensoukyou1337** [comment]
If I may ask, when will you release this fix along with others?
