### ISSUE TITLE
Items that are Visible but not Shown

### ISSUE THREAD

**Issue by mediavrog** [airbnb/epoxy#1173]
Hey I wanted to ask you about a certain condition and if that came up in the past before I go through and create a demo app etc. I searched the issues and could not find anything.

So in our case we "preload" recyclerviews and popolate them off screen (think viewpager).
Once a fragment containing the epoxyrecyclerview is set up and the EpoxyVisibilityTracker is attached, the first items in the recyclerview already receive visibility events, even though the whole recyclerview is not shown on the screen yet.

Is there a simple way to handle that using the current epoxy design? I checked `EpoxyVisibilityItem` but that only checks for the 'VISIBILITY' flag, not the parent recyclerview#isShown

**Comment by elihart** [comment]
Hi, as far as I remember we use `View#getLocalVisibleRect` to check view visibility - https://stackoverflow.com/questions/10451018/android-understanding-view-getlocalvisiblerectrect

As well as `View#isVisible()` like you noted. I'm not completely following how you are setting up your recyclerview - are you setting it to invisible? I don't believe we've ever had anyone with this use case so I suppose we've never needed to check for parent viewgroup visibility.

Could you avoid attaching the `EpoxyVisibilityTracker` until you are ready to show the recyclerview?

**Comment by mediavrog** [comment]
Thanks for your reply.

Yes, basically we have a ViewFlipper, and set up the recyclerview in both views to have fast switching. 
The recyclerview not yet shown on screen will deliver onVisibilityCHanged etc callbacks to the models, which we want to avoid as we track impressions etc there.

I also thought of delaying the EpoxyVisibilityTracker attachment, but I was looking for alternatives first. But thanks for hinting/confirming that this could be a viable option.

I will likely create some test app to isolate this behavior, maybe later issue a PR if that's something that could be interesting for the project. Thanks already for your feedback.

**Comment by mediavrog** [comment]
FYI for anyone reading this issue:

We ended up controlling the timing when the VisibilityTracker would be attached and detached as this was the solution most straightforward/easiest to adopt with our needs.
