### ISSUE TITLE
I updated epoxy 4.1.0 to 4.6.2 so i am getting error everywhere in controller error

### ISSUE THREAD

**Issue by vishalkumarsinghvi** [airbnb/epoxy#1200]
String' can't be called in this context by implicit receiver. Use the explicit one if necessary
any simple solution is there apart from that this@Controller.ourvarvariable.

**Comment by elihart** [comment]
Read the release notes

https://github.com/airbnb/epoxy/releases/tag/4.6.1
https://github.com/airbnb/epoxy/releases/tag/4.6.0

**Comment by vishalkumarsinghvi** [comment]
@elihart I added the following code but the compiler gives me an error like that -> The following options were not recognized by any processor: '[epoxyDisableDslMarker, kapt.kotlin.generated]'

**Comment by mtrakal** [comment]
If someone else is same stupid as me and spend hours to try fix this "issue" without disable new featres as mentioned in 4.6.1, and add just `this` exit on Unresolved references even Android studio show it as correct working code, just add `this@ClassNameController` to make it working.


Example: 
https://github.com/airbnb/epoxy/blob/88d770f88457a14a5ed47a831673666da5527095/epoxy-preloadersample/src/main/java/com/airbnb/epoxy/preloadersample/ImagesController.kt#L15

**Comment by m-sabeeh** [comment]
If using ksp for epoxy, need to add ksp arguments. 

```
android {

    // other configurations

        ksp {
            arg("epoxyDisableDslMarker", "true")
        }
}
```
