### ISSUE TITLE
Lint rule to suggest hash=false if an attribute has no hashcode

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#121]
One of the most common problems I see is either not implementing hashcode on an @EopxyAttribute object, or not using hash=false if that object should not have hashcode (like click listeners).

A lint rule could help a ton with this.

Would love any help if someone wants to set this up.

**Comment by elihart** [comment]
I'm also thinking of making a config class where you can choose to have the annotation processor throw an error if an attribute does not implement hashcode. Lint would be helpful in addition to this for people that don't want such as strict setting

**Comment by geralt-encore** [comment]
I can look into it. I've never done custom lint checks before, but it might be an interesting experience.

**Comment by elihart** [comment]
Great! For reference, I've been thinking lately that Epoxy is pretty good feature wise, but it's power and flexibility comes at a price of difficulty to use well. I've seen lots of issues on my team where people misuse the library, and from issues posted on here it seems other people have the same issue, understandably.

Common issues are:
Instantiating the original class instead of the generated class (hence the move to pushing for abstract classes)
Not setting an ID
Not using hash=false when necessary, or not implementing hashcode (this issue)
Not making correct diffing calls.
Not annotating fields with @EpoxyAttribute 

Linting helps, but I am also interested in catching these at compile time. I'm working on a PR where you can set global configuration options for a project to enforce things like always having the model be abstract and that hashcode is used properly.

**Comment by elihart** [comment]
Here is how I accomplished a check for this in the annotation processor https://github.com/airbnb/epoxy/pull/124

It was trickier than I expected since I had to check for collections, arrays, and generated classes like AutoValue.

I think lint would be useful in addition to this so that you can see the issue right away without having to wait to compile. Additionally for established projects it would be easier to add the lint rule first instead of forcing all violations to change immediately

**Comment by elihart** [comment]
I don't think this is worth the effort anymore given that we have the compile time detection
