### ISSUE TITLE
Is it possible to render fixed top or bottom views?

### ISSUE THREAD

**Issue by Dwite** [airbnb/epoxy#1213]
I'm curious is it possible to do something like in the iOS version - https://github.com/airbnb/epoxy-ios#epoxybars ? Specifically the fixed top/bottom bars?

Currently, I'm adding such views statically in the layout file, but would appreciate keeping them as part of the controller.

**Comment by elihart** [comment]
See https://github.com/airbnb/epoxy/pull/1175 - this is support for using epoxy models to bind arbitrary views outside of a recyclerview. It is a generic system that can be used for any sort of views you want - we use it for bottom footer views mainly

**Comment by Dwite** [comment]
@elihart thank you for the suggestion, looks clear to me 👍🏻 

I assume the preferred way is to have a header/footer along with `RecyclerView` with `EpoxyViewStub` and replace them using `viewBinder` when necessary?

**Comment by elihart** [comment]
That's right 👍
