### ISSUE TITLE
Epoxy Processor error when using kotlin 1.5.21 and @JvmField

### ISSUE THREAD

**Issue by matt400m** [airbnb/epoxy#1222]
I have a problem with @ModelView an @JvmField. After compilation generated java class contains @JvmField. When I'm using kotlin 1.5.10 epoxy doesn't at this annotation.

```
  @JvmField
  private int test_Int = 0;
```

```
 public EpoxyBugModel_ test(@JvmField int test) {
    onMutation();
    this.test_Int = test;
    return this;
  }
```

sample code:
```

@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class EpoxyBug @JvmOverloads constructor(
    context: Context,
    attributeSet: AttributeSet? = null,
    defStyleAttr: Int = 0
) : FrameLayout(context, attributeSet, defStyleAttr) {

    @JvmField
    @ModelProp(ModelProp.Option.DoNotHash)
    var test: Int = 0
}


```

epoxy: 4.6.2
kotlin: 1.5.21

**Comment by elihart** [comment]
why are you using `@JvmField`? can you just remove @JvmField and do `@ModelProp(ModelProp.Option.DoNotHash)
    var test: Int = 0`?

**Comment by matt400m** [comment]
Thanks for answer. I also try yours suggestion but I have:
`EpoxyProcessorException: Field annotated with interface com.airbnb.epoxy.ModelProp must not be static or private (field: test)`

**Comment by elihart** [comment]
you have to use `@set:ModelProp` to annotate the field

**Comment by matt400m** [comment]
Nope. That was my problem. Thanks @elihart :)
