### ISSUE TITLE
Any chance to extend this to React Native?

### ISSUE THREAD

**Issue by jjhesk** [airbnb/epoxy#123]
From my developer experience, this project is tremendous and it resolved alot of problems from memory to module hierarchy issues. As title, are there any chances or thoughts to advance this module or project into a React-native project?

**Comment by elihart** [comment]
Thank you!

I don't know React Native well, but we are starting to use it quite a bit in our app so I have also thought about how it might be used there

I'm not familiar with it enough to know the best way to do that. I'm open to suggestions or PR's, but it's unlikely I would be doing this myself.

**Comment by elihart** [comment]
I have no plans to do this, or any idea if it is possible or what it would entail.

If anybody has ideas or wants to take it on I'm happy to review code and consult.

Closing for now, but if anybody wants to attempt this feel free to reopen.
