### ISSUE TITLE
Epoxy Unit Testing - where can I access expectState ?

### ISSUE THREAD

**Issue by martymiller** [airbnb/epoxy#1293]
This article references a method called expectState and is written by an Airbnb Android developer.  It's almost like this method doesn't actually exist because I don't see it in the SDK and there is no documentation.  This method is exactly what I'm looking for.  Please point me in the right direction!  Thanks.

https://medium.com/airbnb-engineering/better-android-testing-at-airbnb-part-4-testing-viewmodels-550d929126c8

**Comment by elihart** [comment]
That article is about a different repo - https://github.com/airbnb/mavericks

Also, we have not open sourced the unit testing library that the article describes

**Comment by martymiller** [comment]
Then why did you put it in an article if it can't be used?

**Comment by elihart** [comment]
That article isn't trying to be exact documentation or representation of an open source library, it's a review of our testing methodology at airbnb, some of which is open sourced.
