### ISSUE TITLE
default parameter is not working with kotlin 1.7

### ISSUE THREAD

**Issue by edward-rxc** [airbnb/epoxy#1302]
I'm using epoxy 4.6.4 with kapt.
after have been update to kotlin 1.7, [kotlin default parameter](https://github.com/airbnb/epoxy/wiki/Generating-Models-from-View-Annotations#kotlin-default-parameters) is not working.
however, it work well with kotlin 1.6.21.

**Comment by elihart** [comment]
i'll look into this next week

**Comment by elihart** [comment]
Does it work with KSP for you?

**Comment by elihart** [comment]
oh, you should try the 5.0 beta release, it likely works for that. please reproduce with the the latest 5.0 beta first

**Comment by edward-rxc** [comment]
oh, I checked that it works with 5.0 beta release.
thank you.
