### ISSUE TITLE
Upgrade recyclerview version to 1.3.0-alpha02

### ISSUE THREAD

**Issue by WessimBetclic** [airbnb/epoxy#1313]
Hello! 

In order to improve recyclerview interoperability with compose it is recommended to upgrade to 1.3.0-alpha02 to handle disposing properly (see more [here](https://medium.com/androiddevelopers/jetpack-compose-interop-using-compose-in-a-recyclerview-569c7ec7a583)) 

You might be waiting for the stable version to upgrade it but I just wanted to make sure this was in the pipes.

Thank you!

**Comment by martymiller** [comment]
Seems like a risk to base a library on an alpha version.  Doesn't really matter since Epoxy is pretty much abandoned at this point.

**Comment by elihart** [comment]
It's already done :) https://github.com/airbnb/epoxy/pull/1308

**Comment by WessimBetclic** [comment]
That's great ! is there a release planned soon ? because it's not on the 5.0.0-beta03 actually

**Comment by WessimBetclic** [comment]
That's great thank you ! is there a release planned soon ? because it's not on the 5.0.0-beta03 actually

**Comment by elihart** [comment]
yes, a release is planned before long, but you can also make your own too
