### ISSUE TITLE
When bump Epoxy 5.x.x, getting kotlin-compiler-embeddable-1.7.0.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.0)

### ISSUE THREAD

**Issue by nuhkoca** [airbnb/epoxy#1325]
Hello,

Whenever I bump the library to `5.0.0`, I am seeing

> The following annotation processors are not incremental: kotlin-compiler-embeddable-1.7.0.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.0).
> Make sure all annotation processors are incremental to improve your build speed.

Do you know what is the root cause?

**Comment by SubhrajyotiSen** [comment]
`kotlin-compiler-embeddable` is a transitive dependency. 
The dependency is updated in the 5.0.2 release. Updating to this release shouldn't give you the above warning

**Comment by mustafaberkaymutlu** [comment]
We are using Epoxy 5.1.3 and Kotlin 1.8.21 and see a similar warning

> The following annotation processors are not incremental: kotlin-compiler-embeddable-1.8.21.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.8.21).
> Make sure all annotation processors are incremental to improve your build speed.

Do you have any recommendation?

**Comment by SubhrajyotiSen** [comment]
We have doing this:

```kotlin
ksp("com.airbnb.android:epoxy-processor:5.1.3") {
    exclude(group = "org.jetbrains.kotlin", module = "kotlin-compiler-embeddable")
}
```

My understanding is that since our project already uses a specified Kotlin compiler, we do not require it explicitly from a dependent library. We hadn't had any issues with this approach

**Comment by nuhkoca** [comment]
We already migrated our project into Compose so I am closing this issue. I don't think this project will be well maintained in the future.
