### ISSUE TITLE
How to get item view from RecyclerView?

### ISSUE THREAD

**Issue by Michinggun** [airbnb/epoxy#135]
I have problems using epoxy, when I've already added my model in EpoxyAdapter and already set it to the RecyclerView. Somehow when I'm using `recyclerView.getLayoutManager().findViewByPosition(0)`, it always return null. I need to get View from the model that I've already added. Please help me, thank you !

**Comment by elihart** [comment]
From the layout manager docs
```
 /**
         * Finds the view which represents the given adapter position.
         * <p>
         * This method traverses each child since it has no information about child order.
         * Override this method to improve performance if your LayoutManager keeps data about
         * child views.
         * <p>
         * If a view is ignored via {@link #ignoreView(View)}, it is also ignored by this method.
         *
         * @param position Position of the item in adapter
         * @return The child view that represents the given position or null if the position is not
         * laid out
         */
```

Importantly `The child view that represents the given position or null if the position is not laid out`

Epoxy is built upon RecyclerView and has all the limitations of it. RecyclerView's whole goal is to only lay out the ideas immediately on screen to prevent needing to lay out all the rest of the items. So you can never get a view that is offscreen.

Why do you need the view? There are ways to work around this limitation. The common case I've seen is needing to get text input - you can handle that by using a text watcher to get all text entered on the view. Alternatively when the model is unbound you can save the view information.

**Comment by Michinggun** [comment]
I need it to show the tooltip for the specific model. To show it, it needs the parent view of the view and the view itself as an anchor. I end up passing the parent view into the EpoxyModel Attribute and then show the tooltip inside the bind method.

Anyway, thanks for your help!

**Comment by elihart** [comment]
Glad you have it figured out, although your workaround doesn't sound ideal.

For the upcoming 2.0 release I think I have a better way for you to accomplish what you need. Check out https://github.com/airbnb/epoxy/pull/140/files#diff-39d3a673e942753a673189e041f70673. It lets you set a click listener to get the model, parent view, clicked view, and adapter position
