### ISSUE TITLE
[OperatorPrecedence] Use grouping parenthesis to make the operator precedence explicit

### ISSUE THREAD

**Issue by engincancan** [airbnb/epoxy#137]
In Epoxy Processor 
`builder.beginControlFlow("if ($L != null && that.$L == null"
                + " || $L == null && that.$L != null)",`
No Operator Precedence exists
[Reference](http://errorprone.info/bugpattern/OperatorPrecedence)

**Comment by elihart** [comment]
https://github.com/airbnb/epoxy/pull/138
