### ISSUE TITLE
Scroll issue with nested RecyclerView

### ISSUE THREAD

**Issue by fahimk** [airbnb/epoxy#141]
I have root RecyclerView that's used with Epoxy, then in one of my Epoxy models I have another RecyclerView (also vertical) where I use a normal RecyclerView.Adapter. Whenever the page loads, the root RecyclerView with the Epoxy adapter scrolls down until the nested RecyclerView is visible.

When I switch nested RecyclerView to having a horizontal LinearLayoutManager, this issue doesn't happen. Have you seen this issue before? When I've tried using them in the past, I've usually had scrolling/sizing issues but those seem to work fine when using Epoxy, the only part that seems to have an issue is that it automatically scrolls into view.

I'll share some more details in case you might be able to suggest an alternative implementation. I'm building something similar to this:
<img src="https://cloud.githubusercontent.com/assets/857824/23574557/5c3281be-0034-11e7-88f2-71401e23976d.png" width="200">

I have the root RecyclerView which adds multiple SettingsContainer epoxy models. SettingsContainer has a title TextView and a RecyclerView that contains the settings items inside it.

**Comment by elihart** [comment]
Hm, there could be several things going on here. I recently had an annoying bug where a recyclerview automatically scrolled down, and the problem ended up being that one of the items declared itself as `focusable` and the layout manager scrolled down to the first focusable item it found. If that isn't your issue I'm out of ideas.

As a side note, I generally don't think it's a good idea to have nested vertical recyclerviews. I think behavior starts to get weird. It seems like you should be able to have just one vertical recyclerview and add all your items in that. If you change the items in your nested adapter to be EpoxyModels that you can easily add them to to the top level adapter. That's really the reason I made Epoxy, so we don't need to deal with extra complexity like that

**Comment by fahimk** [comment]
@elihart I was hoping to use the design compat CardView for the design features and then have the sublists inside, which is why I don't think I can keep all of them as EpoxyModels at the top level. A temporary fix is to add focusableInTouchMode to the top view, I may decide to just use a dynamically created LinearLayout if I see any other issues for the nested adapters.

**Comment by elihart** [comment]
Oh, of course, I see the need now. That definitely gets trickier. I hope the focus changes can make it work for you!

Otherwise you may want to look into modifying https://github.com/airbnb/epoxy/pull/134 to work for your case. I'm waiting for the 2.0 release to polish that and add sample, but it is pretty straightforward and you could copy it and adopt it to your needs
