### ISSUE TITLE
Have generated models implement Parcelable

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#15]
cc @gpeal 

We can generate the parcelable code on models so that they can easily be saved.

If we go this route we may also want to add an easy way for the `models` list on `EpoxyAdapter` to be included in saved state.

**Comment by geralt-encore** [comment]
@elihart what are your thoughts about this one? From my understanding `EpoxyModel` is an essentially `ViewModel`which shouldn't be used outside of view context (`EpoxyAdapter` in our case). So from that perspective `Parcelable` implementation isn't needed and passing `EpoxyModel`s around application is essentially an anti-pattern.

**Comment by elihart** [comment]
I agree, I've never really seen a use for this in our app, we also store the underlying data elsewhere, like in the activity/fragment, and save the state there. we recreate the models from that state when needed.

I thought this might be an interesting improvement that other people might use, but I guess it is not a pattern we can promote. I put this up to see if people would comment about its usefulness and whether they could use it in their application.

So far this one seems like a dud. I'll close it and people can re-open if they have a need for it.
