### ISSUE TITLE
Qualify layout files in annotation processor

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#152]
To prevent collisions between layout resources of the same value from different libraries. We just need to do the same thing as https://github.com/JakeWharton/butterknife/commit/4ad9f9888c4b62476591488cade3aacda80330ba. Should be straightforward

**Comment by geralt-encore** [comment]
Can you elaborate on this one, please? I got the idea more or less, but just want to be sure that I understand it 100% before starting to implement.

**Comment by elihart** [comment]
Sure @geralt-encore. We want to be able to do `@EpoxyModelClass(R.layout.layout_file)`, but at compile time that annotation param value is just an int, and we need to look up the name of the resource so we can turn it back into just `R.layout.layout_file`. Butterknife does some complex thing to be able to do that which I adopted, and it lives in `ResourceProcessor` in Epoxy.

The problem is that when compiling resources from multiple modules there is a risk of collision. An R file from one module (com.module1.R) and another module (com.module2.R) processed their R files separately and might have a layout resource that has the same int value. In this case we can get a collision since we assume a one way mapping between layout resource value and the resource name. We need to change that to consider both resource value and the package of the R file so we don't get collisions.

The change to butterknife to fix this was made by a coworker of mine and it has worked well for us. I think we just need to change Epoxy's `ResourceProcessor` to copy this

**Comment by elihart** [comment]
fixed with https://github.com/airbnb/epoxy/pull/155
