### ISSUE TITLE
Add an information about using setHasStableIds and enableDiffing together

### ISSUE THREAD

**Issue by engincancan** [airbnb/epoxy#157]
If you use setHasStableIds You must set it before enabled using enableDiffing.
OtherWise throws exception.

**Comment by elihart** [comment]
`setHasStableIds(true)` is done automatically in the EpoxyAdapter constructor. Are you setting it to false or something? If you are using diffing you shouldn't have to touch `setHasStableIds`

**Comment by engincancan** [comment]
My mistake. `setHasStableIds(true)` is already doing what I am trying to achieve. So I removed both lines. This issue can be closed. Thanks for pointing that out.
