### ISSUE TITLE
Support data binding

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#183]
I think we can create a new model type that supports databinding. I think we could generate the bind method to assign databinding variables to whatever epoxy attributes are in the class. Then the model would just look like

```
@EpoxyModelClass(layout = R.layout_my_databinding_layout)
public abstract class MyModel extends DataBindingEpoxyModel {
   @EpoxyAttribute int variable1;
   @EpoxyAttribute boolean variable2;
    ... more attributes
}
```

https://medium.com/google-developers/android-data-binding-recyclerview-db7c40d9f0e4 shows how to use generic databinding in view holders which we could build off of.

**Comment by elihart** [comment]
I'm starting work on this, don't think it will be too hard

**Comment by elihart** [comment]
Almost done, it's shaping up nicely :) https://github.com/airbnb/epoxy/pull/188

This is my first time working with data binding, so if anyone more experienced with it wants to take a look at the PR and see if it makes sense or needs anything else, I'd appreciate it!

**Comment by henriquemelissopoulos** [comment]
@elihart I just started last week to use Epoxy and I'm using DataBinding extending EpoxyModelWithHolder and creating the databinding stuff inside the EpoxyHolder:

    public class ExampleEpoxyModel extends EpoxyModelWithHolder<ExampleEpoxyModel.ExampleHolder> {

    private ExampleViewModel viewModel;

    public ExampleEpoxyModel(ExampleViewModel viewModel) {
        this.viewModel = viewModel;
    }

    @Override
    protected int getDefaultLayout() {
        return R.layout.adapter_example;
    }

    @Override
    protected ExampleHolder createNewHolder() {
        return new ExampleHolder();
    }

    @Override
    public void bind(ExampleHolder holder) {
        holder.binding.setViewModel(viewModel);
    }

    @Override
    public void unbind(ExampleHolder holder) {
        super.unbind(holder);
        viewModel.destroy();
    }

    static class ExampleHolder extends EpoxyHolder {
        AdapterExampleBinding binding;

        @Override
        protected void bindView(View view) {
            binding = DataBindingUtil.bind(view);
        }
    }
    }


This could be even simpler creating a superclass<K extends ViewDataBinding> that extends EpoxyModelWithHolder and would take care of the EpoxyHolder creation.

I saw #187 #188 and It's pretty cool that you're supporting DataBinding like that but maybe it doesn't have to be a core Epoxy feature, I don't know what kind of dependency it will need or what kind of future support it will depend on if something change in the DataBinding code generator.

I just wanted to comment that it's actually quite simple to work with databinding and epoxy but as I'm just starting with Epoxy, I still need to make sure if my databinding approach works well with everything the library does.

Databinding + Epoxy = ❤

**Comment by elihart** [comment]
@henriquemelissopoulos Thanks for the input, and I'm glad databinding is working well for you!

You're right that it isn't too hard to use databinding with Epoxy now, but I really love removing boilerplate :P

My goal is to turn the example you posted into just 

```java
@EpoxyModelClass(layout = R.layout.adapter_example)
public abstract class ExampleEpoxyModel extends DataBindingEpoxyModel {
    @EpoxyAttribute ExampleViewModel viewModel;
}
```

I'm almost done with the PR, just need to finish up the tests (hopefully today). Do you think you would use this?

I'm still brainstorming https://github.com/airbnb/epoxy/issues/187 but I don't think it would be too hard. My current plan is to have users make a `package-info.java` class in the package where they want their models generated, and simply list the layouts that they want models generated for.
```
@EpoxyDataBindingModels({R.layout.adapter_example, R.layout.adapter_example2, R.layout.adapter_example3})
package com.airbnb.epoxy.sample;
```

The annotation processor would generate a model like the one posted above that would have all of the variables from the layout so you wouldn't have to make any model code at all. Do you think you would use that?

**Comment by elihart** [comment]
Oh, and about the dependencies concern. Enabling databinding in a library's build.gradle file does not seem to import that setting into apps that use the library. Those apps still need to enable databinding if they want to use it.  Databinding has been out for a while now and seems pretty stable so I'm not too worried about future changes.

We could make the databinding support a separate module that you would need to add a dependency for in addition to the main Epoxy library, but that doens't seem necessary as far as I can tell.

**Comment by elihart** [comment]
https://github.com/airbnb/epoxy/pull/188 is done and will be merged soon.

**Comment by elihart** [comment]
Ah, nevermind I will have to make the databinding a separate module that you import if you want to use databinding.

**Comment by elihart** [comment]
Done with https://github.com/airbnb/epoxy/pull/188. Will be in a 2.1 release
