### ISSUE TITLE
How to support 14

### ISSUE THREAD

**Issue by e-hai** [airbnb/epoxy#192]
failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library

**Comment by elihart** [comment]
@e-hai sdk 14 should work fine, I just haven't tested it or supported it since we use 16+ in our app. The main dependency is the RecyclerView which is 7+.

Feel free to make a fork and try it with 14, or up a PR to update this repo to min sdk 14.

**Comment by kyhule** [comment]
@e-hai I am just experimenting with Epoxy in my project right now which is min sdk 14 so I added this to my `AndroidManifest.xml`: `<uses-sdk tools:overrideLibrary="com.airbnb.viewmodeladapter" />`

**Comment by elihart** [comment]
The manifest override is a good idea. Feel free to reopen this if API 14 doesn't work for some reason, or if you want to push support upstream.
