### ISSUE TITLE
Strategy for setting callbacks for compound ViewGroups with multiple click listeners

### ISSUE THREAD

**Issue by kyhule** [airbnb/epoxy#193]
I have a few compound ViewGroups (class that extends CardView, LinearLayout, etc.) that have multiple clickable elements within the group. What is the best strategy for passing an `AdapterCallbacks` or similar to the view through the view model? This is my first time working with a view model architecture so excuse my ignorance if there is a known strategy for this but I was not able to find any good examples for this.

**Comment by elihart** [comment]
@kyhule There are probably two decent ways to do this. Either pass an interface to the EpoxyModel, or pass each click listener separately. I don't think there is a big difference between the two, unless you just want to decouple your interface from your model code. We have used both approaches in our app.

```
class Model extends EpoxyModel {
        @EpoxyAttribute CallbackInterface callbackInterface;

        @Override
        public void bind(Object view) {
            view.setListener1(v -> callbackInterface.callbackOne());
            view.setListener2(v -> callbackInterface.callbackTwo());
        }
    }

    class Model extends EpoxyModel {
        @EpoxyAttribute OnClickListener listener1;
        @EpoxyAttribute OnClickListener listener2;

        @Override
        public void bind(Object view) {
            view.setListener1(listener1);
            view.setListener2(listener2);
        }
    }
```

**Comment by elihart** [comment]
Closing this for now, let me know if you have further questions!
