### ISSUE TITLE
Support inheriting @AutoModel models from super classes

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#198]
Right now if you extend an EpoxyController and have @AutoModel annotations in both the subclass and parent, the automodels in the parent will not work in the subclass. We need to add support in the annotation processor to include automodels in the parent.

I didn't design the automodels for inheritance, but it shouldn't be too hard to add. We will also have to consider private/package private AutoModels and not generating helpers for abstract controllers.

If anyone wants to work on this I can provide pointers, but otherwise won't prioritize it.

**Comment by tomoima525** [comment]
Hi @elihart 

Adding below in the proguard file fixed the issue. 

```
-keep class * extends com.airbnb.epoxy.EpoxyController { *; }
-keep class * extends com.airbnb.epoxy.ControllerHelper { *; }
```
Adding this setting at  https://github.com/airbnb/epoxy/blob/master/epoxy-adapter/proguard-rules.pro should solve the issue. Can I create the PR?

**Comment by elihart** [comment]
@tomoima525 A PR would be great, thank you!

I don't think the `-keep class * extends com.airbnb.epoxy.ControllerHelper { *; }` line is needed since the EpoxyController classes are not referenced reflectively, only the ControllerHelpers are. Let me know if it doesn't work without that though.

I think we also need to add obfuscation protection. Judging by what Butterknife and Icepick does we would need something like 
```
-keepclasseswithmembernames class * { @com.airbnb.epoxy.AutoModel <fields>; }
```
I'm not too familiar with proguard though so if you understand it better feel free to improve on that.

**Comment by tomoima525** [comment]
`-keep class * extends com.airbnb.epoxy.ControllerHelper { *; }` was needed because auto-generated EpoxyHelper class extends ControllerHelper. I took out `com.airbnb.epoxy.ControllerHelper { *; }` and didn't work.


```
/**
 * Generated file. Do not modify! */
public class FooAdapter_EpoxyHelper extends ControllerHelper<FooAdapter> {...}
```

on the other hand `keepclasseswithmembernames ` is probably not required since `AutoModel ` is just an annotation.

Btw, I was trying to reproduce this issue with `epoxy-sample` project, but epoxy-sample shows a white screen and does not load MainActivity View. (Tried with Android Emulator(OS M, N) and the real device N9(7.1.2))

I just updated Android Studio to 2.3.1, so that might be the cause, but can you take a look if the view shows up?

<img width=300px src="https://cloud.githubusercontent.com/assets/6277118/25468742/b38e6762-2acc-11e7-8597-b80879c25f8d.png"/>

**Comment by tomoima525** [comment]
@elihart Looks like after you merged this PR https://github.com/airbnb/epoxy/pull/194 sample is not working

**Comment by elihart** [comment]
Yep, sorry. I have the fix in the latest pr that is up

**Comment by elihart** [comment]
@tomoima525 Fix is merged, sorry about that!

And before, I quoted the wrong line. I think `-keep class * extends com.airbnb.epoxy.EpoxyController { *; }` is not needed. We definitely need to keep the ControllerHelper classes :P

I think the `keepclasseswithmembernames` is needed to help in the obfuscation case. We take the simple name of the controller and append `_ControllerHelper` to reflectively lookup the helper class. We need to prevent proguard from changing the class name so that the reflective lookup still works.

At least I'm assuming that based on the butterknife proguard comments https://github.com/JakeWharton/butterknife/blob/master/butterknife/proguard-rules.txt

If you want to include that, and possibly test with proguard obfuscation, that would be awesome. Otherwise just the basic proguard rules in a PR would be helpful too :)

**Comment by geralt-encore** [comment]
Looks pretty straightforward. I can look into it.

**Comment by elihart** [comment]
@geralt-encore That would be great if you are still interested. Should be similar to how the model processor finds @EpoxyAttributes to inherit

**Comment by geralt-encore** [comment]
@elihart  yep, just as I thought. Will start working on it soon.

**Comment by elihart** [comment]
awesome :)

**Comment by elihart** [comment]
Done with https://github.com/airbnb/epoxy/pull/216
