### ISSUE TITLE
Running tests for EpoxyProcessor

### ISSUE THREAD

**Issue by geralt-encore** [airbnb/epoxy#20]
Hey! I was really interested in a way that you guys used for testing annotation processor. I tried to run tests on my local machine and all tests failed because of `java.lang.IllegalArgumentException: resource BasicModelWithAttribute.java not found.` and etc. Am I missing something?

**Comment by elihart** [comment]
For some reason tests that are run in Intellij don't pick up on the files in the resources folder. If you run them from the command line with `./gradlew test` it should work though.

I'll add a comment to that test class to make it clear.

**Comment by geralt-encore** [comment]
Thank you for a quick response!
