### ISSUE TITLE
when I run the project,there's nothing

### ISSUE THREAD

**Issue by ailuoyi** [airbnb/epoxy#203]
Sorry to bother you that when I run the project,there's nothing,like these:
![screenshot_2017-04-27-16-28-43](https://cloud.githubusercontent.com/assets/20197174/25474714/c160cc0a-2b66-11e7-9211-251898bafb89.png)

**Comment by elihart** [comment]
yeah, I broke it a few days ago :( the fix is bundled in https://github.com/airbnb/epoxy/pull/202

Sorry about that! it'll be merged soon

**Comment by elihart** [comment]
Fix is merged :)
