### ISSUE TITLE
Scrolling and notifying

### ISSUE THREAD

**Issue by jayachandrak** [airbnb/epoxy#209]
I am new to epoxy could please guide me how to scroll and notify  when model changes or some loader model is added

when we are using TypedEpoxyController or EpoxyController

**Comment by elihart** [comment]
Same with either TypedEpoxyController or EpoxyController.

You can override `onModelBound` in the controller, or do `loaderModel.onBind(listener)`. This will tell you when the model has its view bound and comes on screen. Note that the `onBind` method is only available on generated models.

If you want to know when a model changes you can override the `bind(T view, EpoxyModel<?> previouslyBoundModel)` inside the model. Alternatively you can add a normal observer to the adapter and listener for when an item change happens.
