### ISSUE TITLE
Is this support used in library?

### ISSUE THREAD

**Issue by CSnowStack** [airbnb/epoxy#214]
It generates classes,but cannot use it.
such as
`public class ListVideoModel_ extends ListVideoModel implements GeneratedModel<ListVideoModel.ViewHolder>`
it tips that ListVideoModel cannot find declaration to go to.
When I move it into applicaton inside, it can be used

**Comment by elihart** [comment]
Sorry, I don't understand the question completely. You're saying you can't use the generated class `ListVideoModel_`? can you provide the exact error message or stacktrace, and can you paste your model code as well?

**Comment by CSnowStack** [comment]
thx,i solved it
