### ISSUE TITLE
Add Option for @EpoxyAttribute to be omitted from generated toString method.

### ISSUE THREAD

**Issue by laszlo-galosi** [airbnb/epoxy#215]
It would be handy, if similar to @EpoxyAttribute(DoNotHash) there would be an option that a particular field is omitted from the generated toString() method. Sometimes when debugging, in models with complex fields  the android logcat is noisy by the fields.
I suggest @EpoxyAttrbute(NoToString) or something similar.

**Comment by elihart** [comment]
That should be easy :) I'll try to do it soon

**Comment by geralt-encore** [comment]
@elihart if you haven't done it yet I can do it

**Comment by elihart** [comment]
@geralt-encore if you could do this that would be great :)

**Comment by elihart** [comment]
done with https://github.com/airbnb/epoxy/pull/221
