### ISSUE TITLE
Which is the most efficient way to write a model in Kotlin

### ISSUE THREAD

**Issue by kokeroulis** [airbnb/epoxy#219]
Hello,

I am trying to port my java models into kotlin, so this is my model so far

```
@EpoxyModelClass(layout = R.layout.layout_foo)
abstract class BookModel : EpoxyModel<FooView>() {
    open @EpoxyAttribute var bookName: String = ""
    open @EpoxyAttribute var isRead: Boolean = false
    open @EpoxyAttribute var author: String? = null
    open @EpoxyAttribute(DoNotHash) var listener: View.OnClickListener? = null

    override fun bind(view: FooView?) {
    }

    override fun bind(view: FooView?, previouslyBoundModel: EpoxyModel<*>?) {
    }

    override fun unbind(view: FooView?) {
    }
}
```

So is this the correct way of doing it? Or i have overlooked into something?

Thank you

**Comment by kokeroulis** [comment]
Sorry i forgot to mention that the above is code produces a generated model with infinite loop inside... This applies only to booleans that they have a name as "isSomething" for example

![screen shot 2017-05-22 at 09 31 39](https://cloud.githubusercontent.com/assets/470064/26295266/bcb7036c-3ed1-11e7-858d-ee84f0d60b85.png)

For example the above does work but as soon as you rename the "isRead" property to "read" everything works fine.

In the generated model there is the following code

 ```
  public boolean isRead() {
    return isRead();
  }
```
So can we consider this one a bug of the annotation processor or it is a "misuse" of mine?

**Comment by geralt-encore** [comment]
It is definitely a bug. I'll look into it. Thanks for reporting =)

**Comment by geralt-encore** [comment]
It is definitely a bug. I'll look into it. Thanks for reporting =)

**Comment by elihart** [comment]
Thanks @geralt-encore !

I still haven't used much Kotlin, and not with Epoxy, but can you also set up the model like this?
 `BookModel(@EpoxyAttribute var bookName: String)`

I can update the Wiki for kotlin model recommendations.

@kokeroulis If you wait a few weeks for https://github.com/airbnb/epoxy/issues/171 you may not have to write the model at all btw, so it might not be worth porting all your models if it will be a lot of work for you.

No guarantees on when that feature ships or if it works perfectly for your use case (hopefully with time it'll get there though!), but I'm done with the alpha and we'll be testing it internally this week at least.

**Comment by elihart** [comment]
Fixed with https://github.com/airbnb/epoxy/pull/220

The fix will ship in the 2.2.0 release, which will be out in a few weeks. Until then can you work around it by not using the `is` prefix?

Thanks for reporting!

**Comment by kokeroulis** [comment]
Thank you both!

Yes sure, i can just use the workaround for now (remove the prefix).

Autogenerated models sound nice, i am looking forward for it.

At the moment i am just porting just a little bit that has to do with annotation processing and reflection(epoxy,butterknife, json parser etc) as a proof on concept, that everything works with kotlin and make sure that there are no regressions...
So no worries about the models... :)

**Comment by geralt-encore** [comment]
@kokeroulis btw forgot to mention it earlier: you don't need to mark your properties with `open` since they are not going to be overridden by Epoxy so they are redundant.

**Comment by kokeroulis** [comment]
@geralt-encore yes, that's correct, thanks. I didn't know that, the annotation processor checks that if the getter and setter exists before creating them..

**Comment by elihart** [comment]
I updated the EpoxyModel section of the wiki to explain Kotlin usage
