### ISSUE TITLE
Automatic Diffing not Working

### ISSUE THREAD

**Issue by saurabhdtu** [airbnb/epoxy#223]
Here is my sample implementation where I am using a TypedEpoxyController.
 ```
public class EpoxyAdapterScoreCard extends TypedEpoxyController<CustomClass> {
    CustomClass customClass;
    public EpoxyAdapterScoreCard(CustomClass customClass) {
        this.customClass = customClass;
        setDebugLoggingEnabled(true);
    }

 @Override
    protected void buildModels(CustomClass data) {
        add(new CustomModel(data.paramA));
   }
}

public class CustomModel extends EpoxyModel<LinearLayout> {
    CustomClass.ParamA paramA;

    public CustomModel(CustomClass.ParamA paramA) {
        this.paramA = paramA;
        id("uniqueId_"+ paramA.id);
    }


    @Override
    protected int getDefaultLayout() {
        return R.layout.row;
    }

    @Override
    public int hashCode() {
        return paramA.id;
    }

    @Override
    public boolean equals(Object o) {
        CustomModel model = (CustomModel) o ;
        return (model.paramA.someValue == this.paramA.someValue);
    }

  public class BattingModel extends EpoxyModel<LinearLayout> {
    private Batsman batsman;
    private int homeCaptainId;
    private int awayCaptainId;

    public BattingModel(Batsman batsman, int homeCaptainId, int awayCaptainId) {
        this.batsman = batsman;
        this.homeCaptainId = homeCaptainId;
        this.awayCaptainId = awayCaptainId;
        id(Types.StatsStaticEpoxyIds.BAT_DATA + batsman.playerId);
    }


    @Override
    protected int getDefaultLayout() {
        return R.layout.item_stat_batting;
    }

    @Override
    public int hashCode() {
        return batsman.playerId;
    }

    @Override
    public boolean equals(Object o) {
        BattingModel bat = (BattingModel) o ;
        return (batsman.onStrike + batsman.nonStrike + batsman.runs + batsman.ballsFaced + batsman.howOut.length()) ==
                (bat.batsman.onStrike + bat.batsman.nonStrike + bat.batsman.runs + bat.batsman.ballsFaced + bat.batsman.howOut.length());
//        return (Types.StatsStaticEpoxyIds.BAT_DATA + batsman.playerId).equals(Types.StatsStaticEpoxyIds.BAT_DATA + bat.batsman.playerId);
    }

    @Override
    public void bind(LinearLayout view) {
        super.bind(view);
       TextView tv = (TextView)view.findViewById(R.id.tv_place);
       tv.setText(paramA.someValue.toString());
    }
}

```
I had previously used @EpoxyAttribute annotation with the **paramA** in the customObject but the diffing didn't work when I called the setData() method of the adapter.
I am not using the @EpoxyAttribute annotation now and I am trying to override the hash() and equals() method. 
But still it's not working. Can you please tell me what's going wrong here ?

**Comment by elihart** [comment]
well, your build models method is doing
```
  protected void buildModels(Inning data) {
       add(new CustomModel(customClass.paramA));
  }
}
```

which is not using the `Inning data` parameter, but instead using the `customClass` field. That field will not change, the Inning data is what is changing when you setData.

**Comment by saurabhdtu** [comment]
Sorry I wrote that by mistake. My bad.. I have edited my issue . 
After this I even tried the EpoxyAdapter, which has the notifyModelsChanged() and enableDiffing() methods thinking it might work, but it resulted into the code getting quite messy.

**Comment by elihart** [comment]
Your controller code only uses `CustomModel`, why are you also including code for the `BattingModel`?

The hashCode and equals methods for `CustomModel` are not correct, these are checking different values. I'd recommend reading up on proper hashCode/equals implementation and making sure you are doing it correctly. Also, the `CustomClass.ParamA` class should just implement equals/hashCode internally instead of inside the model. Use android studio to autogenerate the correct equals/hashcode implementations for you.

Are you creating a new `CustomModel` object or reusing the same one? If you are reusing the same one diffing won't work since you will be comparing the exact same object instance.

I would recommend changing your code to :
```
@EpoxyModel(layout = R.layout.row)
public class CustomModel extends EpoxyModel<LinearLayout> {
   @EpoxyAttribute CustomClass.ParamA paramA;
}

public class EpoxyAdapterScoreCard extends TypedEpoxyController<CustomClass> {

   public EpoxyAdapterScoreCard() {
       setDebugLoggingEnabled(true);
   }

@Override
   protected void buildModels(CustomClass data) {
       new CustomModel_()
                     .id(data.paramA.id)
                     .paramA(data.paramA)
                      .addTo(this);
  }
}
```

CustomClass and paramA should be immutable and not reused. Make sure your equals/hashCode methods are correct.

**Comment by elihart** [comment]
going to assume that fixed it and closing for now unless you still have problems
