### ISSUE TITLE
Generate EpoxyModel classes from EpoxyModelWithHolder in Kotlin Android project

### ISSUE THREAD

**Issue by zaihuishou** [airbnb/epoxy#230]
I want to create an "EpoxyModelClass" by user @EpoxyModelClass annotation  in Kotlin Android project ,but it is not work,it it a big problem for me

**Comment by elihart** [comment]
what is the problem exactly? Do you have error messages or more information?

**Comment by zaihuishou** [comment]
@elihart  I have a sbclass of EpoxyModelWithHolder named BillAllModel,it use @EpoxyModelClass annotation,BillAllModel_ class is created automatically,but i cannot use it in kotlin fragment
![screenshot from 2017-06-11 11-44-11](https://user-images.githubusercontent.com/3625066/27008084-5b37f6c6-4e9b-11e7-8f07-5b158b032cb4.png)

**Comment by elihart** [comment]
Are you using it with `@AutoModel`? Did you follow the instructions at https://github.com/airbnb/epoxy/wiki/Epoxy-Controller#usage-with-kotlin ?

**Comment by elihart** [comment]
If you can post your source code I can take a closer look (including the model, controller, and fragment)

**Comment by elihart** [comment]
Seems like you got this figured out

**Comment by meierjan** [comment]
Getting the same one while making my first steps with Epoxy. I am not using `@AutoModel`.

Just a `EpoxyController` and a `EpoxyModelWithHolder`.

The files seem to be generated as I can reference them in my project. But when I hit 'run' the generated class can not be found.

@zaihuishou How did you fix this?

**Comment by elihart** [comment]
The kotlin setup instructions were a bit hidden in the wiki, I've moved them to the top of the main readme so it is more clear.

**Comment by Saravanan1049** [comment]
how to do swipe in epoxy. I'm struggling with that one.
**Note** -- I don't want full swipe,          half swipe only
