### ISSUE TITLE
Span count improper layout 

### ISSUE THREAD

**Issue by jayachandrak** [airbnb/epoxy#237]
When we change the span count items aligned improper on gridlayout manager
 linearLayoutManager.setSpanCount(defaultSpanSize);
//        mGridController.setSpanCount(defaultSpanSize);
        recyclerView.setLayoutManager(linearLayoutManager);
        recyclerView.postInvalidate();
        linearLayoutManager.requestLayout();
![device-2017-07-02-110140](https://user-images.githubusercontent.com/1639425/27767469-38472d5e-5f16-11e7-93ec-03eade032256.png)
![device-2017-07-02-110200](https://user-images.githubusercontent.com/1639425/27767472-454fc0a6-5f16-11e7-9102-24d59726a967.png)

Need alternative for notifyDatasetChanged() i have tried with controller.setData(list) but it didn't worked

**Comment by elihart** [comment]
I'm a bit confused what you are doing, if you can post full code samples that would help.

It seems like the square layouts on portrait are not resizing in landscape?

Are you handling rotation manually and dynamically changing the span size to handle the configuration change?

By default a model's span size does not affect its state, so if you only change a model's span size it will not update the view.

You generally shouldn't be calling this manually
```
recyclerView.postInvalidate();
linearLayoutManager.requestLayout();
```
