### ISSUE TITLE
Getting Exception on Epoxy 2.2.0

### ISSUE THREAD

**Issue by saurabhdtu** [airbnb/epoxy#238]
I am implementing infinite scrolling with load more option.
This is my code ..
```
   public class AdapterUserProfile extends TypedEpoxyController<Profile> {
     public static final int FLAG_LOAD_MORE = 0, FLAG_MATCH_HISTORY_CLICKED = 1, 
     FLAG_CHOOSE_TEAMS = 2;
    private boolean isMyProfile;
    private ListItemClicked listItemClicked;
    private boolean loadMore;

```
   ```
 public AdapterUserProfile(boolean isMyProfile, ListItemClicked listItemClicked, boolean loadMore) {
        this.isMyProfile = isMyProfile;
        this.listItemClicked = listItemClicked;
        this.loadMore = loadMore;
        setDebugLoggingEnabled(true);
    }

    @Override
    protected void buildModels(Profile data) {
        Log.i("History Size", ""+data.getMatchHistories().size());

        add(new ProfileHeader(isMyProfile, data));

        add(new ProfileTeams(isMyProfile, data.getSportsFan().getTeams(), listItemClicked));

        if (data.getSportsFanSummaryResponse() != null)
            add(new MatchHeader());
        try {
            for (UserMatchHistory userMatchHistory : data.getMatchHistories())
                add(new MatchHistory(listItemClicked, userMatchHistory));
        }catch (Exception e){
            e.printStackTrace();
        }

        if (loadMore)
            add(new LoadMore(new Boolean(loadMore)));
    }

    public void setLoadMore(boolean loadMore) {
        this.loadMore = loadMore;
    }

    @Override
    protected void onModelBound(EpoxyViewHolder holder, EpoxyModel<?> boundModel, int position, @Nullable EpoxyModel<?> previouslyBoundModel) {
        super.onModelBound(holder, boundModel, position, previouslyBoundModel);
        if (boundModel instanceof LoadMore) {
            listItemClicked.itemClicked(0, null, FLAG_LOAD_MORE);
        }
    }
}
```
The load more flag is set to false when there is nothing left more to fetch.
I am getting this exception mostly on the second or third time when the activity starts.
The problem is while binding the match history items sometimes the layout for LoadMore model is binded to the MatchHistory model. And results in the error because the LoadMore model is a RelativeLayout while the MatchHistory model is LinearLayout.

 java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.LinearLayout
at com.threesixteen.app.models.epoxy.MatchHistory.bind(MatchHistory.java:20)
at com.airbnb.epoxy.EpoxyModel.bind(EpoxyModel.java:100)
at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:43)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:106)
at com.airbnb.epoxy.EpoxyControllerAdapter.onBindViewHolder(EpoxyControllerAdapter.java:9)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:14)

**Comment by saurabhdtu** [comment]
Currently I have temporarily fixed it by changing the LoadMore model to LinearLayout so that bind exception doesn't occur . More over I have put a null check on MatchHistory model ui element so that whenever the Binder tries to inflate and bind the LoadMore layout in MatchHistory model , NullPointerException doesn't occur on UI Elements.
But, its just a temporary fix... Whats the correct way to implement the infinite scrolling, without the models and their layout getting jumbled up.

**Comment by elihart** [comment]
The class cast exception is probably happening because model ids are not properly defined. I don't see where you are setting ids, are you doing it inside the models? Also, why do you have a try/catch when adding the match history model? Catching errors is almost never the right thing to do.

The AutoModel system was designed to guarantee correct ids for you. any reason you're not using that? Also, it doesn't seem like you're using generated models, why not? I'm guessing you also don't have your models set up correctly.

Have you looked through all of the sample app and the full wiki? Many of these things are addressed there with examples.

This is how I would rewrite that controller
```
public AdapterUserProfile(boolean isMyProfile, ListItemClicked listItemClicked, boolean loadMore) {
     this.isMyProfile = isMyProfile;
     this.listItemClicked = listItemClicked;
     this.loadMore = loadMore;
     setDebugLoggingEnabled(true);
 }

@AutoModel LoadingModel_ loadingModel;
@AutoModel MatchHeader_ matcherHeader;

 @Override
 protected void buildModels(Profile data) {

     add(new ProfileHeader(isMyProfile, data));

     add(new ProfileTeams(isMyProfile, data.getSportsFan().getTeams(), listItemClicked));

         matchHeader
                 .addIf(this, data.getSportsFanSummaryResponse() != null);

         for (UserMatchHistory userMatchHistory : data.getMatchHistories()) {
             add(new MatchHistory(listItemClicked, userMatchHistory));
         }
```


         loadingModel
           .onBind( -> listItemClicked.itemClicked(0, null, FLAG_LOAD_MORE))
           .addIf(this, loadMore);
 }

 public void setLoadMore(boolean loadMore) {
     this.loadMore = loadMore;
 }
}
```

**Comment by elihart** [comment]
Assuming you figured this out

**Comment by chrisjenx** [comment]
@saurabhdtu what was your fix to this?
