### ISSUE TITLE
Can't generate xxxMode_.java when I use databinding in library projects(module project)

### ISSUE THREAD

**Issue by matrixxun** [airbnb/epoxy#239]
I have already create package-info.java, but still not generate xxxxMode_.java. Does epoxy's databinding support library(module) project?

**Comment by elihart** [comment]
See https://github.com/airbnb/epoxy/issues/226

In short, it does work with library projects, but relies on the R2 file generated by butterknife's gradle plugin. however, that plugin doesn't yet support layout resources, so we use a forked version of the library with a change seen in that issue linked above ^

The change was recently merged though and should be available through a main butterknife release soon

**Comment by matrixxun** [comment]
Thanks @elihart, I know why can't generate model class. As you say because package-info.java used "@EpoxyDataBindingLayouts(R.layout.button)" annotation and butterknife's R2 can't support layout resource.
I didn't have any choice but to wait for butterknife release...

**Comment by elihart** [comment]
Sorry :( hopefully it will be soon.

I'll update #226 when it is released

**Comment by elihart** [comment]
it's released :)

**Comment by matrixxun** [comment]
high efficiency！

**Comment by matrixxun** [comment]
Unfortunately, After I change butterknife's version to 8.7.0, my library project can't still generate **HeaderViewModel_.java** and **ButtonBindingModel_.java** in _build/generated/source/apt/....._  when i port "**epoxy-sample**" to my library project. but **ImageButtonModel_.java** auto generate successfully, So it's something wrong with @ModelView and databinding in library project?

**Comment by elihart** [comment]
when you ported the sample project, did you apply the butterknife gradle plugin and change all R usages to R2 in the annotations?

Is there a specific error that you get?

**Comment by matrixxun** [comment]
no specific error i get.
 I have already apply the butterknife gradle plugin and change all R usages to R2 in the annotations, but still does't work.
