### ISSUE TITLE
Package private field with @EpoxyAttribute annotation breaks when the class is extended in a different package

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#25]
Can either not include those in the generated class or throw an error at generation time

**Comment by geralt-encore** [comment]
I can do it. Which option is better in your opinion?

**Comment by elihart** [comment]
@geralt-encore That would be great!

I've been thinking about the best option, doesn't seem like a clear cut winner.

So far I'm thinking that we should take the route of not including package private attributes in the generated class if the class they came from is in a different package. If the field is package private then the developer should have had the intention that subclasses can't access them anyway.

 I'm a little worried about confusion arising from this if people see their annotated fields being ignored by the generator, but it should be a very uncommon case and we can add details in the readme.

Additionally, we can change the generated equals method to cast the object to the generated class instead of the base class so that `protected` fields in a different package can be accessed.

Does that make sense?

**Comment by geralt-encore** [comment]
Totally makes sense

**Comment by geralt-encore** [comment]
To be sure that we are on the same page could you please provide the simplest possible example of the problem?

**Comment by elihart** [comment]
Sure.

Say we have `ClassA extends EpoxyModel` in package `exampleA`. Then we extend that class with `ClassB extends ClassA` in a different package `exampleB`.

The processor looks for fields with @EpoxyAttributes in all super classes. So @EpoxyAttribute fields on ClassA  will be included in the generated class for ClassB.

However, if those fields on ClassA are package private, ClassB can't access them. Since ClassB's generated class is in the same package as ClassB the generated class won't be able to access the fields as well.

I'm hoping we can detect that problem and just not include those fields.

There is also a problem with protected fields on ClassA, since the generated code for ClassB creates an equals method that casts the object to ClassB, in which case ClassB_ doesn't have access to the protected fields on ClassA.

 If we change this to cast the object to `ClassB_` then the generated code will have proper access.

Hopefully that makes sense :P

**Comment by elihart** [comment]
https://github.com/airbnb/epoxy/pull/47
