### ISSUE TITLE
group model event handling

### ISSUE THREAD

**Issue by yumcoder-platform** [airbnb/epoxy#253]
suppose a group model (Horizontal Linearlayout) that consist of two models: 
TextViewModel       SwitchViewModel

how to pass click event of a TextViewModel to toggle() method of SwitchViewModel ?

**Comment by yumcoder-platform** [comment]
as example the following image compose of a 3 column group model
ImageViewModel          TextViewModel        SwitchViewModel

![image](https://user-images.githubusercontent.com/29568969/28868187-e90e5182-778d-11e7-959d-9d6647bf0208.png)

I want toggle()  SwitchView when click ImageViewModel or TextViewModel?

**Comment by elihart** [comment]
@yumcoder-platform This isn't the intended use case for models. you should have a single view/model that is a horizontal linear layout that includes everything in the row. if you are concerned about reusing models and having to create more of them, I would recommend that you either use the @ModelView annotations to generate models automatically, or databinding to automatically generate a model from an xml layout.

the model group is intended for grouping more complicated models that need to be kept in proximity, but still operate autonomously.

**Comment by yumcoder-platform** [comment]
thanks.

**Comment by yumcoder-platform** [comment]
I would be grateful if you could give me feedback on the following solution:

```
public abstract class SwitchButtonModel extends EpoxyModelWithHolder<SwitchButtonModel.ImageButtonHolder> {

    public interface Services {
        void toggle();
    }
    
    public static class Exposed {
        public Services services;
    }

    @EpoxyAttribute(DoNotHash)
    Exposed exposed;

    @Override
    public void bind(ImageButtonHolder holder) {
        super.bind(holder);
        try{
            exposed.services = holder;} catch (Exception e){/*ignore*/}
      // ...
    }

    @Override
    public void unbind(ImageButtonHolder holder) {
        super.unbind(holder);
        // Release resources and don't leak listeners as this view goes back to the view pool
        // ...
        exposed.services = null;
    }

    @Override
    protected ImageButtonHolder createNewHolder() {
        return new ImageButtonHolder();
    }

    public static class ImageButtonHolder extends YumcoderHolder implements Services {
        @BindView(R2.id.switch_button)
        Switch switchButton;

        @Override
        public void toggle(){
            switchButton.toggle();
        }
    }

}
```

and in a factory method that create a composite group model, we can use as follow:

```
        SwitchButtonModel_ sm = new  SwitchButtonModel_();
        // ...
        final SwitchButtonModel.Exposed exposed = new SwitchButtonModel.Exposed();
        sm.exposed(exposed);

         View.OnClickListener listener = new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                exposed.services.toggle();
            }
        };

        TextViewModel_ titleTextModel = new TextViewModel_();
        // ...
        titleTextModel.clickListener(listener);


```

**Comment by elihart** [comment]
@yumcoder-platform I'd highly recommend not splitting your models like that. Like I mentioned before, model groups are not meant to be used that way.

Instead you should create a single view and model that defines the whole row. I'd recommend you use a custom view with @ViewModel annotations, or use a single xml layout with databinding.
