### ISSUE TITLE
Sample Wanted: work with android.content.ContentResolver Cursor

### ISSUE THREAD

**Issue by conanchen** [airbnb/epoxy#259]
Hi, 
Is there any sample that  epoxy controller work with the cursor ?  if epoxy controller don't support to work with the cursor, any suggestion?

Thanks.

**Comment by elihart** [comment]
I don't have experience with this, but it should work fine. You'll have to handle loading from cursor yourself though, and request a model build when the cursor is updated, and use the cursor to build your models inside `buildModels`.

If you get it working and want to contribute a sample that would be great :)

**Comment by elihart** [comment]
@conanchen were you able to get something working?

**Comment by elihart** [comment]
This article shows a good general approach for using a cursor with a recyclerview - https://medium.com/@JasonWyatt/how-to-use-asynclistutil-16b5175bb468

It should be easy to adapt that approach to Epoxy.
