### ISSUE TITLE
Create Kotlin DSL for building models in controllers

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#270]
We can generate an extension function for each model, so building models would look like
```
buildModels() {
  headerView {
         id("header")
         title("my title")
  }
}
```

**Comment by geralt-encore** [comment]
I'll try to look into it if you don't mind. Looks very interesting!

**Comment by elihart** [comment]
I've actually already started :) I got kotlin poet hooked up and the basics working, it's exciting!

**Comment by geralt-encore** [comment]
Got it. Have fun! Feel free to ping me if you need any help =)

**Comment by elihart** [comment]
thanks :) you can check it out at https://github.com/airbnb/epoxy/compare/eli-kotlin

It's actually pretty straightforward, figuring out kotlin poet was the tricky part, and I'm updating to android studio 3.0 at the same time :P

**Comment by elihart** [comment]
@geralt-encore it would be good to get your feedback on a few ideas on this actually.

1. don't use AutoModel with this and instead declare id as a string, as in the example. I think grouping all the code for a single model like that is easier to read, but I wish there was a better way to force somebody to add the id, if you forget it it is a runtime error, not sure how to build that into the DSL

2. I want to support a condition that when false would skip that model. I'm thinking
```
headerView(condition = myBoolean) {
         id("header")
         title("my title")
  }
```
I like that this is concise, and it is a nice optimization since the model is never created if the condition fails. not sure if there is a better syntax for this though

3. The generated model interface is quite messy right now. There is a ton of old features included on it and things that don't apply when building the model (show/hide/bind/equals/toString etc) plus all of the getters. This makes autocomplete confusing and makes it hard to understand what the actual options are for setting properties on the model. I'm thinking we can generate an interface that contains all of the actual setters and only expose that interface as the receiver of the lambda. Then autocomplete would only suggest  `id` and `title`

4. Should the function return the generated model? I'm thinking not, since at that point its already added to the controller and i don't want to encourage funky behavior by making it easy to keep a reference to it.

5. I'd like the function name to remove "model" wording from it. If the model is `HeaderViewModel` the generated function would be `headerView`. In the context of building models I think appending `model` is redundant and verbose

6. I'm thinking that the functions should be in the same package as the models. All models in the same package will have their own file

**Comment by elihart** [comment]
An example of a generated extension function is 
```
inline fun EpoxyController.kotlinView(condition: Boolean = true,
    modelInitializer: KotlinViewModel_.() -> Unit) {
  if (condition) {
    val model = KotlinViewModel_()
    model.modelInitializer()
    model.addTo(this)
  }
}
```

**Comment by geralt-encore** [comment]
Sorry that I took me so long to get back to you with it =(

1. Totally agree.
2. This doesn't look right to me. I don't think that DSL has to support all the features. It needs to be simple, easy and straightforward because if it is overcomplicated it would be hard to read. If you need conditions then I think that your model is not easy enough to describe it with DSL and it would be better to just go with the standard approach.
3. That sounds really good!
4. +1
5. It's totally up to you. Don't think that it will make much difference. But it might be confusing for someone, I guess.
6. Yep.

Regarding your function example:

```
 val model = KotlinViewModel_().apply {
    modelInitializer()
    addTo(this)
 }
```
This is the more Kotlin way to do it =)

**Comment by elihart** [comment]
Thanks a lot for the feedback! I have the interface work done https://github.com/airbnb/epoxy/pull/277 so this should all come together pretty soon.

I think you're right about the condition case.
I was trying to avoid
```
if (shouldHeaderBeShown) {
            headerView {

            }
}
```

but I just realized this can be written as 
```
if (shouldHeaderBeShown)  headerView {

}
```

which is more clear and standard

Thanks for the kotlin tips :)

**Comment by elihart** [comment]
Pretty much done :) https://github.com/airbnb/epoxy/pull/278
