### ISSUE TITLE
Integrate with Paging Library component

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#285]
We should be able to create an EpoxyController subclass that makes it easy to work with this new component - https://developer.android.com/topic/libraries/architecture/paging.html

**Comment by abeemukthees** [comment]
I'm also looking for this integration.

**Comment by elihart** [comment]
I don't think it will be _too_ hard, but I also haven't looked at the source yet. I can maybe do it next week, but if someone else wants to jump on it that'd be great :)

**Comment by geralt-encore** [comment]
I wouldn't mind trying to take look at it. Can't promise anything tho

**Comment by elihart** [comment]
I actually was able to get started on this https://github.com/airbnb/epoxy/compare/eli-paging

Main work is in https://github.com/airbnb/epoxy/compare/eli-paging#diff-4c2e75cdcce43d0f970a208f344fb1c4

I haven't tested it yet, but it seems pretty straightforward. The one issue I can see is that we would have to iterate over all items in the list, including all the null (unloaded) ones. I'm looking for a way around that.

**Comment by geralt-encore** [comment]
Yep, looks pretty straightforward. Let me know if you'll need any help =)

**Comment by elihart** [comment]
What I have seems to work fine. There is a performance issue though as more items are loaded into the paged list. The paged list starts with just a few items, but as more items are loaded it seems like the list only ever grows larger - eg items from the beginning are not removed as you scroll down and  more items are loaded at the end. 

This is an issue because Epoxy is set up to build a model for each item, but it gets slow to build hundreds or thousands of items and diff them.

I am thinking that we can build a layer of paging on top of the paged list. Basically Epoxy can track where in the list the current bound items are, and only build models for the items around that. As you scroll epoxy would rebuild models as needed.

This seems doable, but will take some tweaking to optimize. The benefit is this will actually be useful for all list cases, not just the new Paged List arch component.

In my branch I've added a working sample. If anyone wants to take a look and discuss feel free to leave feedback here

**Comment by elihart** [comment]
Good progress with https://github.com/airbnb/epoxy/pull/306

**Comment by elihart** [comment]
Closing this since a basic version is done. We can track improvements in separate dedicated issues
