### ISSUE TITLE
LiveData and Paging Library Integration

### ISSUE THREAD

**Issue by juanpmarin** [airbnb/epoxy#287]
Hi, how are you ? 

As you know, recently google has released Livedata and a Paging Library that generates an adapter

[https://developer.android.com/topic/libraries/architecture/paging.html](https://developer.android.com/topic/libraries/architecture/paging.html)

Paging would works well with epoxy but currently I must choose between the Paging Adapter or the Epoxy Adapter, what do you think ?

**Comment by elihart** [comment]
Hey there, I'm definitely interested in supporting this. Already tracking it here https://github.com/airbnb/epoxy/issues/285
