### ISSUE TITLE
error: package DataBindingEpoxyModel does not exist

### ISSUE THREAD

**Issue by markus2610** [airbnb/epoxy#290]
I get a error. In the generate code will not found the DataBindingEpoxyModel.DataBindingHolder.

The import is generated as follows:
import com.airbnb.epoxy.DataBindingEpoxyModel.DataBindingHolder;

So would it right without error:
import com.airbnb.epoxy.DataBindingEpoxyModel;

[Sample project on Github](https://github.com/markus2610/Epoxy-databinding)

**Comment by elihart** [comment]
Thanks for providing the sample, I'll try to fix this soon. sorry for the issue!

**Comment by elihart** [comment]
Hm, this almost seems like a bug with javapoet, it isn't adding the import for the class.

I'll try to find a fix and put up a new release soon

**Comment by elihart** [comment]
This issue should only exist on 2.5.0. 2.4.0 should work fine for you for now

**Comment by markus2610** [comment]
Yes with 2.4.0 no error

**Comment by elihart** [comment]
Fixed with https://github.com/airbnb/epoxy/pull/294. I'll try to have a release out early this week with the change.
