### ISSUE TITLE
Is there any reason to put generated Model_.java under the build folder?

### ISSUE THREAD

**Issue by basin0809** [airbnb/epoxy#297]
First, thanks to this excellent lib! Making complex recyclerview is much more efficient now.
Yet I have a question: Every time I clean build the project, or my company's Tech Ops run the new build on their buildServer, we have to re-build the whole project locally in order to generate the model_.java files before run the project and generate the apk (we don't want to push the build folder to our branch, it is a temp folder after all and should be put in .ignore file). This is kind of inconvenient, and seems that each modification to the model classes requires a local re-build operation.
Is there any possibility to generate these model_ classes under the source folder? I know I can write my own model classes to include functions like setter(), getter() and implements Parcelable, but who don't like the auto-generate feature?

**Comment by yihuaqi** [comment]
@basin0809 Since these generated class are used in production anyway, what is the difference if you choose not to ignore the auto-generated files in build folder than you put them in src folder?

**Comment by elihart** [comment]
No, the way annotation processors work is all code is generated in the build folder. It shouldn't be checked into version control.

You have to build anyway every time you want to create the apk or change a local file anyway, unless your build server is doing something I'm not familiar with.
