### ISSUE TITLE
Epoxy processor generates EpoxyModelKotlinExtensions.kt class from models without EpoxyModelClass annotation

### ISSUE THREAD

**Issue by kusraevs** [airbnb/epoxy#313]
I have epoxy models without EpoxyModelClass annotations in my library project. So that subclasses shouldn't be generated for them. But  EpoxyModelKotlinExtensions.kt file has unresolved references on this classes and project doesn't compile.

Note: to reproduce the issue you should have EpoxyModel classes with fields annotated as EpoxyAttribute but classes themselfs shouldn't be annotated as EpoxyModelClass.
I use this to have abstract base epoxymodel classes for multiple models inherited from them.

**Comment by elihart** [comment]
@kusraevs I just released 2.6.0 which I believe will fix your problem. Please try that and let me know if it is still broken

**Comment by kusraevs** [comment]
Now it works, thanks
