### ISSUE TITLE
RecyclerView scroll issues with PagingEpoxyController

### ISSUE THREAD

**Issue by pcqpcq** [airbnb/epoxy#325]
I have a RecyclerView with PagingEpoxyController, and when I insert some data to db, then scroll RecyclerView to bottom, and keep doing this (insert some data then scroll to bottom), something wrong will happen, sometimes RecyclerView can't scroll and sometimes it auto scroll to top, here is the code:

[UserEntity](https://github.com/airbnb/epoxy/blob/master/epoxy-pagingsample/src/main/java/com/airbnb/epoxy/pagingsample/DataBaseSetup.kt#L12), [UserDatabase](https://github.com/airbnb/epoxy/blob/master/epoxy-pagingsample/src/main/java/com/airbnb/epoxy/pagingsample/DataBaseSetup.kt#L7), [UserDao](https://github.com/airbnb/epoxy/blob/master/epoxy-pagingsample/src/main/java/com/airbnb/epoxy/pagingsample/DataBaseSetup.kt#L24) and [PagingView](https://github.com/airbnb/epoxy/blob/master/epoxy-pagingsample/src/main/java/com/airbnb/epoxy/pagingsample/PagingSampleActivity.kt#L81) just like the [paging sample](https://github.com/airbnb/epoxy/tree/master/epoxy-pagingsample), only change the uid to long type.
Then loading data like this:  

```java
// ...

userListController = new UserListController();
recyclerView.setAdapter(userListController.getAdapter());

// ...

db.userDao()
    .all()
    .create(0, new PagedList.Config.Builder()
    .setPageSize(100)  // <<---- note this page size
    .setEnablePlaceholders(true)
    .setPrefetchDistance(50)
    .build())
    .observe(this, new Observer<PagedList<User>>() {
	    @Override
	    public void onChanged(@Nullable PagedList<User> users) {
	        userListController.setList(users);
	    }
    });
```

And the controller, nothing special:
```java
public class UserListController extends PagingEpoxyController<User> {
        @Override
        protected void buildModels(List<User> list) {
            int size = list.size();
            for (int i = 0; i < size; i++) {
                User user = list.get(i);
                if (user == null) {
                    continue;
                }
                new PagingViewModel_()
                        .id(user.getUid())
                        .index("index > " + i)
                        .addTo(this);
            }
        }
    }
```

 I've try setNumPagesToLoad() and setPageSizeHint(), but nothing change, so I remove them here and let them use default values.

And insert new data like this, **insert 50 items every time**:

```java
long seed = System.currentTimeMillis();
for (int i = 0; i < 50; i++) {
    db.userDao().insertAll(new User(seed++));
}
```

Then, keep doing with **insert new data then scroll to bottom** 

When load 300 items, then load 300-350, the RecyclerView can't scroll, look like the RecyclerView have touch the end.

And if I change the **pagesize** to 50, 
(although accord to the [doc](https://developer.android.com/reference/android/arch/paging/PagedList.Config.Builder.html#setPageSize(int)), this is not a good idea), then keep insert new data and scroll to bottom, when load 350 items, then load 350~400, the RecyclerView will auto scroll to top.

==================

If need, I can push my demo code for testing.

**Comment by pcqpcq** [comment]
I don't think it is a bug with Android Paging Library it self, because when I doing this with only Paging Library, every thing work just fine:

```java
// ...
userAdapter = new UserAdapter();
recyclerView.setAdapter(userAdapter);

//...

db.userDao()
    .all()
    .create(0, new PagedList.Config.Builder()
    .setPageSize(100)
    .setEnablePlaceholders(true)
    .setPrefetchDistance(50)
    .build())
    .observe(this, new Observer<PagedList<User>>() {
	  @Override
	  public void onChanged(@Nullable PagedList<User> users) {
	      userAdapter.setList(users);
	  }
    });
```

And the adapter class, nothing special:

```java
public class UserAdapter extends PagedListAdapter<User, UserAdapter.UserViewHolder> {

    public UserAdapter() {
        super(DIFF_CALLBACK);
    }

    @Override
    public UserViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new UserViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.user_item, parent, false));
    }

    @Override
    public void onBindViewHolder(UserViewHolder holder, int position) {
        holder.bindTo(position);
    }

    static final DiffCallback<User> DIFF_CALLBACK = new DiffCallback<User>() {
        @Override
        public boolean areItemsTheSame(@NonNull User oldUser, @NonNull User newUser) {
            // User properties may have changed if reloaded from the DB, but ID is fixed
            return oldUser.getUid() == newUser.getUid();
        }

        @Override
        public boolean areContentsTheSame(@NonNull User oldUser, @NonNull User newUser) {
            // NOTE: if you use equals, your object must properly override Object#equals()
            // Incorrectly returning false here will result in too many animations.
            return oldUser.getFirstName().equals(newUser.getFirstName());
        }
    };

    static class UserViewHolder extends RecyclerView.ViewHolder {

        TextView index;

        public UserViewHolder(View view) {
            super(view);
            index = view.findViewById(R.id.user_index);
        }

        public void bindTo(int position) {
            index.setText("index > " + position);
        }

    }

}
```

**Comment by pcqpcq** [comment]
I don't know why yet, but looks like something related to the **pagesize**.

**Comment by elihart** [comment]
Are you scrolling to the bottom programmatically (eg recyclerview.scrollTo) or via touch input?

**Comment by elihart** [comment]
Also, can you try to set `setEnablePlaceholders(false)`? The epoxy documentation says to disable placeholders

**Comment by pcqpcq** [comment]
1. I scroll with finger touch, not programmatically.

2. Forgot to say, I've try setEnablePlaceholders(false) as the epoxy doc says, and got this exception:
```java
java.lang.IllegalArgumentException: Invalid snapshot provided - doesn't appear to be a snapshot of this list
     at android.arch.paging.ContiguousPagedList.addWeakCallback(ContiguousPagedList.java:318)
     at com.airbnb.epoxy.paging.PagingEpoxyController.setList(PagingEpoxyController.java:176)
     at com.example.epoxypagingsample.MainActivity$2.onChanged(MainActivity.java:69)
     at com.example.epoxypagingsample.MainActivity$2.onChanged(MainActivity.java:66)
     at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:129)
     at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
     at android.arch.lifecycle.LiveData.setValue(LiveData.java:292)
     at android.arch.lifecycle.LiveData$2.run(LiveData.java:108)
     at android.os.Handler.handleCallback(Handler.java:789)
     at android.os.Handler.dispatchMessage(Handler.java:98)
     at android.os.Looper.loop(Looper.java:164)
     at android.app.ActivityThread.main(ActivityThread.java:6541)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by pcqpcq** [comment]
And, disable place holders with Paging Library, works fine too.

**Comment by pcqpcq** [comment]
RecycleView can't scroll (touch list end), is because the `user` at index 300~350 is null. 

```java
@Override
protected void buildModels(List<User> list) {
    int size = list.size();
    for (int i = 0; i < size; i++) {
        User user = list.get(i);
        if (user == null) {  // <<------ when i >= 300, user is null.
            continue;
        }
        new PagingViewModel_()
                .id(user.getUid())
                .index("index > " + i)
                .addTo(this);
    }
}
```
So, why the PagedList think it's not need and return null while I am scrolling to there.

**Comment by elihart** [comment]
`setEnablePlaceholders(false)` needs to be set to null, and you should not have to do a null check in `buildModels`.

the real problem seems to be
```
java.lang.IllegalArgumentException: Invalid snapshot provided - doesn't appear to be a snapshot of this list
     at android.arch.paging.ContiguousPagedList.addWeakCallback(ContiguousPagedList.java:318)
     at com.airbnb.epoxy.paging.PagingEpoxyController.setList(PagingEpoxyController.java:176)
     at com.example.epoxypagingsample.MainActivity$2.onChanged(MainActivity.java:69)
     at com.example.epoxypagingsample.MainActivity$2.onChanged(MainActivity.java:66)
```

I think we just need to change `PagingEpoxyController` to not pass the new list as the old snapshot. I assumed that would always work, but I guess not

**Comment by pcqpcq** [comment]
Yes, I am trying to make a diff before pass `pagedlist` to `list`,  like the official  `PagedListAdapterHelper` do, but it still failed. Anyway, I'm still working on it, maybe I missed something.

And, the null check was just a workaround with `setEnablePlaceholders(true)`, although I knew it's a bad bad idea.

**Comment by elihart** [comment]
I think this will fix it https://github.com/airbnb/epoxy/pull/329

**Comment by elihart** [comment]
I will push a release with that change soon. Closing for now, but please do reopen if this doesn't fix it. Thanks for reporting!

**Comment by pcqpcq** [comment]
For now...

The `Invalid snapshot provided` exception is fixed, but the RecyclerView still works weird:

Still the same demo , when item counts large then  300, RecyclerView will auto scroll to previous page when insert some new data. I means:

1. when new data being inserted (index >= 300)
2. the `setList()` being called
3. the recyvlerview will auto scroll to index 149 (page 3) 
4. when item count large then 500, recyclerview will auto scroll to top after `setList()` being called

**Comment by elihart** [comment]
by "same demo" do you mean that `setEnablePlaceholders(true)` is still set to true?

**Comment by pcqpcq** [comment]
Oh no, I mean the same action: `insert some new data and keep scroll to bottom`.

I've disable place holder with `setEnablePlaceholders(false)` and use your commit.
To be exact, I changed line 176 with `list.addWeakCallback(previousList, callback);` to `list.addWeakCallback(null, callback);`.

**Comment by pcqpcq** [comment]
I push the code [here](https://github.com/pcqpcq/EpoxyPagingSample)

**Comment by elihart** [comment]
Ok, thanks for clarifying and for providing the examples. I will take a look and try to get to the bottom of this

**Comment by elihart** [comment]
I found two problems:

1.
The callback
```
public void onChanged(@Nullable PagedList<User> users) {
	      userAdapter.setList(users);
	  }
```

gets called several times when you update the db. First it gets called with a list containing _just_ the new items in the list. then it gets called with a list with all items. 

This means that if you add 100 items, from Epoxy's perspective you removed all the old items and added 100 new ones. Once `onChanged` is called again with the full list it thinks that 900 new items were inserted at the beginning.

I updated [the wiki](https://github.com/airbnb/epoxy/wiki/Large-Data-Sets#notes) to say that adding or removing items at the start of the list is not supported. This controller is meant for just appending items. removing 1 or 2 would work fine, but removing almost everything causes epoxy to lose track of the indices it is showing.

So this needs to be changed from the data source side to not pass an incomplete list. I'm not sure if it is a bug or a setting you can change.

2.
```
for (int i = 0; i < size; i++) {
                User user = list.get(i);
                if (user == null) {
                    continue;
                }
                new PagingViewModel_()
                        .id(user.getUid())
                        .index("index > " + i)
                        .addTo(this);
            }
```

this is inaccurate. the "index" is just the index within the current sublist, it is not the index within the entire list. that means that this text will change as you scroll and the window of models shifts.

it is more correct to print `.index("uid: " + user.getUid())`

it is not currently possible to get the index of the item within the total list, but I could change `buildModels(List<User> list)` to add a second parameter with the offset of the item sublist

**Comment by pcqpcq** [comment]
ok, I see. 
1.  I thought it's a feature of Paging Library: it will give you first page, and then give you the next page if need. But I don't know how it calculates the items count of every page.

In my case, the PagedList will give me 3 or 2 items of first page, and then all items. As you saw.

I think it is just a conflict way that how data are loaded between epoxy and paging library. As I've try the normal adapter without epoxy, `onChanged` gets called several times too, but the RecyclerView works well.

And I think a possible way to fix this is doing a diff just like the official do.

code inside the official `PagedListAdapterHelper`:
```java
mConfig.getBackgroundThreadExecutor().execute(new Runnable() {
    @Override
    public void run() {
        final DiffUtil.DiffResult result;
        if (mIsContiguous) {
            result = ContiguousDiffHelper.computeDiff(
                    (NullPaddedList<T>) oldSnapshot, (NullPaddedList<T>) newSnapshot,
                    mConfig.getDiffCallback(), true);
        } else {
            result = SparseDiffHelper.computeDiff(
                    (PageArrayList<T>) oldSnapshot, (PageArrayList<T>) newSnapshot,
                    mConfig.getDiffCallback(), true);
        }

        mConfig.getMainThreadExecutor().execute(new Runnable() {
            @Override
            public void run() {
                if (mMaxScheduledGeneration == runGeneration) {
                    mUpdateScheduled = false;
                    latchPagedList(pagedList, newSnapshot, result);
                }
            }
        });
    }
});
```

What do you think?

On the other hand, I haven't find any useful settings of Paging Library that will affect this.

2. I used the index of current list was just for testing, and thanks for the remind, I'll not do this in other project. 😆

**Comment by elihart** [comment]
If the PagedList has different values then the diff will always say that the original items were removed. If you set a new list that has completely different item ids then there is nothing Epoxy can do - we have to remove all those items.

I'm not sure why it works with `PagedListAdapterHelper`, but I would guess that since their diffing is async it doesn't finish before the full paged list is emitted by `onNext`, so it's more of a race condition that they happen to be avoiding.

It seems like an issue with the paging library, you could see if there is already an issue filed, or file one yourself.

**Comment by pcqpcq** [comment]
Ok, I see, I think it's not a bug with epoxy it self.
Closed for now, I'll update this if I find anything new.
