### ISSUE TITLE
carousel cann't scroll to first position after scrolled once

### ISSUE THREAD

**Issue by JasonHezz** [airbnb/epoxy#328]
[sample link](https://github.com/JasonHezz/CarouselIssue)

**step to reduce:**
- run app
- scroll right
- scroll left

carousel will have a bounce when reach first position and auto scroll a offset **happened in lands landscape**

**Comment by elihart** [comment]
I believe this is the behavior of the default LinearSnapHelper. Something similar can be observed in the epoxy sample app.

Given that this snap helper is the standard behavior provided by google I didn't look into it too much yet, but it would be a good thing to investigate.

In the meantime can set your own default snap helper to change the snapping behavior, or set it to no snap helper.
```
Carousel.setDefaultGlobalSnapHelperFactory(null to disable or a custom value if you want)
```

**Comment by elihart** [comment]
I'm considering using a library such as https://github.com/rubensousa/RecyclerViewSnap as the default, but I want to be a little careful about including other libraries.

**Comment by JasonHezz** [comment]
Thanks, it works , but why SnapHelperFactory  is abstract static class

**Comment by vikrama** [comment]
https://stackoverflow.com/questions/44766186/linearsnaphelper-doesnt-snap-on-edge-items-of-recyclerview

This sort of explains this problem with LinearSnapHelper

**Comment by berendjan** [comment]
[https://github.com/rubensousa/RecyclerViewSnap](https://github.com/rubensousa/RecyclerViewSnap )
I used the above mentioned library in the onBind callback, and set the global default to `null`. (else it will start to dance between the 2 snapping strategies)
```
Carousel.setDefaultGlobalSnapHelperFactory(null)
carousel {
    id("some_id")
    numViewsToShowOnScreen(2.2f)
    models(listOfModels)
    onBind{ _, recyclerView, _ ->
        GravitySnapHelper(Gravity.START)
            .attachToRecyclerView(recyclerView)
    }
}
```

**Comment by Draketheb4dass** [comment]
> ```kotlin
> numViewsToShowOnScreen(2.2f)
> ```

Mine is still dancing... I'm confuse

**Comment by ubarua123** [comment]
I forgot to add this `Carousel.setDefaultGlobalSnapHelperFactory(null)` and mine were dancing left and right. 
The above solution works.
