### ISSUE TITLE
full height using wrap content.

### ISSUE THREAD

**Issue by jjhesk** [airbnb/epoxy#333]
Is that possible to configue a wrap_content height for dynamic height of the recyclerview with gridlayoutmanager?

**Comment by jjhesk** [comment]
resolved. https://stackoverflow.com/questions/26649406/nested-recycler-view-height-doesnt-wrap-its-content/28510031#28510031

**Comment by elihart** [comment]
The answer you linked is old, for a while now the support library has supported `wrap_content` out of the box https://stackoverflow.com/a/35623132/2465722
