### ISSUE TITLE
epoxy-adapter depends on (non-existant) support libs 24.2.0

### ISSUE THREAD

**Issue by madisp** [airbnb/epoxy#34]
These versions were (mistakenly) removed in support repository rev 38.

I guess the deps should be 24.2.1 instead?

as a workaround one can depend on 24.2.1 explicitly.

**Comment by elihart** [comment]
I included the updated dependencies in https://github.com/airbnb/epoxy/pull/33

I believe the Android support library team has fixed the issue where 24.2.0 is no longer available though. They pushed the fixed release just a little while ago.
