### ISSUE TITLE
Anotation generate for facebook litho not work?

### ISSUE THREAD

**Issue by zentechthaingo** [airbnb/epoxy#341]
I run epoxy-sample with ListItemSpec. But it doesn't have ListItemModel_ like docs.<br/>

 This is an example of the optional litho integration. A ListItemModel_ class will be
automatically generated for this component. Any props declared in the layout will be included on
the model.

**Comment by elihart** [comment]
Whoops! thanks for letting me know, fixed with https://github.com/airbnb/epoxy/pull/342
