### ISSUE TITLE
Implement onDetachedFromWindow on EpoxyRecyclerView

### ISSUE THREAD

**Issue by mradzinski** [airbnb/epoxy#344]
Hey @elihart, It would be awesome if ExpoyRecyclerView implemented by default the Wiki recommendations to avoid memory leaks such as overriding `onDetachedFromWindow`. Maybe also expose some setter so that users can disable its default implementation in case they want to handle this by themselves.

Anyway, can't stress it enough: Thanks for the hard work mate.

![bitmoji](https://render.bitstrips.com/v2/cpanel/0c62d877-a0fb-4266-89d5-4d80ec96324f-b8fdcfdd-6cb5-4334-8636-fec5c4e11f8d-v1.png?transparent=1&palette=1&width=246)

**Comment by elihart** [comment]
Thanks for bringing this up, I've been considering it over the last few days. We do this internally, but there is a fairly large snag which is that it breaks fragment transitions. Fragments have their views destroyed (and detached from window) before transitions end, so if you clear the adapter then the screen turns blank and the transition doesn't work.

it's a very unfortunate aspect of how fragment transitions and lifecycle are implemented... To work around this in our internal version I delay the adapter removal for 2 seconds after view detach. This is pretty hacky and I'm not proud of it, and am hesitant to do the same in the general library.

You're right that having a setter to disable this behavior would be nice if we do support it.

I'll keep thinking about this and see if there is a better general solution, it would definitely be nice to handle automatically for everyone.

**Comment by mradzinski** [comment]
Since I'm using [Conductor](https://github.com/bluelinelabs/Conductor) for my views I'm lucky enough to have the `onPostDetach` lifecycle event that triggers right after the view is off the screen but still alive and kicking, so I do all my cleaning there. But I do agree that not everyone is using the same stuff I do and that it can be a bit of a bummer to lose the fragment transition. Delaying is indeed a bit hacky, but I've implemented much worst hacks than that before so I wouldn't mind it at all xD.

I'll do some experiments on my side and if I can come up with something for this.

**Comment by mradzinski** [comment]
@elihart QQ: Got a leak from EpoxyRecyclerView and I'm wondering if it's related to what we were talking about on this issue (if not I'll open a new one):

```
* com.***.HomeActivity has leaked:
* GC ROOT static com.airbnb.epoxy.EpoxyRecyclerView.RECYCLER_POOLS
* references java.util.ArrayList.array
* references array java.lang.Object[].[1]
* references com.airbnb.epoxy.EpoxyRecyclerView$PoolReference.viewPool
* references com.airbnb.epoxy.EpoxyRecyclerView$UnboundedViewPool.scrapHeaps
* references android.util.SparseArray.mValues
* references array java.lang.Object[].[0]
* references java.util.LinkedList.voidLink
* references java.util.LinkedList$Link.next
* references java.util.LinkedList$Link.data
* references com.airbnb.epoxy.EpoxyViewHolder.itemView

* Retaining: 8.6 MB.
* Reference Key: 6959da21-7f02-43ac-869c-bdbdcc88cf21
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5.4 74837f0
* Durations: watch=5282ms, gc=490ms, heap dump=3103ms, analysis=70067ms
```

Might this be related to a bad cleanse of items? If so defo there's a need to implement some way of disposing of items from the shared pools (8.6 MB is not exactly a small leak).

**Comment by elihart** [comment]
This is slightly different, the view pool should be cleaned up the next time an EpoxyRecyclerView is created, you can see the logic in `EpoxyRecyclerView#initViewPool`. We could change it to do some sort of polling after `onDetachedFromWindow`, or do some check then if the activity is destroying.

This is somewhat related to the other memory leak topic though, because if the adapter is cleared from the recyclerview, and if all adapters are detached from the view pool, then the view pool is cleared, so removing the adapter on activity destroy would also clear the pool.

8.6 MB is very large though, I image you have have bitmaps in your views to get to that size. If the recycled views have bitmaps then it means you aren't clearing them properly when they are recycled. I should definitely improve how efficiently the view pool is cleared once the activity is destroyed, but you may have a compounding issue there.

**Comment by mradzinski** [comment]
I do have bitmaps managed by Fresco, but I'm evicting the cache upon activity destruction and disposing of its Pipeline, so it shouldn't be that. What I came to realize is that there seems to be a strong correlation between the leak and using EpoxyRecyclerView. I have 4 RecyclerViews (3 ol' regular ones, 1 epoxy... haven't migrated all yet) and none of the regular ones are leaking though all share one thing in common: same model, same adapter (through different parts of the app of course). The only one showing the leak is the EpoxyRecyclerView one, so the model should't be the problem.

Maybe calling to the `clear` method of ERV would help?

**Comment by mradzinski** [comment]
@elihart, I actually kept getting leaks even after clearing the EpoxyRecyclerView, all pointing to `com.airbnb.epoxy.EpoxyRecyclerView.RECYCLER_POOLS` and ending on leaking my MainActivity. I get leaks even when there're no items added to the adapter, so I'm possitive models aren't the problem. I wonder since I know `RECYCLER_POOLS` has to do with Activities: is there a chance `EpoxyRecyclerView` is holding a strong reference to the host activity?

**Comment by elihart** [comment]
I haven't used Fresco, but I would imagine that evicting the cache does not clear the view's references to the bitmaps. Also, before the activity is destroyed, while the recyclerview is still in use, you don't want your recycled views holding onto those bitmaps while they are waiting to be reused. You should use `@OnViewRecycled` to release all bitmaps.

On the note of the leak, the view pool holds a weak reference to the activity, but a strong reference to the view pool. if the view pool is not cleared then the views inside it will still hold references to the activity.

Calling `EpoxyRecyclerView#clear` clears the models, but it does not clear the view pool. For now you should be able to clear the view pool by calling `setAdapter(null)`. 

I definitely want `EpoxyRecyclerView` to better handle this automatically in the future, I will try to address it in the next few weeks, but also welcome anybody else to submit a PR.

**Comment by mradzinski** [comment]
I'm actually evicting the cache AND durin `@OnViewRecycled` clearing the underlying bitmap. I tried `setAdapter(null)` but it didn't help at all. I'm pretty sure I'm disposing everything, and upon analyzing the HPROF generated by LeakCanary I was able to see my `HomeActivity` (for some reason I'm still trying to determinate) being attached to `com.airbnb.epoxy.EpoxyRecyclerView.RECYCLER_POOL`. 

Maybe exposing a method to manually clear the pool which internally calls `PoolReference.contextReference.clear()` for each `PoolReference` currently in the pool would be a way of preventing this sort of leaks.

**Comment by elihart** [comment]
I am about to leave for vacation, so unfortunately can't address this for the next week, but you can try `RecyclerView#getRecycledViewPool()#clear()`

That should clear the view pool, and allow the activity to be recycled 🤞 sorry for the trouble :(

**Comment by mradzinski** [comment]
Yep, yep yep yep.`RecyclerView#getRecycledViewPool()#clear()` cleared up the reference as expected, so no more memory leak. Enjoy your vacations @elihart!

**Comment by elihart** [comment]
Finally had some time to spend on this - https://github.com/airbnb/epoxy/pull/368. Sorry for the delay!

It's not quite ready yet, but should be soon!

**Comment by elihart** [comment]
change is merged!

**Comment by mradzinski** [comment]
@elihart Sorry, hectic week. Just checked the changes, they all look great. I'll try toying around with it a bit and will let you know in case I notice anything weird.

Cheers mate! and thanks again for this amazing lifesaver!
