### ISSUE TITLE
Carousel padding values

### ISSUE THREAD

**Issue by athornz** [airbnb/epoxy#349]
The Carousel seems to only support one padding value which affects all sides.

It would be great to be able to specify padding values for top, left, bottom and right.

**Comment by elihart** [comment]
Noted. I would like to avoid having too many different methods for setting padding, but I think we can support this by having another `setPadding` overload that passes a custom object as a param - that object can specify padding in each direction (in either px, dp, or dimenRes) as well as item spacing

**Comment by vikrama** [comment]
I have this class that removes the top & bottom padding from the horizontal recyclerview and it seems to be working fine.

```
class JobCarouselModel: CarouselModel_() {
    override fun onViewAttachedToWindow(view: Carousel?) {
        super.onViewAttachedToWindow(view)
        val pad = view?.context?.resources?.getDimensionPixelSize(R.dimen.padding_base) ?: 0
        view?.setPadding(pad, 0, pad ,0)
    }
}
```

and adding it this way:

```JobCarouselModel().paddingRes(R.dimen.padding_base).id("jobs").models(models)```

The above will still give the item spacing for the elements in recyclerview. But I wish it was easier than creating a custom model just to support our padding requirements.

**Comment by elihart** [comment]
I should have a solution up tomorrow

**Comment by elihart** [comment]
This is what I have in mind https://github.com/airbnb/epoxy/pull/369

**Comment by elihart** [comment]
Merged

**Comment by vikrama** [comment]
Thanks. Does the new method also propagate to the CarouselModel_? Is it possible to do?
```CarouselModel_().padding(Padding(....))```

**Comment by elihart** [comment]
Yes, notice it is annotated with `@ModelProp`

**Comment by vikrama** [comment]
Cool, thanks again. Closed.
