### ISSUE TITLE
onBind get called after requestModelBuild()

### ISSUE THREAD

**Issue by yihuaqi** [airbnb/epoxy#350]
Background: I have a list of clickable items which I need to calculate its impression, and I use onBind() as an indication that the item appears on user screen. When the clickable item is clicked, the status of the item changes accordingly, so I register a click listener to change the status of the item.

Problem: However, in the click listener, when requestModelBuild() is called, onBind() also gets called, which results in impressions being calculated twice. Here's the pseudo-code of my implementation:

```

@Override
    protected void buildModels() {
        for (Item i : items) {
            ItemViewModel_ model_ = new ItemViewModel_()
                          .id(item.id)
                          .status(UNREAD)
                          .onBind((model, view, position) ->
                                              // Report impression when item appears
                                              sendImpression(item.impr_id))
                          .clickListener((view) -> 
                                 mItems.get(index).status = CLICKED
                                 // onBind will get called again
                                  requestModelBuild()
                                // redirect to other page
                                 redirectToNextPage(item.url))
            model_.addTo(this)
        }
    }
```

I'm not sure if it's the expected behavior or I mistaken something. My question is that, how should I achieve that the impression event should be reported only when the item appears, and only when it disappears and reappears again?

**Comment by elihart** [comment]
This is the expected behavior - `onBind` is a direct mapping to RecyclerView's `onBindViewHolder`.

If you want to check that it is the first time the view is bound you can check that the view is _not_ attached to the window. When a view is rebound because of an update it will be attached to the window.

I can update the `onBind` method to have javadoc describing its behavior.

**Comment by yihuaqi** [comment]
@elihart Thanks for your explanation!
I tried ViewCompat.isAttachedToWindow, but it only solved part of the problem. It looks like that sometimes onBind can be called repeatedly even when the view is not attached to window, so the views out of the screen are also counted.

Any idea why this happens? It looks like the behaviors is somehow different from RecyclerView which only calls onBindViewHolder when it becomes visible.

**Comment by elihart** [comment]
Great, sounds like everything is working as expected then?

As a side note, doing processing such as converting to HTML is always more efficient to do inside the view instead of when building the model, so that is a good performance optimization as well.
