### ISSUE TITLE
fresco example

### ISSUE THREAD

**Issue by yumcoder-platform** [airbnb/epoxy#351]
how to use fresco (frescolib.org) in the epoxy model?

**Comment by elihart** [comment]
I've never used fresco, but it should work just like any other view.

Have you tried it? Do you have a specific issue or problem?

**Comment by yumcoder-platform** [comment]
I think my problem is related to the following issue :
https://github.com/facebook/fresco/issues/335

**Comment by elihart** [comment]
Ok, so it seems like this is just a Fresco issue then?

**Comment by yumcoder-platform** [comment]
yes
