### ISSUE TITLE
How to get View Type of Model generated using ModelView and autoLayout

### ISSUE THREAD

**Issue by alexbchr** [airbnb/epoxy#352]
It is easy to get the View Type when using @ModelView annotation and defaultLayout parameter, as the View Type is equals to the layout ID (R.layout.my_view).

However, when using the @ModelView annotation with the autoLayout option, I don't see any way to get the View Type of the view.

For example:
`@ModelView(autoLayout = Size.MATCH_WIDTH_WRAP_HEIGHT)`

Do I really need to set a defaultLayout if I want to get the View Type? I need the View Type in a custom ItemDecoration...

Thanks!

**Comment by elihart** [comment]
You can get the adapter off the EpoxyController and call `adapter.getItemViewType(modelPosition)`.

That should give you the view type that is actually used at runtime.

**Comment by alexbchr** [comment]
Ok thanks, I did not think of this approach!

However, there are 2 downsides to this approach:
1. I need to know the position of the item in the RecyclerView (the item may be absent in my case and getting its position in the recyclerview will require me to keep track of the index of each item of this type in the Controller).
2. The items must have been set on the controller at least once in order to use the position in the adapter. In my case, it would have been great to do it before setting the Controller's data.

Thanks anyway for the answer, now I need to choose if I want to rewrite some code to get the View type with your proposition or if I add a layout file and use it's ID to act as the ViewType.

Would it be possible to consider a future improvement to the library where the ViewType would be generated and accessible on the model classes?

**Comment by elihart** [comment]
I see your points, it is possible to make the generated view type accessible, but I would have to think about how to do it in a clean way.

You said you need it for use in an item decoration, which I would have thought means that the models are already added to the adapter and can easily be looked up by position. Care to explain the usage further?

In general accessing view type off of the model was intended for internal library usage only (the method is protected), and the true view type should be accessed off the adapter.

**Comment by alexbchr** [comment]
To simplify my use case, I have a RecyclerView with items (views) grouped in different categories (different views). I may also have different views before/between/after these views. I draw a custom item decoration, acting as a divider between items of a predefined view type (the items grouped in sections). 

To do so, I need to give the view type of the items to the recycler. For now, I setup the item decoration before setting the data of the RecyclerView (using the defaultLayout used in the ModelView annotation). However, as previously mentioned, I would prefer not to use the defaultLayout and replace it with autoLayout. I could set the view type of the item decoration after setting up the RecyclerView, but that implies calculating the first item index. However, since different items may be placed before this one, this asks me to keep track of each view added until the targeted view is added. I would then need to make this index accessible outside the controller, in order to create and set my item decoration. I prefered to go on with the defaultLayout option, which is simpler and cleaner.

I understand that the view type was intended to be used only in the model/adapter. As you say it would need to be available in a clean way. I don't see any one for the moment, especially since a model class could return multiple default layouts if the method is customized...

**Comment by elihart** [comment]
I see, that sounds tricky and I probably don't understand the use case enough to be more helpful unfortunately.

We use a base class for our models that lets us set whether the model should show a divider or not, that way you can easily toggle it manually when building each model. We also use an EpoxyController interceptor to look at models after they are all built and toggle dividers automatically on certain models depending on the divider rules we give it.

We don't use item decorations for our dividers, but an item decoration could get the model at each position, cast it to your base class, and check whether it has a divider set on it.

Just some ideas, there are probably better options for you than relying on view type.

**Comment by alexbchr** [comment]
I like the idea of having the divider set on the Model itself and toggling it using an Interceptor. I think this is a more elegant solution and that it provides more flexibility.

For example, one problem I faced with ItemDecorations is that they don't animate when for example you show a bunch of items with dividers. The items appear with a fade-in animation, but the dividers just appear without any animation. Using the divider directly in the model would fix this issue.

Thanks for your help and ideas!

**Comment by JiangDaYa0** [comment]
@alexbchr I have the same issue.
Can you provide an example? This is a lot to me. Thx.

**Comment by JiangDaYa0** [comment]
@elihart Use the base Models for myself view is a great idea.
But, I guess, this way means i need use a BaseView for all the Views, I don't want to do that.Can you provide an example? The is a lot to me . :)

**Comment by ThugKd** [comment]
@alexbchr  @JiangDaYa0  I have the same issue.
Can you provide an example? This is a lot to me. Thx.
