### ISSUE TITLE
Carousel SnapHelperFactory

### ISSUE THREAD

**Issue by jo8558** [airbnb/epoxy#355]
It is not able to implement a CustomSnapHelperFactory because it is not able to override the buildSnapHelper method.
Another issue: It is not possible to call the method Carousel.setDefaultGlobalSnapHelperFactory(...). Only Carousel.setDefaultItemSpacingDp(...) is available.

**Comment by elihart** [comment]
Sorry about that, my mistake. This should fix it I believe - https://github.com/airbnb/epoxy/pull/356

Thanks for reporting!

**Comment by jo8558** [comment]
Thanks for the instant reply. I thought that this issue was only due to visibility issue
