### ISSUE TITLE
Change view dynamically on View.OnClickListener

### ISSUE THREAD

**Issue by rnitame** [airbnb/epoxy#357]
```
        button.onButtonClick(View.OnClickListener {
            if (viewState == OK) {
                // will change the button background, drawableTop image
            } else {
                // will change the button background color, drawableTop image
            }
        })
```

This code is on `buildModels`
https://github.com/airbnb/epoxy/blob/master/epoxy-adapter/src/main/java/com/airbnb/epoxy/TypedEpoxyController.java#L62-L70

But color and image are not changed :(
Is it different in usage?

Edit:

```
com.airbnb.epoxy.ImmutableModelException:  Position: 4 Model: OverallJudgeBindingModel_{badButtonColor=0, onGoodButtonClick=$buildModels$6@1f7c303, goodButtonShadowVisible=true, onBadButtonClick=$buildModels$7@b3b2280, badButtonShadowVisible=true, goodButtonColor=0}OverallJudgeBindingModel_{id=-11, viewType=2130903203, shown=true, addedToAdapter=true}

Epoxy attribute fields on a model cannot be changed once the model is added to a controller. Check that these fields are not updated, or that the assigned objects are not mutated, outside of the buildModels method. The only exception is if the change is made inside an Interceptor callback. Consider using an interceptor if you need to change a model after it is added to the controller and before it is set on the adapter. If the model is already set on the adapter then you must call `requestModelBuild` instead to recreate all models.
```

**Comment by CharlieChristensen** [comment]
From the [Wiki](https://github.com/airbnb/epoxy/wiki/Epoxy-Controller),

> The EpoxyModel is similar to a ViewModel. It is an immutable class that is the interface between data and a view. It formats the data and updates the view accordingly. The view cannot modify an EpoxyModel, and must instead call back to change your state so that a new EpoxyModel can be created.
> 
So this means that you cannot change the state of an EpoxyModel once it is created. You need to call back to wherever your data is being held(ex. Presenter), change the state of the data, and pass the new data to the EpoxyController with setData(). 

If you have a list, you want to pass the entire list every time, not just the data that is new or changed. The diffing algorithm will determine what has changed and will create and replace EpoxyModels accordingly. This creates a unidirectional flow of data making states much more predictable.

**Comment by rnitame** [comment]
> change the state of the data, and pass the new data to the EpoxyController with setData().
oh, sure!
I would use setData() 👍 

This issue close.
