### ISSUE TITLE
hide and show group 's children

### ISSUE THREAD

**Issue by zaihuishou** [airbnb/epoxy#359]
I use [EpoxyModelGroup](https://github.com/airbnb/epoxy/blob/98c2987b651f00416bdbf99d6b8387564acdae09/epoxy-adapter/src/main/java/com/airbnb/epoxy/EpoxyModelGroup.java)
I want to toggle it children visibility,how to do it?

**Comment by elihart** [comment]
@zaihuishou on each model in the group you can call `model#show` or `model#hide`
