### ISSUE TITLE
Support specifying a rootView for EpoxyModelGroup

### ISSUE THREAD

**Issue by RhysDavis** [airbnb/epoxy#361]
Currently if no ViewStubs are used in an EpoxyModelGroup, the class will put models inside the layout specified (provided it's a ViewGroup. With support to specify a particular ViewGroup by a dedicated root ID to be where Models are laid out, we could create more complex and interesting ModelGroups without requiring the use of ViewStubs.

**Comment by elihart** [comment]
https://github.com/airbnb/epoxy/pull/370 👍
