### ISSUE TITLE
PagingEpoxyController: buildModels() logic causing RecyclerView to reset

### ISSUE THREAD

**Issue by wkranich** [airbnb/epoxy#365]
Seems that with any data set, 5 pages or larger, the logic within the `buildModels` method in `PagingEpoxyController` ends up returning the entire list after it returned a sublist, causing the RecyclerView to reset. This happens starting on the 5th page and all subsequent pages.

All values are default, as well as placeholders disabled.

I've attached some sequential snapshots of the values I noticed while debugging. In the last, `lastBuiltLowerBound` somehow gets reset to 0 after having been greater than zero in previous passes.

![screen shot 2017-12-18 at 7 12 17 pm](https://user-images.githubusercontent.com/5986120/34134406-6d2c250a-e428-11e7-9d1e-b97f8a9d0fea.png)
![screen shot 2017-12-18 at 7 12 24 pm](https://user-images.githubusercontent.com/5986120/34134407-6d38c4b8-e428-11e7-8483-caa5cfb8dc1c.png)
![screen shot 2017-12-18 at 7 12 32 pm](https://user-images.githubusercontent.com/5986120/34134408-6d46f6f0-e428-11e7-9442-bd8afdf97954.png)
![screen shot 2017-12-18 at 7 12 39 pm](https://user-images.githubusercontent.com/5986120/34134409-6d5337bc-e428-11e7-9172-156bc8f96af9.png)
![screen shot 2017-12-18 at 7 12 46 pm](https://user-images.githubusercontent.com/5986120/34134411-6d62231c-e428-11e7-84e2-265c2116f853.png)

Having some trouble fully understanding the logic to decide what the lowerBound should be, but have resorted to just returning the entire list always (I know, this defeats the purpose of the PagingController to only build a subset of models)

**Comment by elihart** [comment]
Thanks for reporting! It looks like your total list grew from 155 to 157 - were items inserted? Might this be related to https://github.com/airbnb/epoxy/issues/325 ?

I plan to spend some time on various Epoxy improvements over the next few days and can take a closer look then

**Comment by wkranich** [comment]
Seems like it might be related? I didn't add anything to the list manually. The total size of the data set was 157 so I assume included in the last page and returned by the Paging Library

**Comment by elihart** [comment]
Sorry, I haven't had time to look at this yet, but if anyone has insight it would be appreciated

**Comment by elihart** [comment]
@wkranich sorry, still haven't looked into this. I'm wondering if the latest paging library update affects this at all though. I'm going to release a new version soon that bumps the paging library, if you can attempt to repro on that version and report back it would be helpful!

**Comment by elihart** [comment]
Can you repro this with the latest Beta1? If not I will close this
