### ISSUE TITLE
Have generated classes duplicate any methods from super classes that return the class type

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#37]
To make chaining easier.

@gpeal

**Comment by geralt-encore** [comment]
What about these improvements that we were talking in PR comments?

**Comment by elihart** [comment]
There were two things:

1) If there is just one param in a method then name it the same as the method name

2) Also look for methods  on super classes beyond the first parent. We  will have to check for duplicates here, as well as package private methods for super classes in different packages. Then we could remove the custom code to build the id, show, etc methods.

And now that I think about it it seems like we should also capture annotations on either the method or the parameters.

**Comment by geralt-encore** [comment]
I was able to look for methods on super classes beyond the first parent and eliminate custom code to build the id, layout, show and hide methods. The only problem right now is that all tests are failing, because of `@LayoutRes` annotation which is missing because we ignore annotations for methods and method parameters. I am not sure how to proceed next since I haven't known yet how to deal with that case and it's kinda out of scope for the PR, but obviously it can't be merged in current state because tests are failing.

**Comment by elihart** [comment]
That's great that you have that part working! The annotations are tricky though.

I've been looking into them and think I know how to do it. I'll put up a PR which we can merge first, then you should be able to add your changes without break tests. Sound good?

**Comment by geralt-encore** [comment]
Sounds good! Let me know if you need help with it.

**Comment by elihart** [comment]
Unfortunately my idea didn't work. I noticed at run time that the method element is a `com.sun.tools.javac.code.Symbol.MethodSymbol` and that contains all the annotation information, and even the parameter name. As far I can tell though we can't cast it to that since it's an implementation of the compiler and not an accessible package. We could maybe somehow do something hacky to work around that but I think that's too ugly.

`typeMirror.getAnnotationMirrors()` is available starting in java 8. I believe this is the only reliable way we could get the annotations and unfortunately we're stuck below java 8.

We could drop the annotations or not include methods in super classes. I don't think dropping annotations is the worst thing. Maybe we could drop annotations on most methods, but manually add the `layout` method from the EpoxyModel class that has one.

**Comment by elihart** [comment]
Awesome, all done!
