### ISSUE TITLE
recyclerview in viewpager

### ISSUE THREAD

**Issue by yumcoder-platform** [airbnb/epoxy#372]
if recyclerview in viewpager (suppose Instagram gallery) after update **setData** the recyclerview does not show image correctly!

![image](https://user-images.githubusercontent.com/29568969/34437638-459c9e9e-ecb5-11e7-9645-6e41934332ef.png)

As you can see the image load in recycleview but not show completely. After scrolling one page everything is ok!

![image](https://user-images.githubusercontent.com/29568969/34437702-de9354ee-ecb5-11e7-8c68-b4a7ef6a04c6.png)

if I called the **setData** with delay everything is ok, such as;

```
Task.delay(300).continueWith(new Continuation<Void, Void>() {
            @Override
            public Void then(Task<Void> task) throws Exception {
                getController().setData(data);
                return null;
            }
});

```

**Comment by elihart** [comment]
@yumcoder-platform seems like you got this figured out. Can you explain your solution so others with the same issue can reference it?
