### ISSUE TITLE
Carousel with circular scrolling

### ISSUE THREAD

**Issue by sauyee333** [airbnb/epoxy#375]
Hi,
I have an image list that need to be able to scroll both ways. The original implementation is using viewpager. After I convert to using carousel, I couldn't find a way to scroll both left and right (loop effect). Please advise. Thanks.

**Comment by elihart** [comment]
RecyclerView itself doesn't readily support circular infinite scrolling. However, you can approximate it by simply adding your items in a loop many times.

That would be less efficient - it could be possible for Epoxy to support circular scrolling with a configuration option to be more efficient, but I haven't looked at that option too closely yet.

**Comment by elihart** [comment]
@sauyee333 I put this together to come up with a better way to support circular scrolling https://github.com/airbnb/epoxy/pull/401

let me know what you think
