### ISSUE TITLE
Static variables for defaultGlobalSnapHelperFactory and defaultSpacingBetweenItemsDp in Carousel class

### ISSUE THREAD

**Issue by sauyee333** [airbnb/epoxy#376]
I have multiple horizontal scrolling rows and only certain rows need to attach snap helper and change spacing. However, these two variables : defaultGlobalSnapHelperFactory and defaultSpacingBetweenItemsDp are declared as static variables, thus changing the value affect all rows instead of just the intended rows.

**Comment by elihart** [comment]
You can subclass Carousel and override `getSnapHelperFactory` to provide our own implementation. Similarly you can use the `setPadding` methods to override default item spacing. Check out the javadoc in the Carousel class

**Comment by sauyee333** [comment]
Thank you! I noticed I need to overwrite getSnapHelperFactory for all Carousel subclass. If just add in one of the subclasses, other subclasses are affected as well. Thanks and I close this issue.
