### ISSUE TITLE
current RecyclerView position

### ISSUE THREAD

**Issue by yumcoder-platform** [airbnb/epoxy#378]
suppose we have two layouts for land and portrait, how to save and restore current RecyclerView(with TypedEpoxyController) position?

**Comment by elihart** [comment]
RecyclerView automatically saves its position as part of saved instance state. make sure your view state is getting saved. the only gotcha is that epoxy models must be set on the RecyclerView before view state is restored

**Comment by yumcoder-platform** [comment]
Let me explain it in a real scenario: in a chat message list, we want to save last message id (set in epoxy model id) that user seen.  If user leave this list and later back to it, new data will fetch from server and the list is constructed but we want to scroll to the last seen message (model id = message id)

**Comment by elihart** [comment]
That should be easy enough. You will have to:
- Save the message id manually via normal Android saved state
- When restoring state, first build all models
- Then use `epoxyController.getAdapter().getCopyOfModels()` to get all your models and find the model who's id matches your saved id
- Scroll the recyclerview to that position like normal

**Comment by sauyee333** [comment]
I have a similar issue with Carousel. I am using fragment and only onPaused is called before starting another fragment. When back to the recyclerview fragment, only onCreateView/onViewCreated/onResume are called. So calling onSaveInstanceState does not help. How to we deal with saving state for Carousel (multiple horizontal recyclerview) in fragment? Thanks.

**Comment by elihart** [comment]
Closing since @sauyee333 opened https://github.com/airbnb/epoxy/issues/385 and yumcoder seems to have this solved
