### ISSUE TITLE
Issue / Question with OnModelClicked callbacks and @CallbackProp

### ISSUE THREAD

**Issue by tikimcfee** [airbnb/epoxy#379]
Hey again!

I hit a minor snag in the combination above; using an `OnModelClicked` listener and using `@CallbackProp`. The models I'm using are of the auto-generated variety when using custom annotated views (still one of my favorite features). Long story short, I was trying to..

1. Reduce the number of click listeners by setting the instance of a listener to a single object
2. Switch, based on some of the callback model's properties, what action to perform.

It looks like when rebuilding/binding models, there's an equality check that says something along the lines of, "Oh, well this _old_ model's listener wasn't null, and this one isn't either. Nothing so set, I'll skip that property set call." Problem there though is the the callback into the view isn't set, and I don't have a chance to call `setClickListener` on the view again. It ends up that the _old_ listener remains registered with the view, and when it's clicked, it ends up calling me back with the wrong model pointer (blah!)

I got a little turned around trying to figure out the best way to handle this, and settled on the simple approach of going _back_ to per-model listeners with `IgnoreRequiresHashCode`.

I think the fix for this one is something like `if the listener you're setting is a model click listener, and the old model already had one, reset its model to this new instance.`

On the other-other hand, I could be completely and totally misusing the click listener Callback prop thing. Feel free to pull out the wet noodles for a flogging if necessary.

As always, cheers and thanks for your time!

**Comment by elihart** [comment]
I think this is spot on, great catch! Much appreciate you reporting this with such great detail, must have been a frustrating bug to track down!

Your idea for a fix would work, but adding more exceptions to the generated code makes the annotation processor complex and difficult to maintain, so I think we can solve this with a slightly different approach like this - https://github.com/airbnb/epoxy/pull/381

I'll think about it a little longer and get some tests around this, but I'll try to release the fix soon.

Thanks again, and sorry for the issue!

P.S. A `WrappedEpoxyModelClickListener` instance is created for every model click listener when a new model is bound. This is a bit wasteful, this doesn't need to get created until the model is first bound. It would be a nice improvement to reduce object allocation when creating models by deferring this.

**Comment by tikimcfee** [comment]
Man, I took a look at that commit - it does look a bit complicated ;) 

I appreciate your looking into it, and I'm glad you've got a fix in mind for it. No big rush on this one since the workaround really isn't bad at the moment (the use case I have at the moment only contains a few rows). Happy to test out as you need!

P.S.: Ok, that makes sense. I see that now in the flow, I must have glossed over while running through the debugger (as is tradition).

**Comment by elihart** [comment]
I've thought of a much nicer way to handle this (and improve model click listeners in general) but it is a larger change. will try to have it up soon

**Comment by tikimcfee** [comment]
>  (and improve model click listeners in general)
I am intrigued. Looking forward to it!

**Comment by elihart** [comment]
I took a new approach https://github.com/airbnb/epoxy/pull/393. The first approach involved storing the click listeners in the view holder and updating them on rebind. That was messy and complex and I worry about it breaking.

This approach is much simpler, with the tradeoff of a little bit of runtime lookup on click. Should be negligible though.

I wanted to get rid of the need to wrap the click listener altogether though, to improve performance. The only way I can think to do that though is to make the `OnModelClickListener` interface an abstract class instead, so it can implement this viewholder/model lookup itself. The downside to that is that we lose the ability to do SAM conversion so it can be used as a lambda, and would be a breaking change.

Not sure if that's worth it... but didn't do it for now.
