### ISSUE TITLE
Better Error Warning when using private attributes in EpoxyModel

### ISSUE THREAD

**Issue by vdubedout** [airbnb/epoxy#380]
Hi there,

I wrote some attributes with the private modifier ```@EpoxyAttribute private lateinit var htmlText: String``` (conditioned reflex, my bad) and I had a weird error that took me way too much time to link to the private modifier. I don't know if it's possible to verify this and display a better error than:
```<identifier> expected``` and ```not a statement```. I was searching an eventual conflict in my gradle or a problem in kapt.

<img width="306" alt="screenshot 2018-01-15 17 14 26" src="https://user-images.githubusercontent.com/657721/34963728-12e7be78-fa18-11e7-86e8-1cdde2e9084e.png">
<img width="479" alt="screenshot 2018-01-15 17 14 06" src="https://user-images.githubusercontent.com/657721/34963729-12f48a54-fa18-11e7-80d7-6af1e9c0edff.png">

**Comment by elihart** [comment]
Thanks for reporting. Java should accurately provide a good error message for this, but I suppose Kotlin handles it differently. I'll try to get this addressed soon

**Comment by geralt-encore** [comment]
I just checked and the same happens in Java as well. The actual error message is at the very bottom. So the problem is not that there is no proper error message, but that processor is still trying to generate something even though some error has occurred. Seems like this problem exists not only for this case but pretty much for all of them since during validation steps we are just logging errors and not throwing actual exceptions so control flow is not interrupted.

**Comment by vdubedout** [comment]
More info, there is an error in Kotlin and Java at the bottom, up to two private attributes. Starting from 3 attributes there is no explicit error anymore.

Java File 1 private attribute -> error
<img width="1213" alt="screenshot 2018-01-16 11 17 40" src="https://user-images.githubusercontent.com/657721/34999143-fe9d4a5e-faae-11e7-8489-c73c4b61d28e.png">

Kotlin File 1 private attribute -> error
<img width="1198" alt="screenshot 2018-01-16 11 18 25" src="https://user-images.githubusercontent.com/657721/34999142-fe8efb84-faae-11e7-99a9-1df9da6b9965.png">

Kotlin file 2 private attribute -> error
<img width="1206" alt="screenshot 2018-01-16 11 26 37" src="https://user-images.githubusercontent.com/657721/34999629-3a3d8e56-fab0-11e7-88c3-a738f181d07f.png">

Kotlin file 3 private attribute -> no more explicit errors
<img width="476" alt="screenshot 2018-01-16 11 27 11" src="https://user-images.githubusercontent.com/657721/34999664-52182bee-fab0-11e7-9ad8-2c3967529df3.png">

Java file 3 private attributes -> no more explicit errors
<img width="489" alt="screenshot 2018-01-16 11 34 33" src="https://user-images.githubusercontent.com/657721/35000002-3dade90e-fab1-11e7-9cac-b71e482b31a2.png">

**Comment by geralt-encore** [comment]
The number of attributes doesn't really matter. It truncates because Java compiler has 100 errors limit by default.

**Comment by elihart** [comment]
Good analysis. The reason we still try to generate code even though we log this error is that without generating the code there is the possibility for hundreds of more errors where referenced generated files don't exist, and that makes it even harder to find the original issue.

I will try to clean up the code generated in this case.
