### ISSUE TITLE
dagger 2 component not generated

### ISSUE THREAD

**Issue by kamike** [airbnb/epoxy#382]
![qq 20180116154215](https://user-images.githubusercontent.com/3920019/34977071-227c1782-fad4-11e7-8725-3c74f916dda5.jpg)
![3233](https://user-images.githubusercontent.com/3920019/34977210-a6eb645a-fad4-11e7-8f5f-549f79b7f0e0.jpg)

I'm  add this code only,it is not work
Android Studio 2.3.3

**Comment by elihart** [comment]
Try the latest dagger version. 2.4 is very old
