### ISSUE TITLE
RecyclerView with wrap_content only binding first child

### ISSUE THREAD

**Issue by athornz** [airbnb/epoxy#389]
I'm not quite sure if this is an epoxy issue or a RecyclerView issue.

I have an EpoxyRecyclerView in a constraint layout. The RecyclerView is setup to wrap content.

When I first add data to my controller, only the first item is bound. As this is bound the RecyclerView expands it's height to accommodate all the children, but the actual views are only bound when the data next changes.

For example in this screenshot, there are 3 models in the controller. The data is all there, but the bind methods are not called until I next update the controller.

<img width="195" alt="issue" src="https://user-images.githubusercontent.com/848767/35467314-abf82f78-0371-11e8-8bf0-b1175a2a2ccb.png">

**Comment by athornz** [comment]
Well it turns out this was a silly mistake on my part. 

I had expected `bindView(holder: BaseEpoxyHolder, previouslyBoundModel: EpoxyModel<*>?)` would always be called even if it was the first bind (previouslyBoundModel would be null). But that obviously isn't the case and my models weren't actually being bound.

**Comment by elihart** [comment]
@athornz thanks for following up. I plan to add @NonNull annotations to all applicable places in EpoxyModel soon to make this clearer
