### ISSUE TITLE
Cyclic recycler view

### ISSUE THREAD

**Issue by abyrnes** [airbnb/epoxy#396]
I have a horizontal recycler view that uses `PagerSnapHelper` so it acts as a view pager. The pager needs to loop back around to the first item when it reaches the end. I am already using epoxy as it was an easy option since the recycler view in question is nested inside another recycler view. I was just wondering if there's an easy way to achieve this cyclic behavior with epoxy.

**Comment by elihart** [comment]
See https://github.com/airbnb/epoxy/issues/375

**Comment by elihart** [comment]
@abyrnes I put this together to come up with a better way to support cyclic scrolling https://github.com/airbnb/epoxy/pull/401

let me know what you think

**Comment by abyrnes** [comment]
I took what you wrote and used it and it works great! The only issue I see, if you can call it an issue, is it allows cyclic scrolling even when there's a single item in the adapter, which I imagine is usually undesired. Do you think it would be reasonable to provide a hook to enable/disable this behavior?

**Comment by abyrnes** [comment]
```java
@Override
public int getItemCount() {
  return getActualItemCount() == 1 ? 1 : Integer.MAX_VALUE;
}
```
Solves the issue
So it should be trivial to toss in a flag that lets the user determine the behavior

**Comment by elihart** [comment]
@abyrnes Thanks for trying it and for the feedback. Glad it works!

You're right that scrolling with a single item is probably usually undesirable, but I want to make sure I leave it flexible for anyone that might want that.

I'll add something to provide control

**Comment by abyrnes** [comment]
@elihart Sounds great! The only other thing I can think of that it doesn't support is being able to scroll to the left when at position 0

**Comment by elihart** [comment]
@abyrnes that's a good point. I don't think there is a good way for the adapter to get around that, but what you can do is force the recyclerview to scroll to (Integer.max_value / actual count / 2) so it starts on the first item, in the middle of the list.

I also think that data set changes won't work well with this approach - the differ will only report that the original item range changed, and recyclerview won't update views past that.

**Comment by abyrnes** [comment]
> I also think that data set changes won't work well with this approach - the differ will only report that the original item range changed, and recyclerview won't update views past that.

Yea that's pretty big. Fortunately for me my particular use case doesn't require the data set to change.

**Comment by elihart** [comment]
Yeah, I don't feel too comfortable adding this with a quirk that large.

Instead of making this an official part of the library I can set up a wiki page, have a gist for this code, list the gotchas and work arounds. And people can do whatever they want with that

**Comment by abyrnes** [comment]
That's probably the best way to go. Thanks for the non data set change solution though!

**Comment by elihart** [comment]
I set up a wiki page with a Gist for the wrapped adapter along with other info: https://github.com/airbnb/epoxy/wiki/Cyclic-Adapters

Please let me know what you think, and if anything can be improved. Thanks!
