### ISSUE TITLE
Proper implementation with DataBinding

### ISSUE THREAD

**Issue by IsseiAoki** [airbnb/epoxy#397]
I'm using databinding library just as view holder.
I have read through the [wiki page](https://github.com/airbnb/epoxy/wiki/ViewHolder-Models), but I couldn't find the way with using databinding just as view holder. (I don't want to use ButterKnife and KotlinAndroidExtensions.)
So I'm trying the code below, but I wonder if it is correct.
```
@EpoxyModelClass(layout = R.layout.item_hoge)
abstract class HogeItemModel : EpoxyModelWithHolder<DataBindingEpoxyHolder>() {
  @EpoxyAttribute lateinit var hoge: Hoge

  override fun bind(holder: DataBindingEpoxyHolder) {
    val binding = holder.binding as? ItemHogeBinding ?: return
    val context = binding.root.context
    Picasso.with(context).load(hoge.imageUrl).fit().into(binding.image)
  }
}
```
```
class DataBindingEpoxyHolder : EpoxyHolder() {

  @CallSuper
  override fun bindView(itemView: View) {
    binding = DataBindingUtil.bind(itemView)
  }

  lateinit var binding: ViewDataBinding
}
```
Do you have any suggestions?

My original adapter code(without using Epoxy) is below.
```
open class HogeItemAdapter(var context: Context, var items: MutableList<HogeItem>)
  : RecyclerView.Adapter<BindingHolder<ItemHogeBinding>>() {

  override fun onCreateViewHolder(parent: ViewGroup,
      viewType: Int): BindingHolder<ItemHogeBinding> {
    return BindingHolder(context, parent,
        R.layout.item_hoge)
  }

  override fun onBindViewHolder(holder: BindingHolder<ItemHogeBinding>,
      position: Int) {
    val binding = holder.binding
    val item = items[holder.adapterPosition]

    Picasso.with(context)
        .load(item.imageUrl)
        .fit()
        .into(binding.image)
  }
}
```
```
class BindingHolder<out T : ViewDataBinding>(context: Context,
    parent: ViewGroup,
    @LayoutRes layoutResId: Int)
  : RecyclerView.ViewHolder(LayoutInflater.from(context).inflate(layoutResId, parent, false)) {

  val binding: T = DataBindingUtil.bind(itemView)
}
```

**Comment by jumperson** [comment]
I think, you do not need to implemet ViewHolder.
Because, Epoxy integrates with Android data binding to automatically generate EpoxyModels from databinding xml layouts.
You should read [this page](https://github.com/airbnb/epoxy/wiki/Data-Binding-Support).

**Comment by IsseiAoki** [comment]
Thank you, I understand what you mean.
I meant that I don't want using `<data>` tag in layout file, if possible.

**Comment by elihart** [comment]
Well, if you don't want to use `data` tags or those other libraries then I guess what you have makes sense. It generally looks fine. Does it work or do you have a specific issue with it?

If you take this approach I would recommend setting up a base model to handle the boilerplate and typing for you
```
@EpoxyModelClass(layout = R.layout.item_hoge)
abstract class HogeItemModel : BaseModel<ItemHogeBinding>() {
    @EpoxyAttribute
    lateinit var hoge: Hoge

    override fun bind(binding: ItemHogeBinding, context: Context) {
        Picasso.with(context).load(hoge.imageUrl).fit().into(binding.image)
    }
}

abstract class BaseModel<T> : EpoxyModelWithHolder<DataBindingEpoxyHolder>() {

    abstract fun bind(binding: T, context: Context)

    final override fun bind(holder: DataBindingEpoxyHolder) {
        val binding = holder.binding as? T ?: return
        val context = binding.root.context
        bind(binding, context)
    }
}
```

**Comment by elihart** [comment]
Did you look at https://github.com/airbnb/epoxy/wiki/Data-Binding-Support#custom-data-binding-models?

I think that can prevent you from having to make your own `BindingHolder`. It passes you the ViewDataBinding automatically

**Comment by IsseiAoki** [comment]
@elihart 
The code that you have suggested worked perfectly fine. :smile:
I am sorry I didn't explain it clearly enough. :sweat_drops:

I'm using data binding library to avoid using findViewById.(just instead of ButterKnife)
I was using the data tag before, but now stop using because our app code for updating the value is becoming little complicated and it is hard to debug.

The code I wrote above seems worked but it needs "unchecked cast", 
so I wanted to know if you know the better solution.
I have read about DataBindingEpoxyModel, but I thought you expected that it is used with the data tag.
I was worried about that unexpected usage cause some problem like performance.

Thank you very much for polite response.
 It's clear now. 👍
