### ISSUE TITLE
Custom view model generated name

### ISSUE THREAD

**Issue by FunnyDevs** [airbnb/epoxy#398]
Is possibile to change the generated name of an automodel custom view? I would like to remove the "Model" suffix because i use a mvvm pattern and there would be a sort of name confusion.

**Comment by elihart** [comment]
Not currently possible, but it would be possible to add this customization. I can see the usefulness.

If anyone wants to work on it I can point them in the right direction :)

**Comment by geralt-encore** [comment]
@elihart I can look into it. I am not that familiar with custom views implementation, but I am sure if you point me in the right direction I will be able to tackle it =)

**Comment by elihart** [comment]
@geralt-encore that would be great!

The general approach I am thinking of is
- Change `PackageModelViewConfig` to have a setting for generated model suffix (default being "Model_`"
- Update `PackageModelViewSettings` to store this data
- Add a method to `ConfigManager` that takes a `GeneratedModelInfo` and returns the model suffix (see `ConfigManager#requiresHashCode` for an example)
- Look up usages of `GeneratedModelInfo#GENERATED_MODEL_SUFFIX` and replace static usages with something that looks up the suffix via the config manager
- Look at tests like `ViewProcessorTest#baseModelFromPackageConfig` for examples on how to test the configuration

**Comment by geralt-encore** [comment]
Thanks for the heads-up!
I am digging into `ConfigManager` and seems like `PackageModelViewSettings ` can be used only for `ModelViewInfo` configs and not for general `GeneratedModelInfo`. Am I missing something?

**Comment by elihart** [comment]
Yeah you're right, I was kind of figuring that models created in other ways would still fall back to the default suffix. I just realized though that the suffix needs to be looked up in the constructor of `ModelViewInfo`, so the `ConfigManager` method should take the `val viewElement: TypeElement` of the `ModelViewInfo` and return the package name.

We could take a similar approach with the `EpoxyDataBindingLayouts` annotation to change the suffix of databinding generated models

**Comment by elihart** [comment]
Will be included in next release. Thanks @geralt-encore !

**Comment by elihart** [comment]
I am pushing the 2.10.0 release with this change right now. I also updated the wiki to reflect this option.

Thanks everyone!
