### ISSUE TITLE
diffing problem

### ISSUE THREAD

**Issue by yumcoder-platform** [airbnb/epoxy#400]
I would be obliged if you could kindly help me to find my mistake. I created a sample project and when the user scrolls down, more data is loaded from a remote server (in this example pageSize=3).

the model is implemented as follows:

![image](https://user-images.githubusercontent.com/29568969/35906168-cd66a7ee-0bfe-11e8-9513-f11076bc91f1.png)

and the controller is as follows:

![image](https://user-images.githubusercontent.com/29568969/35911475-2715c210-0c0f-11e8-8bbd-cdab938c02a6.png)

and the builder returns an instance of the model:

![image](https://user-images.githubusercontent.com/29568969/35907935-8fd0b1c6-0c04-11e8-802e-9678cb740637.png)

but the diff did not work as my expectation !?

![image](https://user-images.githubusercontent.com/29568969/35906142-beab42f0-0bfe-11e8-89a1-b0e27955b7e6.png)

I think the correct log is similar to : 

**Item rang inserted. start: 0 count: 3
Item rang inserted. start: 3 count: 6
Item rang inserted. start: 6 count: 9**
,....

and I guess it causes the following blinking :

![device-2018-02-07-122000](https://user-images.githubusercontent.com/29568969/35906941-9b21a290-0c01-11e8-99ff-9e72a8e8a0c5.gif)

**Comment by yumcoder-platform** [comment]
public class MainActivity extends AppCompatActivity {

    private List<ParseObject> data = new ArrayList<>();
    private final SampleController controller = new SampleController();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                for (int i = 0; i < 5; i++ ){
                    ParseObject obj = new ParseObject("a");
                    obj.put("name", "a->" + i);
                    data.add(obj);
                }
                updateController();
            }
        });

        EpoxyRecyclerView recyclerView = findViewById(R.id.recycler_view);
        recyclerView.setLayoutManager(new GridLayoutManager(this, 2));
        recyclerView.setController(controller);
        updateController();

    }

    private void updateController() {
        controller.setData(data);
    }

    public class SampleController extends TypedEpoxyController<List<ParseObject>> {

        SampleController() {
            setDebugLoggingEnabled(true);
        }

        @Override
        protected void buildModels(List<ParseObject> data) {
            for (int i = 0; i < data.size(); i++) {
                ParseObject obj = data.get(i);
                add(build(obj));
                //add(new MyTextViewModel_().title(obj.getString("name")));
            }
        }

        @Override
        protected void onExceptionSwallowed(RuntimeException exception) {
            // Best practice is to throw in debug so you are aware of any issues that Epoxy notices.
            // Otherwise Epoxy does its best to swallow these exceptions and continue gracefully
            throw exception;
        }
    }

    //////////////////////////////////problem//////////////////////////////////////////////
    int i = 100;
    EpoxyModel build(ParseObject data){
        MyTextViewModel_ m = new MyTextViewModel_().title(data.getString("name")).id(i++);
        return m;
    }
    /////////////////////////////////problem//////////////////////////////////////////////
    

}

**Comment by elihart** [comment]
glad you got it figured out 👍
