### ISSUE TITLE
Scrapped or attached views may not be recycled.

### ISSUE THREAD

**Issue by vdubedout** [airbnb/epoxy#405]
Hi there, 

I have a bunch of errors like this in crashlytics. I'm using EpoxyControllers, with animateLayout set to false in xml. I've been trying to eradicate them, I was using adapters at first, and moved to controller in the hope that it will fix it. I can reproduce sometimes when animating then killing the activity but it's pretty random. Any hints what I should look at?

Thanks

<img width="1029" alt="screenshot 2018-03-05 13 46 33" src="https://user-images.githubusercontent.com/657721/36993477-efe0eeba-207b-11e8-9ae4-bcc5b21cca8a.png">

```
Exception java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true ca.example.application.clean.view.androidviews.NoLeakRecyclerView{56aba42 VFED..... .F....ID 0,300-720,1040 #7f0800e5 app:id/content_messaging_ad_overview_conversationList}, adapter:com.airbnb.epoxy.j@8a2300, layout:android.support.v7.widget.LinearLayoutManager@37b1739, context:ca.example..application.components.messagingadoverview.MessagingAdOverviewActivity@f67d7df
android.support.v7.widget.RecyclerView$Recycler.convertPreLayoutPositionToPostLayout (RecyclerView.java)
android.support.v7.widget.RecyclerView.access$000 (RecyclerView.java)
android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished (RecyclerView.java)
android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished (RecyclerView.java)
android.support.v7.widget.SimpleItemAnimator.dispatchMoveFinished (SimpleItemAnimator.java)
android.support.v7.widget.DefaultItemAnimator$6.onAnimationEnd (DefaultItemAnimator.java)
android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd (ViewPropertyAnimator.java:1121)
android.animation.ValueAnimator.endAnimation (ValueAnimator.java:1149)
android.animation.ValueAnimator.doAnimationFrame (ValueAnimator.java:1309)
android.animation.AnimationHandler.doAnimationFrame (AnimationHandler.java:146)
android.animation.AnimationHandler.-wrap2 (AnimationHandler.java)
android.animation.AnimationHandler$1.doFrame (AnimationHandler.java:54)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:957)
android.view.Choreographer.doCallbacks (Choreographer.java:734)
android.view.Choreographer.doFrame (Choreographer.java:667)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:945)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
```

```
Exception java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true ca.example.application.clean.view.androidviews.NoLeakRecyclerView{9da5955 VFED..... .F...... 0,0-1080,1113 #7f08007f app:id/contentPublicProfileAdsRecyclerView}, adapter:com.airbnb.epoxy.EpoxyControllerAdapter@334899f, layout:android.support.v7.widget.GridLayoutManager@f473aec, context:ca.example.application.components.publicprofile.PublicProfileActivity@5609d7d
android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal (RecyclerView.java:5864)
android.support.v7.widget.RecyclerView$Recycler.recycleView (RecyclerView.java:5808)
android.support.v7.widget.GapWorker.prefetchPositionWithDeadline (GapWorker.java:292)
android.support.v7.widget.GapWorker.flushTaskWithDeadline (GapWorker.java:342)
android.support.v7.widget.GapWorker.flushTasksWithDeadline (GapWorker.java:358)
android.support.v7.widget.GapWorker.prefetch (GapWorker.java:365)
android.support.v7.widget.GapWorker.run (GapWorker.java:396)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
```
```
<ca.example.application.clean.view.androidviews.NoLeakRecyclerView
        android:id="@+id/content_messaging_ad_overview_conversationList"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:animateLayoutChanges="false"
        />
```
```
open class NoLeakRecyclerView : RecyclerView {
    constructor(context: Context): super(context)
    constructor(context: Context, attrs: AttributeSet): super(context, attrs)
    constructor(context: Context, attrs: AttributeSet, defStyleAttr: Int): super(context, attrs, defStyleAttr)

    override fun onDetachedFromWindow() {
        super.onDetachedFromWindow()
        adapter = null
    }
}
```

**Comment by elihart** [comment]
Thanks for reporting. What version of the support library and Epoxy are you using?

**Comment by vdubedout** [comment]
I'm currently using Epoxy 2.9.0 but it was happening since I'm using it (1.4.0)
Support Library is currently 27.0.2 happening since 25.0.0

**Comment by elihart** [comment]
Thanks for the details. From what I have been able to look up it does seem related to animations.

I would look into `EpoxyModel#onFailedToRecycleView` - that is the only callback related to cleaning up animations that I know of.

I would guess that this isn't really related to Epoxy, and is a general RecyclerView issue. If you can help pinpoint any areas in Epoxy that could be changed to address it I'm happy to resolve that.

Looking in our own crash reports I see one random occurence of this, which suggests its a random bug. We  have a huge amount of Epoxy usage, and I'm surprised we're not seeing it more given how much it is happening to you.

Since one of the crashes happens in the gap worker prefetch you could try `setItemPrefetchEnabled(false)` as a palliative bandaid for now

**Comment by mradzinski** [comment]
@elihart @vdubedout I have probably more animated items on my app than most mortals on earth. It's a real-time app so we expect lots of insertions, deletions, updates, etc per second. Out of a 145K user base I've found 0 crashes related to recycling (and my users aren't exactly the brightest lights, so if there's a way to crash something they'll find it for sure). If I should guess I would say there's something else causing this.

I've seen `Scrapped or attached views may not be recycled` issues twice:

1 -  `android:animateLayoutChanges` was set to `true` on the XML (I guess you said no to this, so we can discard it).

2 - The items have one or more EditText's. If one of them is focused and the `Recycler` kicks in to recycle the item then you'll get this kind of exceptions. `android:focusableInTouchMode="true"` should fix this when applied to the RecyclerView.

**Comment by vdubedout** [comment]
Hi there, thanks for the help.

1. I don't even animate a lot. Most of the animations are the defaults of epoxy.  I've forced to false in xml to see if it changes anything. 
2. I don't have any EditText in my Models

Most of my crashed happen on listviews IN a viewpager  (PublicProfile) but not only there. 
* I'm using Glide to load images in most of them
* I try to clear loadings and clicklisteners in most of them

I'm currently working on this bug I would let you know more if I learn something

You can find the app below. It's not available worldwide. You can test it in France. 
https://www.bitrise.io/artifact/4768732/p/d342cabff8da6862fa29e287b3374d2b

**Comment by elihart** [comment]
@mradzinski Thanks for the input! Makes sense.

@vdubedout Thanks for sharing code, I don't see anything weird, not sure why are you having problems. Keep us updated on your debugging!

**Comment by vdubedout** [comment]
I've removed the TransitionManager.beginDelayedTransition in this version. I will see if it avoids those crashes

**Comment by vdubedout** [comment]
No new crashes after removing it. I guess we can suspect the TransitionManager doing those crashes.

**Comment by elihart** [comment]
Great! thank you for following up :)

**Comment by thelou1s** [comment]
@vdubedout Hey, No new crashes till now? Do you know how to remove TransitionManager.beginDelayedTransition in RecyclerView? because I got this exceptions in my recycler view.
