### ISSUE TITLE
How to add click listener on EpoxyModelGroup

### ISSUE THREAD

**Issue by zaihuishou** [airbnb/epoxy#407]
I have already used EpoxyModelGroup in my project ,but i dow`t know how to add a OnClickListener on EpoxyModelGroup(more than one child)?Please help me @elihart,thank you

**Comment by elihart** [comment]
sure, you should be able to override `public void bind(@NonNull Holder holder) {` in `EpoxyModelGroup`
and then use `EpoxyModelGroup#getRootView`

`EpoxyModelGroup` is itself just an EpoxyModel, so you can create attributes on it for click listeners or other customization.
