### ISSUE TITLE
Inifinite loading when using data binding and instant run enabled

### ISSUE THREAD

**Issue by RoudyK** [airbnb/epoxy#408]
**Environment**

Android studio version: 3.0 - 3.1 RC 2 - 3.2 Canary 6 
Gradle plugin: 3.2.0-alpha6
Gradle warpper: 4.5.1
Epoxy version: 2.10.0
Epoxy databinding version: 2.10.0

`implementation 'com.airbnb.android:epoxy:2.10.0'`
`annotationProcessor 'com.airbnb.android:epoxy-processor:2.10.0'`
` implementation 'com.airbnb.android:epoxy-databinding:2.10.0'`

**Problem** (Can reproduce on above android studio versions)

When using epoxy data binding models with instant run, attempting to build and run on a target device ends in an infinite loading (I waited 20 minutes sometimes and it was just stuck) with instant run enabled. When i remove any data binding models, it works. when I remove instant run, the build works.

The build is stuck on the below line:
`:app:transformClassesWithDexBuilderForDevelopmentDebug`

**Can reproduce everytime**

**Comment by elihart** [comment]
Thanks for reporting! Sounds like a bug with instant run, I'm not sure if there is anything I can do. I think instant run does not work well with annotation processors.

I don't have time to investigate this right now, but I am curious what is going on. Maybe you can report it to the android issue tracker?

**Comment by elihart** [comment]
Is this still an issue?

**Comment by RoudyK** [comment]
@elihart doesn't happen anymore with instant run enabled, using 3.2 canary 18, just checked. Will close this. Thank you!
