### ISSUE TITLE
Reuse epoxy component in normal RecyclerView

### ISSUE THREAD

**Issue by yihuaqi** [airbnb/epoxy#410]
I have been using Epoxy in my project and enjoyed it very much.

Right now I'm designing a new module, and have a question for it: Does Epoxy component have interoperability with normal RecyclerView? Is there anyway to reuse the model that I write for Epoxy in the non-Epoxy RecyclerView? Because I don't quite feel like maintaining two pieces of code.

Thank you in advance

**Comment by elihart** [comment]
Are you saying you want to use an EpoxyModel in a non Epoxy RecyclerView Adapter? that doesn't really work, unless you want to write a lot of boilerplate to hook it up.

You can use a normal RecyclerView with an EpoxyController with no problems

**Comment by yihuaqi** [comment]
@elihart Yeah, I guess the best I can do is to reuse the layout only...Unless I migrate the non Epoxy adapter to EpoxyController. 

Thanks
