### ISSUE TITLE
Error in add items from recyclerView

### ISSUE THREAD

**Issue by Jparrgam** [airbnb/epoxy#428]
hi @elihart 

is necessary add id from model. I have this error 

`Caused by: com.airbnb.epoxy.IllegalEpoxyUsage: You must set an id on a model before adding it. Use the @AutoModel annotation if you want an id to be automatically generated for you.`

How do I take the current location of an item?

**Comment by elihart** [comment]
See https://github.com/airbnb/epoxy/wiki/Epoxy-Models#model-ids

If you want to use model index then you have to track that and set it manually
