### ISSUE TITLE
Add class based annotation so EpoxyModels with attributes can still get a generated class

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#43]
Helpful for models that extend other models with Epoxy attributes, where the subclass doesn't need to add any attributes

**Comment by geralt-encore** [comment]
So basically it should be allowed only for models that extend other models with attributes?

**Comment by elihart** [comment]
Yes, but that is just the use cases I have seen. It may be that somebody may want a generated class for a model that doesn't have any attributes on super classes. 

Not sure why that would be needed, but I don't see any errors that would come from that case so I don't see any reason to prevent that usage.

**Comment by elihart** [comment]
#47
