### ISSUE TITLE
Paging with GridLayoutManager

### ISSUE THREAD

**Issue by fcgregorio** [airbnb/epoxy#430]
Does the Paging Library integration work with GridLayoutManager?

I have a 2-column RecyclerView, If the first PagedList contains these items [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], then my screen looks something like this:

1 2

3 4

5 6

7 8

9 10

When I scroll down, the next PagedList contains [8, 9, 10, 11, 12, 13, 14, 15, 16, 17], which then looks like this:

8 9

10 11

12 13

14 15

16 17

When using a LinearLayout Manager, there's no issue here. However when using a GridLayoutManager, you'll see some funky animations happening because of the shift in position of 8, 9, and 10.

**Comment by elihart** [comment]
I don't see why it wouldn't work with a grid layout. The only issue I can think of is your config page sizes might not be large enough. What do you have them set to?

**Comment by fcgregorio** [comment]
I have mine set to this
```kotlin
val config = PagedList.Config.Builder()
        .setPageSize(20)
        .setPrefetchDistance(6)
        .setInitialLoadSizeHint(60)
        .setEnablePlaceholders(false)
        .build()
```

**Comment by elihart** [comment]
Your page size is too small. If you double the number of items on screen the page size should be at least doubled. Look at the javadoc at https://github.com/airbnb/epoxy/blob/master/epoxy-paging/src/main/java/com/airbnb/epoxy/paging/PagingEpoxyController.java#L220

**Comment by fcgregorio** [comment]
> Your page size is too small.

Fixed the Exception. But I still have my original problem with using a grid layout.

**Comment by elihart** [comment]
What have you increased your page size to? if you are showing 10 items in the grid it seems like you should have at least 50. Can you try with a large page size and see if the issue still exists?

**Comment by fcgregorio** [comment]
I replaced the page size to 500. With a 2-column grid, I can view around 60 items on my phone.

**Comment by elihart** [comment]
Thanks for the update, sounds like everything is working fine then. You'll probably want to use an even larger page size for tablets.
