### ISSUE TITLE
adapter.getModelById() not working.

### ISSUE THREAD

**Issue by gevariya-ajit** [airbnb/epoxy#436]
Create model in `bindModels()` :
```
MediaItemView.Model(thmPath, clickListener)
                                .id(101L)
                                .addTo(this)
```

Try to access by id:
`adapter.getModelById(101L)` 

Which is not working probably due to 
```
  public EpoxyModel<T> id(Number... ids) {
    long result = 0;
    for (Number id : ids) {
      result = 31 * result + hashLong64Bit(id.hashCode());
    }
    return id(result);
  }
```

Am I missing something?

**Comment by elihart** [comment]
As you can see in that method, it takes `Number... ids` and hashes them into a single id. the method you're calling with `id(101L)` should be calling `EpoxyModel<T> id(long id)` which does set the id exactly.

when are you calling `getModelById`? it won't work until models are diffed and updated in the recyclerview, so it won't work immediately after adding the model

**Comment by gevariya-ajit** [comment]
Not calling immediately, I tried to find the model at onClick from the controller callback.
Is there any way to find the model? the position isn't working either.

I figured my problem to pass back model from click listeners though.

**Comment by gevariya-ajit** [comment]
@elihart I am also facing one problem that selection wipes out on a scroll if I did that first time, just after loading the grid. 

` it won't work until models are diffed and updated in the recyclerview`

If you can explain it will be helpful to figure out the solution.

![05-22-2018-02 49 09](https://user-images.githubusercontent.com/1627904/40331245-4f78216c-5d6d-11e8-9df8-d299fd1c0c8e.png)

**Comment by elihart** [comment]
if you need the model on click you should use https://github.com/airbnb/epoxy/wiki/Epoxy-Models#click-listeners

**Comment by gevariya-ajit** [comment]
Thank you @elihart, Implemented that.
