### ISSUE TITLE
Loosing attribute state for first time scrolling.

### ISSUE THREAD

**Issue by gevariya-ajit** [airbnb/epoxy#438]
```
    data class Model(
        private val media: Media,
        private val thmPath: String,
        private val clickListener: (Model, Media, Boolean) -> Any?,
        private val longClickListener: (Model, Media, Boolean) -> Any?
    ) : EpoxyModel<MediaItemView>(), MediaEpoxyModel {

        @EpoxyAttribute private var isSelected: Boolean = false
        private var mediaItemView: MediaItemView? = null

        override fun getDefaultLayout() = R.layout.media_item_view

        override fun shouldSaveViewState(): Boolean = true

        override fun bind(view: MediaItemView) {
            Timber.d("BIND model: ${this.id()} hash: ${hashCode()} isSelected: $isSelected")
            mediaItemView = view
            view.bind(media, thmPath)
```
Somehow `isSelected` is getting reset for firsttime scrolling.
*Steps:*
> Select first grid item through long press which set `isSelected` true.
> Scroll down ~30 items with header
> Scroll up so bind perform for that selected item, but somehow getting `isSelected=false`

This problem happens only first-time selection, else getting a perfect attribute value as `true` if selected.

**Comment by elihart** [comment]
How are you updating the `isSelected` property once the user selects it? are you rebuilding models?

**Comment by gevariya-ajit** [comment]
Thanks you @elihart for quick replay 👍 

No, I have implemented the interface to the Model.
```
    interface MediaEpoxyModel {

        fun toggleSelection()

        fun resetSelection()

    }

   data class Model(
        private val media: Media,
        private val thmPath: String,
        private val clickListener: (Model, Media, Boolean) -> Any?,
        private val longClickListener: (Model, Media, Boolean) -> Any?,
        private var isSelected: Boolean
    ) : EpoxyModel<MediaItemView>(), MediaEpoxyModel {

        private var mediaItemView: MediaItemView? = null

        override fun getDefaultLayout() = R.layout.media_item_view

        override fun shouldSaveViewState() = true

        override fun bind(view: MediaItemView) {
            Timber.d("BIND model: ${this.id()} isSelected: $isSelected")
            mediaItemView = view
            view.bind(media, thmPath)
            view.updateSelection(isSelected)

            view.setOnClickListener { clickListener(this, media, isSelected) }
            view.setOnLongClickListener {
                longClickListener(this, media, isSelected)
                true
            }
        }

        override fun toggleSelection() {
            Timber.d("toggleSelection :$isSelected id:${id()}")
            isSelected = !isSelected
            mediaItemView?.updateSelection(isSelected)
        }

        override fun resetSelection() {
            Timber.d("resetSelection :$isSelected id:${id()}")
            isSelected = false
            mediaItemView?.updateSelection(isSelected)
        }
}
```

On click view, I am toggling or on back press resetting model `isSelected` state.

**Comment by elihart** [comment]
This isn't the correct way to use models. They should be immutable, you can't change them once they are added to the EpoxyController. Read more in the wiki https://github.com/airbnb/epoxy/wiki/Epoxy-Controller

the correct way to handle this is to have a callback to your controller to update some state there that keeps a list of all selected items. when you build models you should set the model prop based on that list. When the list is updated models should be rebuilt.

**Comment by elihart** [comment]
I would also recommend using @ModelView instead of making the model manually - https://github.com/airbnb/epoxy/wiki/Generating-Models-from-View-Annotations

this will force you to use better patterns and the generated model will be more efficient

**Comment by gevariya-ajit** [comment]
Thank you @elihart, `requestBuildModels` working as expected
