### ISSUE TITLE
PagingEpoxyController and RxPagedListBuilder Example

### ISSUE THREAD

**Issue by estelle-peterson** [airbnb/epoxy#439]
Hi,

Is there an example that shows how to configure and use RxPagedListBuilder with PagingEpoxyController? One that also includes the usage of a boundaryCallback would be great too!

```
Observable<PagedList<User>> = RxPagedListBuilder(dataSourceFactory, pageConfig)
                .setBoundaryCallback(boundaryCallback)
                .buildObservable()
```

**Comment by herald25** [comment]
Hi @elihart! How can I display progress bar when fetching next page using PagedListEpoxyController? I've tried to make a paginated list but it didn't show the progress bar as default.

**Comment by elihart** [comment]
@herald25 this is a totally unrelated issue. How would you build that progress bar with a normal Recyclerview and Paged List? Epoxy doesn't offer anything special for that.

for the original question we don't have any samples for RxPagedListBuilder
