### ISSUE TITLE
Swipe to delete doesn't work properly after item is removed

### ISSUE THREAD

**Issue by edwinnyawoli** [airbnb/epoxy#441]
After adding a few items to the adapter and swiping to delete an item, I'm unable to delete any other item from the recyclerview.
I created a sample app that illustrates this [here](https://github.com/edwinnyawoli/epoxytest)

**Comment by elihart** [comment]
I'm taking the next two weeks off, so I won't have time to dig into this. But at a cursory glance it looks like your approach of using index to set id won't work. If you swipe to delete an item at position 0, the way the ids are set up it will think that the item at the end of the list was removed. generally using position is not a good idea, id should map to some intrinsic value of the model

**Comment by edwinnyawoli** [comment]
Didn't realize that. I modified the code to use the uuid on each item and everything works perfectly. Thanks :thumbsup:
