### ISSUE TITLE
StaggeredGridLayoutManager - different spans

### ISSUE THREAD

**Issue by tomaszczura** [airbnb/epoxy#442]
I am trying to make the library work with StaggeredGridLayoutManager, where some rows are full width, and some have two columns. How can I accomplish this?

**Comment by elihart** [comment]
Not sure off the top of my head, I've never used a staggered grid. It may not be possible; Epoxy was only designed for linear/grid layout managers.

If you look into it and can figure out a way to make it work please share. Or I can help with a PR if you want to add support

**Comment by kraghu** [comment]
Hi @elihart ,

I am  looking for this as well. First of all I have been using epoxy for more than a year now and I absolutely love it! 
Now just to support StaggeredGridLayoutManager if i have go back to recycle view ,it is gonna make me sad :( I am  trying to have the layout like pinterest as in this image . If you can help me out on achieving this using epoxy ,I would really appreciate that :) 

![pinterest-layout](https://user-images.githubusercontent.com/1152058/42002448-34dc9876-7a1c-11e8-963b-ae1aa6b431e6.png)

**Comment by elihart** [comment]
Have you tried using a StaggeredGridLayoutManager normally with Epoxy? if you're willing to put some work in to try it I can review

**Comment by kraghu** [comment]
Ok i will do some time this week and let you know how it goes . Thanks

**Comment by kraghu** [comment]
Yeah please close this. We went in the different direction. Sorry for getting back to you so late :)

**Comment by JasonHezz** [comment]
StaggeredGridLayoutManager  wroks fine with epoxy.
But for full span, override **getSpanSize**  or **SpanSizeOverrideCallback** is not working, you need do something like below or maybe epoxy can support it latter?

```
override fun bind(holder: BaseViewHolder) {
        super.bind(holder)
        val layoutParams = holder.yourlayout.layoutParams
        if (layoutParams != null && layoutParams is StaggeredGridLayoutManager.LayoutParams) {
            layoutParams.isFullSpan = true
        }
    }
```
![device-2018-08-15-105643](https://user-images.githubusercontent.com/15358765/44131459-c17a8240-a085-11e8-83b7-94f522806460.png)

**Comment by elihart** [comment]
@JasonHezz Thanks for pointing this out. I don't anticipate supporting that in the base library, but I think it would be easy for someone to do on their own. This is what I would do

1. Override `EpoxyController#onModelBound` to get access to the viewholder
2. Check a property on the model to see if it should be set to full span
3. Create a base EpoxyModel that you inherit from that has that property, and create a base EpoxyController that all your other controllers inherit from to handle `onModelBound`

This way you set up a just a little bit of support in your base classes, but all other usages in your app will support it with no extra work.

**Comment by JasonHezz** [comment]
@elihart The solution seems only work for viewHolder, but can't work for both custom views(like Carousels) and viewHolder.

**Comment by elihart** [comment]
Why not? Custom Views can also define a base epoxy model to be used

**Comment by JasonHezz** [comment]
@elihart I got what you mean.
I misunderstood that make a baseHolder rather than a baseModel.

For custom view:
I can define baseModel via  baseModelClass
```
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT, baseModelClass = FullSpanModel::class)
class FlexCarousel(context: Context) : Carousel(context) {
}
```
But what can I do for EpoxyModelWithHolder?
I have tried something like:
```
abstract class FullSpanModelWithHolder<T : EpoxyHolder> : FullSpanModel<T>() {

}
```
It fails Because EpoxyViewHolder check if it's EpoxyModelWithHolder
```
if (epoxyHolder == null && model instanceof EpoxyModelWithHolder)
```
BTW, handle StaggeredGridLayoutManager full span should override ```onViewAttachedToWindow```

**Comment by elihart** [comment]
@JasonHezz Can't you just make a separate model as a base class that extends from `EpoxyModelWithHolder`? So you would have a different base class for models with holders vs custom views. But you could give them the same interface at least if you want to be able to group them together
