### ISSUE TITLE
Generated builder class inheritance

### ISSUE THREAD

**Issue by IVIanuu** [airbnb/epoxy#445]
Hey guys i have the following problem.

I have a base class with a couple of epoxy attributes which then generates a ***ModelBuilder class for it

Because it's a base class i subclass it multiple times which then also generates a ***ModelBuilder class for each of the sub classes

I'm using kotlin so i would like to write a extension function for the builder class of the base class but because the builder classes do not inhere from each other i also need to write the same extension for any of the sub class builders which is not very practical.

Is there a reason why the builders do not inhere from each other?
And is it possible to add that it in the future?

Thanks

**Comment by elihart** [comment]
I don't remember why I didn't make them inherit from each other, probably just to keep things simple.

It's a reasonable request though and the use case makes sense. I'll try to make it happen

**Comment by IVIanuu** [comment]
Ok thanks.

**Comment by IVIanuu** [comment]
Because i instantiate the models via the generated kotlin extensions.

**Comment by IVIanuu** [comment]
Any news?

**Comment by elihart** [comment]
No sorry, I haven't had a chance to work  on this yet.
