### ISSUE TITLE
Generated Kotlin Extensions Don't Adhere to Nullability

### ISSUE THREAD

**Issue by shaishavgandhi05** [airbnb/epoxy#448]
In version 2.9.0, if you have a model in Kotlin like:
```kotlin
@EpoxyModelClass abstract class HeaderModel(val title: String, val subtitle: String?): EpoxyModelWithHolder<Holder>() {}
```
the generated Kotlin Extension function doesn't maintain the nullability of the `subtitle`. Generated extension look something like:
```kotlin
inline fun EpoxyController.headerModule(
    title: String,
    subtitle: String,
    modelInitializer: HomeModuleHeaderModelBuilder.() -> Unit
) 
```

Happy to send a PR if you're able to replicate.

**Comment by elihart** [comment]
Thanks for the report, good catch!

I went ahead and fixed it with https://github.com/airbnb/epoxy/pull/449

**Comment by shaishavgandhi05** [comment]
Awesome! Thanks for the quick turnaround.
