### ISSUE TITLE
Epoxy: Layout margin not respected in epoxy model created using custom view

### ISSUE THREAD

**Issue by Winghin2517** [airbnb/epoxy#456]
I have been testing the epoxy library and cannot seem to get the epoxy model created from the custom view method to respect the layout margin's set. According to epoxy, there is 3 ways to create epoxy models:

1. Annotate custom views
2. Use Android databinding
3. Use the view holder pattern

The guidance material from Epoxy is here: https://github.com/airbnb/epoxy/wiki/Epoxy-Models

I have been experimenting with the **custom view method** and the **data binding method** using the **same** layout and have received different results.

From the screenshot below, you can see that the custom view epoxy model displays the cardview with no margin - the cardview rest on the end of the screen even though the xml shows that I have set a layout_margin of 10dp. It appears that the margin is applied inside the cardview but I have set no padding. 

![screen-shot-2018-06-23-at-17 16 18](https://user-images.githubusercontent.com/7094734/41811227-03f934b6-770c-11e8-9b51-3a703f917ec5.jpg)

For the data binding view epoxy model, the layout margin of 10dp is displaying correctly. 

I have also created a sample app and you can download it here to test: https://github.com/Winghin2517/epoxy_example1

I have also created a SO question here: https://stackoverflow.com/questions/51002634/epoxy-layout-margin-not-respected-in-epoxy-model-created-using-custom-view

Does anyone know how I can get epoxy to respect the margin set for custom views epoxy models?

**Comment by Winghin2517** [comment]
I didn't find an answer in the end but instead I used the ViewHolder epoxy models instead with a custom view and epoxy respected the margins set.

**Comment by elihart** [comment]
Looks like you are nesting two CardViews, you should be using merge tags on the xml file to inflate it into your custom class.

`autoLayout` doesn't let you customize attributes like margin, if you need to do that then you need to specify a layout file with `defaultLayout`

**Comment by Winghin2517** [comment]
Thank you - that makes sense.

I changed my code to inflate the HeaderView from xml and used the includes tag:

```
<?xml version="1.0" encoding="utf-8"?>
<kwaai.com.exampleepoxy.HeaderView
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:id="@+id/cardview"
    card_view:cardBackgroundColor="@color/colorAccent"
    >

    <include layout="@layout/test_card"/>

</kwaai.com.exampleepoxy.HeaderView>

```

test_card.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        app:cardElevation="8dp"
        android:padding="8dp"
        app:cardCornerRadius="3dp"
        app:cardBackgroundColor="@color/colorAccent">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="8dp"
            android:gravity="center"
            android:text="Howdy"
            android:id="@+id/hello" />


    </android.support.v7.widget.CardView>

</merge>
```

headerview.java: 

```
@ModelView(defaultLayout = R.layout.header_view)
public class HeaderView extends FrameLayout {

    @BindView(R.id.hello)
    TextView hello;

    public HeaderView(Context context) {
        super(context);
        init();
    }

    public HeaderView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }


    private void init() {
        ButterKnife.bind(this);
    }

    @TextProp(defaultRes = R.string.app_name)
    public void setTitle(CharSequence title) {
        this.hello.setText(title);
    }

}
```
