### ISSUE TITLE
Prefixing @EpoxyAttribute variable with "is" causes compile error

### ISSUE THREAD

**Issue by shyamu** [airbnb/epoxy#459]
Not sure what's going on here. 

I'm creating my models in Kotlin and have an attribute as follows
`@EpoxyAttribute var isChildComment: Boolean = false`

This causes a compile error in the generated class
`error: isChildComment() in VideoCommentModel_ cannot override isChildComment() in VideoCommentModel
  public boolean isChildComment() {
                 ^
  overridden method is final`

If I change the attribute to the following, the compile error is resolved
`@EpoxyAttribute var childComment: Boolean = false`
or
`@EpoxyAttribute var ischildComment: Boolean = false`

**Comment by shyamu** [comment]
I'm seeing this with Epoxy 2.13.0

**Comment by josephyanks** [comment]
If you add `@JvmField` to the field, that error should go away.

**Comment by shyamu** [comment]
Thank you!

Adding `@JvmField` solved the issue though I'd like to understand the problem more. Is this an epoxy bug?

**Comment by yulimelee** [comment]
you can also use it by making field open
