### ISSUE TITLE
How does Epoxy work with Android Paging Architecture component?

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/epoxy#461]
I wanted to ask on Reddit, but I know @elihart prefers github issues.

**Comment by josephyanks** [comment]
Have you checked out the [sample app](https://github.com/airbnb/epoxy/tree/master/epoxy-pagingsample) and [wiki](https://github.com/airbnb/epoxy/wiki/Large-Data-Sets)?

**Comment by ColtonIdle** [comment]
Feel free to close this @elihart but I would like to recommend that the name of the wiki page be updated to something more accurate. Instead of listing "Add Ons" as 

Paris (Dynamic Styling)
EpoxyRecyclerView
Carousels
Saving View State
Grid Support
Swipe and Drag Support
Grouping Models
Large Data Sets
Litho Support
Cyclic Adapters

I think it's more accurate to say

Paris (Dynamic Styling)
EpoxyRecyclerView
Carousels
Saving View State
Grid Support
Swipe and Drag Support
Grouping Models
Android Paging or Paging Arch Component
Litho Support
Cyclic Adapters

**Comment by elihart** [comment]
Sure, I updated the sidebar name. Also a friendly reminder that searching for "paging" in the search bar brings up the wiki page

**Comment by ColtonIdle** [comment]
@elihart Hm. That was definitely one of the first things I did and it showed 0 results. If I did miss that though, please excuse the oversight. Thanks again for all of the work.

**Comment by mgursch** [comment]
You can find a detailed description how you can use architecture paging component with epoxy:
https://code.allaboutapps.at/articles/advanced-pagination-with-epoxy/
