### ISSUE TITLE
Using Kotlin with ModelView incorrectly provides no build errors

### ISSUE THREAD

**Issue by ebabel** [airbnb/epoxy#462]
Hi,
There is no sample code for creating a `ModelView` from within Kotlin and there are no warnings/build errors when doing it incorrectly. This should be more verbose and this would be a very helpful snippet in `kotlinsample`.
Working approach to creating `ModelView`:

```kotlin
    @ModelView(defaultLayout = R.layout.card_sample)
    open class HeaderView : RelativeLayout {
        constructor(context: Context) : super(context)
        constructor(context: Context, attrs: AttributeSet) : super(context, attrs)
        constructor(context: Context, attrs: AttributeSet, defStyle: Int) : super(
            context,
            attrs,
            defStyle
        )

        private var titleProp: CharSequence? = null
        @TextProp(defaultRes = R.string.app_name)
        open fun setTitle(string: CharSequence?) {
            titleProp = string
        }
    }
```

Incorrect code approach, producing a successful build with no errors/warnings but no epoxy class was made for this:

```kotlin
@ModelView
abstract class HeaderView2 : LinearLayout {
    constructor(context: Context) : super(context)
    constructor(context: Context, attrs: AttributeSet) : super(context, attrs)
    constructor(context: Context, attrs: AttributeSet, defStyle: Int) : super(
        context,
        attrs,
        defStyle
    )
    private var titleProp: CharSequence? = null
    @TextProp(defaultRes = R.string.app_name)
    fun setTitle(title: CharSequence) {
        titleProp = title
    }
}
```
Thanks for this excellent library!

**Comment by elihart** [comment]
Sure, I can provide better samples for this. I'll put it on the TODO list

help is welcome if anyone wants to help with this

**Comment by elihart** [comment]
I added a new wiki section with examples, and also add code to the kotlin sample module.

https://github.com/airbnb/epoxy/wiki/Kotlin-Model-Examples

Your problem here was just that your class was abstract, and epoxy ignores abstract views when generating models. It's the same in java, nothing to do with kotlin. Your `fun` does not need to be `open`
