### ISSUE TITLE
Model removed

### ISSUE THREAD

**Issue by JasonHezz** [airbnb/epoxy#464]
epoxy-paging library upgrade version from 2.11.0 to 2.11.0. When models scroll out of screen, they are seems moved from list and can't scroll back. Version 2.11.0 is fine,

Here is a [sample link](https://github.com/JasonHezz/EpoxyPagingIssue)

**Comment by elihart** [comment]
`from 2.11.0 to 2.11.0`

what is the new version?

**Comment by JasonHezz** [comment]
Sorry ,from 2.11.0 to 2.14.0. Actually it is from 2.11.0 to 2.12.0 after test.

**Comment by elihart** [comment]
Thanks for clarifying. Did you read the release notes carefully for 2.12.0? https://github.com/airbnb/epoxy/releases/tag/2.12.0

your page size seems very small and may be causing your issue

**Comment by JasonHezz** [comment]
Thanks for clarifying. It works after changing page size from 10 to 20.
