### ISSUE TITLE
Data Binding Compiler V2

### ISSUE THREAD

**Issue by iMvBremen** [airbnb/epoxy#466]
As can be seen right [here](https://developer.android.com/studio/releases/#codingide), Android Studio 3.1 supports the [Data Binding Compiler V2](https://developer.android.com/topic/libraries/data-binding/start#preview-compiler).

When testing Epoxy with this new compiler, the build fails saying "_error: cannot find symbol class DataBinderMapperImpl_".

Is it possible for a future version of Epoxy to support this new compiler?

**Comment by elihart** [comment]
I _think_ it should be possible for Epoxy to support the new compiler, but I haven't looked into it extensively yet. It seems like the generated binding classes are now created by the gradle plugin instead of via an annotation processor.

As long as they are available to be looked up in the annotation processor it should be fine, but I probably don't have time to investigate this right now, at least until the new compiler is stable.

If anyone else wants to look into this I can help with guidance

**Comment by iMvBremen** [comment]
Thanks for the answer. I've looked into this a bit today and it looks like all that is needed to make this work is a define in [gradle.properties](https://github.com/airbnb/epoxy/blob/master/gradle.properties). The define being `android.databinding.enableV2=true`.

If anyone is interested in using the new compiler in their own project until it is actually stable and added to Epoxy, here are the steps:

1. Clone the Epoxy git
2. Add `android.databinding.enableV2=true` to the [gradle.properties](https://github.com/airbnb/epoxy/blob/master/gradle.properties) file
3. Build the [epoxy-databinding](https://github.com/airbnb/epoxy/tree/master/epoxy-databinding) module: Build > Make Module 'epoxy-databinding'
4. Add the .AAR Package to your own project: File > New Module > Import .JAR/.AAR Package > ../epoxy/epoxy-databinding/build/outputs/aar/epoxy-databinding-release.aar
5. Add `implementation project(':epoxy-databinding-release')` to your build.gradle (Obviously replacing `implementation 'com.airbnb.android:epoxy-databinding:2.14.0'`)

I have not extensively tested this, but it seems to work just fine for as far as I can see.

**Comment by elihart** [comment]
Good to hear, thanks for the update! It sounds like once the new compiler is officially enabled as the default it will work just fine with Epoxy with no changes.

I'll just have to make sure this project is updated to the latest AGP version once 3.2 is released
