### ISSUE TITLE
Epoxy sets allowBackup="true"

### ISSUE THREAD

**Issue by audax** [airbnb/epoxy#467]
See: https://github.com/airbnb/epoxy/search?q=allowBackup&unscoped_q=allowBackup

I don't see a good reason why Epoxy would need to set this attribute. To actually disable backups for my application, I had to set `tools:replace="android:allowBackup"` in my manifest.

**Comment by elihart** [comment]
Are you using the databinding module? It doesn't seem to be set for the main epoxy module.

I don't think I set this purposefully, and the only thing I can think of is that this is the default when using Android Studio's wizard to create a new module.

I _think_ it should be fine if we remove it. Thanks for bringing it up

**Comment by audax** [comment]
Yes, I am using the databinding module. The default for new modules is indeed `true` which is why I only noticed this after using epoxy for a while.

**Comment by elihart** [comment]
Fixed with https://github.com/airbnb/epoxy/pull/481
