### ISSUE TITLE
Drag and drop between multiple recyclers

### ISSUE THREAD

**Issue by ATizik** [airbnb/epoxy#469]
Is it possible to drag and drop an element from one EpoxyRecyclerView to another without View.OnDragListener?

**Comment by elihart** [comment]
Is this possible in vanilla RecyclerView? If so we should be able to support it with Epoxy.

I feel like this is unlikely to be supported though

**Comment by elihart** [comment]
Looks like this library shows how to handle this: https://github.com/pooja-gaikwad15/recyclerview-list-drag-and-drop

I have no plans to support this in epoxy myself, but would review a PR if someone wants to do the work
