### ISSUE TITLE
Where to handle onClickListeners when using Epoxy?

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/epoxy#470]
Again, another "open ended" question that isn't really an issue. Please let me know if there's a better place for these @elihart 

Anyway, on to my question. Now that I'm using Epoxy almost exclusively it's led me down another path where I don't have a clear answer. I'm very much trying to use the Google recommended approach to Android architecture and I'm not sure where setting the action for my onClickListeners should happen. Using epoxy it looks like it can happen in MyActivity, MyEpoxyController, or MyEpoxyModel.

Is there anything that's recommended? I think it makes a lot of sense for it to just be done in the EpoxyModel itself so that one class really handles everything, but I'm curious if anyone has other opinions on it. Especially when using Android Arch components (i.e ViewModel)

**Comment by elihart** [comment]
I would generally advise against having the model handle the click action. In my opinion it's better to keep the model generic to where it is used.

I think either the controller, activity, or fragment is fine and I'm not too dogmatic about which is best. I think the most important thing is to pick a pattern and stay consistent. It also matters what your click action is doing. If it is updating data then it needs to be routed to your data layer, which the epoxy controller shouldn't be managing. If you're just starting a new activity then the controller can probably do that.

**Comment by ColtonIdle** [comment]
@elihart thanks. I guess I'm probably doing a bit too much in my *EpoxyModel classes then. I will see if I can get away with passing in a listener as an @EpoxyAttribute.
