### ISSUE TITLE
Wish: The EpoxyController has the power to scroll to particular position

### ISSUE THREAD

**Issue by boyw165** [airbnb/epoxy#471]
The code snippet is a quite common use case:

```kotlin
// Give the view controller the data set, where the view controller is exactly the EpoxyController
mRecyclerViewController.setData(...)
// After giving the new view-model set, scroll to particular position
mRecyclerView.post {
    mRecyclerView.scrollToPosition(...)
}
```

The code above is error-prone because if the post-task is not canceled when your user leaves this page (`Activity`/`Fragment`/`custom View`) early before the concurrent task is dispatched, the app crashes. Because we can't guarantee the concurrent task is processed under the constraint of the `Context` is still alive.

To prevent the app from crashing, the code becomes like the boilerplate as below

```kotlin
// Give the view controller the data set, where the view controller is exactly the EpoxyController
mRecyclerViewController.setData(...)
// After giving the new view-model set, scroll to particular position
mUiHandler.post(mScrollToPositionRunnable)

// onDestroy() or onPause()
mUiHandler.cancelPost(mScrollToPositionRunnable)
```

When assigning the view-model set to the `EpoxyController`, the `EpoxyController` runs the view-model building process as well as the async diffing in the background thread, and notifies view to update when that finishes, which means it is the only one aware of the view-models lifecycle. I would suggest adding a method to scroll to the particular position, for example:

```kotlin
// Give the view controller the data set, where the view controller is exactly the EpoxyController
mRecyclerViewController.setData(...)
// After giving the new view-model set, scroll to particular position
mRecyclerViewController.scrollToPosition(100)
```

Internally, the `EpoxyController` knows about when the view-model construction finishes, and it could schedule the scroll-to-position task after the construction.

That's my suggestion, what do you think of it?

**Comment by elihart** [comment]
I agree this is a common problem and epoxy should provide a better solution. It gets even worse if we enable async diffing.

I don't think the solution should be for epoxy to manage scrolling though, it seems better to have a generic approach where a callback an be registered for after epoxy submits change notifications to the RecyclerView.

**Comment by boyw165** [comment]
Thanks for the comment.

I partially agree with that there should be a callback for after `Epoxy` submits change notifications to the `RecyclerView`, where you might create a children class deriving the `RecyclerView`. In result, the code might look like:

```kotlin
// onCreate() or onResume()
mRecyclerView.addChangeNotificationListener { recyclerView ->
    recyclerView.scrollToPosition(100)
}

// onDestory or onPause()
mRecyclerView.removeAllChangeNotificationListeners()

// Somewhere when the data is ready
mRecyclerViewController.setData(...)
```

And because the listener is sort of a hack or extension to the `RecyclerView`, it becomes complicated and adding more dependency.

I understand your concern and I'd still vote for adding this ability to `Epoxy` where `Epoxy` framework is sort of a view controller serving the RecyclerView, which implicitly indicates all the operations applied to the RecyclerView have to go through the EpoxyController. The abstraction prevents the programmers from touching the View directly. Further, the EpoxyController knows about the view-model construction status, so it is a good fit that provides this additional ability.

**Comment by elihart** [comment]
I'm not actually proposing a change listener on the recyclerview. That already exists, you can register an observer on the adapter instead of posting a runnable.

I'm suggesting that epoxy could let you associate a callback with a model building event
```
Controller.setData(data) {
   // call back code when changes from new data are posted
}
```

this lets you closely associate the callback with the specific data and doesn't require changing recyclerview

**Comment by elihart** [comment]
With this PR https://github.com/airbnb/epoxy/pull/425 I have added the ability to register a `OnModelBuildFinishedListener` which gives the before and after model lists, and diff results, when a model build is done, after changes have been dispatched to the recyclerview.

This can be used to do things like scrolling, or anything else people might want.
