### ISSUE TITLE
How to use Dependent Properties in kotlin?

### ISSUE THREAD

**Issue by deltaguita** [airbnb/epoxy#472]
Hi:

How to use Dependent Properties in kotlin?
I got error message:  ` this annotation is not applicable to target 'member property with backing field' `
 when I try to  use
```
    @ModelProp
    var classB: ClassB? = null
```

**Comment by alexbchr** [comment]
`@ModelProp` properties are applied to functions (setter function to be more specific).
So what you need to do is apply `@ModelProp` attribute to setter function of `classB`.

```
var classB: ClassB? = null
    @ModelProp set
```

For more information, see [Kotlin Properties Reference](https://kotlinlang.org/docs/reference/properties.html#getters-and-setters) (see example with `@Inject` attribute).
