### ISSUE TITLE
How to achieve Expandable Recyclerview with Epoxy

### ISSUE THREAD

**Issue by shakil807g** [airbnb/epoxy#473]
I want to create expandable list  using this lib it would be better if there is any sample on how to do it ?

**Comment by elihart** [comment]
Generally what I would recommend is just requesting a model rebuild and adding more models if you want to show the extended state. if you need to visually group them you might need to use EpoxyModelGroup

**Comment by Nimrodda** [comment]
In case anybody is interested in a working example, I wrote a tutorial how to implement such feature: http://bit.ly/2WVeI0S
