### ISSUE TITLE
Frequent updates

### ISSUE THREAD

**Issue by ramanbranavitski** [airbnb/epoxy#475]
Hi. Faced a problem working with Epoxy. I need to implement view selection by clicking on it. Right now I have a following code

```
public class Controller extends TypedEpoxyController<List<Entity>> {

    private Entity selectedItem;

    Controller() {
    }

    @Override
    protected void buildModels(final List<Entity> data) {
        for (Entity entity : data) {
            new EntityModel()
                    .id(entity.getId())
                    .selected(selectedItem != null && selectedItem.equals(entity))
                    .clickListener(new ClickListener(v -> {
                        if (selectedItem == null || !selectedItem.equals(entity)) {
                            selectedItem = entity;
                            setData(getCurrentData());
                        }
                    }))
                    .addTo(this);
        }
    }
}
```
It's works fine, but when I click on different items frequently, views aren't redraw every time. Didn't find smth similar in the wiki page. Is there any way to handle all click events or maybe I do smth wrong. Hope for your advice. Thanks.

**Comment by elihart** [comment]
A couple thoughts

1. make sure `Entity` implements equals/hashcode correctly
2. Data updates are debounced, so clicking very fast could cause some clicks to be dropped because of that. are these fast frequent clicks, or just lots of clicks over time?
3. can you do some debugging and see if you can figure out where the clicks get lost?

This generally isn't a problem and it looks like you're doing this right

as an aside, you should write `entity.equals(selectedItem)` so you don't have to null check `selectedItem`

**Comment by ramanbranavitski** [comment]
Imagine that I have only 2 items in a list. Click on item makes it selected(just change it's background). I'm just fast clicking these two items one by one and expect they become selected. But as you said some of clicks are dropped(not clicks events, but rebuildModels events) and that's a problem for me. Is there any way to configure this debounced logic? Thanks for advice about `equals`:)

**Comment by elihart** [comment]
How do you know that clicks are dropped? Is the `selectedItem ` field set to something that isn't reflected on the display? If clicks are getting dropped how do you know it is in Epoxy and not in Android's view framework and click handling?

The debouncing is only for clicks within the same frame - model building is posted to the next frame. So unless you're trying to click faster than the frame rate of your device it shouldn't make a difference.

Have you done any debugging to check the internal state of your EpoxyController to see what is going on?

**Comment by ramanbranavitski** [comment]
You're right. `selectedItem` is set to one value, while on UI another view is still selected. View's `onClick` event triggers, while `setSelected()`method of my view not. I've made a small test with a default RecyclerView.Adapter class. After changing `selectedItem` I call `notifyItemChangedAtPosition()`with newPosition and previously selected one. Everything works fine. Every click on a new item makes it to be selected. But with Epoxy still have some drops.

**Comment by elihart** [comment]
@ramanbranavitski actually, maybe the best approach is to change to a `Typed2EpoxyController` and pass the selected item as a second piece of data. This way it is guaranteed to be in sync.

`buildModels` is intended to be a pure function to output models based on current state, and you're currently storing some state in the data list, and the other in the `selectedItem` field, and it is getting out of sync

**Comment by ramanbranavitski** [comment]
Ok, thanks, I'll try this approach. On the other hand it's quite strange. It's very simple task and in my opinion `Controller` is the place where such logic should be described.

**Comment by littleGnAl** [comment]
Hello @elihart , as #218 #426 mentioned, we should rebuild the models after the text changed, and it is recommended to use `requestDelayedModelBuild` to avoid rebuilding on every character input. But if I use the `TypedEpoxyController`, there no such `setData(T data, int delayMs)` method to handle delay build.

**Comment by elihart** [comment]
@littleGnAl the `TypedEpoxyController` class is just a small helper. You can create a class like it and modify it to support delay or anything else you want. Or you can just use EpoxyController directly

**Comment by littleGnAl** [comment]
@elihart Thank you for your reply, but why is there no official implementation, do you have any consideration?
