### ISSUE TITLE
Add `setter` boolean param to @EpoxyAttribute

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#48]
It would default to true, but you could change it to false if you don't want to expose the setter.

Something like `@EpoxyAttribute(setter=false) int value`

The use case is when you want to the change the value internally in the model but don't want external usage to change it.

Just an idea I'm playing around with, needs more thought

**Comment by geralt-encore** [comment]
Sounds really good - I don't see any problems with it. It's always nice to have more immutability. Shall I work on it or you still not sure about it yet?

**Comment by elihart** [comment]
I definitely think it would be useful in some situations, and I don't see a better way to prevent setters for certain methods. 

I think we could also add this to your new class based annotation to disable setters for all fields on a class, unless you manually override an attribute with `@EpoxyAttribute(setter=true)`. Maybe have the default value be a `Boolean` so it's null unless set so we can tell the different between a default value and a set value.

I think https://github.com/airbnb/epoxy/issues/37 would also be a useful one to work on and I don't think @gpeal has time to work on it any time soon so you could also take that if you are interested in it.

Thanks, and let me know if I can help at all!

**Comment by geralt-encore** [comment]
Cool! I will try to take care about both of these issues by the end of the week.

**Comment by elihart** [comment]
oh, and fyi @geralt-encore since I merged https://github.com/airbnb/epoxy/pull/53 we don't have to run processor tests from command line, works from Android Studio now :)

**Comment by geralt-encore** [comment]
Yeah, I have already seen this PR. That's really nice :)
