### ISSUE TITLE
RecyclerView with RadioButtons

### ISSUE THREAD

**Issue by Xset-s** [airbnb/epoxy#491]
How to implement smth like RadioGroup with RecyclerView (single selection)?

**Comment by elihart** [comment]
You need to track which item is selected, and when building models mark the correct model as selected. Each model would have a click listener that would update the selected item to that model, and rebuild models to reflect the new state

Roughly in pseduo kotlin
```
class MyController: EpoxyController() {
    var items: List<Item>
    var selectedItem: Item

    override fun buildModels() {
            items.forEach {
                myItemModel {
                    id(...)
                    isSelected(it == selectedItem)
                    onClickListener {
                        selectedItem == it
                        requestModelBuild()
                    }
                }
            }
    }
}
```

**Comment by Xset-s** [comment]
Thx c:
