### ISSUE TITLE
Get actual entity inside click listener callback.

### ISSUE THREAD

**Issue by ramanbranavitski** [airbnb/epoxy#499]
Hi. Spent a lot of time to find a way to get clicked entity inside clickListener callback.
Have the following code

```
@Override
    protected void buildModels(final List<Item> items) {

        for (Item item : items) {
            new ListItemViewModel()
                    .id(item.getId())
                    .name(item.getName())
                    .clickListener()
                    .addTo(this);
        }
    }

   public interface OnItemClickListener {
        void onItemClick(Item clickedItem);
    }
```
 I've tried to use just item from cycle, but as I noticed this entity cached somewhere and if it changes it's state I still receive "old" entity with not actual fields. Is there any way to receive clicked item? Thanks.

**Comment by elihart** [comment]
Have you looked at `OnModelClickListener` and https://github.com/airbnb/epoxy/wiki/Epoxy-Models#click-listeners

Normally epoxy doesn't rebind properties that don't change - that is an optimization that is documented in the wiki. The click listener is a special case though that will always have the most recently created model.

How are you creating your model? The rebinding changes based on the implementation

**Comment by ramanbranavitski** [comment]
Yes, I have. But it's not very convenient to calculate proper  if you're working with 2 different collections of data(let it be `List<Type1>` and `List<Type2>`) and headers for each one. If you have 1 element int these 2 arrays and click on the last item you will receive `position=3` from `OnModelClickListener` but it's the firs element of `List<Type2>`. Right now I'm using this approach as I haven't found any other working solutions. My model is 

```
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
public class ReminderListItemView extends ConstraintLayout {

    @BindView(R.id.tv_reminder_message) TextView tvMessage;
    @BindView(R.id.tv_reminder_name) TextView tvReminderName;

    public ReminderListItemView(final Context context) {
        super(context);
        init();
    }

    private void init() {
        inflate(getContext(), R.layout.item_reminder, this);
        ButterKnife.bind(this);
    }

    @TextProp
    public void setMessage(@Nullable final CharSequence message) {
        tvMessage.setText(message);
    }

    @TextProp
    public void setReminderName(@Nullable final CharSequence name) {
        if (TextUtils.isEmpty(name)) {
            tvReminderName.setText(R.string.reminder);
        } else {
            tvReminderName.setText(name);
        }
    }

    @CallbackProp
    public void clickListener(final @Nullable OnClickListener listener) {
        setOnClickListener(listener);
    }
}
```

and used it in `Controller` like

```
    @Override
    protected void buildModels(final List<Reminder> reminders) {

        new RulesSectionTitleViewModel()
                .id(0)
                .sectionName("Section name")
                .addIf(reminders.size() > 0, this);

        for (Reminder reminder : reminders) {
            new ReminderListItemViewModel()
                    .id(reminder.getId())
                    .reminderName(reminder.getName())
                    .message(messageBuilder.buildMessage(reminder))
                    .clickListener(new ClickListener{doSmth(reminder)})
                    .addTo(this);
        }
    }
```
Every time the List<Reminder> was changed I call `controller.setData(reminders);` with actual state of every reminder but inside clickListener still receive not updated objects.Right now changed the implementation to 

```
.clickListener((model, parentView, clickedView, position) -> {
                        if (onReminderClickListener != null) {
                            final List<Reminder> data = getCurrentData();
                            if (data != null) {
                                final Reminder clickedItem = data.get(getProperPosition());
                                onReminderClickListener.onReminderClick(clickedItem);
                            }
                        }
                    })
```

**Comment by elihart** [comment]
I would change your `ReminderListItemView` to include this line
```
@ModelProp Reminder reminder;
```

then set it on the model 
```
new ReminderListItemViewModel()
                    .id(reminder.getId())
                     .reminder(reminder)
```

Then in the click listener you can easily get it
```
.clickListener((model, parentView, clickedView, position) -> {
                                final Reminder clickedItem =  model.getReminder();
                                onReminderClickListener.onReminderClick(clickedItem);
                        }
                    })
```

that way you don't have to deal with item lookup. Also, the way you are currently looking up data has potential race conditions.

**Comment by ramanbranavitski** [comment]
Yeah, I've also tried this approach. It works, but seems a little bit strange to pass `Reminder` and then all it's properties separately. Anyway thanks for your response.

**Comment by elihart** [comment]
It is a little weird, but it's the best way to tie the exact data model to the view.

If you want, you could set up a base model that has a `Tag` system so you could set arbitrary

**Comment by ramanbranavitski** [comment]
Tried this approach and it doesn't work properly as well.  Imagine that my `Reminder` has the following structure

```
class Reminder{
   String id;
   String name;
   String status;
   boolean isLost
}
```
and only `name` and `status` need for `ReminderListItemViewModel`. I do following 

```
new ReminderListItemViewModel()
                    .id(reminder.getId())
                    .reminder(reminder)
                    .name(reminder.name)
                    .status(reminder.name)
```
Inside click listener I did

```
.clickListener((model, parentView, clickedView, position) -> {
                                final Reminder clickedItem =  model.getReminder();
                                onReminderClickListener.onReminderClick(clickedItem);
                        }
                    })
```
And have the following result. When `name` or `status` of the reminder were updated, then I receive correct model inside `clickListener`. But when only `isLost` field was updated(field that no need for updating the view) then I receive model with incorrect `Reminder` inside.

**Comment by elihart** [comment]
@ramanbranavitski your Reminder class needs to implement equals/hashcode correctly

**Comment by ramanbranavitski** [comment]
What do you mean? It obvious that Reminder will use only id inside equals/hashcode. Can you please describe the logic of such behavior?

**Comment by elihart** [comment]
```
class Reminder{
   String id;
   String name;
   String status;
   boolean isLost
}
```

This class needs to implement equals and hashcode so that all of these fields are included.

Otherwise when you rebuild your epoxy model, epoxy won't think that the Reminder changed, so it won't update the view with it.

**Comment by elihart** [comment]
I know, but if the hashcode/equals of the model does not change, then epoxy discards it. so if you want epoxy to know that the model is updated then `Reminder` must implement equals/hashcode

**Comment by ramanbranavitski** [comment]
But if I add 
```
@ModelProp public isLost(boolean isLost){
    empty method
}
```
without changing equals/hashCode of Reminder then everything starts to work
What is the reason?

**Comment by elihart** [comment]
Every @ModelProp on the view contributes to the model's hashcode/equals implementation.

**Comment by ramanbranavitski** [comment]
As we've found onModelClickListener provide only position and even passing the whole entity to the view also not working as expected. So, the library with almost 5k rating doesn't have built in way to handle click on item with providing clicked entity without writing useless code. Right?

**Comment by elihart** [comment]
It's well documented in the wiki https://github.com/airbnb/epoxy/wiki/Generating-Models-from-View-Annotations

`Every prop must have a type that implements equals and hashCode. This is necessary so that Epoxy can determine when the model's state has changed so it knows when to update the view.`

so this is working exactly as expected.

If you don't want the callback caching to be messing you up like this, then don't use `@CallbackProp` - that is well documented in it's behavior as well to say that it won't update it's closure https://github.com/airbnb/epoxy/blob/master/epoxy-annotations/src/main/java/com/airbnb/epoxy/CallbackProp.java

so just use `@ModelProp` on your setter instead.

Or if these solutions don't appeal to you, put up a PR with a better solution.
