### ISSUE TITLE
2.16.1 Artifact

### ISSUE THREAD

**Issue by shaishavgandhi05** [airbnb/epoxy#503]
Maven Central shows a 2.16.1 was already released but I don't see it in the Releases/Changelog. Can we add what was changed?

**Comment by elihart** [comment]
Done - https://github.com/airbnb/epoxy/releases/tag/2.16.1

Thanks for keeping me honest :P forgot to push that, it's a pretty small fix just for tests

**Comment by shaishavgandhi05** [comment]
Haha no worries. Was looking to upgrade today and just wondered what changed for minor version.
