### ISSUE TITLE
A question about saving state of nested carousel

### ISSUE THREAD

**Issue by tzaitoun** [airbnb/epoxy#508]
A bit of background: I have a navigation bar (4 tabs = 4 fragments). When a user clicks a tab I replace the current fragment, however i keep a reference to these 4 fragments from my activity. I save the controller and the data in the fragment as member variables (so when the fragment is replaced back, these variables still exist because I kept a reference to the fragment). 

In this fragment, I have an epoxy recycler view (vertical) and a nested carousel in each "viewholder". The state of the vertical recycler view is maintained, however the state of the carousel is not. I have overrided shouldsaveviewstate() (returned true) in my carousel's model. If this is not the first time creating the fragment, I do: mEpoxyRecyclerView.setController(mController). So why is the state not being restored, my controller has not changed? 

I would appreciate any help or insight, I apologize if this is not the proper place to ask.

**Comment by elihart** [comment]
Thanks for the well thought out question. Are you calling onRestoreInstanceState and onSaveInstanceState on your EpoxyController? https://github.com/airbnb/epoxy/wiki/Saving-View-State

**Comment by tzaitoun** [comment]
Background: I have 3 "nested" carousels with 20 items in each and they all lie in a fragment.

I didn't do it at first. But I did it now and still no luck. Just for testing, I saved the state on pause and restored it on resume. I made sure that shouldSaveViewState was being called (12 times, 4 items shown in screen for each carousel, it seems like it gets called before onPause). When i save my state in onPause it looks like this: 
![savedstate](https://user-images.githubusercontent.com/21265488/44618211-d1bc8880-a83f-11e8-827e-98a08e2c6499.png)

I don't want to waste your time any longer, but if it is possible to tell me if the saved state looks right-ish, that would be great. You can close the issue and I'll figure it out on my own. (I'll start by saving the state across activity destruction and maybe restructure the way I am doing the navigation bar fragment logic).

**Comment by elihart** [comment]
The size of should not be 0 - I'm not sure what's going wrong, but it sounds like you're on the right track.

I would put a breakpoint in BaseEpoxyAdapter#onSaveInstanceState and see what the data looks like at that point.

I won't close this yet, I'd like to help you get it resolved 👍

**Comment by tzaitoun** [comment]
Thank you for your help Eli. Ok, so I put the break point there and figured out the following two things:

1) I only had the shouldSaveInstanceState defined in in my nested model. But when ViewHolderState.save(EpoxyViewHolder) is called, it returns shouldSaveInstanceState as false (which is probably the parent model, I didn't define shouldSaveInstanceState there).

2) So I was hoping that was the problem and defined shouldSaveInstanceState there (in the parent and nested model). This resulted in the saving of a state. But it still didn't restore the state of the nested models.

This led me to believe that I am probably using the models wrong.

In my **main** model I define an attribute that takes in an arraylist of my secondary model. In **main** model's bind, I do holder.mCarousel.setModels(ArrayList<SecondaryModel_>). The reason I do it this way, is because the **main** model has other ui components. So I cant use the generated carousel model and pass the data from my controller. I am trying to implement something exactly like google play's movies section. Everything is displayed properly, but the state is not being saved.

If my use of models is wrong, could you tell me how to structure my models or point me to a similar example. My structure right now is one model for the main epoxy recycler view, one model (secondary model) for the carousel, and one controller. The controller creates 3 main models and passes an arraylist<SecondaryModel_> to the main model as an attribute. Thank you again.

**Comment by elihart** [comment]
I don't quite understand how you have your models and view set up. How are you using all viewholders for your models? Can you paste some psuedo code showing your structure?

**Comment by tzaitoun** [comment]
```
public class MovieController extends TypedEpoxyController<ArrayList<MovieListResult>> {

    @Override
    protected void buildModels(ArrayList<MovieListResult> data) {

        new MovieListsModel_().mCategoryTitle("Popular Movies")
                .id(0).mMovies(buildMovieList(0, data.get(0).getMovieList()))
       .
       .
    }
```

```
@EpoxyModelClass(layout = R.layout.viewholder_movie_lists)
public abstract class MovieListsModel extends EpoxyModelWithHolder<MovieListsModel.ViewHolder> {

    @EpoxyAttribute String mCategoryTitle;
    @EpoxyAttribute ArrayList<MovieCategoryListModel_> mMovies;

    @Override
    public void bind(@NonNull ViewHolder holder) {
        super.bind(holder);
        holder.mCategoryTitleTextView.setText(mCategoryTitle);
        holder.mMovieListCarousel.setModels(mMovies);
    }
```

The layout for this model is a cardview and inside it the title and carousel defined in xml.

The buildMovieList from the controller returns an array of MovieCategoryListModel_'s , where each one represents one movie object in a carousel.

```
@EpoxyModelClass(layout = R.layout.viewholder_movie_category_list)
public abstract class MovieCategoryListModel extends EpoxyModelWithHolder<MovieCategoryListModel.ViewHolder> {

    @EpoxyAttribute String mMoviePoster;
    @EpoxyAttribute String mMovieTitle;

    @Override
    public void bind(@NonNull ViewHolder holder) {
        super.bind(holder);
        Picasso.get().load(url + mMoviePoster).into(holder.mPosterImageView);
        holder.mTitleTextView.setText(mMovieTitle);
    }  
```

My fragment handles the creation of the controller and passing the movie data to it. Thanks again.

**Comment by elihart** [comment]
Your `MovieListsModel` should override `shouldSaveViewState` and return true. Are you using the `Carousel` view from the Epoxy library, or have you created your own? If you are using Epoxy's it should just work after the model has that setting.

Have you looked at the sample app? It has carousels that demonstrate state saving

**Comment by tzaitoun** [comment]
Alright, thank you. It's working now. I have looked at the sample app but I mainly used it to look at how the models are structured and to understand more clearly what the controller did. I'll go through it again and try to understand it better. Thanks again.

**Comment by elihart** [comment]
Great!

**Comment by zsweigart** [comment]
@elihart Hi eli, this example is great but it only shows how to do it with an activity.

I have a fragment using the navigation component and getting the epoxy data from a view model using live data.

When I navigate to another fragment `onSaveInstanceState` is not called. So when we return to the fragment the data is reloaded from the view model and the scroll position is reset.  Any ideas how to get around this?

**Comment by mgursch** [comment]
> @elihart Hi eli, this example is great but it only shows how to do it with an activity.
> 
> I have a fragment using the navigation component and getting the epoxy data from a view model using live data.
> 
> When I navigate to another fragment `onSaveInstanceState` is not called. So when we return to the fragment the data is reloaded from the view model and the scroll position is reset. Any ideas how to get around this?

+1 - i have the same problem

**Comment by malvinstn** [comment]
For a `Fragment`, since the lifecycle of the view and the fragment itself is different, you'd have to save the state of the controller when the fragment's view is destroyed instead of relying on the fragment's `onSaveInstanceState` callback.

**Comment by yurabuloichik** [comment]
Any examples or other working solutions? Thanks

**Comment by LetrixZ** [comment]
I solved this by saving the state to a `bundle` I defined in a view model, in `onResume()` and `onPause()`, but I had to make the `bundle` *nullable* and create it in `onPause()` otherwise it will throw `Tried to restore instance state, but onSaveInstanceState was never called.` Overriding `shouldSaveViewState` wasn't needed.
