### ISSUE TITLE
Databinding V2 Error

### ISSUE THREAD

**Issue by songzhw** [airbnb/epoxy#515]
I saw [one issue (https://github.com/airbnb/epoxy/issues/466) ](https://github.com/airbnb/epoxy/issues/466), that's suggests us to enable databinding v2. I did that, however, I still get the error : "epoxy cannot find DataBinderMapperImpl"

My Android Studio : v3.1.4
epoxy: v2.16.2
Using Kapt : true
kotlin version: v1.2.61

And once I comment out "android.databinding.enableV2=true", I can compile successfully.

**Comment by elihart** [comment]
The issue does _not_ suggest you use v2. It says v2 does not work.

Epoxy will use v2 once it is officially released as the default compiler.
