### ISSUE TITLE
Can i use EpoxyModel in kotin with kotlin extensions 

### ISSUE THREAD

**Issue by shakil807g** [airbnb/epoxy#516]

**Comment by shaishavgandhi05** [comment]
Yup! Check out the [Wiki](https://github.com/airbnb/epoxy/wiki). There's a section on the right that details the `Kotlin Support`.

**Comment by shaishavgandhi05** [comment]
What does your EpoxyModel setup look like? The kotlin synthetic extensions are available in ViewHolders as well. If you have an `EpoxyHolder` you should be able to access them in the `bindView` method.
```kotlin
class SampleViewHolder: EpoxyHolder() {
  override fun bindView(itemView: View) {
    itemView.myTextView.text = "Wohoo"
  }
}
```

**Comment by shakil807g** [comment]
ok thanks i will try it.

**Comment by elihart** [comment]
@shaishavgandhi05 thanks for helping out with answers!

@shakil807g see https://kotlinlang.org/docs/tutorials/android-plugin.html#view-caching

It looks like this use case would not be automatically cached, but you could possibly come up with a custom implementation of kotlin's `LayoutContainer` so they are cached
