### ISSUE TITLE
Kotlin model class without annotation process.

### ISSUE THREAD

**Issue by shakil807g** [airbnb/epoxy#525]
I don't like to add annotation processing to kotlin model class because same can be achieve with this code  but please add  android kotlin extension sample as well 

       data class SampleKotlinModel(
         val title: String,
         val imageUrl: Uri
         ) : KotlinModel(R.layout.view_holder_page_header) {

         var listener: ((text: String) -> Unit)? = null  // will be exclude form hashcode and equal code 

         val titleView by bind<TextView>(R.id.title)
         val imageView by bind<ImageView>(R.id.image)

         override fun bind() {
          titleView.text = title
          imageView.setImageURI(imageUrl)
       }
    }

does this code will be exclude form hash or equal code in kotlin ?? 

`var listener: ((text: String) -> Unit)? = null  // will be exclude form hashcode and equal code `

**Comment by elihart** [comment]
Yes the listener won't be included, kotlin only uses properties in the primary constructor for equals/hashcode/toString.

this means if you change the listener between null and non null though it won't be detected, which is dangerous.

**Comment by elihart** [comment]
more info https://github.com/airbnb/epoxy/wiki/Kotlin-Model-Examples#custom-kotlin-model
