### ISSUE TITLE
item from the list doesn't get updated at once

### ISSUE THREAD

**Issue by alouanemed** [airbnb/epoxy#531]
I have a list of items that belongs to a groupe. so I have 2 models : groupModel and groupItems.
Each groupItems has a Textview on which on clicked a dialog appears to give an input and then update the correspondant Item object from the list. After that I update the list with the new input and call requestModelBuild().

What I noticed is that the textview doesn't get get updated but it does when I scroll down and move back to that item.I don't do any netowrk call or database operation here.

From the activity I call `controller.updateElement(CartItem)`, on this method I update `groupItemsList` list inside the controller and call `requestModelBuild`
```
   groupItemsList.forEach {
      HeaderModel_()
          .id(it.id)
          .ItemGroup(it)
          .addTo(this)

      val cartItemGroup = it
      var position = 0
      it.cartItems.forEach {
        CartItemModel_()
            .id(it.id)
            .cartItem(it)
            .position(position)
            .cartItemGroup(cartItemGroup)
            .onActionOnItemClicked(onActionOnItemClicked)
            .addTo(this)
        position++
      }
    }
```

Can hashcode solve this ? and is itgoing to be for groupe or groupe items? or there is another solution for this ? Thanks.

**Comment by elihart** [comment]
yes it seems that you don't properly implement hashcode. does the item type for `groupItemsList` implement hashcode and equals correctly? how are your models implemented?

**Comment by alouanemed** [comment]
Yes, I added hashcode to my models, but the issue is the same.

**Comment by elihart** [comment]
did you add `equals` as well?

Have you set any breakpoints to trace this?
