### ISSUE TITLE
Unifying the carousel padding parameter orders ? 

### ISSUE THREAD

**Issue by martinbonnin** [airbnb/epoxy#535]
Typical parameter order in the android framework is `left, top, right, bottom`. This works for [View.setPadding](https://developer.android.com/reference/android/view/View.html#setPadding(int,%20int,%20int,%20int)), [Rect](https://developer.android.com/reference/android/graphics/Rect.html#Rect(int,%20int,%20int,%20int)), [Canvas](https://developer.android.com/reference/android/graphics/Canvas.html#drawRect(float,%20float,%20float,%20float,%20android.graphics.Paint)) and many others.

Would you be open to changing the order of [Carousel.Padding](https://github.com/airbnb/epoxy/blob/82d4161f9340d3fcb6e0ac4b6dd2f9fc502727e9/epoxy-adapter/src/main/java/com/airbnb/epoxy/Carousel.java#L396) which currently uses `top, bottom, left, right`?

That would make my brain a lot less confused. That being said, this will most likely break api-compatibilty at the same time so maybe it's too late ?

**Comment by shaishavgandhi05** [comment]
I think Epoxy will do a 3.0 with AndroidX. That might be a good opportunity to get this change in.

**Comment by martinbonnin** [comment]
Pull request done at https://github.com/airbnb/epoxy/pull/536/files if that can make it for 3.0.
There's a lot of copy/paste down there, hopefully I didn't forget to swap things...

**Comment by elihart** [comment]
Finally merged! will focus on 3.0.0 release next to include this. 

thanks again :)
