### ISSUE TITLE
How to efficiently change model padding,margin and other properties ?

### ISSUE THREAD

**Issue by shakil807g** [airbnb/epoxy#546]
I have model layout like this 

         <EditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPersonName"
            android:text="Name"
            android:ems="10"
            android:id="@+id/editText"/>

and here is a model class  which i want to use throughout my app but i want to have different margin or padding, textsize etc  in some place how it can be done ?

    @EpoxyModelClass(layout = R.layout.item_text_field)
    abstract class EditTextModel : EpoxyModelWithHolder<EditTextModel.EditTextHolder>() {

    @EpoxyAttribute
    var text: String? = null

    @EpoxyAttribute
    var errorText: String? = null

    @EpoxyAttribute
    var hint : String? = null

    @EpoxyAttribute
    @DrawableRes
    var prefIcon: String? = null

    @EpoxyAttribute(EpoxyAttribute.Option.DoNotHash)
    var textWachter: TextWatcher? = null

    override fun bind(holder: EditTextModel.EditTextHolder) {

        if(text.isNullOrEmpty())
            text = ""

        if(holder.editext.extSetText(text)){
            holder.editext.setSelection(holder.editext.length())
        }

        if(errorText.isNullOrEmpty()){
            holder.editext.error = null
        }
        else{
            holder.editext.error = errorText
        }

        holder.editext.addTextChangedListener(textWachter)

    }

    override fun unbind(holder: EditTextHolder) {
        super.unbind(holder)
        holder.editext.removeTextChangedListener(textWachter)
        holder.editext.error = null
    }

    inner class EditTextHolder : EpoxyHolder() {
        lateinit var editext : EditText

        override fun bindView(itemView: View) {
            editext = itemView!!.editText
         }

       }

      }

**Comment by shakil807g** [comment]
I just find out paris is there for same purpose or there is any other option ?

**Comment by elihart** [comment]
I would recommend Paris. otherwise you can use normal epoxy attributes and programmatically set the style changes on bind

**Comment by SamIAmHarris** [comment]
I used normal epoxy attributes for this, but am seeing the margins changing each time I scroll.  Sometimes they respect the margin I set, other times they don't set any margin.

```
    @ModelProp
    fun setTopMargin(int: Int) {
        val params = borderView.layoutParams as LayoutParams
        params.topMargin = int.convertDpToPx(resources).toInt()
    }

    @ModelProp
    fun setBottomMargin(int: Int) {
        val params = borderView.layoutParams as LayoutParams
        params.bottomMargin = int.convertDpToPx(resources).toInt()
    }
```
