### ISSUE TITLE
can't assign sharedPool after updating to support library 28.0.0

### ISSUE THREAD

**Issue by alouanemed** [airbnb/epoxy#547]
This is really not related to Epoxy, but I thought it will be helpfull to post my question here.

After updating the support library to v28 I got several issues and one them is can't assign a value to EpoxyRecyclerView viewPool because it's a `val`.

```
main__buyer_addresses_rv.apply {
      clipChildren = false
      setController(controller)
      setHasFixedSize(true)
      recycledViewPool = sharedViewPool // Val cannot be reassigned
}


```

**Comment by elihart** [comment]
That's very strange, it should still have a getter and setter, but possibly the syntax changed. We haven't updated yet, please let me know if you find the solution :)

**Comment by alouanemed** [comment]
Can be fixed by replacing this

`recycledViewPool = sharedViewPool `

With this :
`setRecycledViewPool(RecyclerView.RecycledViewPool())`
