### ISSUE TITLE
recyclerview scroll to the last models randomly 

### ISSUE THREAD

**Issue by alouanemed** [airbnb/epoxy#552]
There is this weird situation on which the view get scrolled down to the end of the screen. When models created for the first time it doesn't happen. but afterward, it occurs randomly in different activities.

Thoughts?

**Comment by elihart** [comment]
I would look at the debug output of the controller to see what type of model changes are happening. If rebuilding models results in items with changing ids then recyclerview might do weird animations.

Alternatively if a view is focusable it might be taking focus.

Epoxy on it's own never scrolls the view
