### ISSUE TITLE
about Carousel

### ISSUE THREAD

**Issue by leeyun** [airbnb/epoxy#554]
```
@ModelView(saveViewState = true, autoLayout = Size.MATCH_WIDTH_WRAP_HEIGHT)
class GridCarousel constructor(context: Context) : Carousel(context) {


  private val SPAN_COUNT = 3
  override fun createLayoutManager(): LayoutManager {
    return GridLayoutManager(context, SPAN_COUNT, GridLayoutManager.VERTICAL, false)
  }
}
```

 ```
gridCarousel {
      id("grid")
//      numViewsToShowOnScreen(3f)
      val mult = mutableListOf<String>()
      mult.add("1")
      mult.add("2")
      mult.add("3")
      mult.add("4")
      mult.add("5")
      withModelsFrom(mult) {
        GridItemViewRowModel_().id(("grid_$it"))
            .title("item_$it")
      }
    }
```
<img width="476" alt="wx20180928-163226 2x" src="https://user-images.githubusercontent.com/11530379/46197447-7e58c100-c33c-11e8-9b26-2a93e20f6ca0.png">
i think it's grid but...,the height of Carousel is not set?

**Comment by elihart** [comment]
`the height of Carousel is not set` what do you mean? also for a vertical scrolling view `Size.MATCH_WIDTH_WRAP_HEIGHT` might not be what you want, usually you would match height

**Comment by leeyun** [comment]
I hope to achieve a nine-square effect. GridLayoutManager does not seem to produce results,Carousel not be used like   @elihart
