### ISSUE TITLE
Does PagedListEpoxyController requires having andoird arch components ?

### ISSUE THREAD

**Issue by alouanemed** [airbnb/epoxy#556]
Hello, I am trying to use PagedListEpoxyController, I got stuck at the use of PagedList. On my app I am using RxJava not LiveData. 

Is there any alternative without using android arch? Thanks.

**Comment by elihart** [comment]
It only works with PagedList. I believe you can create your own datasource for a paged list to make it work with Rx though, maybe something like https://medium.com/@Ahmed.AbdElmeged/android-paging-library-with-rxjava-and-rest-api-e5c229fd70ba

or there might be existing libraries for this

**Comment by alouanemed** [comment]
I see. Thank you!
