### ISSUE TITLE
Proguard warning EpoxyAsyncUtil

### ISSUE THREAD

**Issue by eloisance** [airbnb/epoxy#557]
Hello,

I have this warning with proguard :

**Warning: com.airbnb.epoxy.EpoxyAsyncUtil: can't find referenced method 'android.os.Handler createAsync(android.os.Looper)' in library class android.os.Handler**

Should I add dontwarn ? or I should not have this warning ?

`-dontwarn com.airbnb.epoxy.EpoxyAsyncUtil`

epoxy version : 2.17.0

**Comment by elihart** [comment]
I believe this warning is safe to ignore. The `createAsync` code is taken straight from the android support library - the method might not be found by proguard, but it should be present in the OS at runtime

**Comment by eloisance** [comment]
Ok thanks, I close this issue.
