### ISSUE TITLE
iOS/Swift version

### ISSUE THREAD

**Issue by MatushkaRossiya** [airbnb/epoxy#562]
Hi,

First of all, thank you for sharing this awesome library with the community! As far as I understand, at Airbnb you have also developed a version of Epoxy for iOS based on Swift. Is there any chance it will be open sourced as well?

**Comment by elihart** [comment]
afaik there are no plans to open source the iOS version. I don't work on it, but I'll ask around to those that do and get back to you

**Comment by lauraskelton** [comment]
We are working on open sourcing the version of Epoxy for iOS we've been using inside Airbnb which is in Swift! The plan is to get it out before the end of the year.

**Comment by MatushkaRossiya** [comment]
@lauraskelton Thank you for the info, much appreciated! And @elihart thanks for asking around!

**Comment by viezel** [comment]
Thats great new @lauraskelton. Our team uses the deprecated HUB Framework and are looking for an replacement for both iOS and Android.

**Comment by jonasbark** [comment]
Any news yet? 🙂

**Comment by etlasky** [comment]
Bump

**Comment by wanjijul** [comment]
Bump

**Comment by elihart** [comment]
There's no news on this

**Comment by Dimillian** [comment]
Still no news ?

**Comment by jonasbark** [comment]
It seems that a public release isn't on the horizon yet. 
Our company is working on an equivalent solution for Swift that includes parts of Epoxy (using LayoutKit as as 'rendering engine') and MvRx. Syntax will be pretty similar and it's already fun to work with. We expect to be able to release it within a few weeks.

**Comment by elihart** [comment]
Our internal work to open source the iOS version is delayed, but still planned.

News will be posted when available

**Comment by hooliooo** [comment]
Check out FFUF's Cyanic framework which is based on Epoxy and MvRx. (Our Android devs use MvRx)
https://github.com/feilfeilundfeil/Cyanic

**Comment by eygraber** [comment]
Any chance that this is gonna be Kotlin MPP capable?

**Comment by elihart** [comment]
No plans for MPP

**Comment by gajicm93** [comment]
Just a bump, how is this going? Thanks.

**Comment by elihart** [comment]
There isn't progress on this, and with Swift UI and Jetpack Compose on the horizon I don't think it makes sense to pursue this.

**Comment by PedroAlvarado** [comment]
Excuse my ignorance, what is the relationship between Jetpack Compose and Epoxy(Java) that doesn't make sense?

**Comment by elihart** [comment]
Jetpack Compose is a complete View framework overhaul that will replace Epoxy.

**Comment by gajicm93** [comment]
As far as I've seen, Jetpack Compose doesn't offer composing recyclable list screens via RecycleView, which is the main purpose of Epoxy, only static layouts?

**Comment by elihart** [comment]
This is not true - compose also produces scrollable, recyclable lists, and will replace RecyclerView as well.

**Comment by sajeel** [comment]
Bump

**Comment by AndreiApostoiu** [comment]
Bump2

**Comment by KiranShny** [comment]
Bump3

**Comment by thedrick** [comment]
You can find the Swift / iOS version of Epoxy here! https://github.com/airbnb/epoxy-ios

**Comment by viezel** [comment]
Wow, it actually happened 🥳
