### ISSUE TITLE
[Question]How to use PagedListEpoxyController and insert views to specific position

### ISSUE THREAD

**Issue by dokiKit** [airbnb/epoxy#563]
What I would like to achieve is, insert a view between items. (Like a typical messaging app, that only shows sender's name on top of the first message of the consecutive messages sent). I realize the addModels() method that allows me to do that, but my solution to this is quite not elegant. Is there a more sensible way to achieve this? Since if you are using Typed2EpoxyController, you can pretty much build the list DSL with buildModels().  Thanks.

Below is my implementation.

```
private fun MutableListIterator<EpoxyModel<*>>.insertSenderModel(currentMessageModel: DBMessageWrapper){

        val senderModel =
                MessageSenderEpoxyViewModel_()
                .id("sender${currentMessageModel.localId}")
                .senderName(currentMessageModel.result.from)
        if (this.hasPrevious()){
            previous()
        }
        add(senderModel)
        if (this.hasNext()){
            next()
        }
    }

    
    override fun addModels(models: List<EpoxyModel<*>>) {

        val copy = models.toMutableList()
        val iterator = copy.listIterator()
        val currentModel = (models[0] as MessageEpoxyViewModel_).dbMessageWrapper()

        // keep track of current sender
        var currentSender = currentModel.result.from
        iterator.insertSenderModel(currentModel)

        for (item in iterator){
            if (item is MessageEpoxyViewModel_){
                val currentMessageModel = item.dbMessageWrapper()
                if (currentSender != currentMessageModel.result.from){
                    iterator.insertSenderModel(currentMessageModel)

                    // update current sender
                    currentSender = currentMessageModel.result.from
                }
            }
        }

        super.addModels(copy)
    }
```

**Comment by elihart** [comment]
what would your ideal dsl look like? you can still use the same type of dsl as with a normal controller, you are just iterating through a list of models instead of iterating through your original data type

**Comment by dokiKit** [comment]
I would just like to have addTo(this) method with a specific index. Not necessarily dsl, but currently addTo(this) only allows you to add to the end of the model list right?
