### ISSUE TITLE
[Kotlin] Sample code not working

### ISSUE THREAD

**Issue by mastrgamr** [airbnb/epoxy#569]
I'm trying to use the library for a kotlin project I'm working on and I'm not able to have my models appear on the screen. I'm implementing the `EpoxyRecyclerView` within a fragment in a `NestedScrollView`.

Using version:
```
implementation 'com.airbnb.android:epoxy:2.18.0'
kapt 'com.airbnb.android:epoxy-processor:2.18.0'
```

In my fragment `onCreateView()` I have:
```
var recView: EpoxyRecyclerView = v.findViewById(R.id.player_recview)

        recView.withModels {
            Log.d(TAG, "onCreateView#withModels")
            for (i in 0 until 5) {
                APlayerItem_().apply {
                    id("id=$1")
                    name("Hello Item! $i")
                }
            }
        }
```

My `APlayerItem` is a very simple item with one TextView in it:
```
@EpoxyModelClass(layout = R.layout.browse_item)
abstract class APlayerItem : EpoxyModelWithHolder<APlayerItem.Holder>() {
    @EpoxyAttribute lateinit var name: String

    override fun bind(holder: APlayerItem.Holder) {
        holder.nameView?.text = name
    }

    class Holder : KotlinEpoxyHolder() {
        var nameView: TextView? = null
        override fun bindView(itemView: View) {
           nameView  = itemView.findViewById(R.id.item_title) as TextView
        }
    }
}
```

When I run my project there's literally nothing populated in the fragment (even showing layoutbounds shows nothing). Debug logs show that onCreateView is actually being called and the loop is indeed running, so why is nothing displayed?

Another thing:
I also tried using the `data class` route. With the data class option the views populate in the Recyclerview but I can't use models of different types. It just stretches the first model to what the entire length of the list would be, with no other items visible. It's just one item thats very long.

**Comment by elihart** [comment]
you're not adding your model to the recyclerview
```
APlayerItem_().apply
```

just instantiates it and drops it, you have to add it to the controller

the generated function `aPlayerItem` does that all for you, or you can call `add` or `addTo` manually

**Comment by mastrgamr** [comment]
Adding `addTo()` worked. I used it for the data class implementation, don't know why I didn't think to do it here smh.

I still have the issue of adding Models of different types to the RecyclerView (not sure if I should open another issue for it). For example: if I wanted to add `APlayerItem_()` and `APlayerItem2_()` to the same `EpoxyRecyclerView`
