### ISSUE TITLE
[Question] Avoid redrawing entire carousel but update specific views?

### ISSUE THREAD

**Issue by AdamMc331** [airbnb/epoxy#570]
Overall context: I have a `PagedListEpoxyController` which displays a carousel of filters at the top, and shows the paged list below it.

I attach a listener to my filter models, so that when one is clicked, I set a `selectedFilterId` on the controller and request a model build. This does work, but the UX isn't great. It appears when it redraws each item in the carousel, it changes the padding on the ones that are selected/deselected. Gif below. 

I've been fighting this for a little bit and tinkered with a few ideas, but I'm not sure the best approach. Do you have any suggestions?

Here is some code if that helps:

```kotlin
override fun addModels(models: List<EpoxyModel<*>>) {
    buildFilterCarousel()
    super.addModels(models)
}

// Passed in through databinding, called when a filter is "clicked"
private val filterConsumer: Consumer<Filter?> = Consumer {
    // Setting this field triggers a callback which pulls for the paged list, and when that happens we request a model build.
    selectedFilterId = it?.filterId
}

private fun buildFilterCarousel() {
    val filterModels: List<FilterEpoxyModel> = filters?.map { filter ->
        // ... Get filter ID and selected status

        return@map FilterEpoxyModel()
                // I had to include "selected" as part of the model ID in order for it to actually update when I call `requestModelBuild`.
                .id("Filter: $filterId, selected: $selected")
                .viewModel(viewModel)
                .filterConsumer(filterConsumer)
    }.orEmpty()

    CarouselModel_()
            .numViewsToShowOnScreen(3.0f)
            .hasFixedSize(true)
            .paddingDp(16)
            .id("Filter Carousel")
            .models(filterModels)
            .addTo(this)
}
```

![carouselbug](https://user-images.githubusercontent.com/9515997/46745976-111e2780-cc7c-11e8-895c-02be5c601a9d.gif)

**Comment by AdamMc331** [comment]
but without using that, changing the selected id and calling `requestModelBuild` seems to do nothing. I figured it was because, since the model id didn't change, the lib saw no reason to "redraw" the item. 

I even tried caching the filter viewmodels inside the controller, but that didn't work. The selected field on the viewmodel is referenced via databinding to determine the background color.

**Comment by AdamMc331** [comment]
The animation as a result of item being added/removed makes a lot of sense. I guess the question becomes: Is there a way to update each item without adding/removing them? 🤔

**Comment by shaishavgandhi05** [comment]
I think there is. I faced something similar. What you want to do is keep your checked status as an `@EpoxyAttribute` in your model. Then, you want to override the `bind(holder: YourHolder, previousBoundModel: EpoxyModel<*>)` method in your model and check your `checked` status and make the necessary changes. Something like this:
```kotlin
@EpoxyModelClass abstract class MyModel: EpoxyModelWithHolder<MyHolder> {
  @EpoxyAttribute var checkedStatus: Boolean = false
  
  override bind(holder: MyHolder, previousBoundModel: EpoxyModel<*>) {
    holder.item.bgColor = if (checkedStatus) Color.BLUE else Color.WHITE
  }
}
```

**Comment by AdamMc331** [comment]
That sounds promising, I'll try it out. My models are all generated via databinding, but it looks like I can manually handle this case? https://github.com/airbnb/epoxy/wiki/Data-Binding-Support#custom-data-binding-models

**Comment by shaishavgandhi05** [comment]
I'm not sure about the databinding part as I haven't used it. Maybe Eli will have insight into that!

**Comment by AdamMc331** [comment]
Gotcha. Going into a meeting so I won't be able to respond - but at least I have ideas and am no longer blocked on this so I'll give an update in a little while!

**Comment by elihart** [comment]
the generated databinding class is much smarter about only rebinding the data that changed, your new manual version always rebinds everything

i would guess that your `viewModel(viewModel)` attribute you are passing does not properly implement equals and hashcode to represent that the selected state changed, so epoxy doesn't think it needs to rebind it

the general advice is this - id should not change, any data that can change on the model must be represented by attributes that correctly implement equals and hashcode. Epoxy will rebind only the data that changed when models are rebuilt

**Comment by AdamMc331** [comment]
My viewmodel was not overriding equals, that was a great guess. That fixes it for me. Thanks so much Eli!

I would love to help document that difference somewhere. I think it would go well on [this page](https://github.com/airbnb/epoxy/wiki/Data-Binding-Support) but the wiki isn't open to public contributors. Is there any way I can help?

**Comment by elihart** [comment]
glad that works. you're right we could make this more clear

I thought https://github.com/airbnb/epoxy/wiki/Epoxy-Models#model-properties covered this, but looking at it now I could make it more explicit. I'll also mention it in the databinding page

I'm not sure how to allow public wiki editing, but thanks for the idea and offer!

**Comment by AdamMc331** [comment]
Of course. Thanks for the great library, and the always timely responses!

**Comment by elihart** [comment]
I'll keep this open as a reminder to myself to update the wiki

**Comment by elihart** [comment]
I've updated the wiki pages a bit for clarity :)
