### ISSUE TITLE
Android Gradle Plugin v3.2.0

### ISSUE THREAD

**Issue by iMvBremen** [airbnb/epoxy#576]
The latest [Android Gradle Plugin](https://developer.android.com/studio/releases/gradle-plugin#3-2-0) now has the [Data Binding Compiler V2](https://developer.android.com/topic/libraries/data-binding/start#preview-compiler) enabled by default (see the _Note_ on the data binding page).

Updating to the latest version would 'fix' #466 

Maybe something for the Epoxy 3.0 release?

**Comment by elihart** [comment]
That sounds about right - we are already planning this for the 3.0 release which should happen soon. There is an RC available if you're interested now

**Comment by jeffreydelooff** [comment]
I have updated the gradle plugin to 3.2.1 in the androidx migration branch.
