### ISSUE TITLE
When I know that Epoxy rows are created

### ISSUE THREAD

**Issue by qbait** [airbnb/epoxy#578]
I'm using `MvRx` and I'm defining my `Carousel`

```
    override fun epoxyController() = simpleController(viewModel) { state ->

        val list = listOf("A", "B", "C", "D", "E")

        carousel {
            id("carousel")
            numViewsToShowOnScreen(1f)
            withModelsFrom(list) {
                MarqueeModel_()
                        .id(it)
                        .title(it)
            }
        }
     }
```

I want to perform an action on this `Carousel` after creating it so I added it in `OnViewCreated`. However, at this point my `recyclerView.childCount` is 0. I added ugly delay by now.

```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        Handler().postDelayed({
            if (recyclerView.childCount > 0) {
                val carousel = recyclerView.asSequence().filterIsInstance(Carousel::class.java).first()
                // do sth with carousel
            }
        }, 200)
    }
```

Is there a better solution to this problem?

**Comment by elihart** [comment]
this isn't really related to epoxy or mvrx.

For Recyclerview in general you could use `addOnLayoutChangeListener` and `addOnChildAttachStateChangeListener`

with epoxy you can use `EpoxyController#addModelBuildListener` but that will be after recyclerview is notified of changes and before it is laid out, so you would have to wait for it to lay itself out

**Comment by qbait** [comment]
Thanks again @elihart

**Comment by HsuHsiaoHsuan** [comment]
I use IdleHandler to fix my problem :)

```kotlin
Looper.myQueue().addIdleHandler {
    // do something
    false
}
```
