### ISSUE TITLE
Epoxy and SharedElementTransitions

### ISSUE THREAD

**Issue by johnnycube** [airbnb/epoxy#579]
Hi,

I'm currently trying to solve the problem of SharedElementTransitions with Epoxy Databinding.

I tryed doing this using the layout tag `transistionName`, I tried using the `ViewCompat `library module using `ViewCompat.setTransitionName`, and currently am out of ideas. 

Implementing transitions from activity to activity, activity to fragment, or fragment to fragment worked flawlessly using these methods without Epoxy.

As I currently have no clue how to implement them I wanted to ask if there is a standard way of doing this. I am also willing to convert my databinding layouts to custom views - if this is easier.

I don't need an in-depth tutorial - a sample project or some hints would be awesome. Thank you very much!

**Comment by elihart** [comment]
Epoxy doesn't really factor into this, what you should look at is how to do shared element transitions from views inside a RecyclerView.

From my experience it just works, as long as you set the transition name on the item view properly. With epoxy we pass transition name as an EpoxyModel prop (for databinding that could be a data variable)
