### ISSUE TITLE
Updating every time even when list is same

### ISSUE THREAD

**Issue by monikasaini856** [airbnb/epoxy#581]
I had implemented epoxy for our home screen but there is issue with diffing. Even when same list is provided it is building whole view again.
I had checked generated model class and everytime their equals class is returning true, still there is diff and it's rebuilding again. On scrolling also, it is building again.

**our data structure**
data class LayoutFeedItem<T>(var data: T?, var layout: Layout)

**Controller class** 

class HomeEpoxyController : TypedEpoxyController<List<LayoutFeedItem<*>>>() {
    init {
        isDebugLoggingEnabled = true
    }

    override fun buildModels(layourFeedList: List<LayoutFeedItem<*>>?) {
        layourFeedList?.let {
            for (layoutFeedItem in it) {
                when (layoutFeedItem.layout.railType) {
                    RailType.GRID_1_2, RailType.GRID_2_2, RailType.GRID_MOODS_2_2, RailType.GRID_VIDEO_2_2 -> {
                        add(GridModelGroup(layoutFeedItem))

                    }
                    RailType.RAIL_SQUARE, RailType.RAIL_POPULAR, RailType.RAIL_VIDEO -> {
                        add(RailModelGroup(layoutFeedItem))

                    }
                    RailType.FEATURED -> {
                        add(
                            FeaturedModelGroup(layoutFeedItem)
                        )

                    }

                    RailType.MY_MUSIC -> {
                        add(MyMusicModelGroup(layoutFeedItem))

                    }
                    RailType.HERO -> {
                        add(
                            ItemHeroEpoxyHolder_().id(layoutFeedItem.layout.id).layoutFeedItem(
                                layoutFeedItem
                            )
                        )
                    }

                    RailType.MESSAGE_CARD -> {

                    }
                }
            }
        }
    }
}

**Model group class -**
class GridModelGroup<T>(layoutFeedItem: LayoutFeedItem<T>) :
    EpoxyModelGroup(R.layout.layout_grid_model_group, GridModelGroup.buildModels(layoutFeedItem)) {

    init {
        id(layoutFeedItem.layout.id)
    }

    companion object {
        fun buildModels(
            layoutFeedItem: LayoutFeedItem<*>

        ): List<EpoxyModel<*>> {
            var item: Item? = null
            layoutFeedItem.data?.let {
                item = it as Item
            }

            val models = mutableListOf<EpoxyModel<*>>()

            when (layoutFeedItem.layout.railType) {

                RailType.GRID_1_2 -> {
                    models.add(
                        HeaderModel_().id(layoutFeedItem.layout.id).listener { _, _, _, position ->

                        }.layout(
                            layoutFeedItem.layout
                        )
                    )
                    val itemGridList = mutableListOf<ItemGridPlaylistEpoxyHolder>()
                    var tempList: List<Item>? = null
                    item?.let {
                        tempList = it.items
                    }
                    tempList?.let {
                        for (item in it.subList(0, 2)) {
                            itemGridList.add(
                                ItemGridPlaylistEpoxyHolder_().id(layoutFeedItem.layout.id + item.id
                                ).listener { _, _, _, position ->

                                }.data(
                                    item
                                )
                            )
                        }
                    } ?: run {
                        for (i in 1..2) {
                            itemGridList.add(
                                ItemGridPlaylistEpoxyHolder_().id(layoutFeedItem.layout.id + item?.id
                                ).data(null)
                            )
                        }
                    }
                    models.add(GridCarouselVerticalModel_().id(layoutFeedItem.layout.id + "_" +item?.id).models(itemGridList))
                }
                RailType.GRID_2_2 -> {
                    models.add(HeaderModel_().id(layoutFeedItem.layout.id).listener { _, _, _, position ->

                    }.layout(layoutFeedItem.layout))
                    val itemGridList = mutableListOf<ItemGridPlaylistEpoxyHolder>()
                    var tempList: List<Item>? = null
                    item?.let {
                        tempList = it.items
                    }
                    tempList?.let {
                        for (item in it.subList(0, 4)) {
                            itemGridList.add(
                                ItemGridPlaylistEpoxyHolder_().id(
                                    layoutFeedItem.layout.id + item.id
                                ).listener { _, _, _, position ->
                                }.data(
                                    item
                                )
                            )

                        }
                    } ?: run {
                        for (i in 1..4) {
                            itemGridList.add(
                                ItemGridPlaylistEpoxyHolder_().id(
                                    layoutFeedItem.layout.id + item?.id
                                ).data(null)
                            )
                        }
                    }
                    models.add(GridCarouselVerticalModel_().id(layoutFeedItem.layout.id + "_" +item?.id).models(itemGridList))
                }
                RailType.GRID_MOODS_2_2 -> {
                    models.add(HeaderModel_().id(layoutFeedItem.layout.id).listener { _, _, _, position ->

                    }.layout(layoutFeedItem.layout))
                    val itemGridList = mutableListOf<ItemSquareLargeEpoxyHolder>()
                    var tempList: List<Item>? = null
                    item?.let {
                        tempList = it.items
                    }
                    tempList?.let {
                        for (item in it.subList(0, 4)) {
                            itemGridList.add(
                                ItemSquareLargeEpoxyHolder_().id(
                                    layoutFeedItem.layout.id + item.id
                                ).listener { _, _, _, position ->

                                }.data(
                                    item
                                )
                            )

                        }
                    } ?: run {
                        for (i in 1..4) {
                            itemGridList.add(
                                ItemSquareLargeEpoxyHolder_().id(
                                    layoutFeedItem.layout.id + item?.id
                                ).data(null)
                            )
                        }
                    }
                    models.add(GridCarouselVerticalModel_().id(layoutFeedItem.layout.id + "_" +item?.id).models(itemGridList))
                }
                RailType.GRID_VIDEO_2_2 -> {
                    models.add(HeaderModel_().id(layoutFeedItem.layout.id).listener { _, _, _, position ->

                    }.layout(layoutFeedItem.layout))
                    val itemGridList = mutableListOf<ItemGridVideoEpoxyHolder>()
                    var tempList: List<Item>? = null
                    item?.let {
                        tempList = it.items
                    }
                    tempList?.let {
                        for (item in it.subList(0, 4)) {
                            itemGridList.add(
                                ItemGridVideoEpoxyHolder_().id(
                                    layoutFeedItem.layout.id + item.id
                                ).listener { _, _, _, position ->

                                }.data(item)
                            )
                        }
                    } ?: kotlin.run {
                        for (i in 1..4) {
                            itemGridList.add(
                                ItemGridVideoEpoxyHolder_().id(
                                    layoutFeedItem.layout.id + item?.id
                                ).data(null)
                            )
                        }
                    }
                    models.add(GridCarouselVerticalModel_().id(layoutFeedItem.layout.id + "_" +item?.id).models(itemGridList))
                }
            }
            return models
        }
    }

}

**Holder class -**
@EpoxyModelClass(layout = R.layout.item_grid_playlist)
abstract class ItemGridPlaylistEpoxyHolder : EpoxyModelWithHolder<ItemGridPlaylistHolder>() {

    @EpoxyAttribute(EpoxyAttribute.Option.DoNotHash)
    lateinit var listener: View.OnClickListener
    @EpoxyAttribute
    var data: Item? = null

    override fun bind(holder: ItemGridPlaylistHolder) {
        holder.apply {
            data?.let {
                if (it.title.isNullOrEmpty()) {
                    title.makeGone()
                } else {
                    title.text = it.title
                    title.makeVisible()
                }
                if (it.subtitle.isNullOrEmpty()) {
                    subtitle.makeGone()
                } else {
                    subtitle.text = it.subtitle
                    subtitle.makeVisible()
                }
                parentView.setOnClickListener(listener)
                playIcon.makeVisible()
                action.makeVisible()
                action.setImageDrawable(
                    ContextCompat.getDrawable(
                        image.context,
                        R.drawable.ic_download
                    )
                )
                image.setPlaceHolder(R.drawable.img_placeholder_song_168_x_168)
                    .setErrorImage(R.drawable.img_placeholder_song_168_x_168)
                    .load(it.smallImage)
            } ?: image.setPlaceHolder(R.drawable.img_placeholder_song_168_x_168)

        }
    }
}

class ItemGridPlaylistHolder : KotlinEpoxyHolder() {
    val image by bind<WynkImageView>(R.id.iv_item_image)
    val playIcon by bind<WynkImageView>(R.id.iv_play)
    val title by bind<WynkTextView>(R.id.tv_item_title)
    val subtitle by bind<WynkTextView>(R.id.tv_item_subtitle)
    val action by bind<WynkImageView>(R.id.iv_action)
    val parentView by bind<View>(R.id.parent_view)
}

**Comment by elihart** [comment]
what is the output of the diff? what does it think changed? have you done any debugging to figure out what is wrong with your setup?

**Comment by elihart** [comment]
you must have some code that is requesting a model build repeatedly, and you must have an item at that position who's hashcode/equals is not stable

**Comment by monikasaini856** [comment]
how to debug if it is not stable. Can you please check code and see if anything is wrong the way I have implemented. Because I am not able to figure out exactly what is wrong.

**Comment by elihart** [comment]
@monikasaini856 if you have solved this, please leave the issue here for others to learn from
