### ISSUE TITLE
PagedListEpoxyController auto-scrolls 

### ISSUE THREAD

**Issue by ganfra** [airbnb/epoxy#587]
Hi, I'm using the PagedListEpoxyController to integrate with the paging libraries.
As I call `submitList(myPagedList)` the items are autoscrolling... it means the latest are always showing up. I'm not using placeholders. 
When using a PagedListAdapter it's all ok...

(My app is a chat application, so I back paginate to get old messages by scrolling up)

Any idea on this ?

**Comment by alouanemed** [comment]
I had the same issue #552 with the EpoxyController.  I searched for any focus or anything that make it scroll to the center on my view but no luck. A fix I am using at the moment : 
```
main__product_internel__rv.apply {
      scrollBy(0, 0)
}

**Comment by ganfra** [comment]
Ok, thanks for your help...
I use epoxy on other screens without trouble, it's really the integration with Paging where things are getting weird.

**Comment by elihart** [comment]
are you using `linearLayoutManager.setReverseLayout(true);`?

epoxy doesn't scroll the recyclerview for you - it will only insert new items as they are loaded, so any auto scrolling is a result of your code's interaction with recyclerview and Epoxy probably isn't related

**Comment by ganfra** [comment]
Yes I'm using reverseLayout(true). But the exact same code is ok with an adapter.

**Comment by ganfra** [comment]
So, do you have any idea about making it works with reverseLayout and stackFromEnd?  :)

**Comment by ganfra** [comment]
Seems like I got some removal that shouldn't happen:
Item range removed. Start: 30 Count: 210

The PagedList newly submitted is smaller than the previous one, but it shouldn't...
Don't figure it out why it's working with the adapter by the way

**Comment by ganfra** [comment]
So, the issue is not coming from epoxy, I close the issue.
Thanks for your time!

**Comment by kakai248** [comment]
@ganfra Are you observing Room and your PagedList doesn't have placeholders? I'm having a similar problem. When the database changes, the PagedList restarts and only loads the current page. This means that epoxy will delete everything up to the current page.

I opened an issue about this: https://issuetracker.google.com/issues/119582511
