### ISSUE TITLE
can't import PagedListEpoxyController

### ISSUE THREAD

**Issue by kim24** [airbnb/epoxy#594]
I added : 
    `implementation 'com.airbnb.android:epoxy-paging:3.0.0-rc1'`
in gradle file and even androidx dependency of paging library but I can't import PagedListEpoxyController why? also is there a variant of this class like PagedTypedListEpoxyController?!
Thanks

**Comment by elihart** [comment]
PagedListEpoxyController is not in the 3.0 rc, it will be in the final 3.0 release. you can use 2.19.0 instead
