### ISSUE TITLE
Using Page Indicator for Carousel with custom carousel?

### ISSUE THREAD

**Issue by alouanemed** [airbnb/epoxy#602]
Per #571, in order to use the page indicator, the carousel should be extended and add it as an item decoration. 

- Is this the correct way doing so?
`public class ScrolledCarouselModel : EpoxyModel<Carousel>() { ...}`

- What method on which the page indicator should be added? `init()`?

- How to reference the epoxy recycleview in the extended class?

Thanks.
https://github.com/TinkoffCreditSystems/ScrollingPagerIndicator

**Comment by jonasbark** [comment]
For anyone stumbling over this, here's a simple implementation of a subclass that adds the ItemDecoration:

```kotlin
class CarouselIndicatorModel : CarouselModel_() {

    val indicator = CirclePagerIndicatorDecoration()

    override fun bind(carousel: Carousel) {
        super.bind(carousel)

        carousel.addItemDecoration(indicator)
    }

    override fun unbind(carousel: Carousel) {
        super.unbind(carousel)

        carousel.removeItemDecoration(indicator)
    }
}
```

**Comment by alouanemed** [comment]
Thank you @jonasbark !
