### ISSUE TITLE
Question: Subclassing auto generated data binding models

### ISSUE THREAD

**Issue by jonasbark** [airbnb/epoxy#603]
Hi!

The auto generated data binding models fit our needs perfectly by stripping all the needed boilerplate. However, if we need to access binded views programmatically (to keep logic out of the XML) I can't seem to find an easy way to do this.

My idea was to subclass the generated model, e.g. like this:
```
@EpoxyModelClass(layout = R.layout.list_item_bindable_title)
abstract class CustomTitleBinding : TitleBindingModel_() {

    override fun setDataBindingVariables(binding: ViewDataBinding?, previousModel: EpoxyModel<*>?) {
        super.setDataBindingVariables(binding, previousModel)
        if (binding is ListItemBindableTitleBinding) {
            //access views directly, e.g. load image from Picasso
        }
    }
}
```

but it (rightfully?) throws several errors in the kapt step, e.g.
```error: name clash: onBind(OnModelBoundListener<TitleBindingModel_,DataBindingHolder>) and onBind(OnModelBoundListener<CustomTitleBinding_,DataBindingHolder>) have the same erasure```

Is there an easy way to do this when you still want to rely on the generated models?

**Comment by jonasbark** [comment]
Thanks for that quick answer and you're right - simply subclassing from `TitleBindingModel_` did the trick. That was the last piece of the puzzle. Epoxy is great!

For anyone else stumbling over this post:

    ```
class CustomTitleBindingModel : TitleBindingModel_() {

        override fun setDataBindingVariables(binding: ViewDataBinding?) {
            super.setDataBindingVariables(binding)
            if (binding is ListItemBindableTitleBinding) {
                //access views directly, e.g. load image from Picasso
            }
        }
    }
```

**Comment by elihart** [comment]
Great :)

btw, `ViewDataBinding` in `setDataBindingVariables` is not actually nullable, so you could remove the `?`. we should add @NonNull to the epoxy code ideally
