### ISSUE TITLE
No Longer Failing on Duplicate IDs

### ISSUE THREAD

**Issue by wkranich** [airbnb/epoxy#609]
Hi there,

I noticed that since the Async Diffing changes epoxy no longer throws an exception when two models with duplicate IDs are added to an `EpoxyController`. Is this intentional?

Cheers

**Comment by elihart** [comment]
Yes, this is because the support library DiffUtil does not fail on duplicate ids.

Check out the wiki https://github.com/airbnb/epoxy/wiki/Epoxy-Controller#filtering-duplicates
