### ISSUE TITLE
Consecutive hidden models in a grid layout manager breaks

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#61]
Once you scroll past the hidden models you can't scroll back up. Hidden models have a span size of 0, which normally seems to work fine, but I found that for a total span count of 2, where two consecutive models are hidden, the recyclerview just breaks and won't scroll up past the hidden models.

**Comment by kevinthecity** [comment]
I've actually solved this (iirc, it's been a while) by having the hidden model always return a span size of whatever the span count is.

```
  @Override public int getSpanSize(int spanCount, int position, int itemCount) {
    return spanCount;
  }
```

**Comment by elihart** [comment]
Dup of https://github.com/airbnb/epoxy/issues/74
