### ISSUE TITLE
Ability to pre-build and cache models before the data is set on the controller

### ISSUE THREAD

**Issue by AndyGOBrien** [airbnb/epoxy#611]
I have having some performance with setting new datasets. wondering if this is possible or if it is a feature that can be added?

**Comment by elihart** [comment]
are you using the feature to build and diff models in a background thread?

The epoxy controller just takes a list of models, if you want to build them somewhere else and cache them you are free to do that, and just add those to the epoxy controller when build models is called.

**Comment by AndyGOBrien** [comment]
Yeah duh sorry, derp moment. That's what I ended up doing. Much better
performance now thanks!
