### ISSUE TITLE
@AutoModel is not properly generating IDs when used in PagedListEpoxyController

### ISSUE THREAD

**Issue by joshfriend** [airbnb/epoxy#622]
I'm using `PagedListEpoxyController` and since updating to 3.0, using `@AutoModel` is not assigning IDs properly and my app is crashing with the exception `This model was already added to the controller at position 102` when trying to add more placeholders to the model list. The `PagedList.Config` has `setEnablePlaceholders(true)`. Here's how I have set up the `buildItemModel` method of the controller:

```kotlin
@AutoModel lateinit var placeholder: PlaceholderModel_

override fun buildItemModel(currentPosition: Int, item: Load?): EpoxyModel<*> {
  return when (item) {
    null -> placeholder
    else -> ItemModel_().apply { 
      id(item.id)
      data(item)
    }
  }
}
```

I was able to fix the crash by not using `@AutoModel` and manually assigning the IDs to the placeholders:

```kotlin
override fun buildItemModel(currentPosition: Int, item: Load?): EpoxyModel<*> {
  return when (item) {
    null -> PlaceholderModel_().apply { 
      id(-1 * currentPosition)
    }
    else -> ItemModel_().apply { 
      id(item.id)
      data(item)
    }
  }
}
```

**Comment by elihart** [comment]
the automodel system does not work with `PagedListEpoxyController`.

If you're using kotlin the recommended approach is https://github.com/airbnb/epoxy/wiki/Epoxy-Controller#usage-with-kotlin

I've updated the automodel wiki info to reflect this: https://github.com/airbnb/epoxy/wiki/Epoxy-Controller#automodels
