### ISSUE TITLE
EpoxyRecyclerView Error performing 'scroll to'

### ISSUE THREAD

**Issue by metanas** [airbnb/epoxy#626]
i try to create tests with Espresso:3.0.2, so i should scroll to view who is not display it for i can test it, but have this error:

 `android.support.test.espresso.PerformException: Error performing 'scroll to' on view 'with id:`

i'm using `com.airbnb.android:epoxy:2.18.0`

this is the test code: 

```kotlin
  @Test
  fun onCheckProductSpecTest() {
    onView(withId(R.id.ho__item_detail__spec_title)).perform(scrollTo())
    onView(allOf(withId(R.id.ho__item_detail__spec_title), withText("Knits"))).check(matches(isDisplayed()))
    onView(allOf(withId(R.id.ho__item_detail__spec_value), withText("Bonded"))).check(matches(isDisplayed()))
    onView(allOf(withId(R.id.ho__item_detail__spec_title), withText("Unbleached"))).check(
        doesNotExist()
    )
  }
```

i also tried with `swipeUp()`  to scrolling down, but i had some problem because the swipe depends to screen, so the tests can be fail depends device.

**Comment by elihart** [comment]
This isn't an Epoxy issue - you would use normal RecyclerView testing techniques for this. Espresso provides tools for working with recyclerview: https://developer.android.com/training/testing/espresso/lists#recycler-view-list-items
