### ISSUE TITLE
How to make sure only one viewholder instance is created

### ISSUE THREAD

**Issue by ulusoyca** [airbnb/epoxy#635]
I have a recyclerview with multiple view holder types. How can I make sure that only one instance of the viewholder is created?

In my case, I am using `@ModelView` on a custom view to generate model. However, I realize that multiple instances of the view were created. How can I limit the instance number to 1? 
I try to utilize recycledViewPool methods:
`recycledViewPool.setMaxRecycledViews(view_type_id,1)`. It doesn't work. Still I see multiple instances.

**Comment by elihart** [comment]
Why do you want to force one instance of the viewholder? that's going against the whole RecyclerView system
