### ISSUE TITLE
How to stay at bottom of List?

### ISSUE THREAD

**Issue by MTRNord** [airbnb/epoxy#648]
Hi I want to use this as a Whatsapp Like Message List. How can I get the list to stay at the bottom if the user is at the bottom when doing submitList on a PagedListEpoxyController?

Means I have 3 states:
1. Init (first time loading the data) -> I want to scroll to the bottom
2. User is already at the bottom after 1 finished and I get new data -> I want to scroll to the bottom
3. User is somewhere in the list aka not bottom after 1 finished and I get new data -> I dont want to scroll to the bottom

How can I archive that? I currently try to do it via the following code but is there a better way of doing it?

```kotlin
val recyclerLayoutManager: LinearLayoutManager = recyclerView.layoutManager as LinearLayoutManager
viewModel.messageList(intent.getStringExtra("roomID")).observe(this@ChatRoom, Observer {
    // Submit Data
    pagingController.submitList(it)

    // Check if we are at the bottom and scroll
    if (recyclerLayoutManager.findLastCompletelyVisibleItemPosition() == recyclerView.childCount) {
        recyclerView.smoothScrollToPosition(recyclerView.childCount)
    }
})
```

**Comment by josephyanks** [comment]
You shouldn't be scrolling to the bottom of the list - instead there is a great property on LinearLayoutManager to reverse the layout to be bottom to top. That should solve issues #1 and #3. See: https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager#setreverselayout

As for not scrolling if the user is at a certain position when data is added, you can use the solution explained at https://github.com/airbnb/epoxy/issues/224 and add an adapter data observer. You may actually not need this if you've done the above with reverse layout on LLM, but if that doesn't do the trick, try the below.

```
controller.getAdapter().registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
    @Override
    public void onItemRangeInserted(int positionStart, int itemCount) {
        if(positionStart == 0) {
            layoutManager.scrollToPosition(0);
       }
    }
});
```

**Comment by MTRNord** [comment]
@josephyanks thanks I actually tried the reveresed LLM. But not sure why but with the pagedListController it seems that it started to add new items in a wrong order. Thats the reason I wrote this issue as I did think there might be a better solution specific to this repo :) but I will try the solution from #224 . Maybe that works better in my specific case.

**Comment by elihart** [comment]
I would guess your PagedList needs to be setup with a DB query that loads from the end, otherwise I'm not surprised that it is loading in a weird way. I'm not sure how to make PagedList do that though.

That should be all up to the Paging/DB library though, and unrelated to Epoxy.

**Comment by MTRNord** [comment]
Ok thanks I will google around a bit :)

**Comment by MTRNord** [comment]
I got it. This awnser on stackoverflow gave me the last needed hint: https://stackoverflow.com/a/53316955/4929236

Basicly set the LLM to reverselayout and setStackFromEnd to false. And order the db query in DESC mode

**Comment by MTRNord** [comment]
Also I use the code in https://github.com/airbnb/epoxy/issues/648#issuecomment-457452438
