### ISSUE TITLE
Retrieve current adapter position of model from inside EpoxyModel

### ISSUE THREAD

**Issue by j-roskopf** [airbnb/epoxy#662]
Hey! 

Let's say I have a screen where I have a list of items. Each one of these items has a checkbox. Based on the checkbox's checked status, I display some extra info in the cell. Here is roughly how I have that mocked out

```
@EpoxyModelClass(layout = R.layout.item_layout)
abstract class Item : EpoxyModelWithHolder<ItemViewHolder>() {

    @EpoxyAttribute(EpoxyAttribute.Option.DoNotHash)
    lateinit var actionHandler: ItemActionHandler

    // I'm not super happy about this - ideally I don't want the model to be aware of the position like this. How to get around this?
    @EpoxyAttribute
    var position: Int = 0

    @EpoxyAttribute
    lateinit var item: Item

    override fun bind(holder: ConciergeOrderDetailItemViewHolder) {
        holder.conciergeReturnsCheckBox.setOnCheckedChangeListener { _, isChecked ->
            actionHandler(ConciergeOrderDetailItemAction.OnCheckChanged(isChecked, position))
        }
    }
    
    override fun unbind(holder: ConciergeOrderDetailItemViewHolder) {
        holder.checkBox.setOnCheckedChangeListener(null)
    }


    class ItemViewHolder : KotlinEpoxyHolder() {
        val checkBox by bind<CheckBox>(R.id.checkBox)
    }

    sealed class ItemAction {
        data class OnCheckChanged(val checked: Boolean, val position: Int) : ItemAction()
    }
}

typealias ItemActionHandler = (ItemAction) -> Unit

data class Item(val text: String, val checked: Boolean)
```

Right now, in my controller class, I am populating the `position` attribute of my model which doesn't seem like the best way to do it. When using an adapter, I am used to checking something like

```
if(holder.hasPosition()) {
    //use holder.adapterPosition
}
```

Is there a way I can achieve this inside my model class?

**Comment by elihart** [comment]
There isn't a built in way to access position from a model - if you do want to get the position of the model while you're building models you can use `EpoxyController#getModelCountBuiltSoFar`

Generally though it isn't recommend to rely on position - instead you can have an id for the data that the checkable Item represents, and have the click listener just pass that id. That will cover whether it is `checked` or not as well. Basically take the id and look up the item information at the time of click.

**Comment by j-roskopf** [comment]
Sounds good! I think I'll convert to using the ID to lookup the data. Thanks for the info!
