### ISSUE TITLE
AdModel - How to not load new Ad every bind()

### ISSUE THREAD

**Issue by eloisance** [airbnb/epoxy#664]
I have an AdModel (who extends EpoxyModelWithHolder) which display an Ad in my list between others models.

Because I load my Ad in the bind method with `adView.loadAd()`, every time I scroll down and come back to this model in my list, this method is recall and load a new Ad but I don't want this behaviour (Ad already reload after X seconds by the Ad SDK).

I have also tried `setIsRecyclable(false)` in `onModelBound` without success

How I can tell to this specific model to not recall bind method every time? Any idea? 
Thanks

**Comment by elihart** [comment]
`setIsRecyclable(false)` is not what you want, the view needs to handle recycling properly.

This isn't an epoxy specific problem - what is your ad SDK's recommendation for use with RecyclerView? it sounds like support their sdk needs to provide (like `loadAd(id) so that you can load a consistent ad)

**Comment by eloisance** [comment]
We use Google Ad Manager SDK (https://developers.google.com/ad-manager/mobile-ads-sdk/android/banner) and nothing about recyclerview in the documentation.

`loadAd` take one parameter who is an `PublisherAdRequest`.
I create this `PublisherAdRequest` and give it to my AdModel with `@EpoxyAttribute` in the `buildModels` method and load it in `bind` method.
But even with this, each time the AdModel is visible again, `bind` is call with `adView.loadAd(samePublisherAdRequestObject);` and a new Ad is displayed.

I don't know how I can load ad only once and let it auto refresh even if the user scroll up and down the list many times with a lot of other models between each Ads?

**Comment by elihart** [comment]
It sounds like what you want to do is incompatible with view recycling - so you may have to just be ok with the ad changing if the view is scrolled off the screen and back on

**Comment by eloisance** [comment]
Ok, I will see how we can do differently.
Thanks for your time Eli !
