### ISSUE TITLE
Performance monitoring of EpoxyController

### ISSUE THREAD

**Issue by L7ColWinters** [airbnb/epoxy#667]
I was wondering what is the suggested approach to do performance monitoring for when the controller builds the models. I know that there's a debug logger that can be enabled on the controller but I'd like to create traces with such data, for instance make a firebase trace and upload that data for a subset of users to the firebase console. My worry is that in production our lists might encounter a slow time to build and then show on the screen.

I was thinking of overriding the DebugTimer in my code and use a singleton to create Firebase Trace objects but the log message doesn't use the class name and also the message is only at the end of the timer, Firebase would require it at the creation of the trace. I know I'm going out on a limb here but it would be nice to be able to make the messages that are sent to the debug timer use the class name so that one could know which controller is loading items even if you usually use one at a time. And maybe if possible pass the message into the start method?

I was looking at ways of doing this myself but really I think this should be a library change.

**Comment by elihart** [comment]
Hey, thanks for explaining your need and use case, it sounds reasonable to add support for this to the library.

Would you be interested in making a PR? If you can offer a clean solution I'd be happy to review.

**Comment by L7ColWinters** [comment]
I have a small change on DebugTimer but for some reason i'm getting a 403 when trying to push my branch to this repo. Is this not an open repo?

**Comment by elihart** [comment]
You have to fork it and open a pull request

**Comment by L7ColWinters** [comment]
Thanks for merging but I'm not seeing the class changed in the 3.3 AAR. I see it if I download or clone the source but not with a maven aar import. Not sure why, I'm pointing to 3.3.0.

**Comment by elihart** [comment]
You're right, I merged both on the same day, but did the release before I merged the debug timer changes. So it will go out in the next release, which isn't planned yet - how important is it to release for you?

**Comment by L7ColWinters** [comment]
Mildy important if you don't mind

**Comment by elihart** [comment]
I've released 3.3.1 which has the change included, sorry about the delay!

it may take a few minutes to be available on maven
