### ISSUE TITLE
Implementing collapse/expandable items in a list

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/epoxy#668]
I got the specs for a new list I have to create that will behave/look like the following:
![1_tzd63qdfm7urwohnz7ga_w](https://user-images.githubusercontent.com/31751141/51779330-ad0d5b00-20d4-11e9-80a4-38e8f0e0e242.gif)

What would you say is the best way to do this if I'm just using epoxy?

**Comment by elihart** [comment]
It looks like each of those expandable rows should be it's own custom view, with internal logic to handle the expansion (and a custom animation).

it looks like this would be difficult to do exactly with a recyclerview because the vertical spacing between items changes when an item expands

**Comment by Nimrodda** [comment]
@ColtonIdle check out my comment https://github.com/airbnb/epoxy/issues/473#issuecomment-500120564
