### ISSUE TITLE
Allow for subclasses in other modules in processor

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#67]
In the annotation processor we look for annotated fields on super classes and bundle them with sub classes. This relies on the super classes being included in the processor - we don't walk up the inheritance tree and explicitly look for super classes with annotations.

This creates a problem where if the super class is in a different module it's annotated fields will not be included in generated subclasses in other modules.

Solution should be to walk up the inheritance tree for each model class found in the processor.

**Comment by geralt-encore** [comment]
Can you elaborate more on this or provide an example? Seems like I don't get it completely =(

**Comment by elihart** [comment]
Sure, say Model A is in module A and Model B extends Model A and is in module B.

When the annotation processor runs it gets annotated elements for a single module at a time, so it will process module B separately from module A.

Since Model B extends Model A it may inherit @EpoxyAttribute annotated fields from Model A. Right now the processor groups inherited fields only if the super class is being processed at the same time as the sub class. This is because it goes through all models with annotations in that module, and then looks at which classes are subclasses of another and adds inherited annotations if so.

This approach doesn't work if the models are processed separately when they are in separate modules.

**Comment by elihart** [comment]
I'll try to work on this myself today
