### ISSUE TITLE
EpoxyModelGroup with ViewStub

### ISSUE THREAD

**Issue by eboudrant** [airbnb/epoxy#672]
I am trying to layout a model group using `ViewStub`, here the xml :

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal">

    <!-- First element -->
    <ViewStub
        android:layout_width="60dp"
        android:layout_height="60dp" />

    <!-- Elastic space -->
    <View
        android:layout_width="0dp"
        android:layout_height="match_parent"
        android:layout_weight="1" />

    <!-- And up to 3 elements -->
    <ViewStub
        android:layout_width="60dp"
        android:layout_height="60dp" />
    <ViewStub
        android:layout_width="60dp"
        android:layout_height="60dp" />
    <ViewStub
        android:layout_width="60dp"
        android:layout_height="60dp" />

</LinearLayout>
```

I am expecting :

<img width="417" alt="screen shot 2019-02-01 at 1 45 34 pm" src="https://user-images.githubusercontent.com/773377/52151579-767d9600-2628-11e9-8287-6f8606de393d.png">

But I am seeing this :

<img width="415" alt="screen shot 2019-02-01 at 1 46 19 pm" src="https://user-images.githubusercontent.com/773377/52151590-82695800-2628-11e9-8db5-f6747a8f34c8.png">

Is there any issue with `EpoxyModelGroup` / `ViewStub` or is it a miss-use from me ?

Full code is here : https://github.com/eboudrant/epoxy/pull/9

**Comment by eboudrant** [comment]
Looks like the stub are removed too early from the layout :

https://github.com/airbnb/epoxy/blob/2de36ba0fdb2223dcb51900efd41da952b5cd1cf/epoxy-adapter/src/main/java/com/airbnb/epoxy/ModelGroupHolder.kt#L67

The position passed in the `ViewStubData` would not allow to re-position correctly the nested model.

**Comment by elihart** [comment]
Thanks for reporting. good catch, this is definitely wrong.

I'm traveling now, but can fix it early next week - sorry for the issue!

Maybe an easy fix could be to have `getNextViewStub` add the count of existing stubs to the index of the newly created stub data - I think that would give the correct adjusted position while not requiring a change to the view removal - I'll have to think about it a bit more though.

**Comment by elihart** [comment]
https://github.com/airbnb/epoxy/pull/676
