### ISSUE TITLE
Saved state enabled everytime ? Not recycled, using EpoxyRecyclerView with DataBindingEpoxyModels

### ISSUE THREAD

**Issue by bellierjonathan** [airbnb/epoxy#673]
Hello,

I wanted to create a complete view using `Epoxy` and `EpoxyRecyclerView` with different`DataBindingEpoxyModel` :
- `ProfileViewEpoxyModel`
- `TextDescriptionEpoxyModel`
- `TextFieldEpoxyModel`
- `MapViewEpoxyModel`

with a controller _MainEpoxyController_. 

But when I scroll, all items state are already saved and I don't know why. All items are not recycled.

In the documentation it's written `Saved State is disabled by default`.

I use `DataBindingEpoxyModel` in `2.19.0`.

I don't know if I have to use grouping models for this... 🤷🏾‍♀️

![Screen](https://user-images.githubusercontent.com/5746542/52214891-16d6f300-2893-11e9-8cc7-af776c6d2fbb.png)

Thanks

**Comment by elihart** [comment]
You'll have to provide more specific details like the code of your controller and views - otherwise I can't help much.

**Comment by bellierjonathan** [comment]
I have deleted all of my code to retry something else sorry. I thought this problem was knows. I will see in few weeks to retry this with using saving state.
