### ISSUE TITLE
[question] Why use Paging if addModels caches everything?

### ISSUE THREAD

**Issue by bernaferrari** [airbnb/epoxy#678]
Hi, I have a question regarding PagedListEpoxyController. I heard it is useful for both network requests and database requests. For network, ok, Epoxy is perfect. For database/internal/offline requests, however, I don't understand the benefit - if there is any.

From my understand, Paging should be good because it should fetch/cache the database values incrementally, as you scroll down. With Epoxy, however, `addModels` already provides every value that was fetched from database, so it is good for updates, but it looks like zero benefit to a 'standard' usage. Am I correct? Should I not page my values, instead fetch hundreds, thousands values from db, put on a list and pass to Epoxy to read, because `epoxy-paging` is doing 'the same'?

**Comment by bernaferrari** [comment]
Oh, makes sense. So, is it correct to say I should use PagedList whatever possible? I really do not know what the 'threshold' is. I stopped testing with 3k items, but my scenario is usually less than 3k.

**Comment by elihart** [comment]
i would use paging for anything more than 100, but it really depends on how complex the views are and what your tolerance for dropped frames is.

**Comment by bernaferrari** [comment]
Ok, thanks!!
