### ISSUE TITLE
crash when using butterknife in model

### ISSUE THREAD

**Issue by rudinesurya** [airbnb/epoxy#680]
the below codes work perfectly fine using kotlin synthetic binding, but with butterknife it will crash. 

```kotlin
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class CoffeeItem @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : LinearLayout(context, attrs, defStyleAttr) {
    
    // View binding
    @BindView(R.id.coffee_name_val)
    lateinit var coffeeNameVal: TextView
    @BindView(R.id.coffee_shop_name_val)
    lateinit var coffeeShopNameVal: TextView
    @BindView(R.id.coffee_price_val)
    lateinit var coffeePriceVal: TextView
    @BindView(R.id.coffee_rating_val)
    lateinit var coffeeRatingVal: TextView

    init {
        inflate(context, R.layout.coffee_item_card_view, this)
        ButterKnife.bind(this)
        orientation = VERTICAL
    }


    @ModelProp
    lateinit var coffee: Coffee

    @CallbackProp
    @Nullable
    lateinit var onClick: View.OnClickListener

    @AfterPropsSet
    fun bindUI() {
        coffee.let {
            coffeeNameVal.text = it.name
            coffeeShopNameVal.text = it.shop
            coffeePriceVal.text = it.price.toString()
            coffeeRatingVal.text = it.rating.toString()
        }

        setOnClickListener(onClick)
    }
}
```

**Comment by elihart** [comment]
I don't believe this is related to Epoxy, more likely a misuse of butterknife. are you applying `kapt` correctly?

I can't help you without a stacktrace though

I wouldn't recommend using buttknife with kotlin anyway, something like kotterknife is much bettter

**Comment by rudinesurya** [comment]
This is part of the error logs, with butterknife only being used in that single file.


`runtime.cc:492]   at butterknife.Unbinder.<clinit>(Unbinder.java:9)
    runtime.cc:492]   at butterknife.ButterKnife.bind(ButterKnife.java:165)
    runtime.cc:492]   at butterknife.ButterKnife.bind(ButterKnife.java:110)
    runtime.cc:492]   at com.rud.coffeemate.ui.modelview.CoffeeItem.<init>(CoffeeItem.kt:38)
    runtime.cc:492]   at com.rud.coffeemate.ui.modelview.CoffeeItem.<init>(CoffeeItem.kt:23)
    runtime.cc:492]   at com.rud.coffeemate.ui.modelview.CoffeeItem.<init>(CoffeeItem.kt:-1)
    runtime.cc:492]   at com.rud.coffeemate.ui.modelview.CoffeeItemModel_.buildView(CoffeeItemModel_.java:69)
    runtime.cc:492]   at com.rud.coffeemate.ui.modelview.CoffeeItemModel_.buildView(CoffeeItemModel_.java:31)
    runtime.cc:492]   at com.airbnb.epoxy.BaseEpoxyAdapter.onCreateViewHolder(BaseEpoxyAdapter.java:79)
    runtime.cc:492]   at com.airbnb.epoxy.EpoxyControllerAdapter.onCreateViewHolder(EpoxyControllerAdapter.java:16)
    runtime.cc:492]   at com.airbnb.epoxy.BaseEpoxyAdapter.onCreateViewHolder(BaseEpoxyAdapter.java:15)
    runtime.cc:492]   at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
    runtime.cc:492]   at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
    runtime.cc:492]   at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
    runtime.cc:492]   at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
    runtime.cc:492]   at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
    runtime.cc:492]   at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
    runtime.cc:492]   at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
    runtime.cc:492]   at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
    runtime.cc:492]   at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
    runtime.cc:492]   at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
    runtime.cc:492]   at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)`

**Comment by elihart** [comment]
Your log is missing the actual error message and details

**Comment by rudinesurya** [comment]
Seems like the crash was caused by something else that only happens when i use butterknife on this epoxy model. Weird!
I did a small demo just to test epoxy and butterknife and in that self contained demo everything works perfect. 
Thank you for your help, Eli.
