### ISSUE TITLE
Can't set initial state (isChecked) of AppCompatCheckBox inside setter method 

### ISSUE THREAD

**Issue by ilsht** [airbnb/epoxy#681]
I'm trying to set initial checkbox state passing it through an annotated setter.

When `saveViewState` option is used, it doesn't work - the checkbox' `isChecked` state is always set to `false`. I've tried to do an additional `requestModelBuild()` after the `buildModelsWith` was executed, with 200ms delay (and when the view was already on the screen) with no success.

When `saveViewState` is disabled it works without any issues.

I suspected kotlinx synthetics and replaced them with `findViewById`, and it didn't help.
I've tested this behavior on TextViews, but they didn't seem to have this issue. EditText seem to have no issues, too.
Is something wrong with implementation so checkboxes are not turned on?

Epoxy and Support Library versions
```
implementation 'com.airbnb.android:epoxy:2.19.0'
kapt 'com.airbnb.android:epoxy-processor:2.19.0'
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:support-v4:28.0.0'
implementation 'com.android.support:recyclerview-v7:28.0.0'
```

Piece of model implementation
```
@ModelView(saveViewState = true)
class RowView: ConstraintLayout {
...
    @ModelProp
    fun setCheckedState(isChecked: Boolean) {
        this.checkbox?.isChecked = isChecked
    }
...
}
```
(This issue is a duplicate of https://stackoverflow.com/q/54142546)

**Comment by elihart** [comment]
look in `CompoundButton` - the checked state is saved in state. you can't have data provided both by saved state and by a model prop since they conflict, saved state overrides model prop settings.

what do you need saved state for? it seems like checked state is better off being tracked as a model prop

**Comment by ilsht** [comment]
I need it for checkboxes' state to be drawn properly when:

- a few checkboxes at the bottom of the list were clicked, having their `isChecked` state toggled "on"
- the list with checkboxes was scrolled up to the top, so the checkboxes that were toggled before are now off-screen and far away
- now we scroll down to the bottom and see that checkboxes that were toggled before have lost their state (they're toggled off while they should've been toggled on)

(No `requestModelBuild` or any other updates were performed during these operations.)

**Comment by elihart** [comment]
you should instead be storing the checked state for those boxes elsewhere, and applying it when you build the models for them

**Comment by ilsht** [comment]
I'm storing the state in my view model, and then another issue (when view state saving is not enabled) appears, you can see it here - https://imgur.com/a/B5rtQlv

Basically, I've changed from `@ModelView(saveViewState = true)` to `@ModelView`, and stored the state (array of booleans) in my view model. I've checked it - and it is changed/stored correctly (after click on checkbox). The state is set during `buildModelsWith` like this
```
RowViewModel_().id(item.id.name)
            .text(item.name)
            .checkedState(model.itemsChosen[item] ?: false)
            .onChangeListener { buttonView, isChecked ->
                if (buttonView.isShown && buttonView.isPressed) {
                    model.itemsChosen[item] = isChecked
                }
            }
            .addTo(epoxyView) // EpoxyRecyclerView
```
If I'm doing something wrong, then it seems I don't get how it must be implemented, any examples? (I've skimmed kotlin-sample and test directories of epoxy, but I don't see obvious mistakes in my code.)

**Comment by elihart** [comment]
your approach of saving state in your view model generally looks right, but I believe you're missing the step of rebuilding models after the view model is updated.if the epoxy models aren't rebuilt for the new state then when the view is rebound on scroll it won't be correct

so request a model build right after model.itemsChosen[item] = isChecked

**Comment by ilsht** [comment]
Got it. Can't test right now or in near time, but I believe this issue can be closed.
(Coming from iOS development, I thought that requestModelBuild() is fairly heavy operation and would trigger view redraw in similar fashion to UITableView's reloadData.)

**Comment by wiztensai** [comment]
> Got it. Can't test right now or in near time, but I believe this issue can be closed.
> (Coming from iOS development, I thought that requestModelBuild() is fairly heavy operation and would trigger view redraw in similar fashion to UITableView's reloadData.)
> 
> Update: I've tested it and it worked.

Could i see your full code?
