### ISSUE TITLE
How to add dynamicly date seperators based on a variable in other models?

### ISSUE THREAD

**Issue by MTRNord** [airbnb/epoxy#683]
Hi I want to make date seperators like in the following image:

![chat room - group - image](https://user-images.githubusercontent.com/1374914/52653328-0f959200-2ef0-11e9-84c1-5ff00a99d9d0.png)

I do have a `created At` value on each message. I do want to add a date seperator in between Message A and Message B if B is on a different day than A. How can I archive that? I do use the PagingController for my room DB data.

**Comment by MTRNord** [comment]
Either I need a way to prepare the paged list ahead of rendering or need a way to look behind to the previous message I guess.

**Comment by elihart** [comment]
It's probably best if the date view is it's own epoxy model. You can add an interceptor to analyze the list of models and insert dates. or you could override `addModels` in the paged controller to add the date models

**Comment by MTRNord** [comment]
I will try that. Thanks for the hint already.

**Comment by MTRNord** [comment]
@elihart I am not sure if I miss something but how do I add stuff to the list of Models in an interceptor? Just extending the list I got?

**Comment by elihart** [comment]
in the interceptor list you should be able to modify the list directly with additions or removals

**Comment by MTRNord** [comment]
This worked using overriding addModels. Thanks for the help
