### ISSUE TITLE
Generate a method to reset fields back to defaults

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#69]
a method like `model.reset()` could set all annotated fields back to their defaults. This is useful if a model is reused or changed and you don't want any previously set values carrying over to the new usage.

**Comment by geralt-encore** [comment]
You mean type defaults or values assigned by a user during declaration? The first should be easy and I dunno about the second one.

**Comment by elihart** [comment]
the first one, type defaults. definitely should be easy, just a little grunt work to enumerate them for each primitive type.

What do you think of this idea? I don't want to head down a path where the generated models include too many helper methods since it could bloat them and be too specific, but a single general method like this seems worthwhile

**Comment by geralt-encore** [comment]
I understand your concerns, but this method looks pretty reasonable to have. I'll try to do it today.
