### ISSUE TITLE
NPE when writing a unit test for controller

### ISSUE THREAD

**Issue by j-roskopf** [airbnb/epoxy#692]
Hey! I have a Controller class that looks something like this: 

`class MyController :
  Typed4EpoxyController<ArrayList<Data>, Data1, Data2, Data3>() {`

I am trying to write a unit test and have something like this: 

    @RunWith(MockitoJUnitRunner::class)
    class ControllerTest {
 
        val controller = MyController()

        @Test
        fun controllerTest() {
           val observer : RecyclerView.AdapterDataObserver = mock()
           controller.adapter.registerAdapterDataObserver(observer)

           ...test using controller
        }
    }

I get a NPE when running the test on the line instantiating the controller

![](https://i.imgur.com/yemG5F7.png)

I tried looking for some unit testing documentation in the wiki / sample applications, but didn't see any. 

I did see these two issues, but didn't seem to be the same problem.

https://github.com/airbnb/epoxy/issues/623
https://github.com/airbnb/epoxy/issues/631

Any thoughts on how to get around this? Thank you!

**Comment by elihart** [comment]
I believe you need to be using robolectric, otherwise the android classes like recyclerview won't have implementations and will crash

**Comment by j-roskopf** [comment]
Ah okay. I will go down that route. Thank you for the response!
