### ISSUE TITLE
Question: Is it possible to create specific view pools for some views?

### ISSUE THREAD

**Issue by kitttn** [airbnb/epoxy#693]
In our app we have a list of items, and every item has 1 to 5 small images below title. 
I want to make a separate view pool for those images. 
Is it possible to do with Epoxy? 

Thanks!

**Comment by elihart** [comment]
Epoxy isn't related to the viewpool, that belongs to the recyclerview. Use a normal recyclerview and set the view pool to whatever you want, same as without epoxy

**Comment by elihart** [comment]
You might also want to make sure you are familiar with EpoxyRecyclerView and it's unbounded view pool

**Comment by kitttn** [comment]
Thanks for quick response, will read about it :)
