### ISSUE TITLE
Have `hash=false` still check for presence

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#70]
When using `hash=false` as an attribute param we don't include that field in the model hashcode at all. We can change this to instead include it in the hashcode as a boolean, for whether it is null or not (would not work with primitives).

The idea is that you may not care about the hash (eg anonymous click listeners that all do the same thing), but there should be a difference between having that field be set and having it be null

I guess for primitives we would leave it as is and exclude them, but it doesn't make sense to not hash primitives (that I can think of).

**Comment by geralt-encore** [comment]
So basically you want to treat any object as boolean if hash code is ignored for him? What about boxed primitives?

**Comment by elihart** [comment]
that's right. if the annotation is marked with `@EpoxyAttribute(hash=false)` right now we completely leave it out from the generated hashcode method. instead I'm proposing just treating it as a boolean.

Boxed primitives could work the same way. That would be saying the state only cares about whether that boxed primitive has a value set or not.

**Comment by geralt-encore** [comment]
And what about `equals` in that case? I am not sure how to implement it correctly. Ignore for primitives and just check for references without calling `equals` on an object itself?

**Comment by elihart** [comment]
I think to match with hashcode it should ignore primitives and make sure either both values or null, or non null to be considered equal.
Something like:
```
if (item != null && that.item == null || item == null && that.item != null) {
      return false;
    }
```
but maybe there is a cleaner more clever way to write that.

**Comment by geralt-encore** [comment]
Nah, I don't see a better way either. Will stick to this one.

**Comment by elihart** [comment]
https://github.com/airbnb/epoxy/pull/75
