### ISSUE TITLE
Partial data updates

### ISSUE THREAD

**Issue by jeroenbeuz** [airbnb/epoxy#703]
The following is stated in the Wiki:

When buildModels is called again Epoxy diffs the newest models against the previous ones to determine what updates need to be made to the RecyclerView.

Now I have the following situation. My items in my EpoxyRecyclerView can share state. Multiple items can have some shared property. So when the user changes one item, it may impact the state for other items. When this action is called it's very easy for me to find out which other items share this state and update only those properties that are impacted.

Now since the built models are immutable, I have to recreate every model and let the diffutil do it's thing and figure out what has changed. This seems rather inefficient since it's already known up front what has changed an which properties need an update.

I hope my explanation is clear enough, I'm happy to share a code example if it's not. 

Thanks!

**Comment by elihart** [comment]
Is your only concern the inefficiency?

Skipping the full build models because the user thinks they can shortcut it complicates the API and allows for potential bugs from incorrect user behavior, which imo is not worth an increase in efficiency. 

If performance is bad then use the async support.

This goes against the philosophy of the Epoxy Controller, if you want efficient manual control you can use the old EpoxyAdapter

**Comment by jeroenbeuz** [comment]
Thanks for your quick response. Yes my concern is inefficiency. I have a seekbar in each EpoxyModel which modifies the state. The state is updated in the onProgressChanged event, which fires a lot. I want my view to update instantly upon these events, not only for the item for which that event is fired, but also the views that depend on that same state. This is a bit laggy, even when using async support. So this is only an issue for me now since the onProgressChanged event fires at least once every 10-20ms.

Do you think the old EpoxyAdapter fits this use case better?

**Comment by elihart** [comment]
Yes, I think EpoxyAdapter would work better for this.

EpoxyController was not designed for 60 fps animations like that

**Comment by jeroenbeuz** [comment]
Thanks for you help!

I'm sticking with my DataBinding solution for now, where a property notifies the view on changes (notifyPropertyChanged(BR.propertyId). But it was fun to get to know epoxy, thanks for making it open source.
