### ISSUE TITLE
Partial rebind not working with databinding

### ISSUE THREAD

**Issue by alashow** [airbnb/epoxy#705]
I have a simple UI for a counter with `count` view and  `-/+` buttons. When `-/+` is clicked, I decrement/increment the counter. I send updated list to epoxy controller.

Everything is working except when `-/+` is clicked, the item view gets reloaded. When `RecyclerView`'s `itemAnimator` is not disabled, the whole view flashes - which I guess means no partial rebinding is happening. Even if I disable `RecyclerView`'s item animation, it removes clicking feedback from the buttons (ripple, click sound) as the view gets removed and added again.

Am I doing something wrong or is this expected behavior?

Relevant code: https://gist.github.com/alashow/cf6ed2b67ad7e33051c1066a9ffa1352

**Comment by elihart** [comment]
You are doing something wrong - `id(it.hashCode())`

The id needs to be unique and stable. Please read through the wiki for a guide on how to use epoxy

**Comment by alashow** [comment]
Damn, don't know how I missed that! I had different implementations for a stable id during refactoring. Don't know how that `hashCode` slipped there...

Thanks!
