### ISSUE TITLE
Updating the id of a model causes a blank view

### ISSUE THREAD

**Issue by JayyyR** [airbnb/epoxy#708]
I have a use case where I change the id of one of my models and when the controller updates, the view is blank. It's a bit weird because there's space in the recyclerview where the view should be but it looks like its set to INVISIBLE.

My specific case is a messaging app. I send a message to the server, while its in "sending" state, I generate a unique id for it. Then when I get a successful response from the server, it contains a unique id. I then override the local id I set and trigger a call to rebuild my models.

My recycler view updates but 33% of the time the view is just blank where my updated view should be

**Comment by JayyyR** [comment]
to be clear, what I'm really doing is updating a unique id in my dataset that I then use as a unique id when building models.

I verified that a call is made to build that new model with the updated data item when the id is changed. But the view is mysteriously blank

**Comment by JayyyR** [comment]
Oh and if I scroll around the view appears

**Comment by JayyyR** [comment]
couple other things,

the view does get bound (verified onBind was called). Using the debug tools, looks like none of the view is actually there

**Comment by JayyyR** [comment]
@elihart any idea around what could be causing this? I'm seeing tangential issues where some views in the recyclerview blink/flash even tho only one call was made to `buildItemModel` and `onBind` was called once. I can provide more details around that as well

**Comment by elihart** [comment]
My only guess is that this is related to the paging library - how do you have that setup with Epoxy?

Can you share any code? I can't do too much without that

**Comment by JayyyR** [comment]
Sorry...this was a bug with some animation library I'm using
