### ISSUE TITLE
Question: Is epoxy controller suitable for frequently changing list?

### ISSUE THREAD

**Issue by diousk** [airbnb/epoxy#714]
I have a chat room like screen and I want to use Epoxy controller 
to achieve the updates of the chat list (mostly insert/remove)

But in my case, the chat list may change very frequently, e.g. insert a new chat item every 100 ms (or even lower than 100 ms)
which means that for every single change, I need to call **TypedEpoxyController's setData** in order to rebuild the models for controller to diff the list.

My concern is the memory usage may grow fast. (because the frequent rebuilding of whole models) 
Would it? Should I worry about that?

**Comment by elihart** [comment]
Yes, there are some things you can do to make Epoxy work well with frequent changes.

First you can use EpoxyController#requestDelayedModelBuild - this is intended exactly for your use case.

Second, you can switch to async model building and diffing to prevent the updates from affecting UI performance.

There are more details in the wiki, and in the javadoc of the source code. You will have to use a normal EpoxyController, and not the typed one
