### ISSUE TITLE
ViewPager like carousel view position

### ISSUE THREAD

**Issue by salexwm** [airbnb/epoxy#719]
CarouselModel works wonderfully and hosts models which almost full width of the screen. Is there a way to know which model is currently fully displayed ? I tried visibility callbacks but it seems they are not getting called.

![ApplicationFrameHost_2019-04-01_20-43-21](https://user-images.githubusercontent.com/1475062/55348009-d7a5d680-54be-11e9-810e-a2095499e69f.png)

both are carousels and scrolling horizontally, and host rv scrolling also scrolling vertically
question is how to know which model is "selected" in top carousel

**Comment by elihart** [comment]
The normal layout manager methods to check displayed items should be able to tell you this I believe

**Comment by salexwm** [comment]
@elihart yes for vertical getPosition(View) works fine, but how to get carousel layout manager which is inside another rv ?

**Comment by elihart** [comment]
you just need access to the nested recyclerview object - which is easy in some cases but not others, it depends where you need to query this from.

regardless the visibility callbacks should be the better option, and nested carousels should be supported as of https://github.com/airbnb/epoxy/commit/c6945f6862ae96745b137929c97d69ba4a356803

are you on the latest version? can you make sure you have that set up correctly and try that approach again? if it still doesn't work can you debug it to figure out why not?

**Comment by salexwm** [comment]
i'm using 2.19, project still didn't migrate to androidx
