### ISSUE TITLE
databinding root view bindings not applied

### ISSUE THREAD

**Issue by alashow** [airbnb/epoxy#721]
Hello,
This might be unrelated to Epoxy but I have encountered weird behavior when using Epoxy with databinding. I had a simple layout like:

```xml
<ConstraintLayout android:disabled="@{!item.isEnabled}">
	<TextView/>
	<TextView/>
</ConstraintLayout>
```
`disabled` binding:
```kotlin
@BindingAdapter("android:disabled")
fun applyDisabled(view: View, value: Boolean) {
    view.alpha = if (value) 0.38 else 1.0f
}
```

First time `controller.setData(list)` the views would have proper `alpha` depending on `item.isEnabled`. But after that, it would reset to `1f` and stop changing.
Trying to figure out what's going on I applied `android:disabled` binding to child `TextView`s and it worked as expected. So I thought it might be a problem with root view and changed my layout to this:
```xml
<FrameLayout>
	<ConstraintLayout android:disabled="@{model.hasSeats}">
		<TextView/>
		<TextView/>
	</ConstraintLayout>
</FrameLayout>
```
So the problem was with the root view.
Weird thing is, I was using `android:clickable="@{item.isEnabled}"` too and it worked properly in both cases.

**Comment by elihart** [comment]
Can you set some breakpoints and figure out why it is changing? I can't do anything without more information - if you can show details about a bug in epoxy I'll look into it

**Comment by alashow** [comment]
Well, apparently `RecyclerView`'s `ItemAnimator` modifies item root view's alpha at some point.

Not related to Epoxy or databinding.

Found related SO question: https://stackoverflow.com/questions/40942116
