### ISSUE TITLE
How do Visibility Events work with groups?

### ISSUE THREAD

**Issue by pwillmann** [airbnb/epoxy#727]
I have a group like this: 

```
class TestModelGroup(id: String, header: EpoxyModel<*>) : EpoxyModelGroup(R.layout.demo ,listOf(header)) {
    init {
        id(id)
    }   
}
```

Which is added in the controller like this (in a loop to fill a feed): 
```
    add(TestModelGroup(
                offer.id,
                TestHeaderEpoxyModel_()
                        .id("offer-${offer.id}-feed-card-header")
                        .title(offer.title)                
        ))
```

How do I attach the `VisibilityStateChanged`Listener to the group? 

I tried overriding `fun onVisibilityStateChanged(visibilityState: Int, view: Holder)` in the ModelGroup class, which throws:

```
error: cannot find symbol
    com.airbnb.epoxy.EpoxyModelGroup.Holder view) {
                                    ^
  symbol:   class Holder
``` 

and the `TestModelGroup` also does not expose a function to add a listener. 

Thanks in advance!

**Comment by elihart** [comment]
Since you are overriding a model you fall into the category of https://github.com/airbnb/epoxy/wiki/Visibility-Events#when-overriding-a-model

So, there is no way to add a listener automatically. In your model you can add that manually if you like - you just override the existing functions in the model and do whatever you like

**Comment by pwillmann** [comment]
Thanks for the quick response! 
Just overriding `onVisibilityStateChanged` did not work, because of the aforementioned exception. 

But adding the annotation and making the group class abstract indeed fixed this!
