### ISSUE TITLE
Kotlin EpoxyModel Implementation

### ISSUE THREAD

**Issue by naj147** [airbnb/epoxy#729]
I'm using Paris so I can Style my Epoxy Components programatically.
But I'm getting the following Kotlin error : 
    

> Methods annotated with @Style must be static and can't be private or protect

**Dependencies**
    
    implementation 'com.airbnb.android:epoxy:3.4.0'
   
    kapt 'com.airbnb.android:epoxy-processor:3.4.0'
   
    implementation 'com.airbnb.android:paris:1.2.1'
  
    kapt 'com.airbnb.android:paris-processor:1.2.1'

**Code for View**

    @Styleable
    @ModelView
    class TypographyView @JvmOverloads constructor(
    context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
    ) : TextView(context, attrs, defStyleAttr) {
    @TextProp
    fun setTitle(charSequence: CharSequence) {
        text = charSequence
    }

    companion object {
        @Style
        fun defaultStyle(builder: TypographyViewStyleApplier.StyleBuilder) {
            builder.textColorHint(Color.BLACK)
                .textSize(16)
                .fontFamilyRes(R.font.torsans_regular)
            }
        }
    }

**Code for Controller**
  
    class TypographyListingController() : TypedEpoxyController<List<TypographyDataModel>>()     {
            override fun buildModels(data: List<TypographyDataModel>?) {
               data?.forEach {
                TypographyViewModel_()
                    .id(it.text)
                    .styleBuilder { builder ->
                    builder.add(R.style.H1)
                }
                .title(it.text)
                .addTo(this)
        }
    }

**Comment by elihart** [comment]
I believe with kotlin you should be using the generation kotlin extension functions were declaring styles
```
@Style
val defaultStyle = typographyViewStyle {
          textColorHint(Color.BLACK)
         textSize(16)
        ....
}
```

you might get better answers on the Paris repo, since this is really not related to Epoxy

**Comment by naj147** [comment]
Thank you for your prompt response! 
I tried using the generated Kotlin extension functions

        @Style
    val defaultStyle = typographyViewStyle {
        textColorHint(Color.BLACK)
        textSize(16)
        fontFamilyRes(R.font.torisans_regular)
    }


 but same error 

     Fields annotated with @Style must be static.

I asked the same question in Paris, still waiting for an answer :)

**Comment by elihart** [comment]
are you using the extension function  `typographyViewStyle ` in the companion object? if so that is exactly what we do so not sure why it wouldn't be working, and you'd have to wait for an answer from @ngsilverman

**Comment by naj147** [comment]
Problem fixed on Paris Repo 🥇  many thanks for the mention and the suggestions 👍 


- Just incase someones gets the same pb : https://github.com/airbnb/paris/issues/108
