### ISSUE TITLE
Model class not found ERROR on upgrading to latest version

### ISSUE THREAD

**Issue by krn1** [airbnb/epoxy#733]
Hi there,
We Just tried to upgrade from **2.14.2** to **3.4.2** . We are unable to build and it keeps throwing `cannot find symbol Model class ` . Is there any thing I should be doing to get it working smoothly? We are using EpoxyController directly and not `Typed2EpoxyController` and for building model we are using this `ModelView` ,
```
@ModelView(autoLayout = Size.MATCH_WIDTH_WRAP_HEIGHT)
public class HeaderView extends ConstraintLayout {
}
```
I keep getting this compilation error 
```
error: cannot find symbol class HeaderViewModel_
```
Any help is highly appreciated ?

**Comment by elihart** [comment]
That error isn't the root cause, something else is happening that is preventing the model from being generated.

Can you work back through versions and see if any of the 3.x versions work?
