### ISSUE TITLE
Tab bar setup with Carousel  &  Dynamic Height 

### ISSUE THREAD

**Issue by hakansuluoglu** [airbnb/epoxy#734]
Hi :hand: :hand:
 I try to create different screens with using epoxy. There are some problems in the following case.

### STRUCTURE
--Epoxy Recycler View
-----Header Model
-----Body 
---------Tab bar Model
---------Carousel Model
--------------Section Models ( Each Model has Recycler)
------------------Components 
 
### Page Controller 
```
    new TabLayoutModel_()
            .id("tab")
            .sectionList(StreamSupport.stream(sectionList)
                    .map(Section::getTitle)
                    .collect(Collectors.toList()))
            .addTo(this);
    new CarouselModel_()
            .models(StreamSupport.stream(sectionList)
                            .map(section -> new SectionHorizontalModel_()
                                    .id(section.getId())
                                    .section(section))
                            .collect(Collectors.toList()))
            .id("carousel")
            .addTo(this);
```
### SE
```
@EpoxyModelClass(layout = R.layout.model_section_horizontal)
public abstract class SectionModel extends EpoxyModelWithHolder<SectionModel.SectionHolder> {

    @EpoxyAttribute Section section;
    private SectionController sectionController = new SectionController();

    @Override
    public void bind(@NonNull SectionHolder holder) {
        super.bind(holder);
        LinearLayoutManager mLayoutManager = new LinearLayoutManager(App.get());
        holder.epoxy.setLayoutManager(mLayoutManager);
        holder.epoxy.setController(sectionController);
        sectionController.setData(section);
    }

    class SectionHolder extends BaseEpoxyHolder {
        @BindView(R.id.epoxy_horizontal_section)
        EpoxyRecyclerView epoxy;
    }
}
```
### Section Controller
```
    for(Component component : section.getComponents()){
        Data data = component.getData();
        if(component.getType() == Constants.COMPONENT_SMALL_IMAGE){
            new ComponentSmallImageModel_()
                    .id(component.getId())
                    .addTo(this);
        }else if(component.getType() == Constants.COMPONENT_NO_IMAGE){
            new ComponentNoImageModel_()
                    .id(component.getId())
                    .addTo(this);
        }
    }
```
### SCREEN 
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/10996313/56509744-765aab80-6530-11e9-820a-4f693c36d398.gif)

I cannot find how to connect between tab bar and carousel. 🔌
 I want to;
-  listen carousel position change and set tab bar selected item , when swipe carousel
-  change carousel visible item  with smooth scrolling, when click tabbar item https://github.com/airbnb/epoxy/issues/210 

- Another problem is recycler view height.
First carousel has only one item, but second carousel has 4. The length of the main epoxy is set according to the carousel that has maximum item.
Is there any possibility of dynamically set the height of the page when the carousel position changes?

**Comment by Oziomajnr** [comment]
Hi @hakansuluoglu , did you get any solution for this?

**Comment by hakansuluoglu** [comment]
> Hi @hakansuluoglu , did you get any solution for this?

No, I built the screen with ViewPager. I only used Epoxy at Fragment that is an item of ViewPager.  It was easier than creating this screen with Epoxy

- Header 
- Tab Bar 
- ViewPager (PagerAdapter)
  - Fragment 
      - RecyclerView
          - EpoxyModel
