### ISSUE TITLE
State save delay between fragment transactions

### ISSUE THREAD

**Issue by D-Fox** [airbnb/epoxy#736]
I want to save epoxy view state across fragment transaction (restore state when navigating back in backstack)
But i noticed that state save is triggered after about 2 second delay.
So when i am navigating back to screen with epoxy, state is restored only if there is 2 second gap between navigating forward and back.
If i navigate back under 2 seconds, the save state will be also triggered, but in that case, screen is already rendered with no saved state
(to show correct state, i must navigate forward and back again, or "scroll out" the view with state and than scroll back again to it).

repo: https://github.com/D-Fox/epoxy-save-state-delay-bug
epoxy versions: 3.3.0, 3.4.2

**Comment by elihart** [comment]
why do you have `controller.onSaveInstanceState(outState)` commented out in your example code?

the onsaveinstancestate callback is what saves the state, that callback is part of the fragment lifecycle and Epoxy has no control over it. it should be called immediately though, we've never had issues with delays

**Comment by D-Fox** [comment]
Fragment.onSaveInstanceState is not called when navigating between fragments, only the fragment's view is destroyed. Controller still lives...

I tried to call controller.onSaveInstanceState/onRestoreInstanceState in fragments onDestroyView/onViewCreated, but in onViewCreated i got:

`State cannot be restored once views have been bound. It should be done before adding the adapter to the recycler view.`

**Comment by elihart** [comment]
It sounds like you have an issue with the Android framework then? Epoxy doesn't have control over when onSaveInstanceState is called, you are going to run into the same thing trying to save any view state in this case.

Epoxy does save the view state to the EpoxyController when the view is recycled - if you want you can reuse the controller and make sure that all of the recyclerview views are recycled to force their states to be saved

**Comment by D-Fox** [comment]
Ok, thanks, i resolved it by clearing epoxy adapter in onDestroyView.

```
    override fun onDestroyView() {
        super.onDestroyView()
        epoxy.adapter = null
    }
```

This will recycle all views and save their state as you mentioned. Thanks again.

**Comment by elihart** [comment]
yes, beware that always using that breaks animations between fragments since the view is cleared immediately
