### ISSUE TITLE
EpoxyRecyclerView#getController

### ISSUE THREAD

**Issue by roiacult** [airbnb/epoxy#737]
i  wanted to bind a list of data in epoxyRecyclerView with databinding 
so i created DataBindingAdapter 
`@BindingAdapter("recyclerData")`
`fun <T> setRecyclerData(recyclerView: EpoxyRecyclerView,data : T){`
`//    val controller = recyclerView.getController()`
`}`
and i tried to retrieve controller to setData 
but i didn't find a getter method

**Comment by elihart** [comment]
Yes, there is no `getController()` function on `EpoxyRecyclerView`. There is a `setController` function and a `setModels` function, use one of those
