### ISSUE TITLE
Built Model not Changing in UI After Update in PagedListEpoxyController

### ISSUE THREAD

**Issue by StuStirling** [airbnb/epoxy#740]
I have updated the data provided by my DataSource using `invalidate` and passed this new `PagedList` into my Controller.

Adding and removing items works fine with the list being updated correctly.

On an update however, the `buildItemModel` function is called and I correctly return a new model using the same ID as the one already existing.

The model's `onBind` method is never called again after the initial addition.

How do I get model updates to take effect?

**EDIT** Added some more findings

I have now breakpointed the `PagedListModelCache` and can see that when an item in the `PagedList` changes, in the `updateCallback` of the `PagedListModelCache`, `onRemoved` is first called followed by `onInserted`. This would be fine I guess if this was reflected in the UI but its not. Obviously the model is being built but not removed/inserted into the adapter.

I then decided to check the `DiffResult` returned in the `modelBuildListener` passed in to the `controller` by adding a `ListUpdateCallback` to it. This resulted in none of the callbacks logging activity. Its as if nothing in the `DiffResult` had changed... 

**EDIT 2** Added more on the `DiffUtil.ItemCallback`

Here is my `DiffUtil.ItemCallback` that I pass in to the `PagedListEpoxyController`. This Seems to be outputting the correct logs with `getChangePayload` being called at the correct time.

```
itemDiffCallback = object: DiffUtil.ItemCallback<MessageItem>() {
            override fun areItemsTheSame(oldItem: MessageItem, newItem: MessageItem): Boolean {
                Timber.d("Checking new.id [${newItem.id}] == old.id [${oldItem.id}] ${oldItem.id == newItem.id}")
                return oldItem.id == newItem.id
            }

            override fun areContentsTheSame(oldItem: MessageItem, newItem: MessageItem): Boolean {
                Timber.d("Checking contents same for new [${newItem.id}] == old.id [${oldItem.id}] ${oldItem == newItem}")
                return oldItem == newItem
            }


            override fun getChangePayload(oldItem: MessageItem, newItem: MessageItem): Any? {
                Timber.d("Getting change payload for item: $newItem")
                return newItem
            }
        }

```
Am I missing something obvious?

**Comment by StuStirling** [comment]
I was not able to get the `Model` to be rebuilt. I spent way too long on this and decided in the end to just extend a `PagedListAdapter` and it worked first time.

**Comment by elihart** [comment]
If the new model was actually being built, and bind is not called, it points to your `MessageItem` not properly implementing equals/hashcode so that Epoxy does not recognize a change.

**Comment by 7-cat** [comment]
> If the new model was actually being built, and bind is not called, it points to your `MessageItem` not properly implementing equals/hashcode, or the `EpoxyModel` returned by your `buildItemModel` not implementing equals/hashcode, so that Epoxy does not recognize a change.
> 
> what was your EpoxyModel code?

save my day!
