### ISSUE TITLE
Losing nested scroll position when scrolling parent

### ISSUE THREAD

**Issue by loutry** [airbnb/epoxy#754]
Hello!

I have a vertical list composed of multiple nested horizontal lists. If I scroll my horizontal list and then scroll vertically my list, I sometime lost the scroll position of my nested horizontal list.

![device-2019-05-22-161930 2019-05-22 16_44_45](https://user-images.githubusercontent.com/4451893/58184690-e1271000-7cb1-11e9-85db-a8746dd0465f.gif)
*Losing nested position demo:
1- scrolling "A voir aussi" to Calls as first fully displayed item
2- scrolling "Sous couverture" to Strike Back as first fully displayed item
3- scroll down
4- scroll up: "A voir aussi" scrolling position is ok but "Sous couverture" isn't, it display as first item "Killing Eve"*

Here is my code: https://github.com/loutry/EpoxySample/commits/lost-nesting-position-on-rebind

I'm using `EpoxyRecyclerView` everywhere and I enable `saveViewState`.

I also followed the discussions https://github.com/airbnb/epoxy/issues/561 but I didn't successfully fix my problem.

**Comment by eboudrant** [comment]
Your `RowGroupView` is a `LinearLayout` and Epoxy is saving its state only (with `saveViewState = true`) . To restore scroll position you need to manually save/restore the state of the inner `EpoxyRecyclerView` from your `RowGroupView`.

As a quick fix try something like : 

```
class RowGroupView : LinearLayout {
    ...
    override fun onSaveInstanceState(): Parcelable? {
        return recycler.onSaveInstanceState()
    }

    override fun onRestoreInstanceState(state: Parcelable?) {
        recycler.onRestoreInstanceState(state)
    }
}
```

**Comment by loutry** [comment]
Hello! Thanks a lot for the tips, it makes so much sense. I did what you suggested here: https://github.com/loutry/EpoxySample/commit/1dd30c4d01d4e1b2390dfb0e0385e27486751568 but I'm still losing the scroll state :/

I tried to debug what was going on but I'm not sure what is going wrong. It looks like the `RowGroupView` isn't recycled correctly because I've never got data to restore my `RowGroupView` on `onBindViewHolder`. When it's working correctly it's because it's not recycled.

I add another branch to my repo with the source to be able to add log directly in the source code: https://github.com/loutry/EpoxySample/tree/lost-nesting-position-on-rebind-with-source

**Comment by eboudrant** [comment]
In your updated code I notice you are saving the Epoxy controller state but it do not contains any scroll position/offset. Your `RecyclerView` will have scroll/offset in its state. Have you tried to save the `recycler` state instead ?

**Comment by loutry** [comment]
I'm using an `EpoxyRecyclerView`. I thought it was doing it by itself as the recycler state `onSaveInstanceState()` and `onRestoreInstanceState(state: Parcelable?)` aren't public and looked like it was doing it.

I just added a commit to do it but still no luck :/ I added a custom `EpoxyRecyclerView` to be able to call the previous methods. I don't know if I missed something as this is really hacky ^^'

Thanks again for your help and time.

**Comment by eboudrant** [comment]
Here a quick fix for your sample app : 

```
    override fun onSaveInstanceState(): Parcelable? {
        super.onSaveInstanceState()
        return recycler.onSaveInstanceStateOpen() // Important to return the recycler save state
    }

    override fun onRestoreInstanceState(state: Parcelable?) {
        super.onRestoreInstanceState(null)
        recycler.onRestoreInstanceStateOpen(state)  // Important to set the recycler save state
    }
```

This is kind of hacky as it need to call save/restore state on `super` (else it crash). In code below the return from `super.onSaveInstanceState()` is ignored and it pass null to `super.onRestoreInstanceState(null)` ;) 

Also I did not knew methods where `protected` on `RecyclerView` ... in the past I usually save the state directly from the `LayoutManager` where methods are public.

In your case what you would have to do is create a custom `Parcelable` for saving the state of `RowGroupView` and the inner `RecyclerView`.

**Comment by eboudrant** [comment]
Also you may have some issue with the custom `RowLayoutManager` you are using. I tested and it works perfectly fine if I switch the layout manager back to a `LinearLayoutManager`.

**Comment by loutry** [comment]
Hi again! I end up fixing my problem by relying on `ViewGroup` and `ViewStub` as state in the documentation: https://github.com/airbnb/epoxy/wiki/Grouping-Models.

Here is the updated branch on the sample: https://github.com/loutry/EpoxySample/tree/viewstub

Our custom layout manager was indeed not compliant regarding state restoration but nothing that we can't manage on or own :)

Thanks a lot for your guidance and time!
