### ISSUE TITLE
How to show image slider with epoxy

### ISSUE THREAD

**Issue by Merka84** [airbnb/epoxy#755]
Hi @elihart 

First of all, thanks for the great work and this extremely helpful library which makes using RecycleView much faster and easier especially for complicated views.

I have a question. I see that in Airbnb app, you have used image sliders inside recycleView. I have the same requirement and I need to show imageSlider with those dots indicators inside a recycleView which is being produced by epoxy. Can you give me a hint on how to  do it with epoxy? 

Any suggestion is highly appreciated.

**Comment by elihart** [comment]
Hi, this is pretty easy to setup. It's just a Carousel with a separate dot
paging system.

The dot pager is completely separate from Epoxy and works with vanilla
RecyclerView. It is open sourced - I can track the link down later for you

**Comment by Merka84** [comment]
@elihart  
Thanks for your answer.
So the dot pager is another library.
I tried to make the imageSlider with carousel but it had the look and feel of a horizontal recycleView not an imageSlider, so I don't get how to create it. 
Can you post few lines of code as a sudo code?

**Comment by elihart** [comment]
The dot pager is https://github.com/rbro112/Android-Indefinite-Pager-Indicator

The feel is controlled by whatever snap helper is set on the recyclerview - the Carousel in Epoxy uses the standard RecyclerView snaphelper, but at Airbnb we created custom snap behavior that is too complicated to show in a few lines, but I am sure there are many examples of different snapping behavior and samples online

I'm not sure what is different about the look for you - but that is completely controlled by your View setup. We basically just use an ImageView though.

Overall Epoxy binds the data to views - but the snapping behavior and UI you're looking for is just standard RecyclerView setup that is unrelated to Epoxy

**Comment by Merka84** [comment]
Sorry for commenting again on a closed issue , but my problem is relevant to this question so I
 am posting it here.

I can show imageSlider using carousel and PagerSnapHelper. 
My problem is how to attach `IndefinitePagerIndicator` library to the same recycleView that holds images. I couldn't figure it so far. 
I tried using `CarouselModelGroup` as it was in `sampleApp` and I can't get the recycleView which shows my list of image to attach it to pagerIndicator.

**Comment by Merka84** [comment]
Finally I realized how to do it, using the hint provided in [this issue](https://github.com/airbnb/epoxy/issues/249).

**Comment by Pooja-Abbott** [comment]
@Merka84 Can you please your sample code i have the same requirement .
