### ISSUE TITLE
TypedEpoxyController throws java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by diousk** [airbnb/epoxy#756]
I'm using Epoxy version 3.4.2 and I extends **TypedEpoxyController** to build my models.

I also add a background handler for diffing and model build at application starts (onCreate of Application) like this

```
        val handlerThread = HandlerThread("async").apply {
            handlerThread.start()
        }
        Handler(handlerThread.looper).also {
            EpoxyController.defaultDiffingHandler = it
            EpoxyController.defaultModelBuildingHandler = it
        }
```

My data will soon be added into the controller after it was created

Sometimes, the buildModels method throw **ConcurrentModificationException**
and the call stack related is:

`com.airbnb.epoxy.TypedEpoxyController.buildModels (TypedEpoxyController.java:77)
com.airbnb.epoxy.EpoxyController$1.run (EpoxyController.java:276)`

I dig into the EpoxyController class, and I found that for the first time of buildModels(...), it will run on the main thread and later it runs on the handlerThread which I assign above

Is this design leading to the exception? how can I avoid this?

Thanks.

**Comment by elihart** [comment]
> for the first time of buildModels(...), it will run on the main thread and later it runs on the handlerThread which I assign above

this is intended, and isn't related to your crash.

The problem is likely that your data is not thread safe - you are changing it somewhere while the model building code is reading it. you must have thread safe data - use immutable lists and kotlin data classes

**Comment by diousk** [comment]
> > for the first time of buildModels(...), it will run on the main thread and later it runs on the handlerThread which I assign above
> 
> this is intended, and isn't related to your crash.
> 
> The problem is likely that your data is not thread safe - you are changing it somewhere while the model building code is reading it. you must have thread safe data - use immutable lists and kotlin data classes

Thanks for pointing that out, I'll check on the data side
