### ISSUE TITLE
Is this type of layout possible using Epoxy 

### ISSUE THREAD

**Issue by denimwho** [airbnb/epoxy#76]
The layout I want to make is this:
**-Header
-LinearLayoutManager(Horizontal)
-Header
-LinearLayoutManager(Vertical)**

The layout should be managed by single RecyclerView.

**Comment by elihart** [comment]
A LinearLayoutManager needs to be used 1 to 1 with a recyclerview, so you wouldn't do a layout like this with a single RecyclerView.

If I am understanding you correctly though, this type of layout should be very easy with Epoxy, and is something we do a lot (actually one of the main reason's I made epoxy).

You would have:

One vertical recycler view at the top level. Nested within that you would have

- A header 

- A horizontal recyclerview

- A header

-  Whatever other items you want in your vertical list

Let me know if that isn't clear. I was thinking about adding a sample activity for this pattern as well.

**Comment by denimwho** [comment]
I would be very much grateful if you could add a sample activity.
