### ISSUE TITLE
defaultModelBuildingHandler is not used the first time models are built

### ISSUE THREAD

**Issue by eygraber** [airbnb/epoxy#760]
I understand that this is intended behavior [from this issue](https://github.com/airbnb/epoxy/issues/756) but this should at least be documented more clearly so that blocking operations aren't done in `buildModels`.

**Comment by elihart** [comment]
Good idea, feel free to submit a PR to update the javadoc. I can update the wiki sometime

**Comment by elihart** [comment]
Closing for https://github.com/airbnb/epoxy/issues/882
