### ISSUE TITLE
How to change the switch when the model has not changed

### ISSUE THREAD

**Issue by beeete2** [airbnb/epoxy#761]
I am using Epxoy to create a form that includes Switch (Compat).
I want to switch back to the previous value without changing the model if the Switch is changed in a specific state.
The value of the switch on the screen has changed, but since the model has not been changed, the current model is sent to LiveData again in ViewModel.

```kotlin
// Fragment
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        vm.friend.observe(viewLifecycleOwner) {
            controller.setData(it)
        }
}

class Controller : TypedEpoxyController<Friend>() {
    override fun buildModels(data: Friend?) {
        data ?: return

        addSwitchItem {
            id("block")
            label(R.string.block_switch_label)
            checked(data.block) // data.block is Boolean
            checkedChangeListener { _, isChecked ->
                if (currentData?.block != isChecked)
                    vm.setBlock(isChecked)
            }
        }
    }
}
```

```kotlin
// ViewModel
private val _friend = MutableLiveData<Friend>()
val friend: LiveData<Friend> = _friend

fun setBlock(value: Boolean) {
    _toast.value = "Can not be changed."
    _friend.value = _friend.value?.copy() // model not changed
}

```

However, since the Boolean in the model has not been changed, the change detection function of Epoxy does not change the Switch.
How do I make switch changes when no model changes have been made?

The easy thing to think of is to use the following class that wraps Boolean.
```kotlin
data class SwitchValue(val checked: Boolean, private val timestamp: Long = System.currentTimeMillis())
```

In this case, the value of Switch will be changed because the timestamp will be different every time.

Please let me know if there is a more appropriate way.

example source code
[SwitcherFragment.kt](https://github.com/beeete2/android-epoxy-example/blob/a2845edd34a50adac806ddbd2f781d9e62aece82/app/src/main/java/com/beeete2/android/epoxyexample/ui/switcher/SwitcherFragment.kt)
[SwitcherViewModel.kt](https://github.com/beeete2/android-epoxy-example/blob/a2845edd34a50adac806ddbd2f781d9e62aece82/app/src/main/java/com/beeete2/android/epoxyexample/ui/switcher/SwitcherViewModel.kt
)

**Comment by elihart** [comment]
I'm not sure I completely understand your use case, but I would possibly think of a different approach - ideally the Epoxy model always completely matches the view model state, and changes to the view update those accordingly.

If you want to block the switch from being toggled, can you just disable it instead?

also be careful of setting listeners like this
```
checkedChangeListener { _, isChecked ->
                if (currentData?.block != isChecked)
                    vm.setBlock(isChecked)
            }
```

that lambda will capture the value of `currentData`, which will not update if that callback is using @CallbackProp

more at https://github.com/airbnb/epoxy/wiki/DoNotHash

**Comment by beeete2** [comment]
Thanks for your response.

In the application I'm making now, when the switch is operated, the API is accessed and if it is a specific result, the switch is restored.
The problem is that we are getting switch events (and swipes) with the onCheckedChangeListener.
At this time, the switch on the UI has already changed. The model does not change, so I have to switch back.

I will consider if you can disable the switch you proposed.

And thank you for your advice on how to use @CallbackProp.

**Comment by beeete2** [comment]
I'm still thinking about it, but I close this issue.
Thanks.
