### ISSUE TITLE
Access holder view value

### ISSUE THREAD

**Issue by sauyee333** [airbnb/epoxy#762]
Hi,
I have a list of checkbox displayed using epoxy and a submit button. Upon clicking submit button, I need to get the states of each checkbox to decide the next step. How do I access the holder.view values from epoxycontroller or epoxyadapter?

**Comment by elihart** [comment]
Yes, you can access them via `epoxyController.getAdapter().getBoundViewHolders()`.

Although I _do not_ recommend this approach, especially in your case. What you really should be doing is storing the state of each checkbox when it is toggled.
