### ISSUE TITLE
The annotation "ModelView" at the top of the custom view class makes my XML very slow

### ISSUE THREAD

**Issue by wdeo3601** [airbnb/epoxy#771]
抱歉我英语不太好...
在我的项目里，几乎所有的 epoxyModel 都是用的自定义 view 的方式定义的。随着项目越来越大，自定义 view 方式的 epoxyModel 也越来越多，这时候当我在写 xml 布局的时候，代码提示就变得很慢。。
```
@ModelView(defaultLayout = R.layout.exe_item_area_name) //this make my xml editor very slow
class AreaNameItem constructor(
    context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : ConstraintLayout(context, attrs, defStyleAttr) {

}
```
为此我写了一个 demo，当我把注解删除掉后，xml 编辑器就会变快了。  

[MultiModule.zip](https://github.com/airbnb/epoxy/files/3329577/MultiModule.zip)

can you help me?

**Comment by luozejiaqun** [comment]
I don't think this is the problem of Epoxy. In my test, any annotation at the custom view will slow the layout xml editor. It probably an issue of the android studio.

**Comment by wdeo3601** [comment]
I have created an issue in the google issue tracker  
https://issuetracker.google.com/issues/136198603

**Comment by wdeo3601** [comment]
Now androidstudio 3.5 has fixed this bug。  
![image](https://user-images.githubusercontent.com/22436965/63396306-3087f400-c3f9-11e9-8944-444dba5593f2.png)
this is the release note: https://developer.android.com/studio/releases/index.html?utm_source=android-studio
