### ISSUE TITLE
Usage of payload within Epoxy

### ISSUE THREAD

**Issue by j-roskopf** [airbnb/epoxy#774]
Hey!

I am trying to solve a bug I'm encountering that I don't believe has anything to do with Epoxy, but the bug is my RecyclerView's item decoration is not applied after I call `setData()`

I believe [this](https://stackoverflow.com/questions/47342034/recyclerview-itemdecoration-doesnt-update-after-item-is-removed-from-recyclervi) SO link pretty accurately describes the problem I'm encountering

The top answer in that SO link is to call `notifyItemChanged()` passing in a payload. 

How do I accomplish that with Epoxy?

Thank you!

**Comment by elihart** [comment]
Sounds like you're on the right track - Epoxy delivers a payload change and uses `notifyItemChanged` anytime a model is updated.

You can force this by having a property/attribute on a model that you change when you rebuild models - you don't necessarily have to use the property - you could do something like set the current clock time to force it to always rebind when it is rebuilt, although that wouldn't be as ideal as being precise about when it is updated

**Comment by j-roskopf** [comment]
Perfect - thank you!
