### ISSUE TITLE
setItemSpacingPx is final in 3.7.0

### ISSUE THREAD

**Issue by ovUdemy** [airbnb/epoxy#779]
Just upgraded from 3.3.0 and noticed the class that had `setItemSpacingPx` was converted to Kotlin. The method went from public to final so it cannot be overridden. We used it to set a custom decorator to only add item decoration padding to bottom and right. Is there a work around?

**Comment by elihart** [comment]
You can submit a PR to change the function to be open, or you can change your approach to not override that function
