### ISSUE TITLE
Can't smooth scroll / fling scroll with Adapter / Controller

### ISSUE THREAD

**Issue by AkshayChordiya** [airbnb/epoxy#788]
I have tested adding various models using `EpoxyController` which works pretty well. But if I try to fling scroll it doesn't scroll naturally. It scrolls a bit and stops and I need to scroll again. 

It's not a major issue but feels like an "usability" issue where the scrolling experience is not so awesome and I'd love to know how it can be improved

I even tested with `EpoxyAdapter` but the results were the same.

**Comment by AkshayChordiya** [comment]
I'm not exactly sure if it's my setup or if there is a configuration to tweak it. I'll try to add a video / gif to explain the behaviour. 
Take an example of a normal list view -> you scroll smoothly till the last item but in my case it does smoothly scroll till a certain item [making it feel like it's end of list] but if you scroll more there are more items below; the same applies for scrolling up.

**Comment by elihart** [comment]
There is nothing Epoxy can do that would cause this behavior, this is at the RecyclerView level.

Only exception is if you're using the PagedList epoxy controller and didn't prefetch enough data

**Comment by AkshayChordiya** [comment]
Here's the preview of how the scrolling looks:
https://drive.google.com/file/d/1A82AV_UbGBhbyLqrEADLFgufK4uWOeR0/view?usp=sharing

Everywhere else it scrolls pretty good but not in this case. The setup is `EpoxyModelGroup` [the card] containing `EpoxyModel` the date and the vertical view.
It scrolls well but you need to apply pressure every time you want to scroll. 

I'd love to know if it's something I am doing wrong 🤔

**Comment by AkshayChordiya** [comment]
Turns out we were doing crazy stuff on our end 😅 
The entire content of the activity was wrapped in `ScrollView` 🤦‍♂ by some base class _double facepalm_

So I'm closing the issue. Thank you for your time.
