### ISSUE TITLE
Support for notifyModelChanged with payload in EpoxyController

### ISSUE THREAD

**Issue by AkshayChordiya** [airbnb/epoxy#792]
Initially we started using `EpoxyController` as recommended but soon realized that one of use case is not feasible with the `EpoxyController` since Controller doesn't expose the methods for notifying changes and relies on diffing [which in my opinion is perfect for most use-cases].

But we needed to notify a model with a small payload due to which we switched `EpoxyAdapter` which btw was pretty straight forward with little care to handle the cases which controller handled automatically for us.

I'd love to use `EpoxyController` but with something like `notifyModelChanged` with payload. I'd like to know why it isn't currently there or what's the history behind it.

**Comment by elihart** [comment]
Any time you use an adapter that supports manual change notifications it opens possibility for user error, which was important for us to absolutely eliminate.

You can still pass payloads to models with EpoxyController, you just change a property on the model and the new value will be delivered.

**Comment by AkshayChordiya** [comment]
Yeah that's very true. As soon as we switched to `EpoxyAdapter` -> the migration was easy but it bought in so many errors.
Can you share a example of passing the payload to models with Controller?

**Comment by elihart** [comment]
See https://github.com/airbnb/epoxy/wiki/Epoxy-Models#view-updates

It depends on how you have created your model.

**Comment by AkshayChordiya** [comment]
Ah that should work. Let me try that and close the issue after that

**Comment by AkshayChordiya** [comment]
I tested and it seems to work and I get notified in `EpoxyModel#bind(T view, EpoxyModel<?> previouslyBoundModel)` but is there a way to invoke `bind(T view, payloads: MutableList<Any>)`

**Comment by AkshayChordiya** [comment]
I'm closing the issue. Because it solves the query which I had. Thank you.
