### ISSUE TITLE
Decorator for Controllers?

### ISSUE THREAD

**Issue by mediavrog** [airbnb/epoxy#795]
Hi, 
first of all thanks for all the efforts on epoxy!

I recently integrated epoxy into a prototype of ours and came across a requirement which I am not quite sure how to best tackle with epoxy.

We have a big list of items (news) and would like to inject some ads per some rules into that list. Now the list is using a `PagedListEpoxyController` (only appends new items). In order to separate the news from the ads code, I realized a RecyclerView Adapter wrapper before migrating to epoxy.

Now I was thinking of how to best address the dynamic injection of ads:

1) Using an `Interceptor`: I tried that at first since it seemed like the simplest solution, but ran into issues when updating the list (refresh, not append). Without much research I figured this approach might be too simplistic to work stable.

2) Using the old style adapter wrapper. After looking at the [cyclic example](https://github.com/airbnb/epoxy/wiki/Cyclic-Adapters) I toyed with the idea of reusing much of the old logic of injecting ads through a decorated adapter. The downside is that I would have to use my own ViewHolder binding logic and won't be able to use the nice EpoxyModels for the ads. I would like to go all in epoxy to keep the developer experience for my team consistent

3) Subclassing or Decorating my custom PagedListEpoxyController. I have not explored that approach thoroughly, but was thinking it might be possible to decorate my paged adapter, delegating the `buildItemModel` method to the original one, and then overwriting `addModels` to inject the ads into the list. I would have to handle the ads positions somehow outside the adapter and react to list/model updates.

Which approach would you recommend me to explore further, given the architecture and intent of epoxy? Thanks in advance for your guidance.

**Comment by elihart** [comment]
For `PagedListEpoxyController` specifically, the intention is that `addModels` should be overridden to add custom models, or otherwise modify the models list in whatever way is needed.

I think this should meet your needs, and is what we intended when creating that class.

**Comment by mediavrog** [comment]
Thanks a lot for your swift response. I will explore this approach further
