### ISSUE TITLE
Wish: Ignoring scroll events for particular model

### ISSUE THREAD

**Issue by AkshayChordiya** [airbnb/epoxy#796]
I'm looking at ignore vertical scroll events of the RecyclerView for a particular model because the model is a custom view handling it's own touch events.

Is there already a straightforward way available from Epoxy for this or a better way to do this? My guess is overriding the `EpoxyRecyclerView` and then intercepting the events.

**Comment by elihart** [comment]
This doesn't seem related to Epoxy - this is happening at the View layer, which Epoxy doesn't control so much.

It's possible it could be an add on to Epoxy, but it is such a rare use case that it is probably better for you to implement it yourself via the RecyclerView

**Comment by AkshayChordiya** [comment]
Yeah it's a rare case. I did it something like this:
Activity -> RecyclerView -> Adapter (get RV when it’s attached) -> Epoxy Model -> View
I have passed the RV to View to intercept touch events.

I'd love to know how bad idea it is 😅
