### ISSUE TITLE
Carousel setDefaultGlobalSnapHelperFactory does not work 

### ISSUE THREAD

**Issue by misaelemc** [airbnb/epoxy#799]
I'm trying to remove the SnapHelper in my carousel but it does not work, I have an issue with that, my first item of the carousel when I do scroll horizontal and come back to the first position part of the item is hiding. 

the item has this configuration -> @ModelView(autoLayout = ModelView.Size.WRAP_WIDTH_MATCH_HEIGHT)

and my carousel has this configuration to show num of views -> 

carousel.numViewsToShowOnScreen = 4.4f

I would like to know how can I fix that, to avoid this behavior

**Comment by saurabhTothenew** [comment]
Hi misaelemc, May I know how did u resolve this issue?, I am facing the same.
