### ISSUE TITLE
Simplify KotlinEpoxyHolders bind method?

### ISSUE THREAD

**Issue by mediavrog** [airbnb/epoxy#809]
Hi again,

we are in the process of code review around epoxy. As we use Kotlin, a colleague pointed out to me that the `KotlinEpoxyHolder`s `bind` method could be simplified to just use the Kotlin `by lazy`

https://github.com/airbnb/epoxy/blob/master/kotlinsample/src/main/java/com/airbnb/epoxy/kotlinsample/helpers/KotlinEpoxyHolder.kt#L20

The result would look as simple as
```kotlin
protected fun <V : View> bind(id: Int): Lazy<V> = lazy {
        view.findViewById(id) as? V ?: error("View ID $id not found.")
    }
```

Are there any obvious drawbacks of doing this we haven't considered? Why was the custom Lazy implementation used over the native lazy?

The only things so far I can think of would be that at the time Kotlin did not provide `lazy` or that this implementation introduces potential memory leaks with the initializer.

**Comment by elihart** [comment]
Kotlins built in `lazy` should work fine. Only caveat is by default it does synchronization which adds unnecessary overhead here. So use `lazy(mode = LazyThreadSafetyMode.NONE)` instead - we know views will only be bound on the main thread by RecyclerView. This "none" mode implementation is basically the same as what I have.

There is no good reason I didn't use that to begin with. I think I was diving into Kotterknife implementations at the time and just had the code handy - or maybe I originally wanted to support unbinding (which isn't necessary).

Oh, I just thought of one real reason, the only way to give a clear error message with the property name is to use a custom delegate:
```
               "View ID $id for '${prop.name}' not found.")
```

Notice here we can give the property name in addition to the id.

**Comment by mediavrog** [comment]
Thanks for the quick heads-up.
Yes, we actually also set the thread mode to NONE and also noticed that the error message will be  less clear in the case of native lazy.
We will go with the native anyways since it is less code to maintain and for new members to understand.

Thanks
