### ISSUE TITLE
[Question] Does epoxy support search view, context action mode, view pager 2

### ISSUE THREAD

**Issue by kaushalyap** [airbnb/epoxy#810]
I am on the way to pick RecyclerView library for a project. I want to know whether the epoxy could do following things

- support search view
- contextual action bar support
- being able to use with ViewPager 2

Thank you in advance!

**Comment by elihart** [comment]
Anything that works with RecyclerView is supported by Epoxy

**Comment by kaushalyap** [comment]
@elihart  Some examples added to the wiki would be highly appreciated. 

Please also think about writing new blog since [this post](https://medium.com/airbnb-engineering/epoxy-airbnbs-view-architecture-on-android-c3e1af150394#.xv4ymrtmk) is outdated
