### ISSUE TITLE
Carousel background color

### ISSUE THREAD

**Issue by dbof10** [airbnb/epoxy#820]
![Screenshot 2019-09-06 at 10 05 22 PM](https://user-images.githubusercontent.com/10725747/64434120-7976c280-d0f2-11e9-9d6a-0ded0bd1abe2.png)

This is my Carousel. Is the any way to set background color instead of setting its parent view?

**Comment by reavcn** [comment]
Hi @dbof10 ,

if I got you right, you can use **onBind** to set a background color for your carousel.

```
carousel {
    id(Model.TAG + "carousel")
    onBind { _, view, _ ->
        view.setBackgroundColor(ContextCompat.getColor(activity!!, R.color.YOUR_COLOR))
    }
    withModelsFrom(...) { ... ->
        // your models here
    }
}

I hope this answer your question!

**Comment by elihart** [comment]
while it works, I don't recommend using the `onBind` callback to style views. View styling should be done within the view, or with something like Paris (https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)).

In terms of carousels and color styling go though, this is no different from how a normal recyclerview works. a model's `bind` function is equivalent to a vanilla RecyclerView adapter's onBindViewHolder, and all styling can be done there
