### ISSUE TITLE
want: int getModelPositionByStableId(long id) in EpoxyAdapter

### ISSUE THREAD

**Issue by conanchen** [airbnb/epoxy#83]
I want to update models by model id as addModels() will throw "java.lang.IllegalStateException: Two models have the same ID. ID's must be unique! ",  can we have this method in EpoxyAdapter? 

    protected int getModelPositionByStableId(long id) {
        int size = models.size();
        for (int i = 0; i < size; i++) {
            if (models.get(i).id() == id) {
                return i;
            }
        }

        return -1;
    }

**Comment by elihart** [comment]
`addModels` will only throw that exception if you are adding duplicate models. You should make sure you either remove an existing model before adding a new one with the same id, or instead update the existing model and let the auto diffing figure out what changed. If you would like to paste the code of your whole adapter I can take a look and make sure you implement it correctly.

I don't see `getModelPositionByStableId` being useful to most people at this time, so I don't think it needs to be added to the library. Feel free to add it to your own adapter as a helper method though.
