### ISSUE TITLE
 set setSpanSizeLookup  don't work 

### ISSUE THREAD

**Issue by AttITuder** [airbnb/epoxy#832]
set setSpanSizeLookup  don't work 。
 GridLayoutManager layoutManager = new GridLayoutManager(getContext(), 6);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setController(viewModelController);
        layoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return 1;
            }
 });
In fact, it still shows six columns.

**Comment by elihart** [comment]
your expectations and understanding of grid layouts are wrong.

You are telling the grid layout to have 6 columns, and via getSpanSize you are saying that each model should take up one column.
