### ISSUE TITLE
section headers does not move on drag

### ISSUE THREAD

**Issue by kaushalyap** [airbnb/epoxy#839]
I was trying out epoxy, in order to pick it for my app. But I encountered an issue when dragging items up and down. In my recyclerview I have two types of views section headers and items. when I drag  item to be the first place of the another sections header, header item does not move and give room to moving item. It seems to me that only normal items get moved but not header items.

![section header does not move](https://user-images.githubusercontent.com/24698778/66183385-62e26d80-e696-11e9-835d-d6eb3fb693e3.gif)

**Why section header item not moving?** Here is [sample repo](https://github.com/kaushalyap/epoxy-sectioned)

**Comment by kaushalyap** [comment]
paging @elihart

**Comment by elihart** [comment]
```
        EpoxyTouchHelper.initDragging(taskController)
            .withRecyclerView(binding.rvTaskList)
            .forVerticalList()
            .withTarget(ItemTaskBindingModel_::class.java)
            .andCallbacks(object : EpoxyTouchHelper.DragCallbacks<ItemTaskBindingModel_>() {
                override fun onModelMoved(
                    fromPosition: Int,
                    toPosition: Int,
                    modelBeingMoved: ItemTaskBindingModel_?,
                    itemView: View?
                ) {
                    TaskController.moveTasks(fromPosition, toPosition)
                }
            })
```

You have specified the target to only be ` .withTarget(ItemTaskBindingModel_::class.java)`. You must include the header model as a target if you want that to be draggable too, using `withTargets` to specify multiple.

Please read the javadoc before asking questions.

**Comment by kaushalyap** [comment]
@elihart thanks for answering, forgive me for bothering. I asked here because last time I asked an another question on SO, it did not get answered, [there are lots of unanswered question on SO with Epoxy tag.](https://stackoverflow.com/questions/tagged/epoxy?tab=Unanswered)
