### ISSUE TITLE
Issue in Generating helper classes with @EpoxyAttribute

### ISSUE THREAD

**Issue by shakil807g** [airbnb/epoxy#84]
public class HeaderModel extends EpoxyModel<HeaderView> 
{
  @EpoxyAttribute String title;
  @EpoxyAttribute String subtitle;
  @EpoxyAttribute String description;
  @EpoxyAttribute(hash=false) View.OnClickListener clickListener;

  @LayoutRes
  public int getDefaultLayout() {
    return R.layout.view_model_header;
  }

  @Override
  public void bind(HeaderView view) {
    view.setTitle(title);
    view.setSubtitle(subtitle);
    view.setDescription(description);
    view.setOnClickListener(clickListener);
  }

}

**Having added this property @EpoxyAttribute(hash=false) View.OnClickListener clickListener;   it still added in hashCode of generated class**

**Comment by elihart** [comment]
It is intended to still be added, however the hashed value only includes true/false for if the object is null or non null. It doesn't actuall call `hashcode` on the value of the field. This behavior was changed a few weeks ago, I can update the readme to be more clear.
