### ISSUE TITLE
Handle configuration changes

### ISSUE THREAD

**Issue by mediavrog** [airbnb/epoxy#844]
Hi, I am using the PagedListEpoxyController and wondered what would be the best approach to handle config changes in my models.
Should I override the equals/hashcode method to include some configuration qualifier (landscape/portrait)?

The goal is to slightly change the appearance of models in landscape.

**Comment by elihart** [comment]
I wouldn't override the equals/hashcode methods. You should specify an additional prop like `isLandscape` on the models you want to style differently in that case.

**Comment by mediavrog** [comment]
Thanks for your reply. But if I annotate that prop with `@EpoxyAttribute` to make it part of the hashCode, I won't be able to change it after the model has already been bound to the view right? (the error message from epoxy lib mentions that and as alternative one should use interceptors)

I also tried a computed value using kotlins dynamic getter, but that cannot be annotated with EpoxyAttrbute.

```
private val supportsLargeItem: Boolean
        get() = some_dynamic_calculation
```

<img width="610" alt="Screen Shot 2019-10-17 at 8 55 07" src="https://user-images.githubusercontent.com/160785/66967442-f155e680-f0bb-11e9-99ce-61a11ed1bbb1.png">

**Comment by elihart** [comment]
You should use a property to represent landscape, and request a rebuild of all models when configuration changes. The views will be rebound with any properties that changed (assuming you are using EpoxyController which you should be). See the wiki for details on partial rebinding.

**Comment by mediavrog** [comment]
Hey, I must be missing some really obvious thing.

I tried the following now:

```
// Fragment
override fun onConfigurationChanged(newConfig: Configuration) {
  super.onConfigurationChanged(newConfig)
  adapter.requestModelBuild()
}

// recalc metrics on orientation change
// this will also execute on `requestModelBuild`
adapter.addInterceptor { models ->
  val isLandscape = checkIsLandscape()
  models.map { it.isLandscape = isLandscape }
}

// Model (EpoxyModelWithHolder
@EpoxyAttribute
var isLandscape: Boolean
```

Upon rotation, the app crashes with 

```
com.airbnb.epoxy.ImmutableModelException: The model was changed between being bound and when models were rebuilt Position: 2 Model: MyModel_{....{id=6875175298939324926, viewType=2131492969, shown=true, addedToAdapter=false}
    
    Epoxy attribute fields on a model cannot be changed once the model is added to a controller. Check that these fields are not updated, or that the assigned objects are not mutated, outside of the buildModels method. The only exception is if the change is made inside an Interceptor callback. Consider using an interceptor if you need to change a model after it is added to the controller and before it is set on the adapter. If the model is already set on the adapter then you must call `requestModelBuild` instead to recreate all models.
```

Just to make sure: When you say `use a property`, do you mean a member variable of the model, which is _not_ annotated with `@EpoxyAttribute`?

**Comment by elihart** [comment]
What you are doing looks correct, the crash is part bug and part feature.

Normally models shouldn't be changed - the interceptor is an exception case where changes are allowed. However, models are also not normally reused, and the paged list is an exception to that as well. The model reuse combined with the interceptor creates a scenario that Epoxy was not designed for.

I started working on something that would allow models to be reused and updated in an interceptor (https://github.com/airbnb/epoxy/pull/846), but a problem remains that the differ would then not be able to detect that the model changed and would not rebind the update.

While it would be nice, and I think reasonable, to update reused models in an interceptor we would need to figure out how to communicate that change to the differ. Shouldn't be too hard, but maybe a bit messy.

In the meantime, you should be able to use `requestForcedModelBuild` to clear the model cache and rebuild all models. To avoid the crash you may also have to not use the interceptor and instead set the property directly on each model when you create them.

**Comment by mediavrog** [comment]
Thank you. I will investigate a solution that suits our needs with the info you provided.

**Comment by mediavrog** [comment]
Just got around to address this in our codebase. So the actual change was pretty straightforward in the end (not using interceptors). Below code *illustrates* the approach eli suggested and we took (not production code).

```kotlin
// Fragment
override fun onConfigurationChanged(newConfig: Configuration) {
    super.onConfigurationChanged(newConfig)
    adapter.onConfigurationChanged(newConfig)
}

// Adapter (PagedListEpoxyController)
fun onConfigurationChanged(newConfig: Configuration) {
    currentOrientation = newConfig.orientation
    requestForcedModelBuild() // needed since cache is aggressive for paged lists
}

..

override fun buildItemModel(currentPosition: Int, item: Item<Any>?): EpoxyModel<*> =
    SomeModel_()
        .id("someid")
        .item(item)
        .orientation(currentOrientation)
```

Thanks @elihart
