### ISSUE TITLE
`defaultValue` for non-primitives in `Kotlin` doesn't work

### ISSUE THREAD

**Issue by qbait** [airbnb/epoxy#858]
Hey,
I can't use `const` for non-primitives in `Kotlin` so I'm setting default color in my view  like
```
@ModelProp(defaultValue = "DEFAULT_EVENT_COLOR")
    fun setColor(color: EventColor) {...}

    companion object {
        val DEFAULT_EVENT_COLOR = none
    }
```

However, I'm getting `Default values for view props must be static, final, and not private.`

I've tried as well
```
    companion object {
        public final val DEFAULT_EVENT_COLOR = none
    }
```
without success.

How are you dealing with that case in `Kotlin`?

**Comment by elihart** [comment]
You need to use @JvmStatic most likely.

Also generally you shouldn't be using the `defaultValue` parameter for Kotlin. The annotation processor supports handling default param values in kotlin so just do this
```kotlin
fun setColor(color: EventColor = myDefault) {...}
```

**Comment by qbait** [comment]
Brilliant! I tried default values first, but I got
`java.lang.IllegalStateException: A value is required for setColor`
My Epoxy version was `3.2.0` though

With `3.8.0`
```
    @JvmOverloads
    @ModelProp
    fun setColor(color: EventColor = blue) {...}
```
works like a charm.

Thank you @elihart

**Comment by svrlopatrik** [comment]
`@JvmField` annotation works for me.

```
companion object {
        @JvmField
        public final val DEFAULT_EVENT_COLOR = none
}
```
