### ISSUE TITLE
Question: What files should be moved into a module in order to achieve incremental builds?

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/epoxy#859]
This is more of a community question, and not really an issue. Incremental annotation processing seems like it might be added soon (https://github.com/airbnb/epoxy/issues/423)... but until that's done maybe someone can outline how to move epoxy to another module?

When using Epoxy I get a message saying:

`w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.airbnb.epoxy.EpoxyProcessor (NON_INCREMENTAL).`

I read on reddit that you can get around this by just moving epoxy into it's own module. I haven't worked with multiple modules, but I'm curious if anyone has done this or know what classes/files would have to go into another module.

**Comment by elihart** [comment]
To get the benefit you are talking about you would move all files with epoxy annotations on them, since these are used in the annotation processor.

Generally this would be all annotated epoxy models, views, databinding layouts, etc

**Comment by ColtonIdle** [comment]
Thanks. I will try this out eventually.
