### ISSUE TITLE
How to retrieve Epoxy view's id in `onClickListener`

### ISSUE THREAD

**Issue by qbait** [airbnb/epoxy#862]
I'm declaring my view like:

```
            checkedTextRow {
                id(it.serializedName)
                clickListener { v ->
                    val idThatIsSerializedName = (v as CheckedTextRow).epoxyId
                }
```

I would like to retrieve this id in `onClickListener`. How to do that? In the debugger, I can see only view id that is `Int`.

**Comment by elihart** [comment]
Can you use https://github.com/airbnb/epoxy/wiki/Epoxy-Models#click-listeners?

**Comment by qbait** [comment]
@elihart Thank you for the quick answer!
I've just tried to use it. I'm guessing that I can retrieve epoxy id that is `String` from `model`. However, I can't see it there.

```
            checkedTextRow {
                id(it.serializedName)
                clickListener { model, parentView, clickedView, position ->
                    val idThatIsSerializedName = model.epoxyId
                }
            }
```

Is there a lookup table that takes id in long and returns `string` id or something like that?

**Comment by elihart** [comment]
There is no way to get the original string that was used to create the id - you'll have to use a different approach.
