### ISSUE TITLE
Visibility events not triggering in fragment's onResume

### ISSUE THREAD

**Issue by MigoTiti** [airbnb/epoxy#863]
So, i have a tabview where the second tab has a EpoxyRecyclerView with a visibility listener attached to it. When the main activity starts, the controller on the second fragment builds and the visibility callbacks are called, with 0% visible height and width to every item. When i switch to second tab, the visibility callbacks don't get called unless i scroll the recyclerview. When i scroll it, the callbacks are called with the right values for every item. Is it possible to force call the callbacks in the fragment's onResume method or bind the tracker to the fragment's lifecycle?

**Comment by eboudrant** [comment]
Unfortunately the `RecyclerView` have no knowledge of the fragment/activity lifecycle and I am not sure we want to add a dependency on Androidx Lifecycle in Epoxy. 

What you can do is make a call to`epoxyVisibilityTracker.requestVisibilityCheck()` from the callback you have when the fragment that host your `EpoxyRecyclerView` become visible.

**Comment by MigoTiti** [comment]
Ahhhhh thanks, i didn't see this method at once but i figured out i didn't have the most recent lib version, and my AS didn't warn me. Anyway, thanks for the assistance.

**Comment by xiaoyuin** [comment]
We also had this issue and we tried using `requestVisibilityCheck` in `onResume` directly but it couldn't detect any epoxy model as visible, from debugging step by step we found out that during the execution of `onResume` all the models internally were recognized as still invisible. 

We have to use a `postDelayed(300) { visibilityTracker.requestVisibilityCheck() }` in `onResume` hack to make sure it calculates the visibility correctly, but this solution is very hacky and not reliable. Could you pls have another look at this issue or propose some better solution?
