### ISSUE TITLE
Unable to generate variable getter and setter methods

### ISSUE THREAD

**Issue by turingking** [airbnb/epoxy#867]
layout:

<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

        <import type="android.view.View" />

        <variable
            name="name"
            type="String" />

        <variable
            name="imageUrl"
            type="String" />

        <variable
            name="sel"
            type="Boolean" />

        <variable
            name="click"
            type="View" />
    </data>

    <FrameLayout
        android:layout_width="140pt"
        android:layout_height="88pt"
        android:onClick="@{click}"
        android:orientation="vertical">

        <ImageView
            android:id="@+id/ivImage"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:imageUrl="@{imageUrl}" />

    </FrameLayout>
</layout>

package-info.java:

```java
@EpoxyDataBindingLayouts({R.layout.view_model_article,R.layout.view_model_atten_trade_type})
package cn.tradewith.bigdesk.ui.viewmodel.epoxy;
import com.airbnb.epoxy.EpoxyDataBindingLayouts;
import cn.tradewith.bigdesk.R;
```
TradeTypeController:
```java
class TradeTypeController : TypedEpoxyController<List<TradeType>>() {

    override fun buildModels(data: List<TradeType>) {



        for (type: TradeType in data) {
            ViewModelAttenTradeTypeBindingModel_()
                .id(type.id)
                .name()  //Can't find this method
                .addTo(this)
        }

    }
}
```
Is there a problem with my use?
Thanks Reply

**Comment by elihart** [comment]
Can you share the complete code of `ViewModelAttenTradeTypeBindingModel_`?

**Comment by turingking** [comment]
@elihart 
I opened AndroidStudio this morning and the problem disappeared.
I just shut down Windows and then reopen Windows and Android Studio
