### ISSUE TITLE
Unable to check RecyclerView.NO_POSITION

### ISSUE THREAD

**Issue by shakil807g** [airbnb/epoxy#87]
As per RecyclerView Animations and Behind the Scenes (Android Dev Summit 2015)
https://youtu.be/imsr8NrIAMs?t=36m2s you should check the ViewHolder's position before triggering an onItemClick that was pass in Model   and how to properly handle item click  is this correct way ??

    public class ButtonModel extends EpoxyModelWithHolder<ButtonModel.ButtonHolder> {

    @EpoxyAttribute
    String text;
    @EpoxyAttribute(hash = false)
    ItemClickListener itemClickListener;

    @Override
    protected int getDefaultLayout() {
        return R.layout.model_button;
    }

    @Override
    public void bind(final ButtonHolder holder) {
        super.bind(holder);

        holder.container.setBackgroundResource(R.color.pink_200);
        holder.container.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                itemClickListener.itemClick(holder.container, text);
            }
        });
        holder.text.setText(text);

    }

    @Override
    public int getSpanSize(int totalSpanCount, int position, int itemCount) {
        return 1;
    }

    @Override
    protected ButtonHolder createNewHolder() {
        return new ButtonHolder();
    }

    static class ButtonHolder extends BaseEpoxyHolder {

        @BindView(R.id.text)
        TextView text;
        @BindView(R.id.container)
        FrameLayout container;
    }

      public interface ItemClickListener {
          void itemClick(View parent, String text);
       }
      }

**Comment by elihart** [comment]
Your model looks pretty good, but also add
```
@Override
        public void unbind(ButtonHolder holder) {
            super.unbind(holder);
            holder.container.setOnClickListener(null);
        }
```

Unbind is called when the view is recycled (which is when position is set to NO_POSITION) so removing the click listener should guarantee you don't register late clicks. We do this, and have never had a problem.

**Comment by elihart** [comment]
Feel free to reopen this if you have more questions, but I'll close it for now.
