### ISSUE TITLE
why epoxy caching views

### ISSUE THREAD

**Issue by beigirad** [airbnb/epoxy#875]
We're currently started using epoxy for the whole of our application.

On a screen that has just one item. This item generated from an `xml` layout that has data binding. in this fragment, I use a separated controller that initialize and bind it to EpoxyRecycelerView.

but after destroying this fragment (goes back) and recreating again (opening this screen), everything is initialized, but this view will remain in memory (as cache) and didn't reinitialize.

and fixing this problem when I clear recycledViewPool in `onDestroyView()`:
```
epoxyRv.recycledViewPool.clear()
```

What happens? 
Why our views did not destroy after destroying view?
Should I clear everywhere for every instance of epoxyRecyclerView?

**Comment by beigirad** [comment]
> We're currently started using epoxy for the whole of our application.
> 
> On a screen that has just one item. This item generated from an `xml` layout that has data binding. in this fragment, I use a separated controller that initialize and bind it to EpoxyRecycelerView.
> 
> but after destroying this fragment (goes back) and recreating again (opening this screen), everything is initialized, but this view will remain in memory (as cache) and didn't reinitialize.
> 
> and fixing this problem when I clear recycledViewPool in `onDestroyView()`:
> 
> ```
> epoxyRv.recycledViewPool.clear()
> ```
> 
> What happens? Why our views did not destroy after destroying view?

**Comment by beigirad** [comment]
Is any body here?

**Comment by elihart** [comment]
Read the javadoc in `EpoxyRecyclerView` - it is clearly explained there.
```
A single view pool is automatically shared between all EpoxyRecyclerView instances in the same activity. This should increase view recycling potential and increase performance when nested RecyclerViews are used.
```

**Comment by beigirad** [comment]
Thanks for your answer. I want to disable it. Can I limited this view-pool scope to a fragment, not an activity?
It causes a lot of memory-leaks part of its document. I'm disposing all object as below but did not affects.
```
override fun onDestroyView() {
        epoxyRv.adapter = null
        epoxyRv.setRecycledViewPool(null)
        super.onDestroyView()
}
```

**Comment by elihart** [comment]
Look through the available methods on EpoxyRecyclerView. For example, there is `shouldShareViewPoolAcrossContext`.
