### ISSUE TITLE
Clarify in wiki that Asynchronous Support is synchronous first time building models 

### ISSUE THREAD

**Issue by mwajeeh** [airbnb/epoxy#882]
In **Asynchronous Support** section https://github.com/airbnb/epoxy/wiki/Epoxy-Controller#asynchronous-support it is not mentioned that `requestModelBuild` will run synchronously if called for the first time on a new instance of epoxy controller. Took me a while to figure out why my controller was blocking the UI. This information is buried deep in the documentation of `requestModelBuild()`.

It would be worth adding in the wiki as well along with a tip to use `requestDelayedModelBuild(0)` if you want to do asynchronous building for the first time too immediately.

Following is javadoc for `requestModelBuild()`:

/**
   * Call this to request a model update. The controller will schedule a call to {@link
   * #buildModels()} so that models can be rebuilt for the current data. Once a build is requested
   * all subsequent requests are ignored until the model build runs. Therefore, the calling code
   * need not worry about calling this multiple times in a row.
   * <p>
   * The exception is that the first time this is called on a new instance of {@link
   * EpoxyController} it is run synchronously. This allows state to be restored and the initial view
   * to be draw quicker.
   * <p>
   * If you would like to be alerted when models have finished building use
   * {@link #addModelBuildListener(OnModelBuildFinishedListener)}
   */

Related 
https://github.com/airbnb/epoxy/issues/760
https://github.com/airbnb/epoxy/issues/756

**Comment by elihart** [comment]
Ok, I've updated the wiki. I wouldn't say the information was buried "deep" - it was in the main javadoc of the function which always be read - but I see where you're coming from.
