### ISSUE TITLE
How to update an EpoxyModel that already has been cached? [NOT DUPLICATE]

### ISSUE THREAD

**Issue by dariush-fathie** [airbnb/epoxy#884]
I know it's common question . i tried to read wiki and issues but  could not found my answer

I fetch Items from remote server and save them in `RoomDatabase ` and finally pass them to the `PagedListEpoxyController `and those will be cached to avoid recreate models for sake of performance .

Now if i want to ( like | bookmark | anyChange ) an item i simply update a single row in database, but how to propagate this changes to models inside `EpoxyRecyclerView `? 
Do i have to `requestForcedModelBuild `?

excuse me for my bad english !

**Comment by elihart** [comment]
Your PagedList should be notified of the database change, in which case its item update callback will rebuild the changed model. So it is up to you to make sure that the database change is propogated to your PagedList.

Otherwise you can use  `requestForcedModelBuild`.
