### ISSUE TITLE
Possible memory leak in ActivityRecyclerPool when EpoxyRecyclerView is created with a ContextWrapper

### ISSUE THREAD

**Issue by rashadsookram** [airbnb/epoxy#886]
I came across this when going through an app with Leak Canary 2. This was happening with an `EpoxyRecyclerView` being inflated within a `DialogFragment` using the inflater passed to `onCreateView`. This `LayoutInflater` had its `Context` set as a `ContextThemeWrapper` because it uses the [`Dialog`'s `Context`](https://android.googlesource.com/platform/frameworks/support/+/2d95dad0be72c1aa45c5a0844c67bb727403bcea/fragment/fragment/src/main/java/androidx/fragment/app/DialogFragment.java#408), which is a `ContextThemeWrapper` (see [1](https://android.googlesource.com/platform/frameworks/support/+/2d95dad0be72c1aa45c5a0844c67bb727403bcea/fragment/fragment/src/main/java/androidx/fragment/app/DialogFragment.java#455) and [2](https://github.com/aosp-mirror/platform_frameworks_base/blob/ad3e08aa693ee0e5936ce6cce2b6036a20554c31/core/java/android/app/Dialog.java#L181-L191)).

Looking at Epoxy's source, it seems to be because of [this code](https://github.com/airbnb/epoxy/blob/3.8.0/epoxy-adapter/src/main/java/com/airbnb/epoxy/ActivityRecyclerPool.kt#L53) which results in the `LifecycleObserver` that cleans things up not being registered.

Let me know if you need any more details, but I think this could be fixed by changing it to recursively unwrap the `Context` to try and find the `LifecycleOwner` / `Activity`.

## Leak Canary Trace

The TL;DR of the trace below is:

`EpoxyRecyclerView.ACTIVITY_RECYCLER_POOL` (static) retains
a `ActivityRecyclerPool` which retains
a `ViewHolder` which retains
a `Context` (specifically the `ContextThemeWrapper` which is wrapping the Activity)

### Full Trace

  ```
  612733 bytes retained
┬
├─ android.os.FileObserver$ObserverThread
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'FileObserver'
│    GC Root: Input or output parameters in native code
│    ↓ thread FileObserver$ObserverThread.contextClassLoader
├─ dalvik.system.PathClassLoader
│    Leaking: NO (Object[]↓ is not leaking and A ClassLoader is never leaking)
│    ↓ PathClassLoader.runtimeInternalObjects
├─ java.lang.Object[]
│    Leaking: NO (EpoxyRecyclerView↓ is not leaking)
│    ↓ array Object[].[3024]
├─ com.airbnb.epoxy.EpoxyRecyclerView
│    Leaking: NO (a class is never leaking)
│    ↓ static EpoxyRecyclerView.ACTIVITY_RECYCLER_POOL
│                               ~~~~~~~~~~~~~~~~~~~~~~
├─ com.airbnb.epoxy.ActivityRecyclerPool
│    Leaking: UNKNOWN
│    ↓ ActivityRecyclerPool.pools
│                           ~~~~~
├─ java.util.ArrayList
│    Leaking: UNKNOWN
│    ↓ ArrayList.elementData
│                ~~~~~~~~~~~
├─ java.lang.Object[]
│    Leaking: UNKNOWN
│    ↓ array Object[].[1]
│                     ~~~
├─ com.airbnb.epoxy.PoolReference
│    Leaking: UNKNOWN
│    ↓ PoolReference.viewPool
│                    ~~~~~~~~
├─ com.airbnb.epoxy.UnboundedViewPool
│    Leaking: UNKNOWN
│    ↓ UnboundedViewPool.scrapHeaps
│                        ~~~~~~~~~~
├─ android.util.SparseArray
│    Leaking: UNKNOWN
│    ↓ SparseArray.mValues
│                  ~~~~~~~
├─ java.lang.Object[]
│    Leaking: UNKNOWN
│    ↓ array Object[].[0]
│                     ~~~
├─ java.util.LinkedList
│    Leaking: UNKNOWN
│    ↓ LinkedList.first
│                 ~~~~~
├─ java.util.LinkedList$Node
│    Leaking: UNKNOWN
│    ↓ LinkedList$Node.item
│                      ~~~~
├─ com.airbnb.epoxy.EpoxyViewHolder
│    Leaking: UNKNOWN
│    ↓ EpoxyViewHolder.itemView
│                      ~~~~~~~~
├─ com.example.epoxy.HeaderView
│    Leaking: YES (View.mContext references a destroyed activity)
│    mContext instance of android.view.ContextThemeWrapper, wrapping activity com.example.activities.MyActivity with mDestroyed = true
│    View#mParent is null
│    View#mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    ↓ HeaderView.mContext
├─ android.view.ContextThemeWrapper
│    Leaking: YES (HeaderView↑ is leaking and ContextThemeWrapper wraps an Activity with Activity.mDestroyed true)
│    ↓ ContextThemeWrapper.mBase
╰→ com.example.activities.MyActivity
​     Leaking: YES (ContextThemeWrapper↑ is leaking and Activity#mDestroyed is true and ObjectWatcher was watching this)
​     key = d4cfe465-d7db-4990-bbbc-93febeefe9eb
​     watchDurationMillis = 14888
​     retainedDurationMillis = 9883

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Google
LeakCanary version: 2.0
App process name: com.example
Analysis duration: 8362 ms
  ```

**Comment by elihart** [comment]
Thanks  for the clear details, this does seem like an issue. I think you're right that unwrapping the context first could fix this. Feel free to put up a PR, otherwise we can get to this eventually (I am on leave right now)
