### ISSUE TITLE
accessing view directly with data binding model

### ISSUE THREAD

**Issue by vipulasri** [airbnb/epoxy#887]
I want to access a view directly with the data binding model, as I need to set some custom elements/properties to the view which can't be provided in the `data` tag. Is this possible?

P.S: I know I can create a custom model and then do the necessary changes.

**Comment by danim1130** [comment]
Unfortunately, looking at the source code, there doesn't seem to be an easy way doing this. There's the onBind callback for every model, but this gets called every time a model is bound to the view. The easiest way would probably be to extend the data binding model, and override it's buildView method.

**Comment by ranjeetscience** [comment]
@vipulasri how did you achieve the accessing view directly with data binding? can you pls share your finding.
