### ISSUE TITLE
Use multiple layout per one model?

### ISSUE THREAD

**Issue by dinhlamvn** [airbnb/epoxy#890]
Hi, I have a question: **Why not we can use multiple layout for an model in Epoxy?**
Example: I have an model with the different layout when **some state change**, but at the moment we can only provide the default layout when create an model. Can we support provide the layout in the array like below:
```kotlin
@EpoxyModel(layouts = [...])
class ModelA constructor(..): View(...) {
// Have some logic to handle the layout
}
```
How do you think about that?

**Comment by elihart** [comment]
the model can only use one layout at a time. The model is immutable, so when it is built it needs a single layout. If you want to use a different layout when you build the model you can specify that.

**Comment by dinhlamvn** [comment]
Yeah, I got it. Thanks u so much
