### ISSUE TITLE
Where to add gradle config script?

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/epoxy#893]
https://github.com/airbnb/epoxy/wiki/Configuration#in-gradle

Not super familiar with gradle, but I want to turn checks off. I tried adding in various places in my root level build.gradle and my app level build.gradle. Everytime I did my build failed instantly. I think I'm missing something here.

**Comment by SubhrajyotiSen** [comment]
You can specify it at the module level `build.gradle`.
You can refer the sample usage at https://github.com/airbnb/epoxy/blob/d98658ad2013b926d0e21acf1275280c602e1cee/epoxy-sample/build.gradle

**Comment by ColtonIdle** [comment]
@SubhrajyotiSen Thanks. This was not working yesterday... but it is today. Maybe a gradle or AS issue. Thank you. Closing.
