### ISSUE TITLE
Support annotation parameter in @ModelView for generating automatic IDs in EpoxyController

### ISSUE THREAD

**Issue by cristianzhang** [airbnb/epoxy#901]
Hi,
We're using extension functions for building models in kotlin, but we must manually specify an ID for each model, or define a field with an `@AutoModel` annotation in EpoxyController.
Could you add an annotation parameter in @ModelView for generating automatic IDs in EpoxyController like `autoId` below?
```kotlin
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT, autoId = true)
class CustomView(context: Context): View(context)
```

**Comment by elihart** [comment]
Auto generating ids is not possible since multiple instances of the model may be  used in one controller, and there is no way for Epoxy to differentiate them.
