### ISSUE TITLE
[Help Needed]Airbnb EpoxyModel are not working in feature modules/library projects in Android

### ISSUE THREAD

**Issue by nksaroj** [airbnb/epoxy#910]
Can anyone able to help the question posted in stackoverflow . We are stuck altogether.

https://stackoverflow.com/questions/59843745/airbnb-epoxymodel-are-not-working-in-feature-modules-library-projects-in-android

**Comment by elihart** [comment]
You are using butterknife incorrectly.
```
    class FooHolder : BaseEpoxyHolder() {
        @BindView(R2.id.textViewTitle) lateinit var textViewTitle: TextView
    }
```

Based on the error message you are not initializing this field correctly. I don't know what is in your base class `BaseEpoxyHolder`, but see https://github.com/airbnb/epoxy/wiki/ViewHolder-Models#baseholder-pattern

In general though, you shouldn't be  using Butterknife with Kotlin. See https://github.com/airbnb/epoxy/wiki/Kotlin-Model-Examples#with-view-holders for Kotlin specific patterns.

**Comment by nksaroj** [comment]
Below code fixed the issue without the need to adding butterknife 

  override fun getDefaultLayout(): Int {
        return R.layout. layout_foo 
    }

**Comment by Nobler** [comment]
Make sure add the kapt config in your module build.gradle, and use kapt instead of annaotionProcessor  in your dependencies:

```
apply plugin: 'kotlin-kapt'
kapt {
    correctErrorTypes = true
}

// ...

kapt  "com.airbnb.android:epoxy-processor:$epoxyVersion"
```
