### ISSUE TITLE
Callback prop is null when accessed in ModelProp

### ISSUE THREAD

**Issue by idrisadetunmbi** [airbnb/epoxy#911]
I have this model set up, but the `onUpdate` function is not invoked when the `model` prop is set and it is somewhat difficult to understand why.

```
class Model

@ModelView(autoLayout = ModelView.Size.WRAP_WIDTH_WRAP_HEIGHT)
class UpdatePropertiesObserverView(context: Context) : View(context) {

    var onUpdate: ((model: Model) -> Unit)? = null
        @CallbackProp set

    @ModelProp
    fun model(m: Model) {
       // onUpdate is null and never invoked even when set in controller
        onUpdate?.invoke(m)
    }
}

```

**Comment by elihart** [comment]
you should not have properties reference each other like this, as there is no guarantee which order they will be set in. for example, `model` may be set before `onUpdate`.

as per the wiki you should instead use `@AfterPropsSet` for cases like this
