### ISSUE TITLE
Single Selection on EpoxyRecyclerView

### ISSUE THREAD

**Issue by berkkulaksiz** [airbnb/epoxy#912]
Hello!

How can i make a single selection on EpoxyRecyclerView? Example screen given at below.

Thanks.

![Screenshot_1580472991](https://user-images.githubusercontent.com/9286989/73538730-ca3ddd80-443c-11ea-98a7-4b66308dd04f.png)

**Comment by elihart** [comment]
General guidance is the same as for any other complex state - have a data class object representing  your state, have a callback from the epoxy  models to  update that state when a new item is selected, and then trigger a model rebuild. When building models use the state to specify which one is selected.

State store libraries like MvRx along with async model building are great for this (immutability for safety, background threading for performance, etc
