### ISSUE TITLE
Cannot be  Use android.support.v4.widget.SwipeRefreshLayout

### ISSUE THREAD

**Issue by yuhanghate** [airbnb/epoxy#92]
Cannot be  Use android.support.v4.widget.SwipeRefreshLayout, Loading Progressbar not show
p.
I'm if replace RecyclerView and RecyclerView.Adapter model,When  Drop Down  Can mormally Display
please my Help

**Comment by elihart** [comment]
Do you have a hidden model as your first model? If so I believe this is a duplicate of https://github.com/airbnb/epoxy/issues/74
