### ISSUE TITLE
How to update list with new data in Typed2EpoxyController?

### ISSUE THREAD

**Issue by vkrm26** [airbnb/epoxy#921]
After fetching a new page from the server, I need to update my recycler view with new data.
How to add new data in the existing list and refresh recycler view?

**Comment by nomankhan18** [comment]
You need to call setData(T data1, U data2), it will refresh recycler view.

**Comment by vkrm26** [comment]
@nomankhan18 doing that shows list from starting.
For example - 
Initially, my list is having 20 items. then after fetching new 10 items from paginated response - my list have - 20 old items + 10 new items, and doing setData with (30 items) shows list from start. but here I want to show items from 21 - 30 in order.

**Comment by nomankhan18** [comment]
new AnyModel_()
                            .id(myid)
                            .url(url)
                            ..addTo(this);

Here myid should be unique and should not change while again calling setData(T data1, U data2) method.

**Comment by vkrm26** [comment]
Yes, this worked. Thanks a lot @nomankhan18
