### ISSUE TITLE
[Feature request] Tag views with Model id for UI Automation

### ISSUE THREAD

**Issue by akvashi** [airbnb/epoxy#927]
During automation is often necessary to tag views so that they can be found more easily in a recyclerview, epoxy models already have unique ids. I am proposing to have a setting to automatically assign id as tags on these views.

Happy to help work on this! Just wanted to gauge if this is feasible, popular, and would actually make it into a release.

**Comment by elihart** [comment]
I'm not sure about a change at the library level, but this would be pretty easy to implement in your own app. Just override `EpoxyController#onModelBound` to set the view id from the model. You can do this in a base class and have all of your controllers extend that.
