### ISSUE TITLE
Travis CI build status and Maven version of master branch

### ISSUE THREAD

**Issue by jpventura** [airbnb/epoxy#928]
Even though the project has both [Travis CI setup](https://travis-ci.com/github/airbnb/epoxy) and [artifact version](https://search.maven.org/search?q=a:epoxy), they are not visible at the [`README.md`](https://github.com/airbnb/epoxy/blob/master/README.md) file.

**Comment by jpventura** [comment]
@elihart @gpeal please, let me know if you have any doubts about the pull request :v:

**Comment by elihart** [comment]
Merged the PR, thanks!
