### ISSUE TITLE
Strange saving scroll sate of epoxy carousel with controller

### ISSUE THREAD

**Issue by Andrushka1012** [airbnb/epoxy#933]
Hi, 
I'm trying to make a nested carousel in epoxy using a controller, but when I change a fragment and pop back (I'm using navigation component), the scrolling state is very strange. It seems like two states are saved and they are replaced one by one. Also, when using **epoxyRecyclerView.withModels(..)** this problem did not occur, but there was no state saving.

![ezgif-7-6a9441f31dd0](https://user-images.githubusercontent.com/33988987/77318209-fa06b480-6d0c-11ea-8cf9-4b65677ed47d.gif)

**Comment by kefasjwiryadi** [comment]
https://github.com/chrisbanes/tivi/pull/482 works for me

**Comment by Andrushka1012** [comment]
@kefasjwiryadi , it's helps. Thank you!
