### ISSUE TITLE
Bug: Incorrectly generated code for click listener comparison (epoxy version 3.9.0).

### ISSUE THREAD

**Issue by lirik16** [airbnb/epoxy#936]
Hello. First of all, thank you for the great app.
About the problem. Epoxy Data Binding Support feature (version 3.9.0) incorrectly generates click listener comparison for automatically generated models. An automatically generated model has setDataBindingVariables method where the app compares the previous model and the current one. If the values are different epoxy updates the old value with a new one. But the current code for click listeners comparison is like this:
```Java
if (((clickListener == null) != (that.clickListener == null))) {
    binding.setVariable(BR.clickListener, clickListener);
}
```
Which is incorrect. Epoxy version 3.8.0. generates a correct version of the comparison and it looks like this:
```Java
if ((clickListener != null ? !clickListener.equals(that.clickListener) : that.clickListener != null)) {
    binding.setVariable(BR.clickListener, clickListener);
}
```
As I understand, `GeneratedModelWriter.generateDataBindingMethodsIfNeeded` incorrectly [generates](https://github.com/airbnb/epoxy/blob/a2372f994e00df548e6815be4c691b320a4d8b45/epoxy-processor/src/main/java/com/airbnb/epoxy/GeneratedModelWriter.kt#L1161) the body of the `setDataBindingVariables(ViewDataBinding binding, EpoxyModel previousModel)` method.

I created a repo with the problem example: https://github.com/lirik16/EpoxyIssue

**Comment by elihart** [comment]
I believe this behavior is expected. Look at https://github.com/airbnb/epoxy/wiki/Data-Binding-Support#detecting-changes-in-data. The current code you shared is what it looks like when "DoNotHash" is applied. The other code is with "DoNotHash" disabled. You should be able to change this default for databinding with the options described in that wiki link

**Comment by lirik16** [comment]
@elihart 
Oh, I see. So the behavior in the previous versions was incorrect because it didn't take into account that DoNotHash was `true` by default and the problem [was fixed](https://github.com/airbnb/epoxy/pull/837) in the [3.9.0 version](https://github.com/airbnb/epoxy/releases/tag/3.9.0).

Thank you very much for your fast answer. I should have checked the documentation more carefully.
