### ISSUE TITLE
Grid Carousel Breaking with Models created with Paris Integration

### ISSUE THREAD

**Issue by idrisadetunmbi** [airbnb/epoxy#937]
I created a very simple [app](https://github.com/idrisadetunmbi/androidlibissueproject) that uses an epoxy `GridCarousel`, a Paris styled custom `TextView` and I have spent a couple of hours trying to figure out why the carousel does not display as a grid. A model created with data-binding works perfectly, however. (please see attached project for different scenarios).

```
// TextView
@Styleable
@ModelView
class CustomText(context: Context) : AppCompatTextView(context) {
    companion object {
        @Style
        val DEFAULT_STYLE = R.style.Text
    }
}

// GridCarousel
@ModelView(autoLayout = ModelView.Size.WRAP_WIDTH_MATCH_HEIGHT)
class VerticalGridCarousel(context: Context) : Carousel(context) {
    override fun createLayoutManager(): LayoutManager {
        return GridLayoutManager(context, 2, GridLayoutManager.VERTICAL, false)
    }
}

// usage in fragment
verticalGridCarousel {
            id("Carousel")
            models(texts.map { text ->
                CustomTextModel_().apply {
                    id(text)
                    styleBuilder {
                        it.text(text)
                        it.textSizeDp(30)
                        it.layoutWidth(ViewGroup.LayoutParams.MATCH_PARENT)
                        it.layoutHeight(ViewGroup.LayoutParams.WRAP_CONTENT)
                    }
                }
            })
        }
```

Result:
![photo5780765783163515770](https://user-images.githubusercontent.com/30455641/78380084-38cd2200-75cb-11ea-89e3-f50ba20f792a.jpg)

**Comment by idrisadetunmbi** [comment]
@elihart, can you assist here, please? Thank you.

**Comment by elihart** [comment]
I don't see where you are setting the span size of the model.

https://github.com/airbnb/epoxy/wiki/Grid-Support

**Comment by idrisadetunmbi** [comment]
Thanks for checking this out @elihart. The models are being used in a `carousel` and not in the main `EpoxyRecyclerview`.

I have the base `epoxyRecylerview` (uses the regular `LinearLayoutManager`) and I am adding a grid carousel model to it (defined above). I added models created from custom views and styled with [Paris](https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)) to the grid carousel, but the grid carousel model items are not displaying in a grid as expected.

This, however, is not the case if I am not styling the grid carousel models with Paris.

**Comment by idrisadetunmbi** [comment]
@elihart, I went through the grid support wiki as advised and after setting the span size of the model, it displayed in a grid as expected. What is rather confusing is that I did not have to set the span size for a model created through databinding when used in the grid carousel before it displayed as expected.

To summarize the issue now, I have a grid carousel defined below:
```
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class VerticalGridCarousel(context: Context) : Carousel(context) {
    override fun createLayoutManager(): LayoutManager {
        return GridLayoutManager(context, 2, GridLayoutManager.VERTICAL, false)
    }
}
```

A model created through a custom view below:
```
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class CustomText(context: Context) : AppCompatTextView(context) {

    @ModelProp
    fun setText(text: String) {
        this.text = text
    }
}
```

Another model created with databinding below (generated model name: `DatabindingTextModel`):
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">

    <data>

        <variable
            name="text"
            type="String" />
    </data>

    <androidx.appcompat.widget.AppCompatTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="@{text}">

    </androidx.appcompat.widget.AppCompatTextView>
</layout>
```

Combining the three above:
```
// Here, without defining the span size override, models do not appear in a grid

verticalGridCarousel {
            id("Carousel")
            models(texts.map { text ->
                CustomTextModel_().apply {
                    id(text)
                    text(text)
                    spanSizeOverride { totalSpanCount, position, itemCount ->
                        totalSpanCount / 2
                    }
                }
            })
        }
```

```
// Here, without defining the span size override, models appear in a grid

verticalGridCarousel {
            id("Carousel")
            models(texts.map { text ->
                DatabindingTextModel_().apply {
                    id(text)
                    text(text)
                }
            })
        }
```

**Comment by elihart** [comment]
Databinding  might have its default grid span size set to 1. did you have a remaining issue  or can we close this?

**Comment by idrisadetunmbi** [comment]
I will close this out now. Thank you!
