### ISSUE TITLE
[Question] How to avoid requestModelBuild for every widgets in a recyclerview

### ISSUE THREAD

**Issue by nksaroj** [airbnb/epoxy#941]
I have a recycler view with fixed number widgets vertically in a specific order. Some of the widgets also contain tabular data hence I've considered using nested recycler view also within it.  

Every widget makes http call asynchronously from the ViewModel and binds the data to the epoxyController as I mentioned below. 

As requestModelBuild() being called for every widget as they receive the data through the public setters for example priceViewData, packageData and etc from where  requestModelBuild() is called. So in this instance every widget bind happens regardless of every time when data is received for any of the widgets. 
This seems to be expensive also, there some analytics gets fired as we needed for every bind.

So, here the analytics call for the widget is multiplied. 
Please suggest if this can be handled through the epoxy without handling manually.

```
class ProductDetailsEpoxyController(val view: View?,
                                  private val name: String?,
                                  private val context: Context?) : AsyncEpoxyController() {

    private val args = bundleOf("name" to name)

    var priceViewData: IndicativePriceViewData? = emptyPriceViewData()
        set(value) {
            field = value
            requestModelBuild()
        }

    var packageData: PackageViewData? = emptyPackageWidgetViewData()
        set(value) {
            field = value
            requestModelBuild()
        }
 
   ...
   ...
 
 

    override fun buildModels() {
        buildPriceViewData()
        buildPackageViewData()
        ....
    }

    private fun buildPriceViewData(){
        priceViewData?.let {
            id("price")
            priceViewDataModel(it)
        }
    }

    private fun buildPackageViewData(){
        packageViewData?.let {
             id("package")
              packageViewDataModel(it)
        }
    }

   ...
   ...
   
}

```

**Comment by nksaroj** [comment]
@elihart , Can you please help?

**Comment by elihart** [comment]
you can use requestDelayedModelBuild to debounce.
