### ISSUE TITLE
com.airbnb.epoxy.ImmutableModelException:  The model was changed between being bound and when models were rebuilt

### ISSUE THREAD

**Issue by dreamblader** [airbnb/epoxy#942]
Hello,

I'm working on a project and I having some trouble with rebuilding the Views through EpoxyController.

Everytime I change some of the data inside the View and call the TypedEpoxyController SetData my app crashes with the error:

com.airbnb.epoxy.ImmutableModelException: The model was changed between being bound and when models were rebuilt Position: 0 Model: // Model Data Here
    
Epoxy attribute fields on a model cannot be changed once the model is added to a controller. Check that these fields are not updated, or that the assigned objects are not mutated, outside of the buildModels method. The only exception is if the change is made inside an Interceptor callback. Consider using an interceptor if you need to change a model after it is added to the controller and before it is set on the adapter. If the model is already set on the adapter then you must call `requestModelBuild` instead to recreate all models.

Code:
```
class CheckoutFragment : ContainerFragment(), CheckoutController.Listener
{

  override val TAG: String = CheckoutFragment::class.java.name
  lateinit var viewModel: CheckoutViewModel
  private lateinit var checkoutProducts: MutableList<Product>
  private lateinit var controller: CheckoutController
  override val toolbarLayout: InteraToolbar?
    get() = toolbar

  companion object {
    fun newInstance(backNavigationEnabled: Boolean = false) = CheckoutFragment().apply {
      arguments = bundleOf(BACK_NAVIGATION_ENABLED to backNavigationEnabled)
    }
  }

  override fun layoutRes(): Int = R.layout.fragment_checkout

  override fun onViewCreated(view: View, savedInstanceState: Bundle?)
  {
    super.onViewCreated(view, savedInstanceState)
    checkoutProducts = mutableListOf()
    initViewModel()
    initRecyclerView()
  }

  private fun initViewModel()
  {
      viewModel= ViewModelProviders.of(this).get(CheckoutViewModel::class.java)
      viewModel.productLiveData.observe(this, Observer {
          checkoutProducts = it.toMutableList()
          updateController()
      })

      viewModel.applyService()
  }

  private fun initRecyclerView() {
    controller = CheckoutController(this)

    erv_product.itemAnimator?.changeDuration = 0
    erv_product.setController(controller)
    updateController()
  }

  private fun setDataAvailableLayout(isAvailable: Boolean) {
    group_calculate_shipping.showOrHide(isAvailable)
    group_content_layout.showOrHide(isAvailable) {
      cl_root.backgroundColorResource = R.color.white
      btn_proceed_with_order.textResource = R.string.proceed_with_order
      rg_payment_type.selectViewProgrammatically(R.id.rb_associated_total_text)
    }

    tv_no_content.showOrHide(!isAvailable) { //BREAKING HERE!!!
      cl_root.backgroundColorResource = R.color.color_f9f7eb
      btn_proceed_with_order.textResource = R.string.make_a_wish
    }

  }

  private fun updateController() {
    setDataAvailableLayout(checkoutProducts.isNotEmpty())
    controller.setData(checkoutProducts) // ERROR HAPPENS HERE AFTER CALLING IT AGAIN
  }

  override fun onRemoveClick(product: Product) {
    viewModel.remove(product)
    updateController()// CALL CRASH THE APP
  }

  override fun onFavoriteClick(product: Product) {
    viewModel.changeFavorite(product)
    product.isFavorite = !product.isFavorite
    updateController() // CALL CRASH THE APP
  }

  override fun onSelectionCountClick(product: Product) {
    val list = (1 .. 20).toList().map { it.toString() }
    selector("Select count", list) { dialog, position ->
      dialog.dismiss()
      val currentSelection = list[position]
       val quantity = currentSelection.toIntOrNull().orZero()
      viewModel.update(product, quantity)
      updateController()// CALL CRASH THE APP
    }
  }
```

I am really stuck at this. I tried a bunch of stuff but somehow I could not progress into making my EpoxyModels to update with the new product data. 

Thanks in advance

**Comment by elihart** [comment]
hard to tell without seeing the code of your model, or your data classes, but this line looks suspicous `product.isFavorite = !product.isFavorite`

The error is pretty straightforward - you can't have any fields in your Epoxy model that are affected by change. no changing properties in data classes, etc

**Comment by MirzaShadman** [comment]
@elihart i am also facing the same issue. I also used the interceptors to update, but no luck. Same error i am getting. If needed i  will paste my code. May i get help please ?

**Comment by zeromod** [comment]
An Exception might happen in `controller.setData(checkoutProducts)` when navigating to other fragment and coming back to this fragment.

`controller` instance was might not be destroyed throughout the lifecycle state changes of the fragment. On each lifecycle `START`, live data emits the latest value.
In case the live data is changed (may be by other fragment), the new value emitted is different from previous, so `controller` throws at `handlePostBind`

**A possible work around is :** 
Destroy the `controller` instance in `onDestroyView()` from the fragment.

**Comment by premacck** [comment]
Up until 3.4.2, code like this was working (I have quite a few usages in my app which are working fIne from over a year):
```
product.isFavorite = !product.isFavorite
updateController() // CALL CRASH THE APP
```

But then #956 occurred, and then after updating, I'm also facing this crash with the code which was working up until 3.4.2.



@elihart is there any way to refactor existing code in a way that it doesn't crash in the new versions? Like in the scenario above, where the RecyclerView items need to be updated after user interaction.

**Comment by elihart** [comment]
these errors should only be thrown when debug validations are enabled, so you can disabled that temporarily while you fix them.

These are errors that you do not want to ignore though, as they are real problems the can lead to your views not working properly

**Comment by wiztensai** [comment]
please, i need this feature for notifyDataSetChanged

> 
> 
> @elihart i am also facing the same issue. I also used the interceptors to update, but no luck. Same error i am getting. If needed i will paste my code. May i get help please ? Why it is so complicated to update models ?? It should be as easy as notifyDataSetChanged, isn't it ?
