### ISSUE TITLE
License is missing in Maven POM

### ISSUE THREAD

**Issue by andreasmakeable** [airbnb/epoxy#945]
After using Google's OSS Licenses plugin in our app, we noticed that Epoxy is missing a Maven POM License. It works fine with Lottie for example.

Please add the license to Maven.

**Comment by elihart** [comment]
I'm not sure what's going on here. We have the license properties defined in https://github.com/airbnb/epoxy/blob/master/gradle.properties, and our maven publish plugin states that it supports those properties - https://github.com/vanniktech/gradle-maven-publish-plugin#setting-properties

**Comment by elihart** [comment]
oh, this was fixed in https://github.com/airbnb/epoxy/pull/898, a release just wasn't pushed with it. I am making a 3.10. release that will include it now
