### ISSUE TITLE
Update the Wiki to mention EpoxyAsyncUtil. getAsyncBackgroundHandler() as alternative to setting the static fields

### ISSUE THREAD

**Issue by Nimrodda** [airbnb/epoxy#948]
In the section about [Async support](https://github.com/airbnb/epoxy/wiki/Epoxy-Controller#asynchronous-support), the Wiki mentions  setting the static fields in EpoxyController.

It mentions that the controller has a 2nd constructor that accepts Handlers, but it doesn't mention that Epoxy provides one out-of-the-box via `EpoxyAsyncUtil. getAsyncBackgroundHandler()`. 
I found out about `EpoxyAsyncUtil` while looking into the source code of `AsyncEpoxyController`.

It seems that many developers that use the library do not know about this. This is kind of a hidden gem, which I really think should be exposed in the Wiki.

**Comment by elihart** [comment]
sure, I've added this
```
Epoxy provides some utils in the class EpoxyAsyncUtil for creating async Handlers. For example, you can use the function EpoxyAsyncUtil#getAsyncBackgroundHandler to easily get a Handler that uses a dedicated async background thread.
```

glad you've found it helpful :)

**Comment by Nimrodda** [comment]
Awesome, thanks!
