### ISSUE TITLE
Incremental kapt

### ISSUE THREAD

**Issue by v-grishechko** [airbnb/epoxy#949]
First of all thanks for the great project. It is boosted our productivity, but our build time increased. We've moved to modular architecture and almost every module uses kapt and epoxy. We hoped to this [PR](https://github.com/airbnb/epoxy/pull/902), because only Epoxy breaks incremental kapt. Is exists simple patch to make it incremental? Where to start investigation? We are using only ```@EpoxyModelClass```. 
#902

**Comment by elihart** [comment]
Hi, you can see in the comments of https://github.com/airbnb/epoxy/pull/902 what the existing issues are. I am planning to finish this work hopefully in the next two weeks

**Comment by elihart** [comment]
There is already an issue for this at https://github.com/airbnb/epoxy/issues/423
