### ISSUE TITLE
Can't call notifyItemChanged(position) to trigger revert swipe

### ISSUE THREAD

**Issue by semanticer** [airbnb/epoxy#954]
As mentioned here https://stackoverflow.com/questions/31787272/android-recyclerview-itemtouchhelper-revert-swipe-and-restore-view-holder

probably the only way to trigger revert swipe animation is to call `notifyItemChanged` on your adapter directly. The problem is that this is not possible with epoxy since you get `java.lang.IllegalStateException: You cannot notify item changes directly. Call requestModelBuild instead.`

The issue is that `requestModelBuild` doesn't trigger redraw since the backing model didn't really change. 

Here is the link to the exact place where I need to use notifyItemChanged but can't https://github.com/toggl/android/blob/5e0c1882ab3ebcba4c7f83486168e300653cbd59/timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt#L138

Do you have some workaround for this?
Thanks

**Comment by semanticer** [comment]
The only way I could find so far is to reattach touch helper: 
```kotlin
itemTouchHelper.attachToRecyclerView(null);
itemTouchHelper.attachToRecyclerView(recyclerView);
```
mentioned in https://stackoverflow.com/a/37342327/509681

This will immediately force the list item to its original position but without the revert animation that we need. Is there really no way to do this properly? 

Thanks for your answer and keep up the good work 👍

**Comment by elihart** [comment]
We can't expose that adapter API in EpoxyController, but I think what you can do is have a boolean prop on your model, like `isSwiped` and when you want to revert it you can set it to false when you rebuild models. This will cause Epoxy to notify an item change on that item.

of course, that won't happen until the next frame, and I'm not sure if that's a problem for your use case. if so the only solution I can see is an Epoxy internal change to allow this to happen synchronously, possible via the touch helper API. i suppose allowing access to notify item changes is pretty safe (as opposed to notifying insertions or removals)

**Comment by semanticer** [comment]
Thanks for the answer. I've experimented with this `isSwiped` approach and it still doesn't solve the problem, unfortunately 🤔. I isolated this issue in a [separate controller with debugging turned on](https://github.com/toggl/android/blob/epoxy-log-is-swiped/timer/src/main/java/com/toggl/timer/log/ui/TimeEntryController.kt).  
And `requestModelBuild` is then called [right after the swipe completed](https://github.com/toggl/android/blob/0c447caf2d7f04ebc184e56cd74572a89698852f/timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt#L120) 
Implementation with `notifyItemChanged()` on exactly the same place with traditional adapter implementation work as expected and the animation is reverted, but with epoxy, nothing happens. The continue animation gets stuck in the final position even though I know for sure that the models are being rebuilt:
```
D/TimeEntryController: Item range changed with payloads. Start: 1 Count: 1
D/TimeEntryController: Models diffed: 0.588ms
```
So the `isSwipe` is triggering the update but it doesn't have the same effect as calling the `notifyItemChanged(pos)` how is that possible, or am I missing something? 

Thanks

**Comment by semanticer** [comment]
It would be really nice to solve this issue once and for all, this is the third time I encountered this in three unrelated projects. It seems to be a pretty common use case.

**Comment by elihart** [comment]
Would you like to put up a PR to solve this? I think the touch helper builder code can return an object which you could later call `cancelSwipe` or something

**Comment by semanticer** [comment]
@elihart I'm afraid this might be impossible to implement. Fundamentally, the problem is in [ItemTouchHelper](https://stackoverflow.com/a/31872357/509681) as it was not designed for any other swipe than swipe-to-delete apparently. The fact that `notifyItemChanged(pos)` works is a hacky miracle :-(

**Comment by elihart** [comment]
ok, it's possible that we could provide a brand new class to set up swiping in the way that you want.

Alternatively i'm not too opposed to adding a function to epoxycontroller to manually notify item change

**Comment by berendjan** [comment]
Has there been any progress on this issue?

**Comment by Gelacio** [comment]
@elihart In what version can I find this change on maven? Are you planning any release with this fix soon?

Thanks

**Comment by elihart** [comment]
It has not been released yet, I'll try to make a new release soon

**Comment by MihashiHans** [comment]
@elihart
looking forward to the release as well, would be of great help to us.

**Comment by elihart** [comment]
I've included the fix in 4.2.0 - artifacts are being pushed now and should be available shortly.

https://github.com/airbnb/epoxy/pull/1085

**Comment by MihashiHans** [comment]
many thanks!

**Comment by Gelacio** [comment]
@elihart Calling notifyItemChanged(position) for PagedListEpoxyController  to revert the swipe action is not working. Neither submitting a new page list with the swiped item changed in the data source.

Any idea to revert swipe action for PagedListEpoxyController? 
Thanks
