### ISSUE TITLE
VisibilityTracker sometimes fails to report visibility changes when ItemAnimator is used

### ISSUE THREAD

**Issue by jess-anders** [airbnb/epoxy#958]
In some scenarios visibility changes aren't fired when a view is brought back onto the screen as part of a model rebuild.  The problem goes away if the ItemAnimator is removed.  

This is a scenario that always reproduces the behavior:

1.  Have a list of items that is longer than the screen.
2. Scroll down the list so a model you are interested in is off the top of the screen.
3. Cause a model rebuild that makes the adapter contents shorter than the screen height.
4. This causes the remaining models to be animated back onto the screen back to scroll pos 0.
5. The view you are interested in that was scrolled off the top of the screen is now back on the screen, but a visibility event is never fired.

This seems to happen because the visibility is checked before the ItemAnimator has finished moving the view onto the screen, so it is seen as still not being displayed.

**Comment by elihart** [comment]
#962
