### ISSUE TITLE
Using Epoxy in Android TV (D-pad, focus interaction)

### ISSUE THREAD

**Issue by yurabuloichik** [airbnb/epoxy#970]
Firstly thanks for such a good library! 
Question: how can I use Epoxy in Android TV? Are there some really good( ~ easy) ways of using it for focus interaction? (I don't like google leanback libraries due to performance). Maybe someone had such experience and can help with that.
Thanks in advance.

**Comment by ColtonIdle** [comment]
It's just a recyclerView and so I haven't had any issues with AndroidTV. Is there something specific you're having trouble with?

**Comment by yurabuloichik** [comment]
As a regular recyclerview it loses focus while navigating from row to row(aka carousel)  or scrolling too fast within a row with dpad. I just wonder whether anybody has some working solution for it(without leanback implementations). Example would be much appreciated!

**Comment by ColtonIdle** [comment]
Maybe someone else has a better solution, but I've always had to set nextfocus ids programmatically when dealing with a recyclerView.
