### ISSUE TITLE
Focusing TextInputLayout + Keyboard open on Fragment creation

### ISSUE THREAD

**Issue by sanogueralorenzo** [airbnb/epoxy#975]
Hello, has anyone played around with epoxy and showing the keyboard on fragment creation?

I tried having it inside the Epoxy View something like below and it works but, as expected, when there is scrolling involved the keyboard will pop up again.
![image](https://user-images.githubusercontent.com/5630683/82157329-aeb4e200-9835-11ea-8f8a-f00d76115945.png)

I was also looking into epoxy interceptors https://github.com/airbnb/epoxy/wiki/Epoxy-Controller#interceptors but at this point, the view hasn't been drawn.

What is the best approach to this scenario? I'm looking for a callback after initial view creation so I can find the view and do it from the Fragment itself.

Is there anything built in Epoxy I could use or should I look into Recyclerviews's Layout manager?

Any suggestions?

Thanks!

**Comment by elihart** [comment]
use the onBind callback? https://github.com/airbnb/epoxy/wiki/Epoxy-Models#binding-views

**Comment by sanogueralorenzo** [comment]
Thanks, missed that.

For reference if anyone is looking for something similar (fragment creation show keyboard focusing on edittext from the epoxy controller) I ended up with this:

``` kotlin
class NameController(private val onNameChanged: (String) -> Unit) :
    TypedEpoxyController<NameState>() {

    var initialInputBind = true

    override fun buildModels(data: NameState) {
        textInputLayoutRow {
            id("name_input")
            body(data.name)
            inputType(android.text.InputType.TYPE_TEXT_FLAG_CAP_WORDS)
            textChangedListener { onNameChanged(it) }
            onBind { _, view, _ ->
                if (initialInputBind) {
                    Keyboard.show(view)
                    initialInputBind = false
                }
            }
        }
    }
}
```

Where Keyboard.show is using the only approach that works with Fragment creation  (that or a nasty handler with 50ms).

``` kotlin
object Keyboard {

    fun show(v: View) {
        if (v.requestFocus()) {
            (v.context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager)
                .toggleSoftInput(
                    InputMethodManager.SHOW_IMPLICIT,
                    InputMethodManager.HIDE_IMPLICIT_ONLY
                )
        }
    }

    fun hide(v: View) {
        v.requestFocus()
        (v.context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager)
            .hideSoftInputFromWindow(v.windowToken, InputMethodManager.HIDE_NOT_ALWAYS)
    }
}
```
