### ISSUE TITLE
4.0.0.beta1 generating duplicate method layout(int) 

### ISSUE THREAD

**Issue by markchristopherng** [airbnb/epoxy#988]
Hi 

The 4.0.0.beta1 version is generating duplicate methods on the builder. When i downgrade to 3.11.0 it goes away.

In the console i get an error like this

 method layout(int) is already defined in class EpoxyOfflineArticles_
  public EpoxyOfflineArticles_ layout(@LayoutRes int layoutRes) {

When i open up the generated class you can see the duplicated method

public interface EpoxyArticlesBuilder {
  EpoxyArticlesBuilder onBind(OnModelBoundListener<EpoxyArticles_, TrackItemRowView> listener);

  EpoxyArticlesBuilder onUnbind(OnModelUnboundListener<EpoxyArticles_, TrackItemRowView> listener);

  EpoxyArticlesBuilder onVisibilityStateChanged(
      OnModelVisibilityStateChangedListener<EpoxyArticles_, TrackItemRowView> listener);

  EpoxyArticlesBuilder onVisibilityChanged(
      OnModelVisibilityChangedListener<EpoxyArticles_, TrackItemRowView> listener);

  EpoxyArticlesBuilder consignmentWrapper(
      @Nullable NonEqualWrapper<Consignment> consignmentWrapper);

  EpoxyArticlesBuilder itemViewListener(@Nullable ActionableTrackItemListener itemViewListener);

  EpoxyArticlesBuilder layout(@LayoutRes int layoutRes);

  EpoxyArticlesBuilder id(long id);

  EpoxyArticlesBuilder id(@androidx.annotation.Nullable Number... ids);

  EpoxyArticlesBuilder id(long id1, long id2);

  EpoxyArticlesBuilder id(@androidx.annotation.Nullable CharSequence key);

  EpoxyArticlesBuilder id(@androidx.annotation.Nullable CharSequence key,
      @androidx.annotation.Nullable CharSequence... otherKeys);

  EpoxyArticlesBuilder id(@androidx.annotation.Nullable CharSequence key, long id);

  EpoxyArticlesBuilder layout(@LayoutRes int layoutRes);

  EpoxyArticlesBuilder spanSizeOverride(
      @androidx.annotation.Nullable EpoxyModel.SpanSizeOverrideCallback spanSizeCallback);
}

**Comment by markchristopherng** [comment]
Hi just a little bit more information the affect classes seem to extend EpoxyModelWithView

E.g.

@EpoxyModelClass
abstract class EpoxyArticles : EpoxyModelWithView<TrackItemRowView>() {

**Comment by elihart** [comment]
thanks for the report. i will get a fix into the next beta release. very helpful to know this happens with `EpoxyModelWithView` :)

**Comment by elihart** [comment]
Fixed with https://github.com/airbnb/epoxy/pull/991. a 4.0.0-beta4 will be out later today that includes the fix
