### ISSUE TITLE
ModelViews does not appear on the Adapter.

### ISSUE THREAD

**Issue by ravzanurknk** [airbnb/epoxy#990]
The model classes that I added, the adapter does not appear.
Did I do something missing?
It would be great if you could give an idea :)

 **My controller class :** 

     class SampleController : TypedEpoxyController<Any>() {
      override fun buildModels(data: Any?) {
        data?.let {
            if (data is NewShortTextModel_) {
               data.id(hashCode())
                data.addTo(this)
            }
        }
   
      override fun onExceptionSwallowed(exception: RuntimeException) {
          throw exception
      }

      init {
         }
        }
     }

**An example model view :**  

    @ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
    class NewShortText : BaseQuestion {
    private lateinit var formItem: BaseFormItem
    private lateinit var etInput: EEditText
    @set:ModelProp
    var questionId = -1

    constructor(form: Form?, questionId: Int, context: Context) : super(context) {
        this.form = form
        this.questionId = questionId
        init()
    }
    constructor(context: Context) : super(context) {
        init()
    }
    private fun init() {
        setPageContenView(R.layout.new_item_question_short_text)
        formItem = findViewById(R.id.questionShortText_formItem)
        etInput = formItem.findViewById(R.id.questionShortText_et)
        setTitle()
        setRequiredField()
    }

**Main class :** 

    val linearLayoutManager = LinearLayoutManager(context, RecyclerView.VERTICAL, false)
        epoxyRv.layoutManager = linearLayoutManager
        epoxyRv.setController(controller)

        val view = NewShortTextModel_()
                        .questionId(question.id)
                        .staticQuestionType(questionTypeValue)
                        .opportunityStaticQuestion(true)
    controller.setDate(view)

**Comment by elihart** [comment]
you're using the controller all wrong. you shouldn't be creating `NewShortTextModel_` outside of the controller. that, should be done in `buildModels.` the data passed in to the controller should be the data needed to create the models, like your `question`.

please read the wiki and sample code
