### ISSUE TITLE
Carousel with endless scroll

### ISSUE THREAD

**Issue by alpeshrathod25** [airbnb/epoxy#994]
Hi,
I am exploring your library and currently I am going through one situation.

I have implemented carousel and I want use endless scroll with carousel to load more items. Is it possible to achieve? I am not getting idea how to achieve this. Can you please help me?

**Comment by elihart** [comment]
See the wiki: https://github.com/airbnb/epoxy/wiki/Cyclic-Adapters and past issues

https://github.com/airbnb/epoxy/issues/375
https://github.com/airbnb/epoxy/issues/396
https://github.com/airbnb/epoxy/pull/401

**Comment by alpeshrathodsa** [comment]
@elihart I want to add one more point, carousel itself is a item of recyclerview in my case. Is it possible to add endless scroll for this carousel?

**Comment by alpeshrathod25** [comment]
@elihart  I want to add one more point, carousel itself is a item of recyclerview in my case. Is it possible to add endless scroll for this carousel?

**Comment by elihart** [comment]
there is no difference

**Comment by DawnNguyenAhiho** [comment]
Hi, I'm implementing a carousel with endless scroll too. I have an epoxy recyclerview and a controller. Inside `buildModels` I have the `CarouselModel_`. Now how can I wrap the carousel adapter with the CyclicAdapter to achieve the endless scroll. Please help me.
