### ISSUE TITLE
Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.

### ISSUE THREAD

**Issue by Chullian** [airbnb/epoxy#995]
I was trying to add multiple viewTypes, and this happens... 

`java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
     ViewHolder 1:EpoxyViewHolder{epoxyModel=MunchRestaurantPricesModel_{providerImage=http://myhubber.me/img/backend/provider/zomato.com/logo.png, munchOffer=Standard Price, providerColor=#C9202D}MunchRestaurantPricesModel_{id=71503083113255448, viewType=2131558538, shown=true, addedToAdapter=false}, view=com.google.android.material.card.MaterialCardView{b62be44 VFE...C.. ......ID 56,1078-1384,1289}, super=EpoxyViewHolder{1fdf6c3 position=1 id=71503083113255448, oldPos=-1, pLpos:-1}} 
     View Holder 2:EpoxyViewHolder{epoxyModel=MunchRestaurantPricesModel_{providerImage=http://myhubber.me/img/backend/provider/talabat.com/logo.png, munchOffer=Standard Price, providerColor=#FF6F00}MunchRestaurantPricesModel_{id=71503083113255448, viewType=2131558538, shown=true, addedToAdapter=false}, view=com.google.android.material.card.MaterialCardView{b9beb2d VFE...C.. ......ID 56,1345-1384,1556}, super=EpoxyViewHolder{d05c9a0 position=2 id=71503083113255448, oldPos=-1, pLpos:-1}} com.airbnb.epoxy.EpoxyRecyclerView{4d90862 VFED..... ......ID 0,0-1440,2722 #7f0a0222 app:id/restaurantRecycler}, adapter:com.airbnb.epoxy.EpoxyControllerAdapter@ec29df3, layout:androidx.recyclerview.widget.LinearLayoutManager@1ef7ab0, context:com.myhubber.myhubberr.ui.activities.munchItemDetails.MunchItemDetailsActivity@d67598a`

**Comment by elihart** [comment]
yes, you have an error in your code. read the error message to see the details and then fix your duplicate id issue

**Comment by Chullian** [comment]
I was trying to build multiple viewTypes inside it, and i got this error when updating the viewTypes as I have more data received from backend

**Comment by dinhlamvn** [comment]
@Chullian Let check your `buildModels` code in `EpoxyController`. Please make sure the `id` òd each model view is unique.

**Comment by ccsavvy** [comment]
Hi, I have the same issue but I can't control what's going to be coming from the API and I want to ensure that I have to resolve this id dups. My initial approached is to `setFilterDuplicates` but it doesn't work with `TypeControllers` Is there any workaround for this to silently handle it?

**Comment by lotaviods** [comment]
I have the same issue, the items is coming  from api in differents tables and maybe occasionally colapse these ids  on my view-holders is there any solution for this ?

**Comment by lotaviods** [comment]
I have the same issue, the items is coming from api in differents tables and maybe occasionally colapse these ids on my view-holders is there any solution for this ?

**Comment by elihart** [comment]
if the id is coming from different tables then use a string in combination with the id to make it unique. notice the `id` function has several overloads with multiple parameters for this exact case

**Comment by lotaviods** [comment]
> if the id is coming from different tables then use a string in combination with the id to make it unique. notice the `id` function has several overloads with multiple parameters for this exact case

But, how do i do this combination with string if i have to return Long from getItemId?

**Comment by elihart** [comment]
epoxy hashes it for you. you should not be implementing `getItemId`, the base EpoxyModel class handles that. just set your id with `id`. look at the source
