### ISSUE TITLE
Detect ImmutableModelException on release builds

### ISSUE THREAD

**Issue by j-roskopf** [airbnb/epoxy#998]
Hello! We are interested in detecting ImmutableModelException on release variants of our applications so they can be logged as non fatals.

We currently have this in our build.gradle to detect usage in debug builds

```
project.android.buildTypes.all { buildType ->
    buildType.javaCompileOptions.annotationProcessorOptions.arguments =
            [
                    validateEpoxyModelUsage     : String.valueOf(buildType.name == 'debug')
            ]
}
```

But we would also like to be able to add logging for release builds in case it is missed.

My initial thought was that we could override `onExceptionSwallowed` in our controllers, but ImmutableModelException does not seemed to be passed through that method in generated models. Is there another way we could accomplish this? If I were to make a PR to pass that exception through `onExceptionSwallowed` - would that be a fine way to go?

Thank you!

**Comment by elihart** [comment]
Hi there, yes I think this could be reasonable. It should be easy enough to change the base EpoxyModel to not throw the exception directly and instead pass it to the controller via the instance `firstControllerAddedTo`.

One issue I see is that the default behavior for `onExceptionSwallowed` is to do nothing, which is a pretty big change from now where it throws an exception. I would like to keep the existing default behavior of throwing the exception - can you propose a way to accomplish what you want while throwing the exception by default?

Another thing, just beware that the debug validations add runtime overhead that will slow down your app. Particularly look at EpoxyModel#validateStateHasNotChangedSinceAdded and see how it computes the hashcode of each model to check for changes. It's not something i would personally want running in release builds, but that's up to you.

**Comment by j-roskopf** [comment]
Ah I did not consider your last point. I think we will forgo that for the reason you listed.

As always thank for the help & info!
